### ISSUE TITLE
Create search form for images MVP

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#1001]
## Type
- ✨ Feature

## Requirements
- [x] New component(s) built

**Comment by kenoir** [comment]
![giphy](https://user-images.githubusercontent.com/953792/27135399-4e8dd45a-5110-11e7-8bc7-029999c52e6a.gif)

**Comment by BethPF** [comment]
@davidpmccormick what was the scope of this ticket please? What's been delivered?

**Comment by davidpmccormick** [comment]
![screen shot 2017-07-17 at 15 46 21](https://user-images.githubusercontent.com/1394592/28273780-22bedb1a-6b07-11e7-9853-67051d931ccf.png)

The works search form. Work completed in #1122.
