### ISSUE TITLE
Create results list for images MVP

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#1002]
## Type
- ✨ Feature

## Requirements
- Display image thumbnails and descriptions within promo components
- Display image title (label)
- Display image description
- Display number of results from query
- Display B number?
- Display created date?
- Display creators?

## User stories
As any user, I want to see all of the images that match my search so that	I can see what's available [MVP, to test]

- [x] New component(s) built

**Comment by Heesoomoon** [comment]
![searchresults_desktop](https://user-images.githubusercontent.com/29206031/27698345-be978a72-5cee-11e7-9ac9-f83d63b02e65.png)
![searchresults_mobile](https://user-images.githubusercontent.com/29206031/27698346-bea0224a-5cee-11e7-9236-1d305b6f2e2a.png)

**Comment by Heesoomoon** [comment]
**Search Results Desktop**
![searchresults_desktop](https://user-images.githubusercontent.com/29206031/27740416-e1d527b8-5da9-11e7-9a58-721c7b877356.png)

**Search Results Desktop with Refine**
![searchresults_desktop_refine](https://user-images.githubusercontent.com/29206031/27740449-fb859b8e-5da9-11e7-9e82-8a3c8c9ce5d0.png)

**Search Results Mobile**
![searchresults_mobile](https://user-images.githubusercontent.com/29206031/27740469-09f422e4-5daa-11e7-9760-6e3d593e4b5a.png)

**Search Results Mobile with Refine**
![searchresults_mobile_refine](https://user-images.githubusercontent.com/29206031/27740504-212c6d18-5daa-11e7-9731-6072cd551401.png)

**Comment by pollecuttn** [comment]
Should 'Refine' instead be 'Sort'? I expect refine to reduce the number of results (refining my search down) but sort to keep the same number of results but arrange them differently.

**Comment by Heesoomoon** [comment]
Glad you asked : )

Well, 'Refine' will grow eventually with Orientation and Copy right options. Since we have limited space on mobile, we thought of grouping **Filters** and **Sort** into one action **Refine**. Yes, sorting isn't really narrowing down the result but it updates your result. I'll investigate further and follow up next week. e.g. http://www.istockphoto.com/gb/photos/animal?phrase=animal&excludenudity=true&sort=best

**Comment by Norvard** [comment]
Below are the design images/files/elements for MVP

![wc_search_desktop_20170704](https://user-images.githubusercontent.com/23660297/27837039-12f8095e-60da-11e7-8775-1fb217facaf9.png)
![wc_search_mobile_20170704_2](https://user-images.githubusercontent.com/23660297/27837042-13b27d34-60da-11e7-8d0a-f9ce569d1e2a.png)
![wc_search_mobile_20170704](https://user-images.githubusercontent.com/23660297/27837040-12f8b0fc-60da-11e7-8b32-0d4fda24f93f.png)

**Comment by Heesoomoon** [comment]
Tomi, we should display [# of results for 'Search Term'] on both desktop and mobile below the search field. Would you add that in and update the files?

**Comment by Norvard** [comment]
@gestchild 
New Sort icon svg code attached

The smaller arrow buttons actually use our small arrows. Just create a small circle to fit around it. Grab me if you got questions.

[Sort_Icon.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1124317/Sort_Icon.zip)

**Comment by Norvard** [comment]
Updated PNG and Sketch files attached:

PNGs:
[20170705.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1125164/20170705.zip)

Sketch:
[WC_Search_Results_MVP_170705.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1125166/WC_Search_Results_MVP_170705.zip)

fyi @davidpmccormick slight change in the sort icon order :)
