### ISSUE TITLE
Create pagination for images MVP

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#1003]
## Type
- ✨ Feature

- Allow results per page to be changed by the user?

Add to #1002 when complete.

**Comment by Heesoomoon** [comment]
**UI Specification**
- Refer to #1002 
- Need to follow up with Jenn to see if we can update the pagination pattern to improve usability.

**Visual Design**
- Refer to Cardigan

**Comment by BethPF** [comment]
@jennpb what was the conclusion please?
