### ISSUE TITLE
Create single work page for images MVP

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#1004]
## Type
- ✨ Feature

## Requirements
- Display image title (label)
- Display large image of work
- Display image description
- Display B number?
- Display created date?
- Display creators?
- Display back to results link?

## User stories
As any researcher, I want to see clear core information about an object (date, size, publisher, provenance) so that I understand this is a quality source (Code & Theory research, 2016) [MVP, to test]

As any picture researcher, I want to see a large high quality image so that I can decide if I want to use it (WI Personas research, 2014)

- [x] New component(s) built

**Comment by jennpb** [comment]
**API / data from Miro**
Work: Identifier 
Miro - Cat 1: Number (prefix + number?)
		
Work: Title	
Miro - Cat 1: Description of image(used as title)	
	
Work: Author	
Miro - Cat 1: Creator		

Work: Created date	
Miro - Cat 1: Creation date (providing that this is the date the item itself was created rather than our image of the item)		
	
**Not available in API yet but will need**

- Work: Subject	MeSH/ LoC: MeSH
- Work: Subject	MeSH/ LoC: Library of congress
- Subjects: Names	
- Subjects: LCSH place

?Work: Genre	
Miro - Technique

Work: Lettering	
Miro - Lettering

Work: hasLicense	
Miro - Copyright information

**Comment by Heesoomoon** [comment]
**UI Specifications (see wireframe attached below)**
- Return to results: Display 'Return to results' link when user arrives to the item page via result list. Links to the result list and anchor to the selected item.
- Image: Display available image (hi-res for MVP) in assigned space for desktop and mobile. No zoom in/out control for MVP. User should be able to zoom in/out on mobile through gesture.
- Download: Display 'Download' button to allow user to save high-res image. 
- Identifying info: Display following information.
Title: Display full value (truncation rule tbd).
Copyright type icon: Display related icon. Links to the detail info under 'Access & Usage Info'.
Author: Display header 'Author' and value.
Date of Creation: Display header 'Date of Creation' and value.
Type: Display header 'Type' and value.
Lettering: Display header 'Lettering' and value.
- Access & Usage Info: Closed accordion menu. Display type, description, and link to Creative Commons. 

**Visual Specification**
Tomi will provide the visual design this week.

**Comment by Heesoomoon** [comment]
**Item Page Mobile**
![itempage_mobile](https://user-images.githubusercontent.com/29206031/27787737-cf0756fc-5fdd-11e7-8441-c6da5c7d04be.png)

**Item Page Mobile with Access & Usage Info**
![itempage_mobile_accessusageinfo](https://user-images.githubusercontent.com/29206031/27787747-d4c16aa6-5fdd-11e7-9915-30ff7a31d559.png)

**Comment by Norvard** [comment]
Latest PNGs:

[20170705.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1125217/20170705.zip)

**Comment by Heesoomoon** [comment]
![itemdesktop_mvp](https://user-images.githubusercontent.com/29206031/28117659-3f804c52-6706-11e7-92ee-fd6523f970a2.png)
![itemmobile_mvp](https://user-images.githubusercontent.com/29206031/28117658-3f7eb66c-6706-11e7-80b1-7af5511894b4.png)

**Comment by pollecuttn** [comment]
@Heesoomoon Looks like this is the overall issue for the item page where you can record whether accordions are open or shut on page load. The screenshots suggest 'more info' is open and 'Using this image' is closed. Is that correct?

**Comment by Norvard** [comment]
@pollecuttn The design comp just demonstrates what an open one looks like and what closed one looks like. As I understood, they are all closed on first view.

**Comment by Heesoomoon** [comment]
@pollecuttn I just updated the comps and UI spec to clarify the default state and menu open state.

**Comment by Heesoomoon** [comment]
@Norvard Would you update the ticket to reflect the display logic of portrait or landscape image?
