### ISSUE TITLE
Display of promo label

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1006]
## Type
- ✨ Feature

**Objectives**: Revisit how we display Promo Label to minimise redundancy and to assist user find relevant article by making it easy to scan. The team decided to explore following display logic.

- Suppress 'Article' label on all promo
- Use the promo label to highlight special feature/series (Electric Sublime, Body Squabbles, etc.)
- Hide the promo label when all articles belong to same feature/series (Series Index page, Feature/Series block, etc.)
- Change the display order: 1 Article Title, 2 Promo Label, 3 Author Name (optional)
- Continue to use the icon overlay for article type (Audio, Video, Comic, Image Gallery Article, etc.)

**Next Steps**
- [x] Tomi to mock up Explore landing with new promo label display logic including author name

- Content team to consider creating a block to highlight key authors similar to Series block in Explore landing

**Development effort to be on hold till we revisit the template after Image Search project.**

**Comment by Norvard** [comment]
After reviewing with Heesoo and Jenn, we have 2 options. One to take action on and second to leave for future consideration/discussions.

**Action:**

- [ ] Suppress 'Article' label on all promo
- [ ] Use the promo label to highlight special feature/series (Electric Sublime, Body Squabbles, etc.)
- [ ] Hide the promo label when all articles belong to same feature/series (Series Index page, Feature/Series block, etc.)
- [ ] Change the display order: 1 Article Title, 2 Promo Label
- [ ] Continue to use the icon overlay for article type (Audio, Video, Comic, Image Gallery Article, etc.)

Below is an imagine which shows how this would look like on the Explore page today (2017-06-15)
[WC_Labels_170615.png.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1078286/WC_Labels_170615.png.zip)

**For future consideration:**
Considering including author names within the promos. Initial implementation of this makes the promos and page very busy.
Questions:
Do we include icon to create visual hierarchy?
What is the icon?

**Initial explorations on this:**

No icon:
![screen shot 2017-06-15 at 17 25 23](https://user-images.githubusercontent.com/23660297/27191447-b4281354-51ef-11e7-8423-f00eb67fcd3d.png)
Person icon:
![screen shot 2017-06-15 at 17 25 31](https://user-images.githubusercontent.com/23660297/27191449-b4296ec0-51ef-11e7-893c-7840bcc59161.png)
Various icons:
![screen shot 2017-06-15 at 17 25 38](https://user-images.githubusercontent.com/23660297/27191448-b428ff08-51ef-11e7-9e5e-88304c87b5c6.png)
