### ISSUE TITLE
Home, Exhibitions, Events - Research & Audit

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#1021]
Conduct a review of "best in class" competitor websites within the museum/attraction/events landscape.

Review experiences through a set of user goals:
- I am a new visitor, I want to understand what they do
- I am near venue and planning a visit in near future
- I live far away and planning a visit one day
- I am familiar with x and want to see what is new

Other considerations:
- Mobile and responsive experience
- Editorial content
- Past event content
- Any on-site content/features

Prepare a series of recommendations based on findings that will be used to kick off collaborative creative work with core team and key stakeholders.

**Comment by Norvard** [comment]
Some helpful articles around visitors of museum websites:
http://www.intk.com/en/ideas/visitor-motivation-in-online-museum-audiences
http://marty.cci.fsu.edu/preprints/marty_mmc_2008.pdf
http://mw2015.museumsandtheweb.com/paper/assessing-the-user-experience-ux-of-online-museum-collections-perspectives-from-design-and-museum-professionals/
https://blog.optimalworkshop.com/understanding-museums-digital-audience

**Comment by jamesgorrie** [comment]
@tomi quite a nice load of stuff from the Guggenheim.
http://exhibitions.guggenheim.org/burri/home

**Comment by jennpb** [comment]
@Norvard Is this still a WIP or is it OK to close?

**Comment by Norvard** [comment]
@jennpb close away :)
