### ISSUE TITLE
Digital Story - Mobile scrolling

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#1023]
## Type
- 🐛 Bug

On mobile the scrolling brakes (is really hard and gets stuck). Does not work as smoothly as other scrolling content trays on the page.

Recommendation: On mobile lose the arrow buttons and implement a smooth scroll (if possible)

**Comment by jamesgorrie** [comment]
Can't replicate, might have been fixed in the slew of things that have been fixed.
