### ISSUE TITLE
Will Fractal let us group components more logically?

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1041]
## Type
- ❓Question

It's going to be a lot easier to use Fractal for our pattern library (in the long term) if we can create component families and nest components within, rather than an alphabetical list. 

For example:
- Social
--Twitter
--SM block
--Instapaper ...
- Navigation
--Header
--Footer
--Breadcrumbs
- Buttons
--B1
--B2
--B3

**Comment by davidpmccormick** [comment]
Fractal will let us group components however we please simply by adding sub-directories… but our current implementation that allows us to share components with the app itself relies on our components living in a single `components` directory (so if we changed it as it currently is, the app would break. Which would suck).

We should investigate our options!

**Comment by jamesgorrie** [comment]
Having a flat organisation stops the questions around, "What is this component?" which will inevitably lead to a categorisation that one person understands, and another disagree with (hence the flat component structure, and also with icons, we have "other" and things that don't make sense, it's a good example of the above case).

Could we we close this until we know what the structure is, the value it adds, and we agree on it?

**Comment by jennpb** [comment]
:boom:
