### ISSUE TITLE
Disappearing thumbnails on results list

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1053]
## Type
- 🐛 Bug

Thumbnails appear briefly on results list, then break. What's up with that?

![image](https://user-images.githubusercontent.com/1446139/27475546-8335bea4-57fd-11e7-97b6-e4f2f9444bcc.png)

**Comment by alexwlchan** [comment]
I can reproduce this in Chrome, but not Safari. Guessing it might be some `srcset`-like attribute that:

* Is trying to load in thumbnails that don’t exist, and
* Is supported in Chrome but not Safari?

**Comment by jamesgorrie** [comment]
@gestchild Closed by https://github.com/wellcometrust/wellcomecollection.org/pull/1240?

**Comment by gestchild** [comment]
@jamesgorrie was fixed by #1056, I'll close
