### ISSUE TITLE
Showing content license

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1078]
## Type
- ✨ Feature

## User stories
As any picture researcher, I want to see clear unambiguous information about copyright and usage so that I don't get confused or sued (WI Personas research, 2014) [mvp, to test]

## Acceptance criteria for MVP
- Licence type visible on page (e.g. Creative Commons CC-BY)
- Machine-readable license in metadata
- Licence taken from API

## Future
Can we make friendlier interpretations of the CC licenses which describe the scenarios you're allowed to use image for? #1109 

## Requirements
- [ ] User research
- [x] New component(s) built
- [x] New visual design

**Comment by gestchild** [comment]
Required license types:

CC0
CC BY
CC BY NC
CC BY NC ND
PDM
Copyright not cleared

**Comment by pollecuttn** [comment]
@ChristopherHilton Please update this ticket for the Experience team to see where we've got to towards unblocking this for them.

**Comment by ChristopherHilton** [comment]
User licence is set out explicitly in a MIRO field ("restrictions on use"), mostly in the form of various CC licences, and mapped onto the "licence" property in our ontology: so it should be straightforward for the stuff that's cleared for general public use to display this licence, when the pipeline from the data platform to the digital experience starts flowing shortly.  I think we can take this off the Blocked list.

**Comment by pollecuttn** [comment]
@ChristopherHilton Thanks for this.

It's still blocked for the Experience team until it's available in the API, which it isn't yet.

**Comment by ChristopherHilton** [comment]
Following up: the picklist in MIRO "Restrictions on use" displays various options - some are CC permutations, but there are also options which are actually restrictions on usership ("Academics" etc) which rather overlap with the "Restrictions on Access" field.  So: we can show which CC licence something is made available under, and allow those CC tagged images to be seen.  But we also have a discussion to have about those digital assets that have those non-standard licences - do we want to change them?  For the moment the need isn't that pressing because they tend to apply to the more clinical images: the V images, our immediate priority, tend not to be affected by them as much.

**Comment by pollecuttn** [comment]
@ChristopherHilton 

> the V images, our immediate priority, tend not to be affected by them as much.

Do you know that all the V images we're currently serving up in the API only use CC-type licences? Please check this as we need to know whether there are any of those usership categories that we'll need to deal with.

One of the Platform team's objectives this quarter is to make all WI collections available so we need to think beyond just the V images. So yes, please do go ahead with discussions on what to do when there are things in "Restriction on use" that aren't CC licences.

**Comment by ChristopherHilton** [comment]
There are a rich mix of licence-type instructions in the relevant MIRO field (restrictions on use), some of which are actually restrictions on access and should be in a different field (eg "Academics").  Talking about this with Christy last week, she was happiest with the idea of putting those things with problematic licences of that sort into a dark archive for the moment and dealing with them later (first question for some of them might well be whether we want to keep them at all).  It would certainly make sense to focus on those images that have CC licences (the vast majority) and put the problematic ones to one side (with one exception, to follow...).
The four CC licences represented in the MIRO picklist for that field are:
CC-0 - 1 instance in the V images
CC-BY - 50338 instances in the V images
CC-BY-NC - 2 instances in the V images, although only one of these is copyright cleared to be made visible
CC-BY-NC-ND - no instances in the V images.
The one non-CC licence that we might want to have a think about now is when the "Restrictions on Use" field reads "None": there are 11766 of those in the V images and we should I suppose decide whether to make a blanket decision about those and determine that these are all some flavour of CC.

**Comment by pollecuttn** [comment]
With the V images we'll get:
CC-0
CC-BY
CC-BY-NC
CC-BY-NC-ND
when licences come through the ontology > model > API.

https://github.com/wellcometrust/wellcomecollection.org/issues/1109 is about the Experience team mapping those codes to human-readable content.

Just checking with @jennpb and @jtweed that the mapping to human-readable content will happen at the best place, i.e. by the Experience team rather than something the Platform team could do?

**Comment by jennpb** [comment]
Human-readable should happen on our side, so we can customize the language based on what's working for users and what's not.

**Comment by ChristopherHilton** [comment]
Makes sense, yes.

**Comment by pollecuttn** [comment]
Depends on https://github.com/wellcometrust/platform-api/issues/621

**Comment by alexwlchan** [comment]
Content licenses are now available in the `thumbnail` field, available exclusively for you* and for a limited time only** by adding `?includes=thumbnail` to API requests:

https://api.wellcomecollection.org/catalogue/v0/works?includes=thumbnail

<sup>*actually available for everyone, but I want you to feel special
**offer not valid beyond the heat death of the universe</sup>

**Comment by jennpb** [comment]
@davidpmccormick I'll provide basic human readable blurbs that go with all possible licence conditions on Thursday.

**Comment by jennpb** [comment]
@davidpmccormick Here are the basic blurbs to map to existing licence codes.

CC0 : `Free to use for any purpose`
CC BY: `Free to use with attribution`
CC BY-NC: `Free to use with attribution for non-commercial purposes`
CC-BY-NC-ND: `Free to use with attribution for non-commercial purposes. No modifications permitted.`

Once these are in, this issue can be closed.

**Comment by davidpmccormick** [comment]
@jennpb Just for clarity, are these blurbs to replace the 'This image is free to use with attribution' text below?
![screen shot 2017-08-24 at 12 32 41](https://user-images.githubusercontent.com/1394592/29664641-660ac56c-88c8-11e7-9e60-6e61728aca6d.png)

**Comment by jamesgorrie** [comment]
@jennpb Do we have an example of an attribution - is that the TASL model?

**Comment by jennpb** [comment]
@davidpmccormick. Yep. 

@jamesgorrie I'm working on this as part of #1109
