### ISSUE TITLE
Print stylesheet

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1079]
## Type
- ✨ Feature

## User stories
As an image researcher, I want to print images so that I can discuss them with my colleagues during selection (WL Personas research, 2015)

## Requirements
Need to ensure that users can print item pages through browser/OS controls. 

Exclude:
- Header
- Footer
- Transporters?

Include:
- Body content

**Comment by jamesgorrie** [comment]
Should we perhaps start with what to include as this is a very specific use case.
e.g.
* Image
* Metadata
** title
** description
** date created

I would wonder if we could work more on creating an addressable personal group of images - promoting it when people print, "You can share images...blahblah".

**Comment by jennpb** [comment]
Close for now - referenced in Trello `Now > Next > Later` board
