### ISSUE TITLE
Digitisation on demand background research

### ISSUE THREAD

**Issue by nancetron** [wellcometrust/wellcomecollection.org#1084]
- ✨ Feature

Looking at the existing workflows and UX for user requested digitisation of assets, understanding tech changes and requirements, creating new internal workflows and external experience.

**Comment by jamesgorrie** [comment]
@kenoir FYI

**Comment by pollecuttn** [comment]
@nancetron I was involved in the project for the current digitisation request process implementation (from the Sierra end of creating links with useful parameters for the online forms). Not sure if that makes me someone to talk to or someone to avoid talking to about it at some point!

**Comment by jennpb** [comment]
Nancy's final document here: https://wellcomecloud.sharepoint.com/sites/wcdigitalexperience/Shared%20Documents/_wellcomecollection.org%20-%20current/PhotographyRequest_BackgroundResearch_NW.pdf?csf=1
