### ISSUE TITLE
"FLOW IMAGE" text instead of actual image on Explore article

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1091]
## Type
- 🐛 Bug

In https://next.wellcomecollection.org/articles/outsiders-the-cook there's a string of text: 

> [FLOW IMAGE: Mary Mallon’s cottage from NYC Department of Records]

which I'm guessing should be an image instead?

**Comment by jennpb** [comment]
I've just looked at the article in WP and don't see the FLOW IMAGE anywhere in the WYSIWIG or HTML view. @jamesgorrie any ideas? has something gone wrong in the parsing?
