### ISSUE TITLE
Navigation can hide text content when paging down

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1092]
## Type
- 🐛 Bug

For example on https://next.wellcomecollection.org/articles/outsiders-the-cook at full screen width of 1920px.

I see this issue when I page down the page using the space bar or Page Down.

The text should read:

> had been presented with and knew she would be prevented from working as a cook if she used her own name.

Instead I see this at the bottom of the page:
![first-line](https://user-images.githubusercontent.com/1446072/27688950-4827a058-5cd4-11e7-8155-c3e095ab012b.PNG)

then this at the top of the page when I space bar down:
![first-second](https://user-images.githubusercontent.com/1446072/27688953-49f0bfc8-5cd4-11e7-9c2a-fb567beaf430.PNG)

I can scroll to see the hidden text but it's annoying to have to take my hands off the keyboard to do so.

I'm using Chrome Version 59.0.3071.115 on Windows.

**Comment by davidpmccormick** [comment]
The issue, as I understand it, is that pressing space/page down to scroll down the page will scroll you by almost a complete viewport height (true in Chrome, at least). This is browser behaviour that we don't have control over.

I think the only available fix would be to stop having a fixed position navigation. We should test whether this is the right thing to do #1104.

**Comment by pollecuttn** [comment]
Oh right, we can't control how much of the page is scrolled ourselves? Okay.

In that case testing as you say around the fixed position navigation would be useful. One for @hthair.

I wonder how many other people use the space bar to scroll down, too.
