### ISSUE TITLE
SEO improvements

### ISSUE THREAD

**Issue by derivadow** [wellcometrust/wellcomecollection.org#1099]
## Type

- 🚑 Health report

**Explore index**
- [x] Missing meta name="description"
_Typhoid Mary article currently displaying: "The Outsiders. 1 ... In March 1907 a cook named Mary Mallon was visited by a sanitary engineer at her place of work, .... TO-03-06-Article." on Googles SERP._
- [x] Text needs to be no longer than 160 characters

**Articles**
- [ ] Missing meta name="description"
- [ ] Text needs to be written with the SERP as the context (consider using Google keywords tool when writing)
- [ ] Text needs to be no longer than 160 characters

**Missing Structured Data**
Errors:
- [x] _Author_ field missing
- [x] _datePublished_ field missing
- [x] _image_ field missing
- [x] _publisher_ field missing

Also consider adding:
- [x] _mainEntityOfPage_ field

**Breadcrumb trail**
- Consider adding crumb trail mark-up e.g. Wellcome Collection > Explore > :articleTitle

- For Digital Stories consider: Wellcome Collection > Explore > :DigitalStoryTitle > :articleTitle (although this would require us to link to e.g. https://next.wellcomecollection.org/series/the-outsiders

**Redirect from blog.wellcomecollection.org**
This means that google is indexing blog. rather than next. dot. Without this none of the above changes will appear of the Google SERP.
- [x] Change from 302 to 301 (perm redirect)

**Comment by jamesgorrie** [comment]
All great suggestions. Especially integral before moving from `next.`.

> Change from 302 to 301 (perm redirect)

The reason for this is that we are on `next.` and will change when we hit the route. 

Another task here is to setup Google Webmaster Tools.

**Comment by derivadow** [comment]
There's no harm in 301 from blog. to next. and then in the future to root. The only reason not to use a perm redirect is if we wanted to return to using blog. etc. and therefore wanted Google to continue to associate inbound links + pagerank with the original URL. Because we won't be doing that there is no harm in setting up a perm redirect to next. and then to www/root. But the absence of a perm redirect is actively harming our SEO today.

**Comment by jennpb** [comment]
Reopening this for further discussion and action on missing structured data, index page descriptions, breadcrumb trails and other metadata concerns.

**Comment by jennpb** [comment]
> Another task here is to setup Google Webmaster Tools.

This was done as #1103. Webmaster Tools is now Search Console.

**Comment by jamesgorrie** [comment]
- [ ] explore description needs some love
- [ ] fix Google SERPS for explore https://wellcomecollection.org/explore/timeplace https://wellcomecollection.org/explore/sicknesshealth
- [ ] Workout what to do with list pages like https://wellcomecollection.org/play
- [x] Page title on prismic #1402
- [ ] Sitemaps for images and editorial content

**Comment by jennpb** [comment]
Also relating to #534, I've asked Danny for some content team input on the meta descriptions https://wellcomecloud-my.sharepoint.com/personal/j_phillips-bacher_wellcome_ac_uk/_layouts/15/WopiFrame.aspx?sourcedoc={9e6848a3-a114-40e1-a574-77983a01ec34}&action=editnew

**Comment by jamesgorrie** [comment]
All pieces that haven't been done have their own tickets:
#534
#1574 
#1611
