### ISSUE TITLE
Search results: sort by oldest/newest/relevant

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1107]
## Type
:sparkles: Feature

## UI
According to Visual comp in #1002 
Uses Date of Creation (of the work, not of the digital surrogate)
Default to relevancy defined by ElasticSearch

## Acceptance Criteria
User can sort:
- Best Match (Most relevant)
- Oldest
- Newest

**Comment by jamesgorrie** [comment]
@jennpb do we know what's blocking this?

**Comment by jennpb** [comment]
I wanted to wait until the MIRO data was matched up with Sierra data so that we'd get a more complete   view of the dates. I think MIRO is missing a lot of key structured data for date of creation.
