### ISSUE TITLE
Item page: human-readable license text

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1109]
## Type
:sparkles: Feature

Building on #1078 we need to map licence codes (CC-BY etc) to plain language copy. 

## Acceptance criteria

- [x] User can view narrative statement about what licence means in practical terms: 
- under which circumstances the material can be used
- examples of permitted use

- [x] User can read a general statement about copyright of work

- [ ] User testing demonstrates that people understand their rights and obligations

- [ ] Overall reduction in calls to Enquiries teams.

## User story
As any picture researcher, I want to see clear unambiguous information about copyright and usage so that I don't get confused or sued (WI Personas research, 2014)

**Comment by pollecuttn** [comment]
For external user testing for V images only, this can be fudged on the front end with a CC licence.

**Comment by jennpb** [comment]
Examples:
- Europeana: minimal info plus CC marks http://www.europeana.eu/portal/en/record/9200397/BibliographicResource_3000126285533.html?q=sheep
- MoMA: prose licensing info : https://www.moma.org/collection/works/50608

CC guidance: https://creativecommons.org/licenses/

**Comment by jennpb** [comment]
Send draft options to Chris M from Legal for review today.

**Comment by jennpb** [comment]
This needs to be put into a new drawer below `description`

Drawer: `Using this image` 

Heading: `Licence information`

| Licence code | Blurb | Link
| -------------- | ------ | --------|
|  PDM | You can use this work for any purpose without restriction under copyright law. | Public Domain Mark (PDM) terms and conditions <https://creativecommons.org/publicdomain/mark/1.0/> |
| CC0 | You can use this work for any purpose without restriction under copyright law. | Creative Commons Zero (CC0) terms and conditions <https://creativecommons.org/publicdomain/zero/1.0/> |
| CC BY | You can use this work for any purpose, including commercial uses, without restriction under copyright law. You should also provide attribution to the original work, source and licence. | Creative Commons Attribution (CC BY 4.0) terms and conditions <https://creativecommons.org/licenses/by/4.0/>|
|  CC BY-NC | You can use this work for any purpose, as long as it is not primarily intended for or directed to commercial advantage or monetary compensation. You should also provide attribution to the original work, source and licence. | Creative Commons Attribution Non-Commercial (CC BY-NC 4.0)terms and conditions <https://creativecommons.org/licenses/by-nc/4.0/> |
| Copyright not cleared | Copyright for this work has not been cleared. You are responsible for identifying the rights owner to seek permission to use this work. |

Heading: `Attribution`

**Image credit:** {{Wellcome Collection}} {{Licence code/CC-BY}}.

{{Title | Link}} by {{Creator}}. Source: {{Wellcome Collection}}.{{Licence code | Link}}  
Astronomy: a diagram of the sun, and various effects of sunlight. Coloured engraving.
 (https://wellcomecollection.org/works/ezyb33ve). Source: Wellcome Collection. CC BY (url).  

A man holding a tube of Bubisan brilliantine for the hair (https://wellcomecollection.org/works/ezyb33ve) by Leonhard F. W. Fries. Source: Wellcome Collection. CC BY.

**Comment by jennpb** [comment]
@Heesoomoon @pollecuttn @davidpmccormick @gestchild Ready to go with this one. I left everything in Heesoo's hands.

**Comment by jamesgorrie** [comment]
What we have currently:

`{digitalLocation.license.humanReadableText}`

Credit: `{work.title}`. [`{digitalLocation.credit || iiifManifest.credit}`](https://wellcomecollection.org/works/{work.id}). [`digitalLocation.license.label`]({license.url)
