### ISSUE TITLE
Search results: back to top

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1112]
## Type
:sparkles: Feature

## UI Requirements
See #1002

## Acceptance criteria
Jump to Top: Display the icon on the right bottom corner after user scrolls down 1 or more screen lengths.

**Comment by jamesgorrie** [comment]
I've added tracking onto this in #1124.

Could we have the user need for this?
I wonder if we had that, we could probably come up with something betters we would know what we are trying to solve. It would also allow us to add tracking to know if we're solving it.

Understandably we are doing more face to face user testing, but when we're releasing to more people, it would be good to validate those findings.

The use cases I can think of, but are not based on any user feedback are:
* They haven't found anything useful, and pagination is not available or they don't care to move onto the next page.
* They need to get back to the search bar (there are better ways of signposting this - e.g. back to search bar, which could not lose your position, but rather just bring the search bar into view).

Using this seems almost like an indicator of us failing to provide something better, perhaps a contextual side bar that changes dependant on your filters or ordering? Similar to Google Photos.

(There is also a small concern here of perpetually adding components without ever thinking of deprecating any that aren't working)
