### ISSUE TITLE
Item page: populating with specified data from API

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1114]
## Type
:sparkles: Feature

## Data requirements
As specified in #1004 
Data is only coming into the API via MIRO at this stage. 

## Acceptance criteria
Can display:
- Title of work
- Date created 
- Creator
- License #1078 
- Lettering #1234
- Genre #1232

**Not available in API yet but will need** #1233

- Work: Subject	MeSH/ LoC: MeSH
- Work: Subject	MeSH/ LoC: Library of congress
- Subjects: Names
- Subjects: LCSH place

**Comment by jennpb** [comment]
@davidpmccormick @pollecuttn I'm pretty sure I'm working from the wrong information w/r/t what I think should have been in API initially. Please can you update this issue (feel free to edit above) with what we *actually* have, and then work out how to get what we don't yet have? 

The reason I have the Subject data listed separately is because I know that that is on the Platform roadmap.

**Comment by pollecuttn** [comment]
This is what's available in Works (no Items available currently):

- identifiers
- label
- description
- lettering
- createdDate
- creators

Label is like Title of work in the list above.

So Genre is the only one in the list above that's missing. And all the Subjects.

**Comment by pollecuttn** [comment]
@ChristopherHilton Please update this ticket for the Experience team to see where we've got to towards getting genre available in the ontology and then the API for them.

**Comment by ChristopherHilton** [comment]
"Genre" is a bit of a baggy one which I've been trying to make more precise, with three basic concepts in the ontology:
1/ WorkType - very broad top-level description of what sort of "thing" is this - book, picture, film, etc.  We can do this from fields in Sierra and CALM; and everything coming out of MIRO, of course, is an image.  (If it's an image of something else in the Library and we want to describe what that thing is, the details will be possible to pick up from the Sierra or CALM descriptions if we want to do that.)
2/ Genre - a description of the *content* - eg Obituary, Caricature, Non-Fiction
3/ Format - a description of the "thing" (not its content) in ways that are a bit more precise than WorkType and relate to precisely how that content is delivered - eg VHS video, etc.
Should be OK to do 1/ without too much bother.  Where we got to at the end of Wednesday's modelling session was a realisation that the data as it currently stands may not make it easy to separate 2/ and 3/ - the same fields can mix together information about the content or the carrier medium, annoyingly.  So tomorrow we'll be looking at whether it's possible to peel those apart or whether they have to be crunched together as one thing.
Hope that's helpful - which of these is the sort of thing you had in mind when putting Genre on the requirements?

**Comment by pollecuttn** [comment]
Closing as we have these available for R1 user testing:
- Title of work
- Date created
- Creator

Everything else now has separate issues and can be released and tested when they become available:
License #1078
Subjects #1233 
Genre #1232
Lettering #1234
