### ISSUE TITLE
Item page: put an image on it

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1116]
## Type
- ✨ Feature

## UI Requirements
As specified in #1004 

## Acceptance criteria
- Display available image (hi-res for MVP) in assigned space for desktop and mobile. 
- No zoom in/out control for MVP. User should be able to zoom in/out on mobile through gesture.
- Image coming from IIIF Image API

## User stories
As any picture researcher, I want to see a large high quality image so that I can decide if I want to use it (WI Personas research, 2014)

**Comment by davidpmccormick** [comment]
Closing this as milestone 1 work has been completed by #1200.

The work to show/hide the image controls on hover/tap/page load is being tracked in #1204.
