### ISSUE TITLE
Zoom in on an image

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1125]
## Type
- ✨ Feature

## Requirements
We're pretty likely to want to offer deep zoom functionality beyond what can be done within native browser. What are our options for zooming in on IIIF images? 

Options in the world include: 
- http://iiif.io/apps-demos/
- OpenSeadragon
- https://viewdir.github.io/
- Universal Viewer
....and there are more I'm sure!

**Comment by Heesoomoon** [comment]
@jennpb @gestchild and I've been working on this. I plan to get user feedback on following
- use of icon
- location of CTA
- zoom in/out interaction
Here's the prototype link.
https://invis.io/6XDWSYMPS#/257889595_WorkPage_Update
