### ISSUE TITLE
Start consuming IIIF images from Loris

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1136]
## Type
- ✨ Feature

## Needs
- [ ] Platform team?

## UI Requirements
n/a

## Acceptance Criteria
- [ ] Images coming from IIIF image server, not S3 bucket

## Problem to be solved
Business requirement for using IIIF images

**Comment by BethPF** [comment]
@jennpb Do we need to do this to hit our first milestone of an internal release via a feature switch?

**Comment by jennpb** [comment]
@BethPF @pollecuttn No, I'll remove this from the R1 milestone.

**Comment by gestchild** [comment]
This is done, but still wrapped in a feature flag with imgix fallback.

If platform team are happy, we should get rid of the feature flag and fallback code
