### ISSUE TITLE
Create 'return to results' link for item page

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#1137]
## Type
- ✨ Feature

## UI Requirements
![screen shot 2017-07-07 at 16 55 36](https://user-images.githubusercontent.com/1394592/27965917-3ecd8c40-6335-11e7-9485-c88b1445e084.png)

## Acceptance Criteria
- [x] The interface should have a link that returns the user to the search results page
- [x] and have an arrow icon
- [x] and have 'Return to results' as copy

## Problem to be solved / User Story
As a
 _user_

I need/want/expect 
_to click a link and be returned to the search results page_

**Comment by jennpb** [comment]
👍 nice use of the new issue template @davidpmccormick

**Comment by davidpmccormick** [comment]
Closed by #1145.
