### ISSUE TITLE
Create item page 'header area' markup

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#1140]
## Type
- ✨ Feature

## Needs
- [x] License info component #1138
- [x] Meta unit component #1139

## UI Requirements
![screen shot 2017-07-10 at 10 39 13](https://user-images.githubusercontent.com/1394592/28013259-586d7e94-6560-11e7-965e-28abb193b45d.png)

## Acceptance Criteria
- [x] It should display a title
- [x] it should display license information
- [x] it should display relevant meta information

## Problem to be solved / User Story
In order to
 _find out the most relevant information about an item_

As a
 _user_

I need/want/expect 
_to view its title, licensing information and most relevant meta information with a clear visual hierarchy_

**Comment by Heesoomoon** [comment]
The order of the right column should be
Author, Date, Genre, Subject, Lettering
