### ISSUE TITLE
Build scroll-to-content component

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#1141]
## Type
- ✨ Feature

## UI Requirements
![screen shot 2017-07-10 at 10 39 26](https://user-images.githubusercontent.com/1394592/28013908-a19359c0-6562-11e7-8429-7a337cd7a99e.png)

## Acceptance Criteria
- [x] It should have a downward-pointing chevron
- [x] it should scroll the user to the written information about the item

## Problem to be solved / User Story
In order to
 _not miss the fact there's more on the page than just the item itself_

As a
 _user_

I need/want/expect 
_to have a a visual indication that there is (and the ability to jump straight to) more information lower down the page_

**Comment by jennpb** [comment]
Hey @davidpmccormick, how did the animation on this come about? It wasn't part of what I'd considered to be for this release.

I'd suggest that we should be AB testing the presence of info icon first - no icon and static icon @hthair

**Comment by davidpmccormick** [comment]
Ah, was result of conversation with @Norvard – the thinking being that if you are pinged to the title/info without animation it could be jarring/confusing.

Does 'static icon' mean link to the title/info without animation?

**Comment by jennpb** [comment]
> Ah, was result of conversation with @Norvard – the thinking being that if you are pinged to the title/info without animation it could be jarring/confusing.

We should test first whether that's true :)

> Does 'static icon' mean link to the title/info without animation?

Yep, that's what I meant. Link to title, no jump

>Oh, maybe you mean the 3 second wobble on page load – that was another would-be-nice-to-have design request (easy to put in, just as easy to remove).

I didn't notice this... can you show me what you mean?
