### ISSUE TITLE
Create (section) accordion component

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#1142]
## Type
- ✨ Feature

## UI Requirements
![screen shot 2017-07-10 at 11 30 37](https://user-images.githubusercontent.com/1394592/28014145-7b11b070-6563-11e7-8b65-b2436563108a.png)

## Acceptance Criteria
- [ ] It should have section headings which reveal section contents when clicked
- [ ] it should have a +/- sign to indicate the open/closed state of the section
- [ ] it should persist its open/closed state independently of other sections

## Problem to be solved / User Story
In order to
 _know at a glance what types of information are available on the page_

As a
 _user_

I need/want/expect 
_to see a list of section headings styled such that they indicate more detailed information is available were they to be clicked_

**Comment by jamesgorrie** [comment]
Can we add some meaningful metric to make sure we're building things that are being used and making people's lives easier to the acceptance criteria please?

**Comment by davidpmccormick** [comment]
Closing as duplicate of #1113
