### ISSUE TITLE
PP: Exhibition Stakeholder Interview

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1146]
## Objectives
To better understand business needs and gather requirements for the redesign of Exhibition section on WC.org

## Tasks
- [x] Interview Emily Sargent
- [x] Summarize the interview and share with the team

**Comment by pollecuttn** [comment]
@Heesoomoon Can you please put the outcomes of these stakeholder interviews here, or link to them.
