### ISSUE TITLE
PP: Brand Stakeholder Interview

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1148]
## Objectives
To better understand WC brand requirements, workflow between Brand/Marketing/Curator team for Exhibition & Events and collect any necessary assets from the design team.

## Tasks
- [x] Interview Maz
- [ ] Interview Rachel
- [ ] Summarize and share with the team

**Comment by Norvard** [comment]
Highlights from Maz:
- Maz oversees all design created for each exhibition
- No guidelines for designers, just examples of past materials
- Sometimes main output has been portrait promo, sometimes landscape
- Marketing pushes back against using imagery with no type
- Marketing handles the digital content
- Curator oversees external vendors (design)

**Comment by Heesoomoon** [comment]
**for Rachel**
Explain the project and driving factors
- Redesign the public program based on branding work done by C&T
- CMS
- Tomi's availability
- Iterative design

**Questions**
- What are her thoughts/feedback on current What's On section?
- What are some business objectives from her team for the project?
- How should we measure success?
- Any thoughts on the project process?
- What's her role on the project? How and when to involve her?
- Anyone else to follow up with?
