### ISSUE TITLE
PP: Talk to venue visitors

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1158]
## Objectives
Talk to visitors to better understand their needs and pain points regarding 'What's On' section of the website

## Tasks
- [x] plan questions to ask ppl
- [x] Talk to visitors
- [x] Summarize findings

**Comment by Heesoomoon** [comment]
Research Objectives
To find out what kind of information our visitors expect before and after visiting WC
To find out if the current site satisfy their needs
Any improvements?

INTERCEPT QUESTION
Hello! Do you speak English? My name is [your name]. I work for Wellcome Collection [Show your badge]. We are currently exploring new ideas for the website and would love to get your feedback. Would you be available for 5 minutes or so?

Interview Questions
[Casually ask where they are from and their profession]
[Record rough age range]
[If group] Who are you visiting with?

1 About Today's visit
1.1 What was the purpose of your visit today?
1.2 Is this your first visit to WC? [If not] How often do you visit? Why did you return?
1.3 Where did you hear about WC?
1.4 How long did you spend?
1.5 What was most memorable?
1.6 What were you expecting to see or learn and was your expectation met? Why or why not?
1.7 How would you rate your experience today? out of 5
1.8 How could we have improved your experience?

2 Planning
We want to ask you a little bit about how you planned your visit.
2.1 How often do you visit museums? Do you tend to check out their websites before your visit?
2.2 Have you visited our website?

3 If Yes
[open a browser, ask them to walk you through]
3.1 How did you get to our website?
3.2 What information were you looking for? Were you able to find out?
3.3 Did you check out any other parts of the website?
[have them check out what's on section]
3.4 Is this what you expected to see?
3.5 Any suggestions for improvements?

4 If No
[show the homepage]
4.1 What would you expect to see under 'What's On'?
[take them to the page]
4.2 Did it meet the expectation?
4.3 What other information would you expect from this page?
4.4 Any suggestions for improvements?

5 Follow up
5.1 Would you recommend the museum to your family and friends?

[Thank you for your time!]

**Comment by hthair** [comment]
Link to feedback (things will be added in future too): https://docs.google.com/spreadsheets/d/1C_0g9Jg9kTZJDHWBPjy45clb2F_EDtbhrtaX4paDe4w/edit?usp=sharing
