### ISSUE TITLE
Digital story navigation: currently reading not shifting into view

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1176]
## Type
- 🐛 Bug

## Problem
When landing on part 4, 5 or 6 of a digital story, the navigation should shift that story part (Currently Reading) into view

## UI Requirements
![2017-07-14_0749](https://user-images.githubusercontent.com/1446139/28201493-3026204c-6869-11e7-991f-9a7e94c7026e.png)

## Problem to be solved
Reader should see what part of the story she is on when landing on

**Comment by Norvard** [comment]
This is something @gestchild already implemented... so not sure why its not working.
He plans on investigating. Should be an easy fix 👍
