### ISSUE TITLE
Search results: truncate title when it is too long

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1184]
- ✨ Feature

## Needs

- [ ] User research
- [ ] New visual design
- [ ] Analytics and/or component tracking

## UI Requirements
See https://github.com/wellcometrust/wellcomecollection.org/issues/1002
See https://github.com/wellcometrust/wellcomecollection.org/issues/772

## Acceptance Criteria
- [x] The interface should truncate titles on results pages per the design

## Problem to be solved / User Story

In order to be able to scan results quickly, as a user, I expect titles to not take up too much space

**Comment by Heesoomoon** [comment]
Need some discussion with @davidpmccormick and @gestchild on potential solutions.

**Comment by BethPF** [comment]
@Heesoomoon what was the outcome of the discussion please?

**Comment by Heesoomoon** [comment]
@BethPF we haven't had the discussion.

**Comment by pollecuttn** [comment]
@alexwlchan This issue is dependent on https://github.com/wellcometrust/platform-api/issues/616

Please update this issue when https://github.com/wellcometrust/platform-api/issues/616 is done.

**Comment by pollecuttn** [comment]
@alexwlchan Also please update this with the length of the longest description in the V images so we can know how long the longest V collection title will be displayed on the item page.

**Comment by alexwlchan** [comment]
It looks like this change has been applied, but only partially. e.g. https://api.wellcomecollection.org/catalogue/v0/works/q38bsy7a has the change, but https://api.wellcomecollection.org/catalogue/v0/works/a22au6yn doesn’t.

Maximum length will be 3914 characters.

**Comment by davidpmccormick** [comment]
> Maximum length will be 3914 characters.

Is that the theoretical maximum, or is there an item with a 3914 character title?

**Comment by alexwlchan** [comment]
>> Maximum length will be 3914 characters.

> Is that the theoretical maximum, or is there an item with a 3914-character title?

That is the length of the longest title in the V collection of Miro.

**Comment by alexwlchan** [comment]
Here’s the work in question: https://api.wellcomecollection.org/catalogue/v0/works/r7e5p7m6

**Comment by alexwlchan** [comment]
Okay, the reindexer has run now, and items in the API have long-form labels where appropriate.

**Comment by pollecuttn** [comment]
https://github.com/wellcometrust/platform-api/issues/694 will give shorter titles for V collection images.

**Comment by alexwlchan** [comment]
We’re deploying a couple of changes to the way we processing image titles – it may go up or down, I don’t know for sure (and it’s now complicated enough that I can’t easily find out with a local script).

I suspect that for now, titles will get shorter – but as we get to Library content, there are definitely long titles on the horizon.

**Comment by pollecuttn** [comment]
Hi @gestchild - what is the rule for this? Are titles truncated at a certain length, or by some other logic? Can you explain it here so we've got the rule visible in this ticket, please?

**Comment by gestchild** [comment]
The truncation is purely a visual treatment. There is a max-height on the title text, so that it can't more than 80px. In practice, at the defined font-size, this means only up to four lines of text will display, with the last line faded out.

**Comment by BethPF** [comment]
Is this a temporary or permanent solution? Do we need to create a backlog issue to remove/change this when backend changes are delivered? When backend changes are delivered will this "break" the front end?

**Comment by alexwlchan** [comment]
> Do we need to create a backlog issue to remove/change this when backend changes are delivered? When backend changes are delivered will this "break" the front end?

Just FYI, we don’t have any plans for more changes to the way titles are presented in the API.
