### ISSUE TITLE
PP: Design Exploration-What's On

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1208]
## Type
UX Discovery 

## Objectives
To refine based on the team's feedback 

## Tasks
- [x] Create the design
- [x] Review with the team

**Comment by pollecuttn** [comment]
@Heesoomoon Are there now designs that are available as an outcome of this issue that can be put/linked to from here? Or does this lead to a new ticket for the designs to go on?

**Comment by Heesoomoon** [comment]
The latest design from Tomi are posted 
https://wellcomecloud-my.sharepoint.com/personal/h_jennings_wellcome_ac_uk/_layouts/15/guestaccess.aspx?guestaccesstoken=c6bAzp070lc4OaLmtus3uwNJQ%2bcwIkE7cRrovkSaxU8%3d&folderid=2_181327914535147afa3427c3bb01c97e1&rev=1

The design will be updated for the prototype #1286.
