### ISSUE TITLE
PP: Design Exploration-Refine

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1209]
## Type
UX Discovery

## Objectives
To refine the design based on the team's feedback

## Tasks
- [ ] Exhibition
- [ ] Events

**Comment by Norvard** [comment]
Sketch files are on 1D:

https://wellcomecloud-my.sharepoint.com/personal/t_lahdesmaki_wellcome_ac_uk/Documents/Design%20delivery/Public%20Program/Latest%20Sketch%20files/WC_Exhibition_170712.sketch

**Comment by Heesoomoon** [comment]
The latest design mockups
https://wellcomecloud-my.sharepoint.com/personal/h_jennings_wellcome_ac_uk/_layouts/15/guestaccess.aspx?guestaccesstoken=c6bAzp070lc4OaLmtus3uwNJQ%2bcwIkE7cRrovkSaxU8%3d&folderid=2_181327914535147afa3427c3bb01c97e1&rev=1
