### ISSUE TITLE
Build text styles

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#121]
- [x] Body copy 
- [x] Standfirst
- [x] H1, 2, 3, etc
- [x] Bullets
- [x] Link styles

@davidpmccormick

**Comment by davidpmccormick** [comment]
Waiting for standfirst re-design.

**Comment by jennpb** [comment]
https://cardigan.wellcomecollection.org/components/detail/body-content.html

**Comment by jennpb** [comment]
Ok for me to close this @davidpmccormick?
