### ISSUE TITLE
Build block quote styles

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#122]

**Comment by davidpmccormick** [comment]
'Done' as far as the current designs are concerned (although I think there's an outstanding question regarding whether or not there's a further/different blockquote style required).

**Comment by jennpb** [comment]
We talked about the pull quotes and block quotes with Danny today.

The pull quote is good as is.

The block quote should have quote marks removed, feel more a part of the narrative structure 

@Norvard
