### ISSUE TITLE
Build image styles

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#123]
- [x] Header hero
- [ ] Header hero with caption
- [ ] Inline image without caption
- [x] Inline image with caption

**Comment by davidpmccormick** [comment]
Added hero/inline images with captions. Original designs show reversed-out caption text over the image. I haven't implemented this because of accessibility and tech considerations. Currently, the hero image style is the same as the inline images, but the image is full-bleed.

**Comment by jennpb** [comment]
Here's an example of an image without a caption: https://next.wellcomecollection.org/articles/fly-sugar-crystals

- remove camera icon
- remove extra space for caption
