### ISSUE TITLE
Preparing Usability Sessions on Images Search

### ISSUE THREAD

**Issue by hthair** [wellcometrust/wellcomecollection.org#1230]
## Type

- 🚑 Health report

## Needs

- [ ] User research

- [x] advertise for internal users
- [x] reserve room (check with Sophie)
- [x] plan task/questions
- [x] check room and install silverback (or bluejeans)
- [ ] pilot sessions
- [x] have consent forms ready

**Comment by pollecuttn** [comment]
@hthair Can this user testing preparation ticket be closed now? Is all the prep done?

The ticket for conducting the testing is https://github.com/wellcometrust/wellcomecollection.org/issues/1268 and I'll move the problem to be solved to that ticket.

**Comment by hthair** [comment]
@pollecuttn Yes prep is done, I'll refer to the other ticket for conducting :) thanks
