### ISSUE TITLE
Item page: populating with subjects from API

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1233]
- ✨ Feature

## Data requirements
As specified in #1004 

## Acceptance criteria
Can display:
- Subjects

**Not available in API yet but will need**
- Work: Subject	MeSH/ LoC: MeSH
- Work: Subject	MeSH/ LoC: Library of congress
- Subjects: Names
- Subjects: LCSH place

**Comment by pollecuttn** [comment]
Subjects from the API was originally on #1114

**Comment by pollecuttn** [comment]
Subjects are now showing up in the API but these will be changed by the Platform team so consider this still blocked.

**Comment by jennpb** [comment]
This has been done, in all of its uncontrolled glory.

![25-08-2017 13-59-18](https://user-images.githubusercontent.com/1446139/29715106-cdcca136-899d-11e7-99b7-49a2de3f983e.png)
