### ISSUE TITLE
Item page: populating with lettering from API

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1234]
- ✨ Feature

## Data requirements
As specified in #1004 

## Acceptance criteria
Can display:
- Lettering

**Comment by pollecuttn** [comment]
Subjects from the API was originally on #1114

**Comment by alexwlchan** [comment]
Lettering is now appearing in the API, _and_ showing up on Works pages. How fancy is that?

https://next.wellcomecollection.org/works/a24dbqqp

**Comment by jennpb** [comment]
Closed via https://github.com/wellcometrust/platform-api/issues/843
