### ISSUE TITLE
Images: Conduct first round of user testing

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1268]
4 sessions of user testing

## Problem to be solved / User Story

In order to
accomplish a goal

As a
images researcher

I need/want/expect 
be able to find and decide whether to use an image.

**Comment by hthair** [comment]
Two participants tested. Link to full recordings here: https://bluejeans.com/s/Jc63c

**Comment by hthair** [comment]
5 people tested. Feedback meeting happening later today. Slides with high level feedback being created and will be shared soon.
