### ISSUE TITLE
Images: high-level planning for round 2 of user testing

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1269]
## Needs
- [ ] User research

- [ ] get recruitment plan in place
- [ ] recruit users for testing
- [ ] update test script
- [ ] find out how to do remote screen share for testing
- [ ] reserve room (check with Sophie)
- [ ] check room and install silverback (or bluejeans)
- [ ] pilot sessions
- [ ] have consent forms ready

**Comment by hthair** [comment]
I'm closing this for now, as we did a second round but didn't have a focus on images. We can reopen when we are doing so.
