### ISSUE TITLE
Images: understand what can be done on search landing page

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1270]
@Heesoomoon wants to understand what can be done with the search landing page for remote testing.

Heesoo will talk to devs to find out what can/can't be done.

**Comment by jennpb** [comment]
Can this be done simply with text below the search box? 
What messaging needs to be in place?

**Comment by Heesoomoon** [comment]
@jennpb I've reviewed the ideas for the Image Search Landing with David and here's the summary of  our discussion.

**Problems to be solved** 
When we go live with the public with the image search feature, we would like to inform the users on what the image search is about and the beta status (not all features/images are available).

**Potential Solutions**
- Update the text to ‘Search image collections’ in the search field for the internal testing (done)
- Add a tagline ’Explore [53,000+] items from Wellcome Image collections’ above the search field
- Link to https://next.wellcomecollection.org for more information

Nice to have
- Showcase sample images to reflect the type of images available in the collection
- Test different ideas for new features (ability to browse collections, access to recently viewed items, etc.)

**Next Steps**
- Need to scope the effort and prioritize before going live with the public

**Comment by jennpb** [comment]
Thanks for the update @Heesoomoon 

**Potential Solutions**
I think we could add text below the search box that could be updated to reflect the progress. I'm not so sure about the tagline: people don't know how many images are in WI now, so they're not going to know that 53K is a subset. 

I wonder about a NEW! starburst or some kind of visual that draws attention (rather than calling it a beta). For example: 

:boom: :new: You can now search and download images from our collections. All images are free to use under Creative Commons licences. 

**Release notes**
August 2017: 53,000 artworks, including paintings, prints and drawings are now available!

**Comment by Heesoomoon** [comment]
@jennpb The number of available images can help to set the expectation. Including it in the release notes seems like a good solution.

Btw, current search landing is a bit confusing with the footer right below the search field (one user already commented about it.). What do you think of taking user to the Next landing (https://next.wellcomecollection.org) with the search field below the nav? 

And should we close this ticket and create a new one for the design and development?

**Comment by jennpb** [comment]
@Heesoomoon If we do that, I want to reconsider that huge image; I think it's distracting and doesn't serve a purpose. Do you have any thoughts on that image on next.?

**Comment by pollecuttn** [comment]
@Heesoomoon Yes, design and dev would be separate issues, thanks.

**Comment by Heesoomoon** [comment]
@jennpb Users are attracted to images in general and it makes the landing more inviting. However, it needs to be purposeful. It should reflect the collection and keep useful information above the fold. I think NYPL's solution works well. https://digitalcollections.nypl.org 

Btw, let's keep the search landing separate so we can explore different features and ideas on that landing. Let's discuss tomorrow and I can mockup the recommendation.

**Comment by Heesoomoon** [comment]
Met with the team and finalized the scope of work. Design work to be posted to #1337
