### ISSUE TITLE
Public Program: User Research Objectives & Plan

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1272]

**Comment by Heesoomoon** [comment]
**Public Program Project Goals**
Engagement: increase time spent on the page and onward journey
Useful: provide the information 
Inspirational: inspire users to come visit the venue

**Research Objectives**
Inform the team on what features would be useful 
Help to prioritize the features for MVP

**Assumptions to Validate**
Immersive experience and rich media will increase engagement
Photos of people and environment give better context of the exhibition and events

**Flow/Pages to Test**
1 Public Program Landing (What’s on)
What does user expect to see from the homepage vs. What’s on? 
What’s the purpose of What’s on? Inspirational or informational?
Do they find personal messaging useful?
Does the content make sense?
Does the order of information make sense?
Is it the right amount of information?
Does the wording/grouping make sense?

2 Exhibition
What do they expect to see from the Exhibition page? (Probe on items, videos, reviews, etc)
Does the content make sense?
Does the order of information make sense?
Is it the right amount of information?

3 Events
What do they expect to see from the Events page?
Does the order of information make sense?
Does the content make sense?
Is it the right amount of information?

**Research Methods**
In-person interviews with visitors from 183
Remote interviews with user panel group

**Prototype Fidelity**
TBD

**Comment by jennpb** [comment]
@Heesoomoon @hthair Do we have enough information to be able to create user stories before conducting the research? The Goals listed above are very much for Wellcome, not for the users, and we should be testing against user needs.

**Comment by Heesoomoon** [comment]
@jennpb We can create a high-level set of user stories based on the potential user profiles we presented to the team:
- Potential visitors planning a visit
- Venue visitors wanting contextual info at the venue
- Venue visitors wanting more information after the visit
- Social media visitors wanting to find more information about the event/exhibition
- Global visitors who may not visit the venue

However, these are our assumptions and need to be validated as well. I think the research will help us uncover user needs and help us to refine and prioritise our user stories and features. Let's chat today.

**Comment by Heesoomoon** [comment]
**User Stories**
- Users can view and navigate to specific exhibition/event
- Users can find out basic information about exhibition/event
- Users can view information about the objects from the exhibition
- Users can view related exhibitions/events/stories.

**Comment by hthair** [comment]
These can be edited, but this is what I'm thinking so far. I've tried to make sure they cover the points above. Will need to decide what we want to take to 183 and what should be remotely tested. Currently might be a bit long for 183 with all of them. 

**Public Programme research questions** 

* How did you plan your visit before coming here today? 
* Do you often visit other museums and galleries? 
* Why did you want to come here today? (to find out why they come to see exhibitions and events, was it by chance, were they passing by, did they come for one but then enjoy another?) 
* Do you usually plan your visit beforehand? How? 
If they did visit website:  
* What information were you searching for? 
* Did you find all the information you were looking for? 
* Did you come across other things that were useful that you weren't necessarily looking for? 

Show them home page 
*Is this the sort of thing you would expect from a home page? Is there anything you'd expect that you can't locate on this page? 

New design pages 
* "we're redesigning currently and have some new versions of existing pages we'd like to show you. Can you imagine if you were planning your visit and have a look through this new design and tell me what you think of it" [also get them to click on things we want like anchor links] 

Gather general comments, then cover specifics if not already mentioned: 
What's on 
* How do you feel about the amount of information available on the page? (try to probe if it's too much, or too little) 
* Is this what you were expecting to see under 'what's on'? (If no, why not?) 
*Is there anything in particular about this page that would make you want to find out more?/is there anything presented here that would make you more likely to come and visit? 
* [if we can use mock up of current exhibition..] having visited here today, do you feel what you can view on these webpages accurately reflects what you've seen today? 
* Is there anything in particular you really liked about this page? 
[show alternate page and ask same qu's. Counterbalance order of showing pages] 
*Which one did you prefer and why? 
*Was there one that you preferred visually regardless of the information?/was one design easier to extract relevant information from? 
 
End questions: 
*After your visit, either here today, or at other museums, is there usually anything you want to follow up on by visiting the website after? 
*If you enjoyed the event or exhibition you came to see today, would you be keen to find out about related events/exhibitions, both past and upcoming? 
*Need to make this less leading: Having seen these now do you think you'd be likely to visit our site before your visit next time or do you think you would turn up without checking what's on?

**Comment by hthair** [comment]
New tickets are being created for each aspect of the research. See #1323
