### ISSUE TITLE
Don’t request the info.json for image dimensions on the search page

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/wellcomecollection.org#1287]
## Type

- 🚑 Health report

## Acceptance Criteria

Search pages only request the image files, not the info.json for images.

## Problem to be solved / User Story

This should improve the performance of search pages, by reducing the number of API calls required. This backs out the hacky fix in #1240.

Blocked on https://github.com/wellcometrust/platform-api/issues/698.

**Comment by kenoir** [comment]
Related to: https://github.com/wellcometrust/wellcomecollection.org/issues/1288

Reducing the number of requests to display an image will increase page load performance.

**Comment by alexwlchan** [comment]
Loris now supports arbitrarily large images! 🎉 

https://iiif.wellcomecollection.org/image/V0000003.jpg/full/5000,/0/default.jpg
