### ISSUE TITLE
Image Search Page performance

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/wellcomecollection.org#1288]
## Type
- Health/Feature

## Needs
- [ ] User research to identify optimal loading strategies.

## Acceptance Criteria
- [x] Performance budget for image search pages
- [x] Performance budget met!

## Problem to be solved / User Story
In order to return usable search results to users, the search pages should return useful images as quickly as possible.

**Comment by jennpb** [comment]
@pollecuttn @davidpmccormick @jamesgorrie @kenoir Do we know where we are with this one? I know it's being monitored in dotorg-explosions but it's not clear who needs to do what next.

**Comment by jamesgorrie** [comment]
I'm not sure this is - we can start looking at how to get RUM on images only perhaps, and then roll forward with perf improvements.

**Comment by gestchild** [comment]
The search page is being monitored on speed tracker with the same startRender and speedIndex metrics as other pages. We're also passing a parameter in the url for the test, which means images always come from origin, not the CDN, which simulates the slowest the page will ever be.  

The page is consistently passing: http://ghp.wellcomecollection.org/speedtracker/works/?period=week

**Comment by davidpmccormick** [comment]
We should add some of the speedtracker stuff to our perf principles in Cardigan (currently threadbare): https://cardigan.wellcomecollection.org/docs/principles.html#perf

**Comment by pollecuttn** [comment]
Does this still need 
> User research to identify optimal loading strategies

if the page is passing the speedtracker test? It sounds like it doesn't and this issue could be closed (and a new issue opened related to this for adding speedtracker stuff to Cardigan).

But is there still work to be done around RUM on images (per James' suggestion)?

**Comment by gestchild** [comment]
Closing this issue, as discussed with Natalie and have created new ones (#1476 ) to address issues raised above.
