### ISSUE TITLE
Images: UX/devs to get joint understanding around options for downloading images

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1301]
## Problem to be solved 
Understand what options are available around downloading images from works pages, e.g. size, crop, rotation, etc

**Comment by Heesoomoon** [comment]
Gareth and Heesoo went over initial scope of the download feature.
- Allow user to choose from different image sizes: Original Image and Current Image with option to add additional sizes based on user feedback.
- Display image dimension: width and height (need to follow up with the platform team)
- Display license info: "Free to use the image with ..."
- Explore the location of all actions: View Info, Download, Copy Link 
- Explore different options to display the action links: Icons only, Icons with label, etc.

Next Steps: Need to review the scope and design with the team and work with David to implement the feature (open a ticket).
