### ISSUE TITLE
Digitised content UX: find competitor web sites

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1305]
## Problem to be solved

Find and list similar web sites for user research

**Comment by jennpb** [comment]
**Book readers**
Internet Archive - https://archive.org/details/BAMD1944-12No83 
IA Book Reader view - https://archive.org/stream/b28652162#page/1/mode/2up

**Comment by jennpb** [comment]
@Heesoomoon Are you happy for me to close this?
