### ISSUE TITLE
PP: meet with brand team to review hero image for What's On

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1308]
## Problem to be solved
We need to get images for the next two exhibitions to go into Prismic.

**Comment by Heesoomoon** [comment]
Met with Lindsay and Chloe from the brand team and reviewed the latest hero image treatment.
- They agreed to create multiple exhibition images to be used for hero and promo spots. This provides them creative control over how images are displayed.
- Chloe is working on Ayurvedic Man and plans to explore different treatments once the lead object is selected. She mentioned the campaign will be object driven and it will fit nicely with the current design treatment. However, she wanted to find out how it will scale for mobile experience. 

Next Steps: Meet with David/James on following questions.
- Could we apply different hero image for the mobile? 
- Could we fix the max width of the hero image for desktop to allow for creative control?
- Could the brand team assign focal point for the image?
- Could the template support to display video and a background image in the hero spot?
- Could the brand team assign color scheme per exhibition?

**Comment by Heesoomoon** [comment]
I followed up with David and here’s the latest update.
Assigning a focal point on the image won't be part of the scope. Therefore, he suggests following options:
• The new template can support separate hero images for desktop and mobile. This allows for creative control on how the image is positioned in the layout per device.
• We can fix the max width of the hero image for the desktop if desired. We may want to look at the design and see if this is something we want to explore.
 
Also, we can support video, and a background image in the hero spot and ability to chose a colour scheme from a fixed set of options.
