### ISSUE TITLE
Public Programme: follow up with exhibitions team on getting images and contents for next two exhibitions

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1309]
## Problem to be solved
We need images and contents in Prismic for the next two exhibitions.

How do we get these? Who is responsible?

**Comment by Heesoomoon** [comment]
Here's the [summary](https://wellcomecloud-my.sharepoint.com/personal/h_jennings_wellcome_ac_uk/_layouts/15/guestaccess.aspx?guestaccesstoken=JwmwE6BVW54mn6O8qvBnkqadFKt45pUmXWsOykmmPIY%3d&docid=2_17ab4b078bae541d7bf372a78baa14b14&rev=1) from the meeting with Barbara who's the curator for Ayurvedic Man.

**Comment by Heesoomoon** [comment]
I'll be meeting with Becca, the project manager on 'Can graphic design...' next Monday.

**Comment by Heesoomoon** [comment]
Here's the [summary](https://wellcomecloud-my.sharepoint.com/personal/h_jennings_wellcome_ac_uk/_layouts/15/guestaccess.aspx?guestaccesstoken=UH4pGkD5tBCztwmVtTL55xixt7yxWh43N9IfcRPag7w%3d&docid=2_136bae9ce123340498ec012f64d3b91a5&rev=1) from the meeting with Becca, the project manager on 'Can Graphic Design Save Your Life'.

**Comment by Heesoomoon** [comment]
@jennpb @jamesgorrie I've created the spreadsheet with the latest updates and posted on the team folder.
https://wellcomecloud.sharepoint.com/sites/wcdigitalexperience/Shared%20Documents/Project_PublicProgram/PublicProgram_Content.xlsx?d=w62a94ceb27f84eebb3971a1ab8903e36&csf=1

**Comment by Heesoomoon** [comment]
We will be providing a template for the brand team to create the hero image. I'm closing this and create a separate ticket to collect the visual assets for the Ayurvedic Man exhibition.
