### ISSUE TITLE
Improve diagnosis of 500 alerts

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1313]
## Type
- 🚑 Health report

as mentioned in a standup

**Comment by jamesgorrie** [comment]
Closing as we have sentry and CloudWatch alerts - when we move to using the modules created by the @wellcometrust/platform team , we get some stuff there for free.

We might have a consolidated error platform (ELK) - but this shouldn't exist here and the effort put into developing it has dwindled.
