### ISSUE TITLE
Public Program: Design Research with Gallery Visitors

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1323]
## Type
Research

## Objectives
1 To validate visitor planning workflow and their motivation
2 To gather user feedback on new features: image gallery, videos, messaging, anchor links, social media, etc.

## Methods
Contextual interview, Intercept at 183

## Design Prototype
Concept 1 https://invis.io/C3CZQD0GT
Concept 2 https://invis.io/Q3CZQGW8M

**Comment by Heesoomoon** [comment]
@hthair Would you revise the interview questionnaire and link to this ticket? Let's go over the research methods and discuss during the planning meeting.

**Comment by hthair** [comment]
#1335 new ticket continues from this one. Intercept questions being selected and intercept on website being planned this week. Another ticket will be opened to refer to interview qu's too.
