### ISSUE TITLE
Do old dates deter people reading editorial content?

### ISSUE THREAD

**Issue by hthair** [wellcometrust/wellcomecollection.org#1326]
## Type

- 🚑 Health report

## Needs

- [ ] User research

Editorial want to know whether having dates on their articles is useful or not. When sharing older content with users, would the date deter them from engaging? 

Talk to users either in person or using pop-up survey on explore (to target those more likely to engage with editorial content) to ask this.

**Comment by jennpb** [comment]
@hthair do you know if this is being covered in the Systems Concepts research?

**Comment by hthair** [comment]
@jennpb I checked and this wasn't something directly covered and didn't seem to come up in the interviews. I'll add this to our research questions backlog notion board for now.

**Comment by jennpb** [comment]
Ok. I'll close the issue for now as we won't be taking any action on it immediately.
