### ISSUE TITLE
Article title in URL

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1327]
## Type
- 🐛 Bug or Feature?

## Problems to be solved
The problem now is that the URL is unfriendly for sharing. Best practice is to allow readers to understand what they're clicking on.

The other problem is that this makes it really difficult when looking at Google Analytics to gain any quick insight about content performance. 

## Needs
- [ ] Analytics and/or component tracking

## Acceptance Criteria
- [ ] Editors should be able to set a title stub in Prismic
- [ ] Articles should have a human-readable name, e.g. /articles/sharing-nature-parks-for-people instead of /articles/WYnDgyoAAOKcYTk1

**Comment by jennpb** [comment]
Here are reasons why we need to do this:

http://web.archive.org/web/20130907044718/http://www.not-implemented.com/urls-are-for-people-not-computers/

https://moz.com/blog/15-seo-best-practices-for-structuring-urls 
`First, keywords in the URL help indicate to those who see your URL on social media, in an email, or as they hover on a link to click that they're getting what they want and expect`

`Second, URLs get copied and pasted regularly, and when there's no anchor text used in a link, the URL itself serves as that anchor text `

`URL is one of the most prominent elements searchers consider when selecting which site to click.`

**Comment by jamesgorrie** [comment]
Excerpts as to why we decided not to do this:

> Most people don't see the full path of the URL
> Most clients for sharing now use embeds / cards (including email)
> SERPs the domain is displayed but the rest of the path is replaced with the crumb trail
> Google doesn't use this when determining pagerank

As adding unique URLs is actually a very hard job, and inconsistent with what we're doign everywhere else across the product, I would be inclined to ask to wait till we get told it's a problem and then come up with a better solutions.

Having data in a URI is a nasty hack of the internet before metadata / JSON-LD become a thing, using them as URIs is best practice... but, if we get told it's a problem we can look why e.g. We aren't using the correct JSON-LD / OG data thus confusing people.

**Comment by jamesgorrie** [comment]
> a very hard job

When I say that, I mean it's a bit of work to do a shit job, to do it properly is hard, hence the platform team's ID Minter.

**Comment by jennpb** [comment]
Ohhh kay.
