### ISSUE TITLE
Google Scholar tags

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#1333]
## Type
- 🚑 Health report

## Problem to be solved / User Story

In order to
 _get indexed well from Google Scholar_

As a
 _Bot_

I need/want/expect 
_to find the relevant meta tags_

Guidelines:
https://scholar.google.com/intl/en/scholar/inclusion.html#indexing

Example site:
http://www.britishartstudies.ac.uk/issues/issue-index/issue-6/wound-man

**Comment by jennpb** [comment]
https://wellcome.slack.com/archives/C294K7D5M/p1502715037405453?thread_ts=1502709477.793988&cid=C294K7D5M

**Comment by jamesgorrie** [comment]
From @derivadow 

> Google Scholar won’t index our content :disappointed: they are very focused on scholarly peer reviewed articles.

> When I joined I was in contact with them to see if they would include the unique content but it wasn’t in their scope
