### ISSUE TITLE
Images: Workpage Action Enhancement

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1361]
## Type
- ✨ Feature (enhancement to #1334)

## Problem to be solved / User Story
Make visitors aware that they can use and download the image using clear CTA.

**Comment by Heesoomoon** [comment]
Here's the concept with buttons for Download and Save to a list.
https://wellcomecloud.sharepoint.com/sites/wcdigitalexperience/Shared%20Documents/Project_CollectionWorks/UX/Screens/Download_Desktop_Concept1.png?csf=1

**Comment by jennpb** [comment]
@heesoomoon can we close this? I assume we'll end up with new components that aren't these?
