### ISSUE TITLE
Troubleshoot crawl errors from Google Search Console

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1365]
## Type
- 🚑 Health report

## Problem to be solved 
In the last week or so we have had a big spike in server errors and not founds. 
https://www.google.com/webmasters/tools/crawl-errors?hl=en&siteUrl=https://next.wellcomecollection.org/

- What's causing this sudden surge?
- Is there any way we can set up alerts?

@jamesgorrie @davidpmccormick @gestchild You should all have full access to Search Console

**Comment by jamesgorrie** [comment]
@jennpb any chance of getting a screengrab, I am getting no errors.
This is also for next. whereas we should use the root domain me thinks.

**Comment by jennpb** [comment]
It was from August, so I don't have a screen grab - which is why I closed it because I thought if it had come up again since then we would have noticed.

**Comment by jamesgorrie** [comment]
ah - sorry, completely missed that, I thought I was reading your comment, not the fact it was closed...
