### ISSUE TITLE
Standalone image gallery

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1369]
## Type
✨ Feature

## Needs
- [x] Content from Content Team 
First standalone gallery for CGDSYL:
https://wellcomecloud.sharepoint.com/sites/wcdigitalexperience/Shared%20Documents/_wellcomecollection.org%20-%20current/Editorial-Content-Storytelling/Image%20galleries/Graphic%20gallery%20RED%2001.docx?d=w6d6db114269a4ff58c1854bb124ba5d6&csf=1

Example image gallery from previous exhibition:
https://wellcomecollection.org/articles/selection-z-objects/

- [ ] New visual design
- [ ] Analytics and/or component tracking

## UI Requirements

Page should include:
- Title
- Standfirst
- Author (optional)

Each image has:
- Image (landscape or portrait)
- Flexible length copy, not hidden 
- Image credit (TASL)

We may also want an image gallery promo suited to the format. Here's #667 as a start.

## Problem to be solved
Current inline image gallery not suitable for use when the images are the purpose of the story. 
Need to be able to include longer paragraph of text
Needs to be lovely and easy to use on mobile
Consider editorial **and** exhibition use

## Acceptance Criteria TBD

- [ ] The interface should do this thing
- [ ] and this thing
- [ ] and this thing.

**Comment by Heesoomoon** [comment]
@jennpb @pollecuttn I'm going to close this for now and create a new ticket to include new set of objectives and investigation from the dev team for early November.
