### ISSUE TITLE
Add 'Images' to global nav

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1372]
## Type
✨ Feature

## Needs
- [ ] Analytics and/or component tracking

## UI Requirements
Add 'Images' to navigation between Explore and What We Do

## Acceptance Criteria
- [ ] Link to Image search available on both wc.org and next.wc.org
https://next.wellcomecollection.org/search
~- [ ] Shown to 50% of visitors via Optimize for a month~
- [ ] All site visitors can see Images link in navigation after 5 November.

## Problem to be solved / User Story
In order to find images from Wellcome Collection to use in my research

As a
Researcher

I need/want/expect 
to find where Images are when I've been plonked on the site from wellcomeimages.org

**Comment by davidpmccormick** [comment]
What would the purpose/hypothesis of showing it to 50% of users be? It doesn't seem like a fair condition for an A/B test.

**Comment by jennpb** [comment]
You're right, it doesn't make sense. We agreed (after I opened this issue) that we are happy to include the link in the navigation now to get people to use it.
