### ISSUE TITLE
Tracking and metrics for /works/ and /search

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1374]
## Type
:speech_balloon: Conversation

## Needs
- [ ] Analytics and/or component tracking
- Number of downloads
- Which option downloaded
- Return to results
- Pagination controls
- Copy link
- Search refinements
- Monitor searches by: query, 

## Questions
- Is Mixpanel the right way of tracking these components?
- Does Google Search Console provide useful information about search behaviour?

## Problem to be solved / User Story
In order to monitor depth and breadth of content accessed
As the front-end team
We need/want/expect to be able to find out how people are using what we've built and to see how much of the collection is being used

**Comment by hthair** [comment]
To be confirmed in meeting on Thursday:
- download and download options, and copy link tracking have been set up.
- being able to track number of click throughs from home page to works search can be done in GA
- check how GA knows what counts as 'site search' --> is this going to show search on images as well as main site or not. Can we split this to get a value for '% search refinements' just for works.
- check tracking is on back to results button.

**Comment by jennpb** [comment]
Team agreed that Mixpanel isn't doing anything that GA Events can't do, and lacks some of the functionality that GA provides. Before stopping use of Mixpanel we need to agree an events tracking schema.

**Comment by jennpb** [comment]
@davidpmccormick @hthair If we're going live with images in the navigation we need to sort out our event tracking schema!

**Comment by hthair** [comment]
Data is being recorded in GA including:
* number of downloads (and what they are for)
* number of copy-links (and what they are for)
* can check outbound links to see how many click on CC link
* can see which works pages are most viewed
* can view most popular search terms, however this is a slightly tricky process so may look at a better way to do this, but it is currently possible in GA. 

Mix panel may be tracking the down arrow button that moves people to the info below the image. GA is not presently doing this.

**Comment by hthair** [comment]
Back to results button tracking will be set up on GA by @davidpmccormick
