### ISSUE TITLE
'Return to results' should take users back to where they left off

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1376]
## Type
- ✨ Feature

## Acceptance Criteria
- [ ] Return to place in list

## Problem to be solved / User Story
Similar to the browser back button, when a user clicks on 'Return to results' from a /works/ page, she should go back to the place in the list where she left off.

**Comment by gestchild** [comment]
This works everywhere except Chrome, where the autofocus we have on the search box is overriding the anchor link - will need to investigate further
