### ISSUE TITLE
PP: verify correct content for graphic design exhibition

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1428]
## Needs
- [ ] Content checking with Exhibition/Content Team

Including:
- [x] Hero image for desktop and mobile (Fran)
- [x] 'Image Gallery' promo thumbnail image (Fran/Heesoo)
- [x] Location #1468 (Fran)
- [x] Exhibition info: summary and detail (Fran)
- [x] Content styleguide: mixed/sentence case for labels, title, links, CTA, etc. (Wellcome Trust Styleguide)
- [x] Date format
- [x] Related books
- [x] Accessibility info (Georgia/Orla)

**Comment by Heesoomoon** [comment]
Here's the status.
**Hero image:** once we provide the dimensions, Fran can work with the external designer to provide the assets. Mar's team will have to review before going live.
**Image gallery:** Need to follow up with Chloe/Lindsay if they can help to create the image for us. If not, I can create one and have the team review it.
**Location:** Level 0
**Exhibition info:** Fran will write up and send to us.

Question:
Who should be part of the content review before going live?

**Comment by Heesoomoon** [comment]
The assets for the image gallery and the large print guide are posted on the project folder.
https://wellcomecloud.sharepoint.com/sites/wcdigitalexperience/Shared%20Documents/_PublicProgramme/CGDSYL?csf=1

**Comment by Heesoomoon** [comment]
We have all the contents for AB testing. Georgia will provide the pdf file for Exhibition Texts on Tuesday.
