### ISSUE TITLE
Why music: talk to photographers to understand more about this project

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1437]
## Needs
- [x] Research
- [x] Find out dates for receiving content from Helen

**Comment by davidpmccormick** [comment]
There will be four article-like things published week commencing October 9, each of which will contain a 3.5 minute audio file.

The intention is to provide something interactive to display on the page along with the audio.

BBC R3 will be providing .wav files – we can convert these to whatever we choose and embed in an html5 `audio` element (or we could upload to SoundCloud if we wish – `audio` element is _probably_ more straightforward – I think we've already done something similar for a poem, maybe?).

The article will largely follow the article template we currently have, i.e. hero image, standfirst, body copy.

One (possibly two) of the articles will contain one of our pre-existing image galleries (so, in effect, will follow precisely the current article format).

One will also contain a couple of spinnable VR objects – [pomanders](https://www.google.co.uk/search?q=pomander+wellcome&tbm=isch&imgil=hVhRTdt2x8rJqM%253A%253B7A5XgkSc4eUf9M%253Bhttps%25253A%25252F%25252Fcommons.wikimedia.org%25252Fwiki%25252FFile%25253APomander_Wellcome_L0043780.jpg&source=iu&pf=m&fir=hVhRTdt2x8rJqM%253A%252C7A5XgkSc4eUf9M%252C_&usg=__3OL79Ub4GFKL881xFb5er-XaMfg%3D&biw=1368&bih=912&ved=0ahUKEwjilOnyzKTWAhUkAcAKHQqIDFYQyjcINQ&ei=u2u6WaLLEKSCgAaKkLKwBQ#imgrc=hVhRTdt2x8rJqM:) – created using 'Object2VR' software. [Example of Object2VR](https://ggnome.com/object2vr/examples/dragon).

One will contain [photogrammetry](https://en.wikipedia.org/wiki/Photogrammetry) of the wall of genome books in medicine now – [example of photogrammetry](https://sketchfab.com/models/b5e653de876348f4834ca52aaf9f410e).

There is a possibility that one will contain a Google streetview-style panorama of the reading room – like [this example](http://www.bengilbert.co.uk/wellcome/AdamsonCollection/BlogPostAssets/360s/output02/BTG161022130617%20Panorama.html), although the likelihood is that this won't be done in time and we'll use an image gallery instead.

I think the best approach for us would be to modify the article template to be able to accept arbitrary iframed html and we can drop in the files as we receive them from the photography team. We should obviously try to ensure that page weight isn't silly and signpost any possible data issues to (especially mobile) users.
