### ISSUE TITLE
Why music: talk to Helen to understand more about this project

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1438]
## Needs
- [ ] Research

**Comment by jennpb** [comment]
@pollecuttn @davidpmccormick Any next steps from this or should it be closed, given chat with photography team?

**Comment by davidpmccormick** [comment]
I'd say close.

**Comment by pollecuttn** [comment]
@davidpmccormick Did you talk to Helen? If so can you please note here what came out of that so we can see what new things are now known as a result? Doesn't have to be long and discursive, just concise will do.

**Comment by davidpmccormick** [comment]
Spoke briefly with Helen. There will be four articles going live in the week commencing October 9.

My understanding so far is that each will have  a hero image, a standfirst, an audio player (SoundCloud/standalone TBD), and some body copy.

- One will contain one of our pre-existing editorial image galleries
- One will contain a 'spin round object'*
- Two will contain a Google Street view-style panorama (possibly with links to other pages within)

* I don't know/can't remember what this is – will find out tomorrow

**Comment by pollecuttn** [comment]
See also https://github.com/wellcometrust/wellcomecollection.org/issues/1437

**Comment by pollecuttn** [comment]
@davidpmccormick Did you find out what the 'spin round object' was? Is it the pomanders mentioned in https://github.com/wellcometrust/wellcomecollection.org/issues/1437?

Did Helen say when they will get the content for us to build with?

**Comment by davidpmccormick** [comment]
Spin round object = VR pomanders, yep.

I don't have a note of when the files will be ready, but if (we agree) the intention is to allow the article template to accept iframed html, then we(/Helen) can test with example content up till the wire. I'll make a note to find out the dates from Helen.
