### ISSUE TITLE
Build video player for article (main content)

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#146]
![image](https://cloud.githubusercontent.com/assets/1446139/22376235/1790c55c-e4a5-11e6-81a9-58581adda675.png)

**Comment by jennpb** [comment]
Here's the design from Tomi, I'd like to look at how we can build this using existing components and enhance accordingly. @gestchild @davidpmccormick

**Comment by davidpmccormick** [comment]
Unassigned myself for now because I'm lost in the server-side stuff. Hopefully be able to pick it up with @jamesgorrie later.

**Comment by jennpb** [comment]
Status as of today:
We can publish video articles, hurrah!
Editors need to select Video format in Wordpress; this should pick up the play button indicator in the article title and in the article promo. 

This has been done as a straight up YT video without the WC chrome as shown in screenshot. I'll keep this in the backlog for now; we'll want to pick it up at a later date when looking at other media.

@dannybirchall @davidpmccormick @jamesgorrie @gestchild

**Comment by dannybirchall** [comment]
Can you check the preview; the featured image doesn't seem to be quite working 

https://next.wellcomecollection.org/articles/preview/13188

**Comment by jennpb** [comment]
Holding off on this one for now.
