### ISSUE TITLE
Create link from /works/ to Sierra catalogue 

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1460]
## Type
- ✨ Feature

## Problem to be solved
In anticipation of the shutdown of wellcomeimages.org, we will need to create some way for users to link to the library catalogue record for that same item should they wish to see more information, or to request to view it in the library. **This link should only be temporary** until Sierra data is exposed through the API and we build better ways of doing the same thing.

## Needs
- [x] Agreement about suitable CTA  / `More information about this work`

- [x] Tracking on outbound link

## Acceptance Criteria

- [x] Use the `sierra-system-number` from API
- [x] Construct destination URL `http://search.wellcomelibrary.org/iii/encore/record/C__R_________?lang=eng`

**Comment by alexwlchan** [comment]
> Construct destination URL http://search.wellcomelibrary.org/iii/encore/record/C__R_________?lang=eng

Where does that URL come from? The existing Wellcome Images site links to `http://catalogue.wellcomelibrary.org/record=b{innopac_id}` – I assumed we were just going for feature parity with the existing site?

**Comment by jennpb** [comment]
That's Encore. I don't know why wi.org was never updated to point to it rather than catalogue. If it's the same task to construct a `search.wellcomelibrary.org` URL rather than `catalogue.wellcomelibrary.org` then I'd prefer to do that as it's our main catalogue UI and familiar to more people.

If for reasons we shouldn't point to `search.wellcomelibrary.org`, then `catalogue.wellcomelibrary.org` will work.

**Comment by pollecuttn** [comment]
For an Encore record you can use this pattern:
`http://search.wellcomelibrary.org/iii/encore/record/C__Rbxxxxxxx`
and Encore will add whatever it needs on the end of it.

e.g. if you follow http://search.wellcomelibrary.org/iii/encore/record/C__Rb1080537 it ends up at http://search.wellcomelibrary.org/iii/encore/record/C__Rb1080537?lang=eng

**Comment by alexwlchan** [comment]
These are now appearing in the API, with the identifierScheme `sierra-system-number`.

https://api.wellcomecollection.org/catalogue/v0/works?includes=identifiers

Most (all?) of the current records will have this ID, because we still have just the V images – once we start providing records from non-library content, this ID will not be present. So you shouldn’t assume it’s there!

**Comment by jennpb** [comment]
Note to self @jennpb: inform WMS when this has been done.
