### ISSUE TITLE
PP: location in 183

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1468]
## Type
- ✨ Feature

## Needs
- [ ] Content from Content Team

## Problem to be solved / User Story

In order to
visit and plan to visit an exhibition

As a
visitor with accessibility needs

I need
to know which floor the exhibition is on

**Comment by pollecuttn** [comment]
@jennpb Can you please check/correct/delete the user story I've added

**Comment by jennpb** [comment]
According to Fran, the gallery numbers aren't revealed to the visitors at any point in the building. However, we should refer to location as such:

level 0
level 1
level 2
etc.

Only capitalise level if it starts a sentence.

**Comment by jennpb** [comment]
@Heesoomoon @davidpmccormick  I think this belongs in the vicinty of/within the accessibility block

**Comment by pollecuttn** [comment]
@davidpmccormick Is this issue closed by https://github.com/wellcometrust/wellcomecollection.org/pull/1485?

**Comment by davidpmccormick** [comment]
I believe so, yep. I didn't want to close it straight away in case @Heesoomoon or @jennpb had any amends. Maybe I should close by default?

**Comment by jennpb** [comment]
I've asked for content team to review, so let's keep it open to see if they have any amends.

**Comment by jennpb** [comment]
No content team feedback yet, but in order to go live I had a quick look at the text that is currently there.

It follows content style guidelines AFAIK, but may be subject to further feedback from the exhibitions folks.

The only changes I'd suggest making are:

- [ ] Change heading to `Access information`
- [ ] Add link to `Exhibition text and captions (filetype xxKB)`
- [ ] Add appropriate icon for document download

@Heesoomoon @davidpmccormick

**Comment by Heesoomoon** [comment]
@davidpmccormick Georgia will provide the pdf file at the end of the day. Let's add a placeholder file (e.g. Bedlam) for now. She also had a minor copy tweak which she will send it along.
https://wellcomecollection.org/sites/default/files/Wellcome%20Collection_Bedlam%20Exhibition%20text%20and%20captions%20%28351%20KB%29.pdf

**Comment by davidpmccormick** [comment]
- [ ] Add link to 'Download exhibition texts (PDF ##KB)
- [ ] Change third a11y item to 'Large print guides, transcripts and magnifiers are available in the gallery'
