### ISSUE TITLE
PP: related events

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1470]
## Type
- ✨ Feature

## Needs
- [ ] User research
- [ ] Content from Content Team
- [ ] New visual design
- [ ] Analytics and/or component tracking

## Acceptance Criteria

- [ ] The interface should do this thing
- [ ] and this thing
- [ ] and this thing.

## Problem to be solved / User Story

In order to
be made aware of events related to an exhibition

As a
an exhibition visitor or potential exhibition visitor

I want
to be told of events that are happening related to the event I'm looking at

**Comment by pollecuttn** [comment]
@jennpb Please check/edit/delete the user story

**Comment by davidpmccormick** [comment]
Closed by #1501
