### ISSUE TITLE
PP: split summary and detail on exhibition body

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1471]
Summary and detail are currently one thing.

Split these so they can be treated separately, e.g. display summary and hide detail by default on page load.

## Type
- ✨ Feature

**Comment by jennpb** [comment]
@Heesoomoon @pollecuttn Do either of you know what this is? If yes, is it still required? If not, I suggest we close it.

**Comment by Heesoomoon** [comment]
@jennpb I think we already addressed this by adding 'Standfirst' treatment. I'll close.
