### ISSUE TITLE
PP: tags - labels or links?

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1472]
@Heesoomoon to think again about how we're using tags: are they labels or are they links?

How do they work in conjunction with or in the absence of breadcrumbs?

**Comment by Heesoomoon** [comment]
Here's the latest recommendations.
Tags are used to
- inform users of the type of the content (e.g. Articles, Exhibitions, Events, etc.) 
- inform users the content is part of a group (e.g. Series, Exhibition, etc.)
- link to the list view (All articles, All exhibitions, All events, etc.)

Tags will be displayed on top of the content page or over the hero image for Exhibition. 
For promo, it will be displayed as informational label to minimise the visual noise and keep existing information hierarchy.

We will post the design tomorrow.

**Comment by Heesoomoon** [comment]
![promo](https://user-images.githubusercontent.com/29206031/30537785-0f0d18ce-9c63-11e7-92d8-01a726f963c4.png)
