### ISSUE TITLE
Works page: On-hover transparency gets in the way of image detail

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1491]
## Needs
- [ ] New visual design

## Problem to be solved 
The black horizontal transparency on a /works/ viewing area gets in the way of reading any of the text at the top and bottom of the image. This is problematic for artworks with lettering at the top/bottom, and will become more of a problem once we introduce text-based digitised works.

This has come from direct **internal user feedback** and **observation** of people interacting with the page; it's hard to know when the transparency will fade, and it reappears as soon as you nudge the mouse.

**Comment by gestchild** [comment]
Agreed with @Heesoomoon to remove the full width transparency and add gradients just on the links themselves

**Comment by jennpb** [comment]
Super - go for it!
