### ISSUE TITLE
Inconsistent text style in the article page

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1502]
## Type
- 🐛 Bug

## Problem to be solved
The weight of the text is being displayed differently from one paragraph to another.

## How to reproduce
Safari browser on Mac (34% sessions Sept 2016-Sept 2017)
https://wellcomecollection.org/articles/WXXZUyoAAJpKfPOq

![article](https://user-images.githubusercontent.com/29206031/30437591-e8e677e8-9966-11e7-9603-a409fd4ba46b.png)

**Comment by jamesgorrie** [comment]
Closing as I can't replicate this.
