### ISSUE TITLE
Incorrect exhibition date on Exhibition info box

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1509]
## Type
- 🐛 Bug

## Problem to be solved / User Story
The correct exhibition date for CGDSYL is '7 September 2017 - 14 January 2018'.

## How to reproduce
https://wellcomecollection.org/exhibitions/WZwh4ioAAJ3usf86
Chrome and Safari on Mac OS

**Comment by pollecuttn** [comment]
And I'm seeing the same on Chrome on Windows

**Comment by jennpb** [comment]
Is someone able to pick this up today? @davidpmccormick @jamesgorrie @gestchild ?

Thanks!
