### ISSUE TITLE
Is "Exhibition" label in the wrong font on narrow screens?

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/wellcomecollection.org#1510]
## Type

- 🐛 Bug

## Problem to be solved / User Story

Looking at https://wellcomecollection.org/exhibitions/WZwh4ioAAJ3usf86 on screens of different widths, the "Exhibition" label is variously in Wellcome Bold or Helvetica Neue:

![screen shot 2017-09-15 at 11 46 21](https://user-images.githubusercontent.com/301220/30479093-9a40429a-9a0b-11e7-90e8-35c8cca8897f.png)
![screen shot 2017-09-15 at 11 46 23](https://user-images.githubusercontent.com/301220/30479094-9a5b3424-9a0b-11e7-880a-d8e522a79a90.png)

Feels like it should be the same throughout, no?

Safari and Chrome, macOS. I have the Wellcome font installed locally but I don’t *think* that’s causing the issue.

**Comment by davidpmccormick** [comment]
It's in a _different_ font (as per visual designs)

**Comment by alexwlchan** [comment]
@davidpmccormick Sounds like this can be closed as working-as-designed?
