### ISSUE TITLE
Browser compatibility bug - Android 2.3.6

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1527]
## Type
- 🐛 Bug

## Problem to be solved
William S has reported that he's unable to use any of the new Wellcome Collection pages on his phone. 

> A phone that has the problem with Wellcome Collection webpages is Samsung Nexus S, Android version 2.3.6, Baseband version I9023XXKF1, Kernel version [long number, can send if required], Build number GRK39F.  Browser is Android version 2.3.6

**Comment by pollecuttn** [comment]
@jennpb Which browser is he using?

**Comment by jennpb** [comment]
That's all the info I currently have.

**Comment by pollecuttn** [comment]
Okay, I just spoke with William and it sounds like it's the stock browser that came on his Samsung Nexus S.

**Comment by davidpmccormick** [comment]
[Our Android support is 4.4+](https://cardigan.wellcomecollection.org/docs/principles.html#support) (Android is now on version 8).

2.3.6 is 7 years old(!)

**Comment by jennpb** [comment]
Ha, OK, this goes into the `wontfix` bucket.
