### ISSUE TITLE
Find a way to stop us from releasing without alt text

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1535]
## Type
- 🚑 Health report

## Problem to be solved / User Story

In order to help the content team produce accessible content

As a dev

I need to help the content team find a way to remember to add alt text to images

**Comment by davidpmccormick** [comment]
[The editorial images wiki](https://github.com/wellcometrust/wellcomecollection.org/wiki/Editorial:-Images) now has some `alt` advice, and Prismic previews highlight images with empty `alt` attributes.
