### ISSUE TITLE
PP: establish content relationships

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1538]
i.e. related content

This piece is so we know how different content relates to other content e.g. an event promo on an exhibition page

**Comment by jennpb** [comment]
@Heesoomoon @jamesgorrie @davidpmccormick @gestchild Can you let me know if this can be closed because it's part of another issue? If it's not, it needs more discussion/refinement.

**Comment by Heesoomoon** [comment]
I'm pretty sure this relates to the work @jamesgorrie is doing for the event.

**Comment by jamesgorrie** [comment]
Ah, if we're talking about related content as a whole, we need to look at that as a separate thing.
I would suggest closing this, we can create a new, more explanatory ticket when we need to do the work.
