### ISSUE TITLE
PP: prep for meeting with Georgia around exhibition accessibility

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1539]

**Comment by hthair** [comment]
Notes from meeting with Georgia and Becca.
- Decided to have a larger meeting on November 1st to finalise the organisation of the sessions. 
Georgia will be doing the recruitment which may comprise of people with accessibility needs and those without to gather a lot of information about the CGDSYL exhibition in terms of ease of access, what people engage with, use of large print guides etc. 
- Before November's meeting we need to think about how many of us will be involved in the testing, so we can test multiple visitors concurrently and get the whole team to see and hear the feedback. 
- Need to decide length of session, thinking about how we might have users with different access needs.
- Think about payment for visitors, reward voucher or payment for transport. Let Georgia know so she can specify when recruiting. []
- Next meeting will be Hayley, Jenn, Heesoo, Georgia, Becca, and Orla.
