### ISSUE TITLE
Content team requirements checklist

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1543]
Need to go through all outstanding SEO and content-related issues to see where the Digital Content Team could help.

**Comment by jennpb** [comment]
**Design + Production of:**

**Articles**
- use of right rail https://wellcomecollection.org/articles/six-personal-health-zines-that-might-change-your-life
- adding multiple contributors
- listicle format https://wellcomecollection.org/articles/WbvdiCUAAAitlByw
- hero image caption/credit https://wellcomecollection.org/articles/WbvdiCUAAAitlByw
- in-line image gallery https://wellcomecollection.org/articles/WZHSlSoAAJH9hMCI
- timestamp
- estimated reading time
- grid adjustment to provide more prominence to the left column

**Galleries/image lists**
- Checking narrative purpose of supporting + feature-length image galleries (in light of exhibition gallery design)

**Images**
- alt text
http://webstyleguide.com/wsg3/11-graphics/8-web-graphics-markup.html#alt-text
- redundant images on Articles (hero & content)

**Promo**
- feature promo treatment on Explore landing
- information display (title, label, description, etc.)

**Ongoing site maintenance**
- Ownership of homepage and other landing pages
- How can we get new features highlighted?

**Meta descriptions**
/explore
/articles
/series
/works
/events
/exhibitions
/events/event-name
/exhibitions/exhibition-name
