### ISSUE TITLE
Exhibition: Add 'Scroll to info' button on mobile

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1544]
## Type
- 🐛 Bug

## Problem to be solved
We would like to apply 'Scroll to info' pattern implemented on Work Page to Exhibition and Article templates to make it easy to view the info.

![bedlam_hero_mobile](https://user-images.githubusercontent.com/29206031/30600632-e943a298-9d57-11e7-975e-377ed223a3e7.png)

**Comment by jennpb** [comment]
@Heesoomoon @GarethOrmerod Is this a feature we still need to accommodate?

**Comment by GarethOrmerod** [comment]
Ideally not as we should expose enough content below to encourage scrolling.
