### ISSUE TITLE
Design: Update inline image gallery to address usability issues

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1554]
## Type
- enhancement

## Description
Quick visual fixes
- Increase contrast between selected and non-selected image
- Display image gallery title
- Move Previous/Next buttons above the images

Need to follow up with the dev on long term solutions.

**Comment by Heesoomoon** [comment]
@jennpb Here's the update from Tomi.
- Image gallery title on top left
- Previous/Next button on top right
- Increase the contrast between selected and non selected images
- Update picture icon
![image gallery](https://user-images.githubusercontent.com/29206031/31148634-350871da-a885-11e7-8de9-acb9d72ced4f.png)

**Comment by Heesoomoon** [comment]
@davidpmccormick @Norvard Can we look at the font style & size for the image gallery header (and subheader for the content )? Also, the spacing seems off on this.
![inlineimagegallery](https://user-images.githubusercontent.com/29206031/31237327-87e4240c-a9ee-11e7-9d30-888b1842faa1.png)

**Comment by jennpb** [comment]
Killing this one off as it's no longer useful in the new image list world.
