### ISSUE TITLE
Search Close

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#157]
Lets add a "close" X to the search bar once the user has activated the search field. This way they can close the search and get back to navigation. Use the same X we have in other places and place it on the right side edge and move search icon 30px over to the left.

**Comment by davidpmccormick** [comment]
Yep. I think clicking anywhere that isn't the search field/button should probably also close the search field?

**Comment by Norvard** [comment]
Yes agree

**Comment by jennpb** [comment]
I've got Chrome Version 54.0.2840.99 m on my PC. The search field overlaps the logo on expansion.

![image](https://cloud.githubusercontent.com/assets/1446139/21020126/04f01918-bd6b-11e6-877b-4ea38fad351f.png)
