### ISSUE TITLE
Alt text for images on works pages(?use image title or description)

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#1576]
## Type
- ✨ Feature

Relates to #1224, as a suggested SEO improvement. However, it conflicts with best practice advice for writing alt text which recommends not providing the same information as text within the context of the image. See https://webaim.org/techniques/alttext/ (example 2)

Needs thinking about

**Comment by jamesgorrie** [comment]
@gestchild don't we show the title on the search results, and we can show the description if it's different?

Annoyingly, while I suggest this, I remember finding one where the difference between title and description was a `.` at the end - but we can't do much about that.

**Comment by jamesgorrie** [comment]
With the JSON LD (structured is way better than inferred) and the fact the description is on the page, let's go with what is more accessible?
