### ISSUE TITLE
Provide HTML snippet for others to embed in their page (include links back + licensee)

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#1579]
Taken from #1224
- needs detail

## Type

- ✨ Feature
- 🐛 Bug
- 🚑 Health report

## Needs

- [ ] User research
- [ ] Content from Content Team
- [ ] New visual design
- [ ] Analytics and/or component tracking

## Acceptance Criteria

- [ ] The interface should do this thing
- [ ] and this thing
- [ ] and this thing.

## Problem to be solved / User Story

In order to
 _(why? accomplish a goal/get a benefit)_

As a
 _(who? user/persona)_

I need/want/expect 
_(what? to do this thing)_

**Comment by jamesgorrie** [comment]
Evolved into #2382
