### ISSUE TITLE
Include mark-up thumbnail image

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#1580]
Taken from #1224 
- needs detail

## Type

- ✨ Feature
- 🐛 Bug
- 🚑 Health report

## Needs

- [ ] User research
- [ ] Content from Content Team
- [ ] New visual design
- [ ] Analytics and/or component tracking

## Acceptance Criteria

- [ ] The interface should do this thing
- [ ] and this thing
- [ ] and this thing.

## Problem to be solved / User Story

In order to
 _(why? accomplish a goal/get a benefit)_

As a
 _(who? user/persona)_

I need/want/expect 
_(what? to do this thing)_

**Comment by jamesgorrie** [comment]
@gestchild could you explain this further, I have no idea what it means?

**Comment by gestchild** [comment]
Ha, me neither. It was taken out of #1244 with the intent to:

> capture more specific requirements, and prioritise accordingly

It was originally raised by @derivadow, can you remember what this is?
