### ISSUE TITLE
works page: include relevant schema.org tags

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#1581]
Taken from #1224

## Type
- ✨ Feature

## Needs
- [x] Determine which schema.org tags are most relevant

## Acceptance Criteria
- [ ] All relevant schema data is present
- [x] [schema data validates](https://search.google.com/structured-data/testing-tool)

## Problem to be solved / User Story
Help people find our stuff by making it indexable

**Comment by davidpmccormick** [comment]
Looking at the [works ontology](https://github.com/wellcometrust/platform/blob/master/ontologies/Documentation/Works-Ontology.png), these look like the best candidates for schema.org properties of a [`creativeWork`](http://schema.org/CreativeWork)

WC ontology term    | Schema property
--------------------|---------------------
workType            | additionalType*
creators            | creator
publishers          | ?
placeOfPublication  | ?
placeOfCreation     | locationCreated
subjects            | about
genres              | genre
publicationDate     | datePublished
createdDate         | dateCreated
modifiedDate        | dateModified
title               | name/headline
lettering           | ?
level               | ?
alternativeTitle    | alternativeHeadline
physicalDescription | description
isPartOf            | isPartOf
isOriginalOf        | ?
isCopyOf            | ?



\* possible values: book, map, musicRecording, photograph, sculpture, painting, publicationIssue, publicationVolume, thesis, atlas, article, musicComposition, visualArtwork

**Comment by pollecuttn** [comment]
There's a bibliographic extension to schema that you might want to consider using for publishers:
http://bib.schema.org/publishedBy

**Comment by davidpmccormick** [comment]
This is done as far as is currently possible, with `TODO:` stubs for things that we require from the API to complete it in future.
