### ISSUE TITLE
Improve Prismic preview experience

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#1585]
## Type
🐛 Bug

Reports from the content team are that it's taking up to an hour for changes they're making to be visible at the preview URLs.

Confirmed with @gestchild that the `/preview` routes are missing Cloudfront (as desired). @jamesgorrie any ideas on why information from the API might be stale (or any other ideas on this)?

**Comment by jamesgorrie** [comment]
Closed in #1587?
