### ISSUE TITLE
Feature flag to direct users to a particular index

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/wellcomecollection.org#1594]
## Type
✨ In order to show different sets of users different indexes available through the catalogue API the app should have a mapping from group -> index.

## Needs
An expected format for the mapping:

```json
{
  "groups": [
    {
      "id": "group_name",
      "search_index": "search_index_id"
    }
  ]
}
```

The JSON will be made available via S3 and will be publicly accessible.

**Comment by kenoir** [comment]
Might be nice to work on this with @alicefuzier

**Comment by gestchild** [comment]
Tweaked feature flag functionality to enable this instead, so we can control the mappings with Prismic
