### ISSUE TITLE
Add tracking to new site notification

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#161]
Add tracking to the "Find out more" and "Take me back" links on the bar.

**Comment by jamesgorrie** [comment]
It might actually be more accurate to use how many people visit the article link.
I will check to make sure that we can filter traffic by `?v=1` - if so that would be the most accurate measure of the "take me back"

**Comment by jennpb** [comment]
The "take me back" link needs to set a cookie to expire in 7 days. 7 days is totally arbitrary, btw - my thinking is that we want to give another opportunity to a) notice the changes to the site and b) follow up by clicking on the "find out more" link. Happy to shorten it if you think better.

**Comment by jennpb** [comment]
@jamesgorrie Is there anything about this issue that's still relevant to us?

**Comment by jamesgorrie** [comment]
Nope.
