### ISSUE TITLE
Rework top-level navigation and footer

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1611]
## Type

✨ Feature

## Purpose
We need to do some work to understand the best approach to global navigation, based on user research and types of content we're developing. Aim is to start testing navigation as part of the content restructure in Q4 2017-18.

## In scope
- Header nav
- Footer

## Value
- Navigation header that gives an idea of what we do at a glance
- Optimised footer
- Better understanding of content relationships and how users move from one kind of content to another
- Ways of navigating that are both content and audience-focused

## Outcomes
- We've done enough research to give us confidence that the site is arranged in the best way for all users
- Sitemap produced (header and footer content links)

## Not in scope
- Contextual navigation that makes the most of our graph data - not strictly linear or parent-child (this will become part of content relationships discussion, header redesign, etc)

## Design considerations
- mobile menu: revisit location and touch target area
- opening hours
- expose sub categories

**Comment by jennpb** [comment]
## to do

- [ ] Mini content inventory to establish what content we now have on the new site
- [ ] Document (drawings, text docs) strawman ideas to explore and test
- [ ] Test plan

**Comment by jennpb** [comment]
@Heesoomoon I've updated the description above and have taken out 'contextual navigation'. Can you fill in any detail you might have that relates to your post-it 'Navigation Strategy Doc'?

**Comment by Elltie** [comment]
Navigation treetest 1 deck https://wellcomecloud.sharepoint.com/:p:/r/sites/wcdigitalexperience/Shared%20Documents/User%20Research/Navigation%20201903/Navigation%20Treetest%202019_10/Treetest%201/Navigation%20Treetest%201%20Results.pptx?d=w88b7ef04aa204c0098c0cddd845db726&csf=1&e=KJMrv6

Navigation treetest 2 deck
https://wellcomecloud.sharepoint.com/:p:/r/sites/wcdigitalexperience/Shared%20Documents/User%20Research/Navigation%20201903/Navigation%20Treetest%202019_10/Treetest%202/Navigation%20Treetest%202%20Results.pptx?d=w2f99301d21424032a829a0723dd3b167&csf=1&e=dLM7Kl

Navigation treetest 3 deck 
https://wellcomecloud.sharepoint.com/:p:/r/sites/wcdigitalexperience/Shared%20Documents/User%20Research/Navigation%20201903/Navigation%20Treetest%202019_10/Treetest%203/Navigation%20Treetest%203%20Results.pptx?d=wb588ab4b248e43c696c0eefbb56f9221&csf=1&e=aOSZ9D

**Comment by jennpb** [comment]
Old issue, will open new ticket.
