### ISSUE TITLE
Embedding images in content directly from API

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1613]

**Comment by jamesgorrie** [comment]
Prismic allows oEmbed embeds.
This could be a good place to start with this.

**Comment by jamesgorrie** [comment]
We were also given access to the integration field:
https://prismic.io/feature/integration-field

This was the feedback given after trying to integrate:

> Hey Renaud. Just some thoughts and things we’ve hit while trying this integration.
> * The fact we don’t have the concept of `last_update` is strange on our side, but it might take a while to figure out what that is to us… not sure if that’s a general-enough case for you to consider
> * We cannot send over our whole API as we have over a million records, and our service won’t let us serve that many (we’re restricted by ElasticSearch’s 10000 limit). Again, a restriction of our system, but it raises how we surface content
> * Given that we have 1m records, we’re not sure free text search would be good enough. We are planning on adding date searches, entity searches and others, and this would obviously not be ported across when putting it into the integration service
> * Our image records could benefit with having a crop before service (we might reference and image, but want to show a zoom on an interesting part)(could we use prismic’s crop? That would be really useful). 
> * The testing tool is great, thanks

> The first two are problems on our side, but it would be good to hear what you think about the 1m records - and perhaps if this would also incur a large cost on our behalf?
The other about search and crop is something we will need to work with our editors on, bt can see it being a limitation, but maybe that’s not what this service is for.

> What we might plan on doing is creating a tool where you can search & crop, and then embed it in Prismic, the problem being we don’t get updates, which is a shame.
We could have another service that updates Prismic is there was a write API, but know this is such an edge case that that wouldn’t make sense to make one for this.

> The only other though is around extending the ProseMirror editor, so we could have a special WellcomeIiifImage plugin.

CC @kenoir as we spoke about it.

**Comment by jamesgorrie** [comment]
Evolved into #2382
