### ISSUE TITLE
Why music: Come up with hosting strategy for photography HTML

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1625]
## Type

- ✨ Feature
- 🐛 Bug
- 🚑 Health report

## Needs

- [ ] User research
- [ ] Content from Content Team
- [ ] New visual design
- [ ] Analytics and/or component tracking

## Acceptance Criteria

- [ ] The interface should do this thing
- [ ] and this thing
- [ ] and this thing.

## Problem to be solved / User Story

In order to
 _(why? accomplish a goal/get a benefit)_

As a
 _(who? user/persona)_

I need/want/expect 
_(what? to do this thing)_

**Comment by davidpmccormick** [comment]
We now have an S3 bucket for this purpose, available at `static.wellcomecollection.org`
