### ISSUE TITLE
Check TASL pattern is not broken by new image sets being introduced

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1627]
## Type

- ✨ Feature
- 🐛 Bug
- 🚑 Health report

## Needs

- [ ] User research
- [ ] Content from Content Team
- [ ] New visual design
- [ ] Analytics and/or component tracking

## Acceptance Criteria

- [ ] The interface should do this thing
- [ ] and this thing
- [ ] and this thing.

## Problem to be solved / User Story

In order to
 _(why? accomplish a goal/get a benefit)_

As a
 _(who? user/persona)_

I need/want/expect 
_(what? to do this thing)_

**Comment by jennpb** [comment]
Nothing has been filled in in this ticket. Where am I supposed to check that TASL won't be broken? @pollecuttn

**Comment by pollecuttn** [comment]
@jennpb I think this was on wc.org

**Comment by jennpb** [comment]
In that case, I don't think this issue is a thing at all, because we don't currently pull in data from the API so there's nothing to break. It's all done manually.
