### ISSUE TITLE
Works: Collate and summarise user testing feedback and identify next steps from results

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1628]
## Needs

- [x] User research

**Comment by hthair** [comment]
I'll organise a meeting post testing to go over findings with the team.

**Comment by hthair** [comment]
- [ ] transcribing sessions into a shareable format for team
- [ ] arrange wash up meeting to discuss outcome and next steps with team

**Comment by jennpb** [comment]
@hthair Where did you get to with this one? If it's done, would you please close and then we can revisit when we're ready to test again?

**Comment by hthair** [comment]
More detailed doc with quotes is in sharepoint in the user research folder called 'usability session (events and exhibitions)'
Meet with team to discuss feedback. Decided that our points to address would be:
- people need a way to plan their visit as a whole i.e. seeing what else is on at the same time
- wording of free ticketing can be confusing
- order of host/speakers on events pages
- timing of events not clear i.e.g should they arrive at the time specified, earlier? drop in during that time? 

summary points are on trello board in digital engagement.
