### ISSUE TITLE
Wrong icon on gallery title

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#1635]
Looks like this might of happened during the latest icon update work:
<img width="570" alt="screen shot 2017-10-04 at 15 25 40" src="https://user-images.githubusercontent.com/23660297/31181134-77090232-a918-11e7-8dfd-b8341c34b8be.png">

We had it right before. Its one of the icons that doesnt fit into the 26x26 set, but its a unique case.

**Comment by Heesoomoon** [comment]
@davidpmccormick If you are doing any work on that, would you also update the subheader size to WB4?
