### ISSUE TITLE
Wrong image size (Explore article)

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#1636]
Might be for editorial but capturing here anyways.

This article uses wrong image size. Should be 16x9

<img width="1284" alt="screen shot 2017-10-04 at 15 20 07" src="https://user-images.githubusercontent.com/23660297/31181206-a9d6429c-a918-11e7-829f-8e71c0f2c84f.png">

**Comment by jennpb** [comment]
This has now been fixed
