### ISSUE TITLE
Works Page: Design Update

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1638]
## Type
Feature

## Problem to be solved / User Story
Removing transparency on hover #1491 
Create link from /works/ to Sierra catalogue #1460
Make using images more prominent

**Comment by Heesoomoon** [comment]
Here's the latest mockup with following updates.
- Remove on-hover transparency
- Apply transparent box around 'Return to results' link and transparent background to 'Scroll to info' button
- Remove 'More informaiton' accordion menu and display 'Description' below 'Lettering'
- Add 'View more information at Wellcome Library' link below the description
- Change 'Download' header to 'Use this image' and increase the header size to HNM3 (20px)
- Update download icon and change link text to 'Download original' and 'Download smaller (##px)'
- Update copy link button and copied state (refer to the mockup)

![workpage_update](https://user-images.githubusercontent.com/29206031/31198799-6c2def00-a94d-11e7-8055-69d82941f957.png)

**Comment by Heesoomoon** [comment]
@jennpb Would you take a look at the updates and let us know if you have any feedback?

**Comment by jennpb** [comment]
@Heesoomoon Just a few label/text changes:

`Download Original` change to `Download original`
`Download Smaller` change to `Download small`
`Copy Link` to `Copy link`
`View more information at Wellcome Library` to `View Wellcome Library catalogue record`
