### ISSUE TITLE
Modify /works page to give better context for shonky data and unsettling images

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1655]
Alexandra and Simon have drafted a bit of text which helps put the image collections into context which is especially important when we don't:
- have good data from Sierra yet
- include fairly serious content alongside lighter editorial content
- haven't yet introduced the concept of Wellcome Library...

The draft has been passed on to @Heesoomoon and @pollecuttn to find someone to subedit.

Last minute sketch idea on @Heesoomoon's desk.

- [x] Add 'Where do these images come from?' section (content to come from Alexandra/Simon)

**Comment by Norvard** [comment]
Just a note. The stacks of images for each topic is a single image with a transparent background. These are simple to create and I can do the first set.

**Comment by Heesoomoon** [comment]
@jennpb @pollecuttn @davidpmccormick  I had a chance to show the landing page (the version implemented by David) when I was talking to the library visitors (2 graduate students, 3 researcher, 1 non researcher) about the Zoom in/out. Here's quick recap.
- 5/6 of them scrolled down quick and went back up and didn’t bother to read it. People tend to ignore the content when it's text heavy and long.
- 2 people suggested it would be nice to see sample images from the featured categories (tags). 
- 3 people assumed 'Images' category would contain images from the exhibition or gallery.
- 1 senior researcher with poor vision had her computer setup to enable her to view larger fonts and images. She uses lots of shortcut to get to information she needs. Something to note as we develop features for users with access needs.

I understand we don't want to put too much effort to this yet but it would be good to plan for something more visual and inspirational like these examples.
https://www.museumoflondon.org.uk/collections
https://collections.museumvictoria.com.au
https://collection.barnesfoundation.org

**Comment by jennpb** [comment]
Thanks for the info. Just want to note that I don't expect the explanatory text to be read by everyone; people doing deep research into the collections will want to know how the collection came about, why we have the data we have, and so on, but for the majority of light-touch researchers, I don't imagine they'd engage with the text in the same way.

**Comment by jennpb** [comment]
[AEedit Wellcome Collection images - cultural insensitivities warning-DBEdit.docx](https://github.com/wellcometrust/wellcomecollection.org/files/1391392/AEedit.Wellcome.Collection.images.-.cultural.insensitivities.warning-DBEdit.docx)
@Heesoomoon @davidpmccormick Here's the text that we'd like to use.

**Comment by Heesoomoon** [comment]
@davidpmccormick Here's the comp for the landing page.
![imageslanding](https://user-images.githubusercontent.com/29206031/31713336-dffc64c2-b3f5-11e7-9a14-64ecc82d7d88.png)

**Comment by jennpb** [comment]
Done!
