### ISSUE TITLE
Mobile layout tweaks

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#168]
Spotted a few layout issues from my phone (iphone safari latest version). 

1. Navigation not collapsing into burger even though it does on desktop browser (Chrome)
![articlesmobile1](https://cloud.githubusercontent.com/assets/1446139/21048581/dea1bdfa-be07-11e6-8e79-ee80017c4989.png)

2. Opt-out bar not resizing
![articlesmobile2](https://cloud.githubusercontent.com/assets/1446139/21048638/2cfdb0e4-be08-11e6-9101-a533f8b9974a.png)

@gestchild one for you?

**Comment by gestchild** [comment]
@jennpb yep, I can take a look
