### ISSUE TITLE
Firefox: Tabbing through content goes in a strange order

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#1689]
## Type
- 🐛 Bug

When in firefox, tabbing from the load of the document sends me on a strange little adventure.
I'd expect to go through the natural order of things.

**Comment by davidpmccormick** [comment]
Any page? Sounds like it might be to do with flexbox `order` (http://www.useragentman.com/blog/2017/01/28/flex-layout-fail-fixing-firefox-keyboard-accessibility-with-the-css-order-property/).
