### ISSUE TITLE
Works page should display the legacy Wellcome Images ID *somewhere*

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/wellcomecollection.org#1692]
After November 6th, the Wellcome Images site goes away, and I have to look up images at the new https://wellcomecollection.org/works.

Suppose I have a reference to an old Wellcome Images ID. I don’t have a URL, because I’ve never looked it up before (so redirects don’t work for me). I can search for it in /works, and in most cases I’ll get either zero or one results, depending on whether the image is still available. If I get one result, I click through.

**Am I looking at the right image?**

How do I know that this is really L0028629? There’s nothing on the page to tell me why it matched the search – I could be looking at the image with that ID, or just an image that refers to it somewhere. Nowhere does that ID appear on the page, so I can’t be sure I’m at the right place.

The old ID needs to appear somewhere on the page so that old references continue to be useful. If you want to drive the knife in, how about calling it *Legacy Wellcome Images ID*?

(Example of such a reference in the wild: [PP/SUL/B/2/5/7:Box 92](https://search.wellcomelibrary.org/iii/encore/record/C__Rb2140019__SPPLw%3D%3DSULLw%3D%3DBLw%3D%3D2Lw%3D%3D5Lw%3D%3D7__Orightresult__X3;jsessionid=F27C88CE167E3F95BD320EFF213972DF?lang=eng&suite=cobalt))

**Comment by jennpb** [comment]
@alexwlchan It is with regret (on your behalf) that after further conversations with Alexandra and Hannah, this isn't something that we're going to expose on the page itself. Alexandra is very keen to not perpetuate legacy IDs, and the best way to do that is to go cold turkey. 

I will put a feedback widget on the page so we can capture feedback from users who are expecting to see something, and also to monitor search queries so we can see whether this is a problem at all.
