### ISSUE TITLE
UI tweaks: Zoom and Return to Results 

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1696]
## Type
- ✨ Feature

## Problems to be solved
While the new explicit zoom mode and the non-fading transparencies are lovely, we now have a few more issues.

**1. View Larger Image CTA obscures useful text which could be read without going into zoom mode.**
<img width="1273" alt="screen shot 2017-10-16 at 15 51 50" src="https://user-images.githubusercontent.com/1446139/31622557-a62ee344-b294-11e7-95d0-6005b00f37c0.png">

**2. Fullscreen, Return to Results and Jump to info button really get in the way of the image on mobile.**
![mobilezoomiphone5](https://user-images.githubusercontent.com/1446139/31622534-957dd4a6-b294-11e7-97c5-89405de48afc.jpg)

We might want to consider testing the buttons justified left and right, or modify the fade effect that was previously in use. Any other ideas?

**Comment by Heesoomoon** [comment]
@jennpb @gestchild Here's the recap of our meeting.
- Display Zoom feature over browser viewport instead of full screen
- Allow user to activate the feature by clicking the image in addition to CTA
- Update full screen icon to zoom Icon
- Update icons in the Zoom mode 
- Heesoo to provide updated comp with CTA location and treatment for both desktop and mobile

**Comment by Heesoomoon** [comment]
Desktop https://invis.io/A4E2999PT
Mobile https://invis.io/4DE23Y8F3

**Comment by jennpb** [comment]
Thanks @Heesoomoon 
A few comments:
- On desktop zoom state, the control bar is charcoal while in other places it's pewter. Subjectively I prefer the charcoal, and to use only one colour for the control panel in all states
- You've used the download icon to jump to the info panel - is there a reason for showing this and not the jump-to arrow currently in use?

**Comment by Heesoomoon** [comment]
@jennpb 
- Charcoalworks. I thought the action bar needed a bit of visual separation from the image background but Charcoal makes it cleaner. 
- As for the download icon, it seems to be better CTA than the arrow. It promotes ability to use the image and sets clear expectation. We should apply 'smooth scrolling' transition so people can discover additional contents on mobile.

I'll update the comps and repost.

**Comment by jennpb** [comment]
But the download icon has already been tested and people understand it to mean download, so I don't think we should use it to jump to download (but keep it for the download action itself).

**Comment by Heesoomoon** [comment]
@gestchild Here are the files. 
[Zoom.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1415193/Zoom.zip)
It's also posted on the project site.
https://wellcomecloud.sharepoint.com/sites/wcdigitalexperience/Shared%20Documents/_Collections/Design/Screens/Zoom?csf=1
