### ISSUE TITLE
Long search keywords overlaps with 'Clear keywords' button

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1697]
## Type
- 🐛 Bug

## Problem to be solved 
**Current**
![screenshot-wellcomecollection org-2017-10-16-17-15-30-034](https://user-images.githubusercontent.com/29206031/31622943-c51fd83e-b295-11e7-9776-9a8f73def92b.png)

**Potential Solution**
Could we set character limit on the display of the text to avoid the overlap?
![screenshot-wellcomecollection org-2017-10-16-17-14-53-433](https://user-images.githubusercontent.com/29206031/31622949-c937e326-b295-11e7-9b4a-93948b5ddf42.png)

**Comment by davidpmccormick** [comment]
This was fixed in #1668 
![oct-26-2017 17-37-12](https://user-images.githubusercontent.com/1394592/32065324-5eed6374-ba74-11e7-8cc2-e56919619c9d.gif)
