### ISSUE TITLE
Works pages should expose attribution information

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/wellcomecollection.org#1707]
Currently works pages simply say _Free to use with attribution_, but don’t tell me who I should attribute it to!

e.g. Following https://wellcomecollection.org/works/ec8kmq5f?query=plumbing back to WI takes me to https://wellcomeimages.org/indexplus/image/L0059166.html, where the image credit is “Science Museum, London, Wellcome Images”.

The page should expose attribution information somewhere.

(This is partially blocked by the fact that the API doesn’t expose this information yet… oops.)

**Comment by pollecuttn** [comment]
e.g. https://api.wellcomecollection.org/catalogue/v1/works/ec8kmq5f?includes=items
