### ISSUE TITLE
Navigation bar 

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#171]
Desktop:

- [x] Center WC logo vertically
- [x] Search open needs close icon to close search field

Mobile:

- [x] Burger icon and close icon should be smaller in size to align with general icon sizes
- [x] Center burger and close icons vertically
- [x] Open search butts up against burger icon, should have 30 px buffer
- [ ] Search open, blinking type line black and 2 px width
- [x] Add close icon when search is open

**Comment by davidpmccormick** [comment]
Fixed by #210 (with the exception of 'blinking type line black and 2px width').
