### ISSUE TITLE
Exhibition: create separate display field for subtitle

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1716]
## Type
- ✨ Feature

## Problem to be solved / User Story
Some Exhibitions require long title to describe the exhibition.
e.g. Ayurvedic Man: Encounters with medicine man
Long exhibition title doesn't scale well for tags, exhibition hero info box and promo. 

## UI Requirements
Allow the exhibition team to add optional subtitle on Prismic and support following display logic.
- Tags: display title and suppress subtitle (e.g. Part of: Ayurvedic Man)
- Exhibition hero info: apply smaller font size for subtitle to provide appropriate visual hierarchy and fit in the exhibition info box 
- Promo: display title and suppress subtitle

**Comment by Heesoomoon** [comment]
We are going to close this for now and follow up with the content team to provide guidelines for exhibitions and events titles.

**Comment by jennpb** [comment]
Reopening this due to several issues with 

Smoke and Mirrors: The psychology of magic
Jo Spence and Oreet Ashery: Misbehaving Bodies

**Comment by jennpb** [comment]
What we want to do is have the notion of a Full Title and Short Title.
Short title should appear wherever we have 'Part of', so as to avoid this:

![part of](https://user-images.githubusercontent.com/1446139/53110520-fe253900-3532-11e9-8c6b-7705937ea0c8.jpg)

**Comment by jamesgorrie** [comment]
> Short title should appear wherever we have 'Part of', so as to avoid this

What would we expect on a card?

**Comment by jennpb** [comment]
Where it's a 'part of', it's the first part of the title: Part of **Ayurvedic Man**

The full title will need to be used on the exhibition page itself, and would appear as the full title on the card when it's an Exhibition card - e.g. the card would say **Ayurvedic Man: Encounters with Indian Medicine**.

**Comment by jamesgorrie** [comment]
Thanks! Just wondering what we call it to make it clear to editors that that's what it'll be used for.
Short title kind of makes sense, but feels a little clunky.

**Comment by jennpb** [comment]
Let’s ask Danny & co. tomorrow to see how they’d think of it.

**Comment by jamesgorrie** [comment]
I wonder if this is something we should apply to the common content model e.g.
* Title
* Promo text
* Promo image
* Contributors (still needs putting on page)

Seems to make sense that it would be used on anything that is displayed on "Part of"?

Easy enough to do on exhibitions first though.

**Comment by jamesgorrie** [comment]
Or if the model is broken up into title and subtitle?
Then we just set the model to "{The title: the subtitle}" which follows more standard naming of fields?
