### ISSUE TITLE
PP: 'Planner' Navigation Analytics

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1727]
## Type
Discovery

## Needs
- [ ] Analytics

## Objectives
To investigate how our visitors use the site to find the information for their visit.

**Comment by hthair** [comment]
I'm looking in to the adwords interface today to see if the path analysis is available. I'll keep @Heesoomoon updated.

**Comment by jennpb** [comment]
Can this be closed @hthair?

**Comment by hthair** [comment]
it can be for now, I'll open a different one when I do other navigation investigation.
