### ISSUE TITLE
Work Page: Inconsistent height of the image viewport

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1740]
## Type
- 🐛 Bug

## Problem to be solved
The height of the viewport seems to change depending on the image both on desktop and mobile making the viewing experience quite jumpy. It was originally decided to take up (?)% of the screen to ensure part of the image info is displayed on desktop and cover fully on mobile. Could we investigate the current setting and see what's causing the inconsistency?

![screenshot-wellcomecollection org-2017-10-23-12-06-37-230](https://user-images.githubusercontent.com/29206031/31886086-c1dcd802-b7ea-11e7-93f9-95728f9b6b10.png)
![screenshot-wellcomecollection org-2017-10-23-11-49-59-893](https://user-images.githubusercontent.com/29206031/31886087-c204fde6-b7ea-11e7-919f-ce14b66d5a7d.png)

**Comment by davidpmccormick** [comment]
The image container (charcoal background) is now fixed based on the height of the browser viewport.
