### ISSUE TITLE
Move dotorg-dash into our monorepo

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1746]
## Type
- 🐛 Bug

https://dash.wellcomecollection.org/ seems to have stopped collecting info for this month on 10 October. 

It looks like we've had no visitors to wellcomecollection.org since then.

**Comment by jamesgorrie** [comment]
Hijacking the ticket for something else that needs to be done.
Let's move the dash into our mono repo.

**Comment by jamesgorrie** [comment]
As a point - the bug here was that the page doesn't autorefresh

**Comment by jamesgorrie** [comment]
We're using data studio almost exclusively now.
