### ISSUE TITLE
Events tags misplaced

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1769]
## Type
- 🐛 Bug

My Events tags have gone all wonky, sliding off the hero image.

My viewport: 1280 × 663
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4

<img width="1251" alt="screen shot 2017-10-27 at 14 13 26" src="https://user-images.githubusercontent.com/1446139/32105742-660fa74a-bb21-11e7-9fc5-bedbdf988d10.png">

<img width="1280" alt="screen shot 2017-10-27 at 14 16 39" src="https://user-images.githubusercontent.com/1446139/32105788-8bcdb742-bb21-11e7-9969-1921ae2365be.png">

**Comment by davidpmccormick** [comment]
Looks like you're zoomed out one step in Safari. `⌘+0` should fix it. Weirdly, zooming in/out in Firefox/Chrome doesn't alter the lock-up of the tags and the image, only Safari. And I couldn't see anything obvious about it being a known bug after a little Googling.

**Comment by jennpb** [comment]
:see_no_evil:
