### ISSUE TITLE
Refresh old hard-coded content on Explore

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1786]
## Type
- ✨ Feature

We should update some of the currently-static content on Explore to highlight some of the recent stories and series. SPECIFICS TO COME SHORTLY

Should include:
Memory Objects series
New digital story

...

## Problem to be solved 
We haven't refreshed the page for awhile and it's looking a bit outdated, and we're missing out on featuring some of our recent innovative content.

**Comment by jamesgorrie** [comment]
@jennpb what do we want to do with this?
We added the new digital story.

**Comment by jennpb** [comment]
Close it!
