### ISSUE TITLE
Build service for Events

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1789]
## Type
Before going too far in building out the events model, we need to peel Events away from the rest of the app.

### 💪  More resilience
Separate different parts of the site, so when one goes dow (perf, bugs etc) we keep serving the rest

### 🍡 More relevant infrastructure
Allow us to scale differently for different needs e.g. busy times when ticketed events are released

### ⛓ Less tie in to certain technologies
If there is a more relevant or better tool / technology for a certain  job, we should be able to use it

### :rage4: Developer sanity (time saving)
Makes creating new services a cinch, and easier to fathom as they grow in complexity.

**Comment by jamesgorrie** [comment]
## The plan
![20171102_124027](https://user-images.githubusercontent.com/31692/32333513-0e6f4de2-bfe0-11e7-827f-ec84fd9aa6a7.jpg)
![20171102_124032](https://user-images.githubusercontent.com/31692/32333514-0e858c74-bfe0-11e7-93e9-3f9929ad6d77.jpg)
