### ISSUE TITLE
What's on page

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1796]
## Type
- ✨ Feature

## Why?
- So we can get all /events and /exhibitions in one place, which will help us deal with past content
--> When an event is over, it shifts into the 'Past events' bucket
--> When an exhibition is over, it shifts into the 'Past exhibitions' bucket
- Migration of content from Drupal site

**Comment by jamesgorrie** [comment]
Initial tasks:
- [ ] Create a page
- [ ] Fetch all current exhibitions and display on the page
- [ ] Apply visual design

**Comment by jamesgorrie** [comment]
We have an all exhibitions page that performs quite well in for search engines.

When we've got a beautiful, really useful ex-ev landing page, we could think about redirecting this traffic to it.
https://www.google.co.uk/search?q=wellcome+collection+exhibitions

**Comment by jamesgorrie** [comment]
@jennpb given this - could we setup the redirects and close this?
https://experience.wellcomecollection.org/exhibitions/

**Comment by jamesgorrie** [comment]
List pages tracked here:
#1934
#1862

**Comment by pollecuttn** [comment]
Description text needed:
- [ ] structured data
- [ ] meta description

**Comment by pollecuttn** [comment]
Daily tours promo: https://github.com/wellcometrust/wellcomecollection.org/issues/2051

**Comment by jennpb** [comment]
Here's the meta description for /whats-on:

`Discover all of the exhibitions, events and more on offer at Wellcome Collection, the free museum and library for the incurably curious.`

Does this mean we can finally close this issue?
