### ISSUE TITLE
Related content: exhibitions, events, seasons, etc

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1797]
## Type
- ✨ Feature

We need to work out how to 
- relate events to an exhibition (and ensure that they are ordered as we want and that we have an expiration policy)
- identify events as part of an exhibition series/season
- relate supplementary content (articles, books) to exhibitions and events

## Why?
- So users can see all of the things happening during an exhibition
- So we can group things as a season/series 
- So we can offer supplementary content to engage visitors, relating to an exhibition or event, in a way that's **sustainable** and as **automated as is reasonable**

**Comment by jamesgorrie** [comment]
@jennpb Could we close this due to all the good work being done around our domain?
