### ISSUE TITLE
Stats for Why Music?

### ISSUE THREAD

**Issue by hthair** [wellcometrust/wellcomecollection.org#1823]
## Type

- 🚑 Health report

## Needs

- [x] Analytics and/or component tracking

Overview of stats from GA for the Why Music series requested by comms. Will look at pageviews, bounce rate, and engagement with iframes

**Comment by hthair** [comment]
@jamesgorrie is there a way in GA to group all the why music pages together that I might not be aware of? Currently I'm unable to do this as they don't have a common url or page title and don't appear in the series tag. I've counted 19 event pages and 4 articles.

**Comment by jamesgorrie** [comment]
@hthair 
As the events weren't published on V2, you're going to have to do those manually.
We have a series custom dimension, but it only applies to content on V2.
It was also broken for Prismic, content, although we should have that fixed.

The way to do this would be to get all the URLs and run them through GA unfortunately.

I have put a PR in #1824 to help make this easier in the future.

**Comment by hthair** [comment]
high level stats sent to Marni in comms.
