### ISSUE TITLE
Need to provide meta description for Exhibitions to avoid unwanted concatenation of whole body

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1849]
## Type
- 🐛 Bug

Reported by @derivadow :
If you look at Can Graphic Design Save your life the meta description is:
 
`  <meta name="description" content="Comprising over 200 objects including hard-hitting posters, illuminated pharmacy signs and digital teaching aids, 'Can Graphic Design Save Your Life?' considers the role of graphic design in constructing and communicating healthcare messages around the world, and shows how graphic design has been used to persuade, to inform and to empower.This exhibition highlights the widespread and often subliminal nature of graphic design in shaping our environment, our health and our sense of self. Drawn from public and private collections around the world, it will feature work from influential figures in graphic design from the 20th century, as well as from studios and individual designers working today.'Can Graphic Design Save Your Life?' is curated by graphic designer Lucienne Roberts and design educator Rebecca Wright, founders of publishing house GraphicDesign&amp;, with Shamita Sharmacharja at Wellcome Collection.Please see our advice for visiting during busy times" />`
 
But the Promo text in Prismic is: Explore how graphic design affects your health
 
i.e. the template isn’t using the right field and appear to be concatenating multiple fields instead. This is particularly problematic because if a meta description is over 160 characters Google ignores it and grabs whatever text it thinks works best. Hence the unhelpful descriptions on the SERP.

## To Do
- [ ] Prismic to allow editors to create meta description
- [ ] Editors to be shown how to create meta description

@dannybirchall FYI

**Comment by jamesgorrie** [comment]
This is done for exhibitions.
