### ISSUE TITLE
Finding out why people are downloading exhibition texts documents: general interest? access?

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1850]
## Type
- ✨ Feature

## Needs
- [ ] User research
- [x] Discussion about what methods appropriate to find this out (trigger a survey on download? put a call out to exhibition-goers for a phone/inperson interview?

## Problem to be solved
Many more people download exhibition text files than I'd expect. The exhibition project teams create these documents to meet a range of business needs and **assumed** user needs:
- to have a document available so that when they go missing from the exhibition space there is a place where VEAs can direct visitors
- Large print wall texts, for access
- Because it's the only place where a map of the gallery space can be made available 

I'd like to know:
- How people who download these documents actually use them
- What people expect to get when they download a document
- Whether formats like PDF and Word have legit use cases _for users_, over HTML

**Comment by hthair** [comment]
Poll placed on site as trigger when download is initiated (late on Wednesday). Checkbox responses to encourage more people to quickly engage. Also have second question about if they have already visited or not. Should enable us to collect lots of responses quickly to find out why people are clicking this link.

**Comment by jennpb** [comment]
@hthair This one is ready to close, yes? Want to add a link to the summary here, and then close the issue?

**Comment by hthair** [comment]
https://docs.google.com/presentation/d/1KKtfFMkSDWdarGZW1px4uQDE-KpjrCGXruUPSHGc7h4/edit?usp=sharing
link to slides summary. Will reopen when we do any qual follow up.
