### ISSUE TITLE
Works: Revisit the order of modules

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1854]
## Type
- 🚑 Health report

## Problem to be solved
The works page with less meta data leaves white space between main info and 'Using this image' drawer due to how we structured the page. We should revisit the order of the modules to avoid this (Title > Main info > Drawer > Use this image). This won't have any display impact on desktop. It will display 'Use this image' module last on mobile view.

https://wellcomecollection.org/works/cszvhh89?query=Engravings
![screenshot-wellcomecollection org-2017-11-22-12-30-51-410](https://user-images.githubusercontent.com/29206031/33127836-17791d6c-cf82-11e7-80c6-4f6739ffffaf.png)

**Comment by Heesoomoon** [comment]
@jennpb @davidpmccormick Could we also display the download links above the credit info per our discussion? See the attached mockup.
![workpage_d_info](https://user-images.githubusercontent.com/29206031/33128040-d707bad0-cf82-11e7-8657-896858ad8585.png)

**Comment by davidpmccormick** [comment]
> It will display 'Use this image' module last on mobile view.

I think the 'Using this image' drawer _should_ be lower on the page than then sidebar content though, right? It's less important and belongs lower down in the source order. Not sure how to solve the space issue though

**Comment by jennpb** [comment]
We also need to keep in mind that the gap will be filled by additional data once we bring in the library catalogue data (from Sierra). For the gappy example specifically, here's its catalogue record: http://search.wellcomelibrary.org/iii/encore/record/C__Rb1215501?lang=eng (more possible data, including improved title, subject, genre, publication date and place).

Not to say that we won't need to rethink, but just that we're not currently seeing the full picture. Figuratively.
