### ISSUE TITLE
Works: Revisit two-column display logic 

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1855]
## Type
- 🚑 Health report

## Problem to be solved / User Story
Currently, we have 7% (34,631 past 4 months) sessions through iPad. The works page uses two-column layout for this screen resolution (768x1024) making the information column quite narrow and tight. For Exhibition template, we break for single-column for this screen resolution. It would be ideal to apply same display logic for templates using two-columns by displaying single column layout for screen width between 600-959px.

Works page on iPad
![works_768x1024_ipad](https://user-images.githubusercontent.com/29206031/33129960-a7347bc0-cf89-11e7-8685-fc7c6341fc35.png)

Exhibition page on iPad
![exhibition_768x1024_ipad](https://user-images.githubusercontent.com/29206031/33129985-b3ef15a0-cf89-11e7-8ecb-420004cb1456.png)

**Comment by Heesoomoon** [comment]
@davidpmccormick Could we also investigate why the column width are different on Exhibition and Works template? And potentially increasing Large breakpoint over 960px to let the content breathe a bit?

Exhibition on 960x600
![exhibition_960x600](https://user-images.githubusercontent.com/29206031/33130023-dba0ee98-cf89-11e7-89fb-334cd10a3d04.png)

Works on 960x600
![works_960x600](https://user-images.githubusercontent.com/29206031/33130033-e0a22880-cf89-11e7-815c-d1909f1c62d3.png)

**Comment by davidpmccormick** [comment]
We can change how many columns each of the template sections span to make them match – that's relatively easy.

Changing a breakpoint variable at this point would almost certainly be painful though and I think we should try to avoid it.

**Comment by jamesgorrie** [comment]
Let's avoid this - comparing exhibitions and works is maybe a mistake to as researchers and visitors use the site very differently (see stats, most `/works` visits are on large screen).
