### ISSUE TITLE
Homepage: how does it currently support user journey?

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1861]
## Type
- ✨ Feature

## Needs
- [ ] User research
- [x] Analytics and/or component tracking

We need to do a piece of research and analysis work on the homepage. In order to progress with a homepage redesign, we need to decide:
- Is it for new or returning visitors? 
- Are we positioning only the venue or also digital? 
- Should the focus be on us or on what's happening? 
- Do we allow people to customise it based on what they've looked at before, or opt in to customisation based on audience type (for example)?
... and loads of other questions we might have about its purpose.

## Questions to answer
- What's the user flow from homepage to other content (both Collection and Library sites)
- Top paths
- Is there a difference in behaviour between new and returning visitors?
- Is there a difference based on device?
- Top searches within site (so we can understand what info people are possibly not finding)

**Comment by jennpb** [comment]
Can we please see a path analysis, top 3 journeys, for both new and returning visitors? Woop!

**Comment by hthair** [comment]
Link [here](https://wellcomecloud.sharepoint.com/sites/wcdigitalexperience/_layouts/15/guestaccess.aspx?guestaccesstoken=MzX05D5Y4F5vS1n1pdk%2FgzY7qP6iMCdj%2FZsGccTYSpM%3D&docid=2_1a87bee74c3d549e7a696f0ed145be231&rev=1&e=37510c32a61a417c8e7e7f50740eb4d3) to analytics summary from GA. Planning for user testing and interviews is underway and will follow.

**Comment by jennpb** [comment]
@hthair Can we look at this again in our next team research review? Then I think we can close it.

**Comment by hthair** [comment]
Document in link above has been updated with link to slides to show data and also new table at end showing current homepage stats (post new what's on page launch)
