### ISSUE TITLE
Description copy for /events and /exhibitions list pages

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#1893]
https://github.com/wellcometrust/wellcomecollection.org/pull/1890/files#r154339827

**Comment by jennpb** [comment]
/exhibitions meta description
`Explore the connections between science, medicine, life and art through our permanent and temporary exhibitions. Admission is always free.`

/events meta description
`Take part in a range of free talks, tours, performances and workshops. Join artists, scientists, educators to unravel big ideas around health and wellbeing.`

@davidpmccormick This one's ready to go.
