### ISSUE TITLE
Exhibitions list page

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1897]
## Type
- ✨ Feature

## What is it?
- Aggregated list of all exhibitions: past, present, permanent, future - for search engine exposure
- A way to see only exhibitions

## UI Requirements
Uses generic list template (see `/articles`)
Displays promos in this order: 
- Permanent
- Everything else **reverse chronological by date**

## Acceptance Criteria
- [x] Lists all current exhibitions (temporary and permanent)
- [x] Lists future exhibitions
- [x] Links to past exhibitions on Drupal (R1)
- [x] Redirection from `wellcomecollection.org/exhibitions/all-exhibitions/` to v2 `wellcomecollection.org/exhibitions/`

## To Do
- [x] Write summary blurb to display on page
- [x] Page description for SEO #1893 
- [x] Work out what other pages link through to this one @Heesoomoon

**Comment by jennpb** [comment]
Can we please use this copy as the summary at the top of the /exhibitions list page

`Explore the connections between science, medicine, life and art through our permanent and temporary exhibitions. Admission is always free.`

**Comment by jamesgorrie** [comment]
@jennpb given this - could we setup the redirects and close this?
https://experience.wellcomecollection.org/exhibitions/

**Comment by jamesgorrie** [comment]
>  Work out what other pages link through to this one

This doesn't really mater, we'll have a redirect from all exhibition pages.

**Comment by jennpb** [comment]
@davidpmccormick @gestchild This one's ready to go when you are.

**Comment by jennpb** [comment]
This is now done at wellcomecollection.org/exhibitions
