### ISSUE TITLE
Holiday hours flag

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#1907]
## Festive opening hours

> We will be closed from 24-26 December, with modified opening hours from Saturday 23 December until Tuesday 2 January. Please check our full festive opening hours [link https://wellcomecollection.org/visit-us/festive-opening-hours] before you travel.

Up: Monday 11 December 11:30
Down: Tuesday 2 January

Easiest way I can think is to get it behind a flag, then we can turn it on.
If we felt ambitious we could create timed flags?

**Comment by jamesgorrie** [comment]
For opening hours component:

> We have modified opening hours from Saturday 23 until Tuesday 2 January. Please check our full festive opening hours.

**Comment by davidpmccormick** [comment]
Closed by #1920
