### ISSUE TITLE
PP: user research testing What's On designs

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1917]
## Needs
- [x] User research

**Comment by hthair** [comment]
Online tests gathering feedback on the content have been concluded. Some further research talking to visitors on newer iterations of the designs will take place early in the new year. Link to current findings: https://wellcomecloud.sharepoint.com/sites/wcdigitalexperience/_layouts/15/guestaccess.aspx?guestaccesstoken=Y6hVD1lVgH9iKgdGCBRsQfPDXkPe%2B8%2BlvCgKJ13tPBQ%3D&docid=2_179eb9d6a8f934ab8b2b1dc97dd42e5d7&rev=1&e=aac0fc10683d49818e72320604ba8ebe

**Comment by hthair** [comment]
Closing this issue as online tests are completed. Will open new ticket for further user testing on newer designs.
