### ISSUE TITLE
New external IP range due mid-January 2018

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1925]
The Trust's internet connection is migrating to a new IP range in mid-January. 

This will affect:

- [ ] Google Analytics

**Comment by pollecuttn** [comment]
@hthair IT are asking if Digital Experience have updated what's needed to at this end for the new external IP range. Has anything been done about this for GA yet?

**Comment by hthair** [comment]
@pollecuttn Nothing yet, hoping IT will give us what we need to make any changes. Do you know when the switch is due?

**Comment by pollecuttn** [comment]
@gestchild @jamesgorrie @davidpmccormick Do you have anything you need to do for this IP change? I don't think you did but I'm double checking. I'm already talking to Hayley about GA.

**Comment by hthair** [comment]
Filters for both internal and external traffic have been changed and will work for both the new and old IPs. I will need to remove the old one once the switch has happened though. Will check traffic tomorrow to ensure changes are correct.

**Comment by pollecuttn** [comment]
Drupal won't be affected by the IP change (from Kate via James)

**Comment by pollecuttn** [comment]
Hayley checked on 11 Jan 2018 and changes are fine for the IP switchover.

**Comment by pollecuttn** [comment]
@hthair Chris Luen emailed today: The new date [for the changeover] is Monday 19th March 7pm – 8pm.
