### ISSUE TITLE
Two-Column Template Grid and Breakpoints Standardisation

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1930]
## Type
- 🚑 Health report

## Problem to be solved
Currently, we have different grid and breakpoints applied on following templates; Exhibition, Works, and Article. We would like to standardise the aspect ratio and breakpoints behaviour across the site to provide consistent viewing experience for our visitors.
1. Use the grid display logic applied on Exhibition and apply to other two-column templates (e.g. Works and Article)
2. Use the breakpoint logic applied on Exhibition to Works page
3. Revisit the alignment of the information box in the exhibition hero image

**Exhibition Template**
![desktop_exhibition](https://user-images.githubusercontent.com/29206031/33892296-5a9caa0e-df50-11e7-99ca-58bb7f8cf8fb.png)

**Article Template**
![desktop_article](https://user-images.githubusercontent.com/29206031/33892294-5a1fe672-df50-11e7-8822-f587d9c347b7.png)

**Works Template**
![desktop_works](https://user-images.githubusercontent.com/29206031/33892295-5a44ad54-df50-11e7-8dfa-e565a645f933.png)

**Exhibition Medium Breakpoint**
![ipad_exhibition](https://user-images.githubusercontent.com/29206031/33892298-5aefc2b6-df50-11e7-97d7-5360f42d1ae0.png)

**Works Medium Breakpoint**
![ipad_works](https://user-images.githubusercontent.com/29206031/33892297-5aca2de4-df50-11e7-93eb-a2c3f35baf74.png)

**Comment by Norvard** [comment]
Below is an audit of the 2-column page template we currently have, along with a recommendation that will help unify and streamline the experience. Currently the Exhibition/Event column application is the right standard.

Current experience mapped out across the 3 breakpoints:
![00_grid_current](https://user-images.githubusercontent.com/23660297/35161080-02bc5550-fd37-11e7-90ae-bf08a8800c7f.png)

Recommended experience mapped out across the 3 breakpoints:
![00_grid_recommended](https://user-images.githubusercontent.com/23660297/35161093-0f4e7956-fd37-11e7-9992-16798cf1a5ee.png)
