### ISSUE TITLE
A/B test colour header - What's On

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#1952]
Let's add some colour to our experience!

To kick that off, we could test 2 header colours on What's On landing. A cool banner background and a warm one. See which colour entices people to explore and inspires them to click :)

**I suggest the following:**

Current Cardigan palette:
- Option 01: turquoise-graphics
- Option 02: orange-graphics

Proposed colour palette:
- Option 01: turquoise
- Option 02: orange

Proposed colour palette mock-up
![screen shot 2017-12-18 at 10 45 37](https://user-images.githubusercontent.com/23660297/34107997-33aadb5a-e3f6-11e7-9dbf-dcb573c1c6cf.png)
![screen shot 2017-12-18 at 10 46 03](https://user-images.githubusercontent.com/23660297/34107998-33c0a6ba-e3f6-11e7-9152-99d5583c2d89.png)

**Comment by jamesgorrie** [comment]
Closing - feel free to reopen if we're going to run the test.
