### ISSUE TITLE
Adding CC BY NC ND condition to /works pages + minor bug fixes

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1981]
## Type
- ✨ Feature AND bug

Christy spotted that we have a handful of [CC BY-NC-ND images](https://wellcomecollection.org/works?query=%22cc+by+nc+nd%22#mkgyxc6p
) for which I never provided human readable blurbs. 

Please add the following text for the Licence Information 
```
You can copy and distribute this work, as long as it is not primarily intended for or directed to commercial advantage or monetary compensation. You should also provide attribution to the original work, source and licence. 

If you make any modifications to or derivatives of the work, it may not be distributed. 

Creative Commons Attribution Non-Commercial No-Derivatives (CC BY-NC-ND 4.0) terms and conditions <https://creativecommons.org/licenses/by-nc-nd/4.0/>
```

Also noticed that there is an embarrassing misspelling in the Licence information section: 
![screenshot-wellcomecollection org-2018-01-05-11-18-33-057](https://user-images.githubusercontent.com/1446139/34607293-dfdf5c12-f20a-11e7-827b-8cd12f8bec2c.png)

And we're also getting an extra space + full stop in instances where there is not author as part of the TASL model.

**Comment by jamesgorrie** [comment]
@jennpb 

Consider it closed?
https://wellcomecollection.org/works/s44q9jy9?query=%22cc+by+nc+nd%22

**Comment by jennpb** [comment]
Mega. Thanks.
