### ISSUE TITLE
Preview items on list pages

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#1988]
As an editor I'd like to see what a piece of content looks like on it's respective list pages to make sure that we can ensure we're delivering top quality work to our users.

We know this will be valuable as it's pinched us in the past re: Promo text.

**Comment by jennpb** [comment]
Can this be closed @jamesgorrie ?

**Comment by jamesgorrie** [comment]
Yea, not something that's come up more than once.
