### ISSUE TITLE
Automatically generate looping movie files from gifs

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#1990]
Editors want to add gifs to content, but gifs are inefficient (large file size). We should find a way to allow editors to automatically generate (more fit-for-purpose) movie files from gifs.

**Comment by davidpmccormick** [comment]
This tool does an excellent job of converting gifs to mp4s: https://ezgif.com/gif-to-mp4

**Comment by jamesgorrie** [comment]
Happy to close this off if we're using that tool?

**Comment by davidpmccormick** [comment]
I think it probably makes sense to close it until such time we hear that it's a broken process from the editorial team. I think Lalita and Kirsten have both used it relatively happily (at least, they haven't complained to me).
