### ISSUE TITLE
Content testing: Events copy, calls to action, imagery

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2006]
## Type
- :question: User research

To prepare the content team to work with the Events & Marketing folks responsible for writing copy and selecting images for Events, we need to do a bit more research to understand what information people need out of an Event.

Can use Events on v1: https://wellcomecollection.org/whats-on/events/all-events
and on v2 (not public): https://preview.wellcomecollection.org/events

## Questions
- What do you think this event will be like?
- What do you need to know in order to decide to attend? How would you find that here?
- What questions do you have about this event?
- (If audience appropriate): How would you find an event for teens? how would you find an event for Speech-to-text/BSL/Audio Described?
- Preference for imagery styles; does picture tell you anything about the event?

**Comment by hthair** [comment]
Ideas:

- give out questionnaire/some kind of intercept/invite to testing directly to people that attend the next event next week. 

- online survey on events pages

- recruit for usability sessions from events newsletter email list + targeted invites to special events like BSL/teen

**Comment by hthair** [comment]
Do we just want to talk to event go-ers (return visitors)/ people familiar with events?

**Comment by jennpb** [comment]
We should hit a few types:
Regular visitors
New visitors
Overseas (if possible)

If we only ask return visitors, we'll probably learn that they rely on Wellcome Collection's reputation, and are already familiar with how we do events, so will need less information. It's the people who need more help who will give us some useful info.

**Comment by hthair** [comment]
spoke to new and returning visitors about this. write up in shared folder.
