### ISSUE TITLE
Add 'Installation' to event data model

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2049]
## Type
- ✨ Feature

Installation examples:
S.P.I.R.I.T. Booth https://wellcomecollection.org/spiritbooth
Our Provocation https://wellcomecollection.org/exhibitions/our-provocation
YellowBluePink https://wellcomecollection.org/exhibitions/states-mind-ann-veronica-janssens 

## Acceptance Criteria
- [ ] Installation type can be created in Prismic
- [ ] Installation appears on What's On

**Comment by jennpb** [comment]
Duplicate of #2053

**Comment by jamesgorrie** [comment]
Questions:

**Comment by jamesgorrie** [comment]
Closing to be looked at later when we can do it more holistically.
