### ISSUE TITLE
PP: Events KPIs

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#2050]
## Needs
- [ ] Decision on which KPI(s) are appropriate, e.g. are people going through to something else from /events
- [ ] Analytics and/or component tracking
- [ ] Display of those analytics on a dashboard

## Acceptance Criteria

- [ ] The appropriate KPIs displayed on a dashboard

## Problem to be solved / User Story

In order to discover if the /events page is working for our users

As a staff member

I need/want/expect to see how the page is performing in terms of giving users what they need

**Comment by jamesgorrie** [comment]
I've created a dashboard on Data Studio with:
Pageviews

**Comment by pollecuttn** [comment]
Pinging @hthair
