### ISSUE TITLE
Coming up with an approach to Audiences

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2058]
## Type
- ✨ Feature

## Needs
- [x] User research: Youth and Schools/Teachers separately
- [ ] Agreement on data model
- [x] Drupal audit of Schools and Youth contents
- [ ] Audience label audit

## Hypothesis
Our hypothesis is that people will want to narrow down to events and content that are relevant specifically to the audience they belong to, or represent. 

EXCLUSIVE segments, e.g. those where the activities are limited to that group's participation. These are:
- Youth/Teens 14-19
- Teachers (arranging things for YOUTH in a SCHOOL setting)

May be EXCLUSIVE, depending on specific instance of that activity:
- Visually impaired (AD)
- Hearing impaired (BSL, STT)

INCLUSIVE, e.g. anyone can take part, but there might be a targeted audience, e.g.
- Visually impaired (AD)
- Hearing impaired (BSL, STT)
- People more engaged at the academic end of research

## Problems to be solved
- Teachers, teens, people with impairments and people interested in academic-led programming can't currently find their 'stuff' easily
- General public attempt to attend events and other programmes that are designed for specific groups
- Need to decide where to signpost audiences across the experience: promos, pages, navigation, filters

## Research
We need to have a better understanding of
- How people view themselves (impacts labelling): Are 'Schools' and 'Youth 14-19' the right labels? 
- How people seek information relating to their specific group (impacts labelling, navigation, filtering)
- What information are people looking for?
- What motivates them to join the youth programme and how do we encourage the involvement online?

**Comment by jamesgorrie** [comment]
@jennpb AD, BSL, and STT are interpretations the audiences for those haven't been set.

That is not to say we shouldn't have them - perhaps that's a better mechanic for Primary interpretation.

e.g. 
An event that has a BSL interpretation.
An event that has a BSL interpretation that is specifically designed for BSL speakers.

The above makes more sense to me than the "Primary interpretation" which was the last untidy piece to tidy up... thoughts?

**Comment by jennpb** [comment]
I'm happy with them as primary interpretation, definitely. I just want to be open (in the research) to thinking about whether there are ways of signposting audience-relevant content that we haven't considered.

**Comment by jennpb** [comment]
@Heesoomoon @jamesgorrie @pollecuttn I updated the main description at top after our chat just now.

**Comment by Heesoomoon** [comment]
@jamesgorrie Here's an example of Teachers' event. https://wellcomecollection.org/events/learning-resource-consultation-can-graphic-design-save-your-life

**Comment by Heesoomoon** [comment]
@jennpb @jamesgorrie Here's the Drupal audit of Youth and School pages. https://docs.google.com/spreadsheets/d/1jpripxJcdLiqjH1L4NLVIyJ3EC3A8Dw7uWLMvNjjaak/edit?usp=sharing

**Comment by jamesgorrie** [comment]
@Heesoomoon @jennpb Am I right in saying we completed this with audiences being exclusive, but interpretations allowing everyone to know how the content can be accessed?
