### ISSUE TITLE
Image gallery 'More' link showing unnecessarily

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#2093]
## Type
- 🐛 Bug

Looking at the image gallery in Part 4 of [The Story of Modern Yoga](https://wellcomecollection.org/articles/WmYSMCQAACQAn-Ke).

![more](https://user-images.githubusercontent.com/1446072/35390816-96e388d8-01d4-11e8-8d8f-cd5688fdb23e.PNG)
![no-more](https://user-images.githubusercontent.com/1446072/35390817-9704b364-01d4-11e8-918c-16064df2ca1f.PNG)

Does the 'More' link have to be there if there isn't any more info available?

**Comment by jennpb** [comment]
More/Less removed as part of #2321
