### ISSUE TITLE
Adding social networks to the footer

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#213]
Assuming that the collection ones will be good enough for launch?

**Comment by jennpb** [comment]
-- Twitter https://twitter.com/explorewellcome
-- Facebook https://www.facebook.com/wellcomecollection/
-- Instagram https://www.instagram.com/wellcomecollection/
-- Soundcloud https://soundcloud.com/wellcomecollection
-- Tumblr http://wellcomecollection.tumblr.com/
-- YouTube https://www.youtube.com/user/WellcomeCollection

@jamesgorrie
