### ISSUE TITLE
Convert works (search) page components to JSX

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#2175]
- [x]  search box (DMC)
- [x]  tags (DMC)
- [x]  captioned image (DMC)
  - [x] chapter indicator (DMC)
  - [x] tasl (DMC)
- [x]  pagination (DMC)
- [x]  promo (DMC)

**Comment by jamesgorrie** [comment]
Closing in favour of a new plan.
