### ISSUE TITLE
Display of diacritics on /works

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2185]
Here's an instance where we need to deal better with diacritics in the collections

https://wellcomecollection.org/works/zhhhfz2a = 
http://search.wellcomelibrary.org/iii/encore/record/C__Rb1198767?lang=eng

**Comment by alexwlchan** [comment]
FWIW, that’s an API issue: https://api.wellcomecollection.org/catalogue/v1/works/zhhhfz2a

😞

**Comment by jennpb** [comment]
Oh no! @pollecuttn :arrow_up:

**Comment by pollecuttn** [comment]
@jennpb When Sierra records with correct diacritics are merged with Miro records without correct diacritics this sort of thing will be resolved (so hopefully by the end of this quarter).

**Comment by pollecuttn** [comment]
Update: didn't get to this last quarter but hope to this quarter (Q3)

**Comment by jennpb** [comment]
@pollecuttn @alexwlchan Is it helpful to provide examples as we find them?

**Comment by alexwlchan** [comment]
> Is it helpful to provide examples as we find them?

I’d double check with Harrison, but I think it would be.

**Comment by pollecuttn** [comment]
@jennpb If you add them here we'll all be able to see when they're done.
