### ISSUE TITLE
Write content for Waiting list

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2198]
Addresses #2204 

If an event is ticketed, and sold out, we would like to surface to the user that we have a waiting list, and how it works, so they might decide whether or not to chance it on the day.

[Currently the text is taken from here](https://wellcomecollection.org/visit-us/events-tickets).

> A waiting list will operate for most free ticketed events. This opens in Wellcome Collection 60 minutes before the event starts and must be registered for in person. If you register for the waiting list, you'll be given a numbered ticket to take away, so you can enjoy the café, galleries and bookshop if they are open before the event. Moments before it starts, pre-booked places that fail to show are allocated to waiting list ticket holders according to the numbers on their tickets.

> If you come to register for the waiting list in person, you can take away a maximum of two tickets.

Perhaps something more succinct?

**Comment by jennpb** [comment]
Here's the copy from Jen @wellcometrust/experience-dev 

**This event has been fully booked – but there is a waiting list!**
Our waiting list opens an hour before a fully-booked event starts. Arrive early, and we’ll give you a numbered ticket. Just before the event starts, waiting list ticket holders will be allowed – in order – to take the seats that have not been filled.

**Comment by jamesgorrie** [comment]
Nice and conversational!
