### ISSUE TITLE
Write content for "limited spaces" messaging on events

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2205]
Addresses #2204 

We have limited spaces for events that aren't drop in.

We would like to make it clear to potential visitors that they are not guaranteed a seat with a ticket, thus need to show up on time.

We would also like to make it clear on non-ticketed events, being early would make it more likely that you get a seat.

**Comment by jennpb** [comment]
Ticketed - With cost
---
**Guaranteed entry**  
With our paid events, you are guaranteed entry to the event. We're unable to offer any refunds unless the event is cancelled. Concessions are available for people over 60, students, people on jobseekers allowance and people registered as disabled. An additional companion ticket for people registered as disabled is available for free.


Ticketed - Free
---
**First come, first seated**
Please note, booking a ticket for a free event does not guarantee a place on the day. Doors usually open 15 minutes before an event starts, and you can take your seats in order of arrival. We advise arriving 10 minutes before the event is scheduled to start.
Ticket terms and conditions {link}

Tickets all gone - Add to Waitlist block
We hold some spaces for people with access requirements. Please email access@wellcomecollection.org if you would like to request one of these spaces.


Tickets not yet available
---
Tickets are available to book from {TIME} on {DATE}


Not ticketed - First come, first seated
---

**Limited seats available**  
Doors will open for this event 15 minutes before the event starts. When you arrive, please collect a ticket from the Information Point on Level 0.  These tickets are first come, first served and may run out if we are busy.

Not ticketed - Drop In
---
**Drop-in**
We try to programme some drop-in events every month. These include our Packed Lunch events and our late-night events, where activities happen all over the building. For these events you just have to turn up, and there is usually room for everyone.

**Comment by jennpb** [comment]
@jamesgorrie it's all here now!
