### ISSUE TITLE
Pattern Library: Wellcome Collection brand and use of patterns

### ISSUE THREAD

**Issue by derivadow** [wellcometrust/wellcomecollection.org#226]
To ensure brand consistency esp when working with externals we should include guidance on usage e.g.
- [x] Audiences and use cases
- [ ] What we need to include in Cardigan
- Vision and mission of WC
-  Product personality and creative attributes (provocative, playful, purposeful and eclectic);
- design principles incl accessibility
- Notes of use of brand elements (typography, logo, colour)
- House style (dates, times abbreviations, organisation name (Wellcome Collection not The Wellcome Collection etc.)

**Comment by jennpb** [comment]
@Norvard Here's this issue to chat about this week.

**Comment by jennpb** [comment]
- Defining the component model

**Comment by jennpb** [comment]
Re: audiences
This will need to be useful to 3rd party designers and developers

**Comment by jennpb** [comment]
**Who’s it for**

1. **Our developers and designers**, as a living pattern library for ongoing site development. Also serves as onboarding documentation for any new starters. 
2. **Freelance designers and developers**, to use WC brand and guidelines to build digital things that we commission
3. **Guidance for exhibition designers** so they produce design assets appropriate for our website and understand the purpose of the design
4. **Guidance for content folks**, to help them select imagery, understand the logic behind the design system; also offer opportunity to propose new components or changes
5. **Peer audiences** who want to learn from our work

**Comment by jamesgorrie** [comment]
#832 in terms of style.

**Comment by jamesgorrie** [comment]
Useful for discussion, but we're not actively working on this, and this issue is not actionable.
