### ISSUE TITLE
Alignment on what's on / opening hours

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2264]
Noting this as a nitpick.

`Galleries closed today` and the `Opening hours` link aren't aligned properly

![image](https://user-images.githubusercontent.com/1446139/36664317-3054bb52-1adc-11e8-837b-af11fb0e158f.png)

**Comment by davidpmccormick** [comment]
Seen in Chrome on Windows.

**Comment by jamesgorrie** [comment]
Is this a `wontfix` the @davidpmccormick?
