### ISSUE TITLE
Changing status of 'enquire to book' events to Fully Booked

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2266]
**Who's it for?**
Teams who offer events as 'enquire to book'

**What's the change?**
We need to be able to make events that don't have Eventbrite links 'fully booked'. This indicates that the event has reached capacity.

**Comment by jamesgorrie** [comment]
https://wellcomecollection.org/events/WmXJYyQAACQAnqMj

Closing - if we need more messaging we can get that as a separate thing.
