### ISSUE TITLE
URL scheme

### ISSUE THREAD

**Issue by derivadow** [wellcometrust/wellcomecollection.org#227]
Need to agree our approach to designing URLs - both the principles and the instantiation of those principles. 

These should include things like:
- [x] ~~use of plural vs singular (/articles/:article vs /article/:article)~~ Use plural
- [ ] inclusion of dates and titles etc. 
- [x] ~~different representations e.g. /article/:article.json vs /json/ and the use of conneg~~ the wellcomecollection.org client website won't be responsible for this as we will have our own URI patterns, still probably very closely linked to the API uris.
- [ ] the principles that everything (all resources) should have a URI (and that pages are made up of resources (this also implies that e.g. anchors should follow the same pattern (replace the # with a / and get the resource)
- [ ] identifiers

**Comment by jamesgorrie** [comment]
As per Mr. Tweed's suggestion - I have been assuming we're using plurals...

**Comment by jamesgorrie** [comment]
> different representations e.g. /article/:article.json vs /json/ and the use of conneg

Assuming we would just have `api.wc.org/articles/identifier` return JSON as that's what we expect from an API, and HTML from the website.

**Comment by derivadow** [comment]
what about other representations? e.g. XML, RDF, .ics (for date based resources), PDF, csv...

**Comment by jamesgorrie** [comment]
@derivadow That could be an override e.g. `format=json`- happy to defer to @jtweed @kenoir and @alexwlchan, as this won't affect `wc.org`.

**Comment by derivadow** [comment]
that's one solution but it has always felt a much more elegant solution (esp for representations that are intended for the end user) to append the format. But I'm a bit of a RESTafarian.

**Comment by jamesgorrie** [comment]
It could be argued that having a different URI (which adding an extension is) means you should be requesting another resource, which JSON, RDF etc isn't? But maybe I am being ARGnostic.

**Comment by derivadow** [comment]
Yes the addition of the extension is also a different resource but that coz the WWW doesn't differentiate URIs and URLs very well and it feels, to me at least, that the extension is more akin to Roy's original intent/ feels more like a different representation even if that is mostly a thing in my head and not on the server.

Without wishing to go too far down the httpRange-14 rabbit hole... but we will a bit if we want to play in the LOD world... we also need to think about the URI for the thing (i.e. the NIR) which I would argue should be be something like /article/:article#thing (assuming we don't do the 303 /resource/ thing, which we don't) and the URI for the document would be /article/:article at which point we would coneg to the appropriate representation.

**Comment by jamesgorrie** [comment]
And, as mentioned, this is not a problem to be solved with this project, but still super interesting.

**Comment by kenoir** [comment]
Why not just pay attention to `Accept` headers with regard to returned format?

**Comment by alexwlchan** [comment]
> Why not just pay attention to `Accept` headers with regard to returned format?

I am a tentative :-1: on relying on HTTP headers here. In general, I find that HTTP clients make it easier to tweak your query string and/or URI extension than HTTP headers, so I’d prefer one of those. (And even if you can change the raw HTTP headers, writing an RFC 2616-compliant `Accept` header is the hardest of the three options for an end-user).

**Comment by jamesgorrie** [comment]
I really like [this article](https://www.troyhunt.com/your-api-versioning-is-wrong-which-is/) on this type of thing. You could apply the model to the accept headers too, just allowing all three methods to be used.

**Comment by jtweed** [comment]
For the API, we will be using conneg and a query parameter to change representation format. The default content type will be application/json, but we will send the same response to a request for application/ld+json.

Conneg as it's the way the spec says, query parameter as it's easier for human use in-browser for learning and debugging. Extensions would make each representation a different resource, so we won't be doing that.

For URIs of IRs and NIRs, sorry to break it to you Tom, but we won't be using hash URIs. We will have a separate URI for the NIR (TBD) and from an API point of view, a URI for the IR on api.wellcomecollection.org. The API will also point to the www.wellcomecollection.org URL.

Hash URIs are a pain to work with. Clients also don't have to send them to servers as per the spec, so it's far too easy for them to be stripped. Given we're JSON-first, LD-second, the cost of doing things any differently from the above comes at too great a cost to pragmatism and ease of use for the 99.99999%.

**Comment by jamesgorrie** [comment]
[See here for our V1 strategy](https://github.com/wellcometrust/wellcomecollection.org/wiki/V1-=--V2-URL-migration-plan).

Closing as a useful conversation.
