### ISSUE TITLE
Event Schedule: Promo styles for /whats-on/ and /events/

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2289]
Looking at treatment of promos for event series so that the series can be promoted and identified more easily.

**Comment by Heesoomoon** [comment]
@jennpb I updated the issue name from 'Event Series' to 'Event Schedule'.

**Comment by jennpb** [comment]
We have designs for event and event series promos ready to go once we do a promo system audit.
