### ISSUE TITLE
Event Series: Define content requirements for /event-series/ pages

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2290]
Looking at past events, current events, and content ambitions of the content team to define what content we need to plan for on an event series page

**Comment by Heesoomoon** [comment]
@jennpb Here's the summary of how we want to handle past events.
https://www.notion.so/wellcometrust/Events_Past-Events-cc2ff44298dd471dab4bbba7d74ac6f1
