### ISSUE TITLE
Multi-event in Eventbrite not registering as fully booked when it is

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2294]
We may have spotted a bug. 

The RawMinds comedy event has two bookable instances. The first night has been cancelled due to ❄️ , the second night is still on.

The first night has been taken down, the second night is still up on the site.
https://wellcomecollection.org/events/Wn3UUSoAACkAIe-_

However, despite both sessions being fully booked in Eventbrite, it hasn't switched the ticket button to fully booked. 

The Events team have made attempts to correct this. Abbie says 

> I’ve tried my best to work this out but it’s not correlating with the website to show as ‘fully booked’. It does not give me the option to put ‘0’ for comps or waiting list tickets. I thought that as these were hidden tickets that they wouldn’t affect the website updating to say ‘fully booked’. I also tried updating the total amount to 50 to reflect only the public tickets but this didn’t work either!

**Comment by jamesgorrie** [comment]
We can manually override this at the moment.
Not great - but wonder if we can close this for the greater task of a better knit Eventbrite integration.

**Comment by jennpb** [comment]
@wellcometrust/experience-dev Will this problem be resolved by virtue of using the widget?

**Comment by jamesgorrie** [comment]
The eventbrite widget will show both as fully booked.

**Comment by jamesgorrie** [comment]
@jennpb the two case we might need this are:

### On the promo
We currently just say that there are multiple dates, and you should check them

### On the event
The EB widget does this for us
