### ISSUE TITLE
Event schedule tasks

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#2332]
- [x] Add location from event model
- [x] Pull in event images (first pass use images from first three event images)
- [x] Add EventBrite ticket information
- [x] Add something to GA specifying that the page has an event schedule
- [x] Update ticket text/icon
- [x] Promos of events with scheduled events, show the number of events in the schedule
- [x] Update interpretations
- [x] Update design
- [x] Mobile layout
- [ ] Add contributor component
- [ ] Add background texture/brand image asset (to replace block colour) - need to pin down requirements
- [ ] Gather requirements for top 3 images (currently using first 3 from the events in the schedule)

**Comment by jamesgorrie** [comment]
@davidpmccormick Could we close this as we've decided to not actively work on this, but rather have it as part of the design audit.

**Comment by davidpmccormick** [comment]
Yep.
