### ISSUE TITLE
Library Discovery Phase

### ISSUE THREAD

**Issue by hthair** [wellcometrust/wellcomecollection.org#2349]
## Needs

- [ ] User research
- [ ] Analytics and/or component tracking

## Problem to be solved / User Story
In order to understand and plan how to begin merging the library site into the the collection site, we need to complete a discovery phase which includes:
- [ ] Organisational structure: learn who the stakeholders are, who should be involved in the process
- [ ] stakeholder interviews: gather information from key stakeholders around what they think is the purpose of the library site, how is it serving our users, how should it be serving our users, any pain points known, etc.
- [ ] Internal document review: Roadmaps, objectives, marketing docs etc. 
- [x] Existing research: Hayley to go through older research and pull out useful findings in order to know what we need to validate against.
- [ ] Desk research: analytics, collaboration with other teams, consolidate research.
#3038 
- [ ] User research: interviews, creating personas, user journeys, surveys etc including talking to staff. 

These steps will enable us to know what direction to move forward in and enable us to come up with ideas that address points discovered in the disco phase.

**Comment by jennpb** [comment]
Closing to make way for more defined tasks
