### ISSUE TITLE
What's on closed message

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#2358]
## Type
- ✨ Feature

## Acceptance Criteria
- [x] Currently the galleries closed message is shown whenever today's date is a Monday, this needs to be overridden for Mondays when the galleries are open, i.e. bank holidays
- [x] The galleries are sometimes closed on additional days, e.g. Christmas Day, the message should also display on such days
- [ ] Need to clarify which dates the galleries are open and closed

## Problem to be solved / User Story
In order to know whether I can visit the galleries today
As a visitor to the website
I need to be shown the galleries are closed message on days the galleries are closed

**Comment by pollecuttn** [comment]
Easter 2018 opening hours:
Friday and Monday are bank holidays so equivalent to Saturdays for galleries, cafe and shop. 
Easter Sunday = usual Sunday hours
Library closed all weekend (Fri-Mon).
