### ISSUE TITLE
Installations

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2367]
As a visitor, I'd like to see what exhibitions you have on to plan my visit.

__TODO Now__ 
- [x] Add `installation` tag as per design
- [x] Style body slice to fit a quote
- [x] Add contributors with bios #2597
- [x] Make sure it looks good as exhibits on exhibition page
- [x] Add "part of" async component

__TODO Later__
- [ ] At the moment the content team is putting a placeholder image in for contributors without a face, we should probably do this automagically☨.
- [ ] Potentially add links to contributors? They'll have some pretty high traffic sites, so Google juice would be good. And it's probably the right thing to do (but could also just be done in the content) 
- [ ] Have a think about the artists name in the title. We're meant to be moving to a more clean metadata model, maybe we can introduce the concept of Display options and have something like "Display primary contributor name in title"?
- [ ] Style contributors block as per some design

☨  ![screen shot 2018-05-04 at 18 00 27](https://user-images.githubusercontent.com/31692/39641135-0d718200-4fc5-11e8-84f7-d6d2210bdb8e.png)

**Comment by jamesgorrie** [comment]
We have installations on exhibition pages, and they have their own event-link installation page.

You can see these on [somewhere in between](https://github.com/wellcometrust/wellcomecollection.org/pull/2403) when in the installations cohort.

![screencapture-wellcomecollection-org-exhibitions-whvoaykaacgaldoo-2018-04-09-13_59_17](https://user-images.githubusercontent.com/31692/38499094-6f1787a0-3bfe-11e8-8a8d-5ee8737487f2.jpg)

![screencapture-wellcomecollection-org-installations-wryoox8aaajk9xr0-2018-04-09-14_01_29](https://user-images.githubusercontent.com/31692/38499130-88607ce4-3bfe-11e8-9a7d-de0f8ca8b22e.jpg)

**Comment by jennpb** [comment]
@jamesgorrie do you know why contributors aren't showing even though they're in Prismic?

**Comment by jamesgorrie** [comment]
@jennpb Yes - as we moved to the event template, it doesn't have the contributors block.

Gareth O I think had some for of design, I will try get it in.

**Comment by jennpb** [comment]
Just to follow up from conversation with Jen S:
- We should have `title` and `summary` visible as part of the promo + possibly also header, for example
**SPIRIT Booth**
An interactive photobooth which captures your inner self


- Contributor blocks should be insertable with an editable heading so it can be made contextually appropriate depending on the nature of the contribution. This applies to all contributor modules.

- Contributors should have optional avatar

@jamesgorrie @Heesoomoon

**Comment by pollecuttn** [comment]
@jamesgorrie In the image gallery the information 'i' is hidden or partially hidden between ~840-1340 px wide.

**Comment by jennpb** [comment]
We've done lots of work on this, so closing it now!

**Comment by jamesgorrie** [comment]
Just closed #2616 so should be available soonish.
