### ISSUE TITLE
Event schedule label change: More information link

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2371]
To make the site more accessible to screen readers, let's change the link label on the Event Schedule from `More information` to `Full event details`

**Comment by davidpmccormick** [comment]
@jennpb – @gestchild has done some work to get 'more information about {event title}' on the page for screenreaders: https://github.com/wellcometrust/wellcomecollection.org/pull/2352

**Comment by jamesgorrie** [comment]
I'd say we're good to close this?

**Comment by jennpb** [comment]
Can we do the combination? I still think 'Full event details' is better to read than 'More information'

**Comment by jamesgorrie** [comment]
@jennpb https://github.com/wellcometrust/wellcomecollection.org/pull/2425
