### ISSUE TITLE
Fallback png for svg not behaving as expected in <= IE10

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#242]
The fallback technique was taken from [this post](https://css-tricks.com/a-complete-guide-to-svg-fallbacks/) – needs revisiting to figure out what's missing.

![screen shot 2017-01-10 at 12 58 07](https://cloud.githubusercontent.com/assets/1394592/21807091/ede8a508-d734-11e6-8e3b-cd8c57bb3a6c.png)

**Comment by gestchild** [comment]
This issue was showing in IE10
