### ISSUE TITLE
Redirect all regular event series

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2430]
After we deal with adding additional onward journeys to event series, we need to set up redirects.

## To Do
- [ ] `https://wellcomecollection.org/exhibitions/packed-lunch` to `https://wellcomecollection.org/event-series/WifrbikAAGSyDtHk`

- [x] `https://wellcomecollection.org/saturdaystudio` to `https://wellcomecollection.org/event-series/WlYT_SQAACcAWccj` - do this after we work out how to deal with related promos

## Done
- [x] `https://wellcomecollection.org/exhibitions/wellcome-library-insights` to `https://wellcomecollection.org/event-series/WoK-NioAACkANeWK`
- [x] `https://wellcomecollection.org/exhibitions/perspective-tours` to `https://wellcomecollection.org/event-series/WlYUDCQAACQAWcdt`
- [x] `https://wellcomecollection.org/accesstours` to `https://wellcomecollection.org/event-series/WoLgbSoAACgANnxB`

**Comment by jamesgorrie** [comment]
Given Saturday studio and Packed Lunch are the only ones that have onward journeys can we redirect the other two?

**Comment by jennpb** [comment]
Aye aye cap'n

**Comment by jamesgorrie** [comment]
Done...
