### ISSUE TITLE
Event Series: Booking CTA status not displaying properly 

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#2440]
## Type
- 🐛 Bug

The booking CTA for 'Sex, Gender and Sexuality' event on 'Embracing the Goddess' is displaying incorrect status. The event is fully booked but it's displaying 'Searching for tickets...' instead.
https://wellcomecollection.org/events/Wqkd1yUAAB8sW4By
https://wellcomecollection.org/events/Wo1ZxioAAMLuZF_Q
![screenshot-wellcomecollection org-2018 04 04-10-20-36](https://user-images.githubusercontent.com/29206031/38301349-2d10ad24-37f7-11e8-9f5f-38b291e8bef5.png)

**Comment by jamesgorrie** [comment]
Fixed in #2448
