### ISSUE TITLE
Image list starting at zero

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2441]
## Type
🐛 Bug

Our inline image galleries are now displaying index zero: 
0/4, 1/4, 2/4, 3/4

Here's a recent example:

![screen shot 2018-04-04 at 13 43 08](https://user-images.githubusercontent.com/1446139/38308229-524ce3e8-380e-11e8-852f-4d830cdc8eb6.png)

**Comment by jamesgorrie** [comment]
Fixed.
