### ISSUE TITLE
Mysterious line wrap in tag component / safari

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2443]
## Type
- 🐛 Bug

The series tag is wrapping to a second line in Safari, just for a bit of fun.

Safari 11 browser
1366x768 + screen resolution

![screen shot 2018-04-04 at 14 37 30](https://user-images.githubusercontent.com/1446139/38311090-34707238-3816-11e8-9228-136740ad74d2.png)

https://wellcomecollection.org/events/WoL4VSoAACoANuXL

**Comment by davidpmccormick** [comment]
This _appears_ to have something to do with the custom letter-spacing we apply to Wellcome Bold (0.02em), in conjunction with this precise set of letters(!)

Any other copy or letter-spacing render as expected.

I think @GarethOrmerod might have a plan to stop overriding default letter-spacing at some point. If that's the case, then this bug will go away.
