### ISSUE TITLE
Resizing Safari on Exhibition page can break hero layout

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#2449]
When resizing Safari from narrow to wider, this can happen:

![screen shot 2018-04-05 at 10 12 39](https://user-images.githubusercontent.com/1394592/38357268-fd5947da-38b9-11e8-8359-b1c7fd24a57a.png)

Quick test looks like adding `width: 100%` to the `figure` element fixes this, but unclear why it happens in the first place.

**Comment by jamesgorrie** [comment]
Given the conversation around reworking exhibitions, this is being closed.
