### ISSUE TITLE
Digital Story: alignment issue

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#2453]
## Type
- 🐛 Bug

Part of the transformer in the digital story is being hidden.
https://wellcomecollection.org/articles/WjK0mSsAAJCEh4A1
![screenshot-wellcomecollection org-2018 04 05-11-22-30](https://user-images.githubusercontent.com/29206031/38376478-8aaf52c4-38f0-11e8-942a-588fe20b7ca3.png)

**Comment by jennpb** [comment]
![image](https://user-images.githubusercontent.com/1446139/39308481-78b1eac8-495d-11e8-9c55-ce6eb249b6c7.png)

https://wellcomecollection.org/articles/Wtdl8iAAABJiKOvK

This is in Chrome Version 65.0.3325.181

**Comment by davidpmccormick** [comment]
Fixed by #2548
