### ISSUE TITLE
/works 'View Wellcome Library catalogue record' link not working

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#2461]
## Type
- 🐛 Bug

Here are three examples where the 'View Wellcome Library catalogue record' link ends up at a blank page on Encore:
https://wellcomecollection.org/works/nenssqve
https://wellcomecollection.org/works/zhhhfz2a
https://wellcomecollection.org/works/k36yehnm

In all three cases the bnumber has 8 digits (7 plus check digit):
http://search.wellcomelibrary.org/iii/encore/record/C__Rb15333589
http://search.wellcomelibrary.org/iii/encore/record/C__Rb11987674
http://search.wellcomelibrary.org/iii/encore/record/C__Rb14656036

If you strip off the check digit (the 8th character after the 'b') the links work:
http://search.wellcomelibrary.org/iii/encore/record/C__Rb1533358
http://search.wellcomelibrary.org/iii/encore/record/C__Rb1198767
http://search.wellcomelibrary.org/iii/encore/record/C__Rb1465603

So I think the /works pages need to be changed to have the link to Encore have a b plus 7 digits. Not sure where/when this issue came in or if it affects all 'View ...' links.

**Comment by alexwlchan** [comment]
Yep, this is our fault. When we updated the API, we changed the format of the Sierra identifiers.

Previously: `bXXXXXXX` (7 digits, record type prefix)
Now: `bXXXXXXXX` (8 digits, record type prefix)

Fix is to strip off the last digit from the Sierra record number, and then Encore should be happy.

**Comment by pollecuttn** [comment]
FYI the last character on a b number can be an 'x' rather than a digit.
