### ISSUE TITLE
Design system: consistent header styles

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#2484]
## Type
- ✨ Feature

## Needs
- [x] Define what a header is for basic, event, exhibition
- [x] Define purpose of a header
- [x] Test the definition with current content
- [x] Align with promo content
- [x] Feedback to team to decide next steps (this is ongoing)

## To Do
- [ ] Tidy up design files enough so that devs have enough to work from
- [ ] Split booking information out from Event header style

## Agreed
- We'll use cream background in build but may change later

**Comment by jennpb** [comment]
Relates to #2521

**Comment by jamesgorrie** [comment]
Closing as an epic.
Having a meeting to gather requirements for Cardigan which will allow us to create more focussed pieces of work.
