### ISSUE TITLE
Events: Improve display logic to communicate appropriate event status (past/full)

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#2485]
## Type
- 🚑 Health report

## Problem to be solved
Currently we don't display past event status on Events and Events w/schedule. It's not obvious that an event is a past event especially for users coming from Google search results. Need to define how we display appropriate event status for following use cases.

Past event w/Booking
https://wellcomecollection.org/events/Wp7_KiUAAB8sL29M

Past event w/Email to book
https://wellcomecollection.org/events/WoL4VSoAACoANuXL

Past event w/Add to calendar
https://wellcomecollection.org/events/Wn3Z_CoAACkAIgeV

Event w/Multi dates, partially past and fully booked 
https://wellcomecollection.org/events/WmXMnCQAACYAnrFn

Event w/Schedule
https://wellcomecollection.org/events/Wqkd1yUAAB8sW4By

Reference: #2399

**Comment by jamesgorrie** [comment]
@Heesoomoon does this close this?
![past](https://user-images.githubusercontent.com/31692/44158523-c84b5780-a0ac-11e8-988a-1e1ef1248b83.png)

**Comment by jamesgorrie** [comment]
@Heesoomoon as far as I can tell this is closed?
We have past where we need it, and the event info isn't shown anywhere?
