### ISSUE TITLE
Drupal migration

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2490]
Working from this list of top 1000 pages in past year (Apr 2017-Apr 2018) https://wellcomecloud.sharepoint.com/:x:/s/wcdigitalexperience/EUsYHITaCpxBv0pyBrZRx-kBr3I4Kf7hLQfJ-qPA3vLk3g?e=AmN7YD

# Criteria for inclusion

* Has an impact on marketing and front-of-house operations if content were not available
* Content needs to be editable (therefore needs to be in Prismic)
* Priority activity for Wellcome Collection
* Is the type of thing we'll continue to publish (this means that some stuff gets excluded in the first round, but may be brought back in if there is a use case and the content can be reframed to suit current structure)
* Viewed more than 100 times in past year - except as noted below.

# Content to be included that does not fulfil inclusion criteria
* Past  exhibitions, but not all of the associated articles and galleries – with some rewriting to fit the page and be in the past tense
* All publications/books, whether they’ve had much traffic or not
* Content relating to Event Spaces/Commercial activities

# Taxonomy
We currently have these sections that pages are put into:
* Visit us
* What's on
* What we do
* About this site

# Types that have been used recently (in 2018)
* Basic page [e.g.](https://wellcomecollection.org/what-we-do/research-network)
* Book [e.g.](https://wellcomecollection.org/shapeshifters)
* ~Event~
* ~Exhibition season~
* Front page (homepage only)
* Landing page (https://wellcomecollection.org/books <= the only one)
* Press release [e.g.](https://wellcomecollection.org/press/get-your-teeth-wellcome-collection%E2%80%99s-2018-programme)
* Webforms (see below)

# Types that have not been used recently (pre 2018)
* Basic landing page (there are [only](https://wellcomecollection.org/visit-us/making-nature-learning-resource) [two](https://wellcomecollection.org/visit-us/gallery-guide))
* Artefacts [e.g.](https://wellcomecollection.org/articles/aids-posters). These include
  * Articles
  * Audio
  * Credits
  * Essay
  * Event
  * Image gallery
  * Interactive
  * Interview
  * Learning resource
  * Podcast
  * Profile
  * Publication
  * Social media
  * Video

# Structure
All content has 
* A main image (promo image)
* Title

Some content has
* [Children pages](https://wellcomecollection.org/what-we-do/working-wellcome-collection)

# Web forms (data collection)
* https://wellcomecollection.org/youth-and-community-workers-sign (email signup)
* https://wellcomecollection.org/young-people-aged-14-19-sign (email signup)
* https://wellcomecollection.org/teachers-sign (email signup)
* https://wellcomecollection.org/ideas-hub-register-your-interest
* ~~https://wellcomecollection.org/submit-your-sleep-stories~~
* https://wellcomecollection.org/contact-us
* https://wellcomecollection.org/stay-touch
* ~~https://wellcomecollection.org/complete-survey~~
* ~~https://wellcomecollection.org/what-er-are-you~~
* ~~https://wellcomecollection.org/ask-researchers~~
* ~~https://wellcomecollection.org/self-guided-group~~
* ~~https://wellcomecollection.org/guided-tours~~

# Questions
* What do we do with content that seems to have seemingly been split into multiple sections e.g. https://wellcomecollection.org/what-we-do/working-wellcome-collection? Could we potentially have these as 1 page with section headers, and potentially a overview nav at the top?
* When bringing over publications 
* What would we need to have a Drupal content freeze on new content, and use the info page already on Prismic? From looking at recently published content, some form of list of erlevant onward journey content? Although, as mentioned above, it feels like a lot of that content could be put into 1 page (maybe we do both). This content was created recently (11 April)
  * https://wellcomecollection.org/what-we-do/research-network
  * https://wellcomecollection.org/what-we-do/hub
  * https://wellcomecollection.org/what-we-do/hub-award
* Is the hub actually a `Place` https://wellcomecollection.org/what-we-do/hub
* Are the cafe's etc actually places?
  * https://wellcomecollection.org/visit-us/wellcome-caf%C3%A9
  * https://wellcomecollection.org/visit-us/wellcome-kitchen
* Do we want to allow pages to expire? Either automatically, or buy user input e.g. "This page is not relevant after the 15 June 1987" to allow us to at least let users know when they arrive on those pages (or redirect them).
~~* What shall we do with press images: Press images https://wellcomecollection.org/press/press-images~~

## Make sure
* When migrated add drupal URL to Prismic

**Comment by jamesgorrie** [comment]
# Basic page with basic page children

Are these landing / listing pages?

**Comment by jamesgorrie** [comment]
Another question potentially how do we retire content in the future.

**Comment by jamesgorrie** [comment]
Press images https://wellcomecollection.org/press/press-images

**Comment by jamesgorrie** [comment]
Reminder to store drupal API in prismic.

**Comment by jamesgorrie** [comment]
Questions for the DB:

* How many pages in What we do section and published?

**Comment by jamesgorrie** [comment]
# First steps

Could we have a go at the "What we do" section, here is a spreadsheet of that content (I'll be making it slightly more tidy and rich):
https://docs.google.com/spreadsheets/d/1jSHEf3q7-sJFCQVsXDiflr2QUMVijkuAgFlzi-6oSEI/edit#gid=0

**Comment by jennpb** [comment]
Answered questions:

> What shall we do with press images: Press images https://wellcomecollection.org/press/press-images

We have approval to get rid of them entirely as these photos aren't any good.

**Comment by jamesgorrie** [comment]
- [ ] Promo text as meta description
- [ ] Adding non-Prismic content to content lists
- [ ] Visit us page (map component?)
- [ ] Update newsletter with new logo and content
- [ ] Make Rachael new main contact at dotmailer
