### ISSUE TITLE
Drupal migration: Basic pages

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2526]
~There are currently 90 pieces of content in the what we do section of the site.~
This will include What we do, Visit us, and press releases.

I think the process can be something like:
* Create content with basic HTML (no content lists)
* Import into Prismic
* ~Once the pages are created, we can then import the Content list slices. We need the content to exist before linking to it.~ We might look into creating more rich content lists that can have API backfill.

To achieve this the model needs to store the Drupal ID, we can then start create the references.
We should also store the "Site section" just in case.

The first piece seems simple, the second piece might take a little more time.

---
## Media migration

It seems that importing all these images from Drupal / Wordpress is messing up the very tidy media library that the content team has been creating. 

A solution to this would be to import the URLs of the images, and embed the URLs, rather than import them as URLs and render them sans credit info etc.

This would then allow us to go through and update them over time.

This solution comes with the caveat that we _will_ deprecate this solution, which will mean any of the images that haven't been replaced in the body will cease to exist, and promo images will default to placeholders (Speak to Gareth about what this might mean).

This could be stored in a field which is a standard link called `drupalPromoImage`.

When they get replaced this link will be broken, we can then have a page for the content team which is a query of `hasDrupalPromoImage` allowing them to know what content needs attention.

---
## Things we need, but will deprecate

* Store Drupal ID
* Media files

---

## Things that will not migrate across

* [Images in body content content](https://wellcomecollection.org/summer)
* [Video in body content](https://wellcomecollection.org/what-we-do/rawminds-project-film-out-wild)
* [Tables in body content](https://wellcomecollection.org/event-spaces/rooms/medicine-now-gallery)

---
Shape of Drupal pages

![img_20180424_143533](https://user-images.githubusercontent.com/31692/39190662-f3b98600-47cc-11e8-9575-1289934c98ad.jpg)

---

**Comment by jamesgorrie** [comment]
@jennpb given the 2 step nature of how we do the process, do you think it would be fair to ask the content team to review the content without the content lists, and add those in after?

**Comment by jennpb** [comment]
Perhaps, but it's likely to be me and Jen doing the review anyway (sadly!)

**Comment by jamesgorrie** [comment]
We have tables on these pieces of content which we haven't supported, but I imagine would want to.

It's a big push in Prismic to allow it in the RTE, but they haven't added it, we can add a body slice that could support it though.

https://wellcomecollection.org/what-we-do/access
https://wellcomecollection.org/what-we-do/henry-wellcome-auditorium
https://wellcomecollection.org/what-we-do/williams-lounge
https://wellcomecollection.org/what-we-do/dale-room
https://wellcomecollection.org/event-spaces/rooms/burroughs-room
https://wellcomecollection.org/event-spaces/rooms/medicine-now-gallery

**Comment by jennpb** [comment]
In the short term I think we should just transform these as unnumbered lists. Once we rewrite the content (later on) it might not require tables (this also gives us time to design tables)

Here's an example:

- **Theatre**: 154
- **Classroom**: 154 (with armrest tables)

**Comment by jamesgorrie** [comment]
Taken from the list supplied, things that have been marked up as `exclude` or `V2`, it's actually most of the content.

There is 64 / 88.

/what-we-do/proposing-online-article
/what-we-do/ideas-hub-who-can-apply
/what-we-do/whats-involved
/what-we-do/frequently-asked-questions-0
/keep-in-touch-with-hub
/what-we-do/research-network
/what-we-do/created-out-mind
/what-we-do/hubbub
/what-we-do/hub-award
/what-we-do/ideas-hub
/what-we-do/safeguarding-children-and-vulnerable-adults-policy
/what-we-do/rawminds-summer-filmmaking-project
/what-we-do/rawminds-public-speaking-and-presentation-project
/what-we-do/outsider-art-community-workshops
/what-we-do/rawminds-ambassadors-panel
/vocalexercises
/what-we-do/previous-saturday-studios
/schools
/what-we-do/community
/what-we-do/working-wellcome-collection
/visit-us/it-could-happen-anyone
/what-we-do/states-mind-learning-resource
/sleepstories
/visit-us/tabiyat-medicine-and-healing-india
/what-we-do/rawminds-creative-merchandise
/what-we-do/tools-trade
/visit-us/learning-resources-permanent-exhibitions
/electricitytouring
/visit-us/rawminds-creative-audio-project
/what-we-do/rawminds-trailer
/rawminds
/thecollectors
/medicinecorner
/sexologyresource
/mindcraft
/transvengers
/what-we-do/food-and-drink
/what-we-do/venue-hire
/what-we-do/library-collections-online
/what-we-do/youth-and-schools
/what-we-do/previous-touring-exhibitions
/what-we-do/touring-exhibitions
/what-we-do/art-global-health
/what-we-do/projects
/what-we-do/curious-conversations
/what-we-do/space
/what-we-do/interested
/what-we-do/residents
/what-we-do/introducing-henry-wellcome
/what-we-do/wellcome-trust
/what-we-do/wellcome-images
/what-we-do/frequently-asked-questions
/what-we-do/collection-enquiries
/what-we-do/learning-resources
/what-we-do/access
/what-we-do/terms-conditions
/what-we-do/henry-wellcome-auditorium
/what-we-do/williams-lounge
/what-we-do/franks-and-steel-rooms
/what-we-do/dale-room
/event-spaces/rooms/burroughs-room
/event-spaces/rooms/medicine-now-gallery
/what-we-do/about-wellcome-collection
/what-we-do/hub

**Comment by jennpb** [comment]
:boom:
