### ISSUE TITLE
Newsletter promo

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#2559]
:sparkles: Feature

## Who's it for?
- People who want to keep up with what WC offers
- Marketing team who want to make signing up for email newsletters appealing

Current design looks like this:
![image](https://user-images.githubusercontent.com/1446139/40131261-6762e68a-5931-11e8-922d-eee03a020f9d.png)

Let's make it lovely!

**Comment by jennpb** [comment]
Here's the Newsletter Signup promo design. https://zpl.io/V1lrEpX

**Comment by pollecuttn** [comment]
https://github.com/wellcometrust/wellcomecollection.org/pull/4384

**Comment by GarethOrmerod** [comment]
There's some additional QA/design work needed before this is fit to be pushed to the live site.

**Comment by jennpb** [comment]
Text on promo should be:

**Be the first to know**
Stay connected with email updates from Wellcome Collection

CTA = Sign up

@davidpmccormick @gestchild @pollecuttn This is ready to go!

**Comment by taceybadgerbrook** [comment]
16 August, the date of the newsletter promotional change, is marked with a red arrow on the graph below:
 
![image](https://user-images.githubusercontent.com/32418070/64958542-58973580-d887-11e9-98f5-ce1b11c4b663.png)



Also marked in yellow highlighter are lulls in page views for the /newsletter page during the end of December and July/August, most likely linked to the school term.  For this reason, a baseline statistic for the month preceding the change is likely to lead to the conclusion that the change has been successful.  To avoid including these lulls in the baseline or comparison period, I suggest using the 60-day period 1/4/19 - 30/5/19:  1,812 page views) to compare to 6-month period 1/9/19 - 30/10/19.

**Comment by taceybadgerbrook** [comment]
Here's a link to the Sharepoint document for baseline comparison: [https://wellcomecloud.sharepoint.com/:w:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/Baseline%20data%20for%20newsletter%20promo%20ticket%202559.docx?d=we482243cd5704f8da2194ecba3c44bd5&csf=1&e=7f237l](url)

**Comment by taceybadgerbrook** [comment]
Comparing the 90-day periods 1/4/19 - 30/6/19 (baseline) vs 13/8/19 - 11/11/19, shows a similar trend (gradually declining) but % of newsletter promo of homepage unique page views shows a decline mid September to late October.  

If the homepage was altered during September, is it worth looking again at another comparison period starting 1/11/19?

Here are links:
https://wellcomecloud.sharepoint.com/:w:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/Baseline%20data%20for%20newsletter%20promo%20ticket%202559.docx?d=we482243cd5704f8da2194ecba3c44bd5&csf=1&e=FflkBi

https://datastudio.google.com/reporting/1yLef4Q39v5LhA_sgzx-y6EvpC5_LI1qk

**Comment by taceybadgerbrook** [comment]
Summary statistics show lower clicks on the newsletter signup button during the 90-day period 13/8/19-11/11/19 compared to both 1/4/19-30/6/19 and 13/8/18 - 11/11/18 and declining percentages of clicks/total unique page views.

Work on newsletter promo text, button positioning and design to differentiate card from footer to be ticketed separately.
