### ISSUE TITLE
Drupal migration: Manual migration

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2565]
Some pages are best to manually migrate over.
So far we have:

## List pages
https://wellcomecollection.org/visit
https://wellcomecollection.org/what-we-do

## Exhibitions
But are actually event series:
https://wellcomecollection.org/saturdaystudio (https://wellcomecollection.org/event-series/WlYT_SQAACcAWccj)
https://wellcomecollection.org/exhibitions/packed-lunch (https://wellcomecollection.org/event-series/WifrbikAAGSyDtHk)

We should redirect these :arrow_double_up: 

~https://wellcomecollection.org/onlight~
~https://wellcomecollection.org/sexologyevents~
~https://wellcomecollection.org/exhibitions/hubbub~

## Has video
We don't support it in the body, but can be easily
https://wellcomecollection.org/what-we-do/rawminds-project-film-out-wild
https://wellcomecollection.org/what-we-do/rawminds-project-film-roots
https://wellcomecollection.org/what-we-do/young-people-respond-superhuman

# Contain images
~https://wellcomecollection.org/summer~

## Rooms
They have images and tables, shouldn't take to long to migrate over:
~https://wellcomecollection.org/what-we-do/access~
~https://wellcomecollection.org/what-we-do/henry-wellcome-auditorium~
~https://wellcomecollection.org/what-we-do/williams-lounge~
~https://wellcomecollection.org/what-we-do/dale-room~
~https://wellcomecollection.org/event-spaces/rooms/burroughs-room~
~https://wellcomecollection.org/event-spaces/rooms/medicine-now-gallery~
~https://wellcomecollection.org/what-we-do/franks-and-steel-rooms~
~https://wellcomecollection.org/visit-us/support-voice-hearing~

**Comment by jennpb** [comment]
With those that are actually event series (Saturday Studio and Packed Lunch), we can simply redirect.

However, those Drupal pages have a bit more explanatory content that we don't support on event series pages (like contact details). Could go live without but add as a feature later.
