### ISSUE TITLE
Article - author

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#257]
Author image and name should also include Twitter handle

**Comment by jennpb** [comment]
if they have one :)

**Comment by jennpb** [comment]
@davidpmccormick can you please remove the bio copy from `div class="author  author--border-bottom "` in cardigan?

**Comment by davidpmccormick** [comment]
@jennpb Done. Can this now be closed?

**Comment by jennpb** [comment]
:1st_place_medal:
