### ISSUE TITLE
New exhibition status: temporary closure

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2599]
## Problem to be solved
Medicine Man is closing temporarily for refurbishment (from 21/5 to 24/6). We need to have a status that allows for this.

Example:

![image](https://user-images.githubusercontent.com/1446139/39754134-0c057650-52b9-11e8-87f0-23bc0259801c.png)

## Acceptance Criteria
- [ ] The status should appear on the promo and header
- [ ] Message should say `Temporarily closed between 21 May-25 June 2018`
- [ ] The status should use a different colour indicator to the 'Now on' status (use orange?)
- [ ] Temporary closure info should display in a SERP
- [ ] The reopen date should be changeable (in case work overruns and exhibition doesn't reopen on stated date)
- [ ] The exhibition should not appear on `What's On` list while it is closed (from 21 May)

**Comment by jennpb** [comment]
Message should say `Temporarily closed between 21 May-25 June 2018`

**Comment by jamesgorrie** [comment]
> SERP

There isn't a clear way to do this as far as I can tell.
https://github.com/schemaorg/schemaorg/issues/819
https://schema.org/OpeningHoursSpecification

There is some hint that not specifying the times of opening and closing implies shut for a period, but I'm not sold.

@gestchild how did we handle this for other closing dates?

Also as an FYI - are you aware you can specify opening hours in this format?
https://schema.org/openingHours
