### ISSUE TITLE
Header - logo shift

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#260]
Mobile nav. When opening the navigation, the logo shifts to the right.

**Comment by jamesgorrie** [comment]
Can't seem to replicate - please let us know what browser etc.

**Comment by Norvard** [comment]
Chrome. The search icon shifts as well

**Comment by davidpmccormick** [comment]
Is this behaviour perhaps the result of a scrollbar being added to the page when the header is viewed on its own (e.g. in Cardigan) and when your OS settings are to always display scrollbars? If so, then I think this can safely be closed as won't fix.

If it isn't to do with that, then I still can't replicate it.

![scrollbars](https://cloud.githubusercontent.com/assets/1394592/22303164/e98db650-e329-11e6-9300-b38edc2b5d1b.gif)
![screen shot 2017-01-25 at 18 10 38](https://cloud.githubusercontent.com/assets/1394592/22303175/f278a4b4-e329-11e6-96aa-2e89fbd67034.png)

**Comment by Norvard** [comment]
Yep, my bad. Close this away
