### ISSUE TITLE
Contributors component

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2619]
## Type
- ✨ Feature

from #2367 

- At the moment the content team is putting a placeholder image in for contributors without a face, we should probably do this automagically☨.
- Potentially add links to contributors? They'll have some pretty high traffic sites, so Google juice would be good. And it's probably the right thing to do (but could also just be done in the content)
- Have a think about the artists name in the title. We're meant to be moving to a more clean metadata model, maybe we can introduce the concept of Display options and have something like "Display primary contributor name in title"?
- Style contributors block as per some design

**Comment by jamesgorrie** [comment]
> Potentially add links to contributors

The content team currently adds the links in the bios, which feels nice, but we can also add an official link - but wonder if that would be a list of links (Schema.org uses `sameAs`).

> artists name in the title

Yea, I was thinking about this and thought we could start having a set of properties on content, something like "Display properties" and add things like, "Display artist name in title". Or - as we on;y do this for installations, do this as a rule for installations - and address the problem if we decide some installations shouldn't be this way.

**Comment by jennpb** [comment]
Currently we render contributors in these ways: https://docs.google.com/presentation/d/1b6T_TbF4v0xG-_xkZSFzAwAa450OuIDxC9KYgj4pxzI/edit?usp=sharing
