### ISSUE TITLE
Footer - opening times

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#263]
Correct wording on opening times: Library tab: the Library is closed on Sundays (it currently says "Sunday 10:00 - 16:00"). I don't know what the wording for Sunday should be. On the Galleries tab it says "Galleries closed"; on the Restaurant tab it just says "Closed"

**Comment by jamesgorrie** [comment]
@jennpb Could we have a complete audit on the wording for the opening times please?

**Comment by jennpb** [comment]
here you go @jamesgorrie 

Galleries
Monday	Galleries closed
Tuesday	10:00 - 18:00
Wednesday	10:00 - 18:00
Thursday	10:00 - 22:00
Friday	10:00 - 18:00
Saturday	10:00 - 18:00
Sunday	11:00 - 18:00


Library
Monday	10:00 - 18:00
Tuesday	10:00 - 18:00
Wednesday	10:00 - 18:00
Thursday	10:00 - 20:00
Friday	10:00 - 18:00
Saturday	10:00 - 16:00
Sunday	Library closed


Restaurant
Monday	Restaurant closed
Tuesday	11:00 - 18:00
Wednesday	11:00 - 18:00
Thursday	11:00 - 22:00
Friday	11:00 - 18:00
Saturday	11:00 - 18:00
Sunday	11:00 - 18:00


Cafe
Monday	08:30 - 18:00
Tuesday	08:30 - 18:00
Wednesday	08:30 - 18:00
Thursday	08:30 - 22:00
Friday	08:30 - 18:00
Saturday	09:30 - 18:00
Sunday	10:30 - 18:00


Shop
Monday	09:00 - 18:00
Tuesday	09:00 - 18:00
Wednesday	09:00 - 18:00
Thursday	09:00 - 22:00
Friday	09:00 - 18:00
Saturday	10:00 - 18:00
Sunday	11:00 - 18:00
