### ISSUE TITLE
Title on digital story flicking from white to transparent

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#2647]
## Type
- 🐛 Bug

Seen scrolling through https://wellcomecollection.org/articles/Wub0aCIAAJjUxliL. Did the title always flick from white to transparent?

[Yoga](https://wellcomecollection.org/articles/Wi_yzSQAAFqPOrDY) does the same.

![white-title](https://user-images.githubusercontent.com/1446072/40193194-863fdec8-59fe-11e8-9dba-884e3e43633e.PNG)

![transparent-title](https://user-images.githubusercontent.com/1446072/40193197-896049e4-59fe-11e8-8ab0-d6b70379579c.PNG)

**Comment by gestchild** [comment]
@pollecuttn which browser is this happening in?

**Comment by pollecuttn** [comment]
@gestchild Well it's not happening in mine anymore! (It was on Chrome Version 66.0.3359.181 (Official Build) (64-bit) on Windows.

The title on both the yoga and genius links look right again now, so I'm closing this.
