### ISSUE TITLE
Can't page beyond the first page of articles

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#2662]
## Type
- 🐛 Bug

There's a forward arrow at the bottom of https://wellcomecollection.org/articles for the next page of articles. It doesn't take you to more articles; instead it links to page 2 of works https://wellcomecollection.org/works?page=2 

Please fix the link so it goes to the next page of articles.

**Comment by jamesgorrie** [comment]
On it.
