### ISSUE TITLE
Copy changes to newsletter signup

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2692]
https://wellcomecollection.org/newsletter
- [x] Change h1 from `Sign up` to `Stay connected with email updates from Wellcome Collection`

- [x] Change What's On blurb to
`What’s On at Wellcome Collection: our roundup of the latest exhibitions, events, new books and opportunities to get involved. Sent monthly with up to one extra update per month.` - RETAIN BOLD ON WHAT'S ON

- [x] In legal small print, change `third party` to `third-party`

https://wellcomecollection.org/newsletter?result=success

- [x] Remove exclamation mark from h1
- [x] Remove `Thank you for signing up to receive updates from us.`
- [x] Replace rest of body with `If this is the first time you’ve subscribed to updates from us, you will receive an email asking you to confirm. Please check your email and click the button. Thank you!`

**Comment by jennpb** [comment]
@jamesgorrie @gestchild here's the copy for Dotmailer's unsubscribe screens (there are 2):

**First unsubscribe page**

Default text is
```
Amend your settings
To stop receiving commercial and marketing related messages from us, or to amend your preferences or personal details, enter your email address below and click 'Submit'.

Once unsubscribed, you may still receive transactional emails from us such as order or shipping confirmations.

Note: You'll need to enter the email address to which we sent the email message. If the email address you enter is not recognized, we may be sending to an old email address of yours, or an email alias that you're part of (for example, 'info@', 'sales@' and so on).

Please enter your email address 

Email address [email field]
```
**CHANGE TO** 
```
[h1] Update your preferences

Please take a few seconds to update your preferences or personal details. Enter the email address which we send communications to and click submit.

Enter your email address

Email address [email field]
```

**SECOND UNSUBSCRIBE SCREEN**
**Change to** 

```
[h1]Update your preferences

We want to send you content that is interesting and relevant to you. You can tell us the newsletters you would like to subscribe to below.

To stop receiving all newsletters from Wellcome Collection, click unsubscribe [UNSUBSCRIBE BUTTON]

[h2]My email address
You can change the email address which we sent newsletters to:
Email address [email field]

[h2]Wellcome Collection updates
I would like to receive:
[ ] What's On
[ ] Access
[ ] Young people 14-19
[ ] Teachers and schools
[ ] Youth and community workers


Boilerplate text
Wellcome Collection is part of the Wellcome Trust, a global charitable foundation dedicated to improving health. The Wellcome Trust is a charity registered in England and Wales, no. 210183. Its sole trustee is The Wellcome Trust Limited, a company registered in England and Wales, no. 2711000 (whose registered office is at 215 Euston Road, London NW1 2BE, UK).
```



Include
Wellcome Collection logo
Green button
Change blue bar to vertical dashes


Delete any data fields pertaining to collection of personally identifiable information

**Comment by jamesgorrie** [comment]
@jennpb 

> Change blue bar to vertical dashes

We use a very un-standard way to do this, and I'm not sure they're going to be able to implement it.
If they can't do that - do we ask for the black one?

**Comment by jennpb** [comment]
Black is fine. Was just trying to be fancy.

**Comment by jamesgorrie** [comment]
Changes have been requested, tracking through Wrike, their change log system.
I have requested access for Natalie.

> Many thanks for your sign off.
I’ve now placed your branded unsubscribe & FTAF in the queue to be built; it will be built to the approved design. 
Once this has been scheduled, one of the team will start coding your pages. When this is completed, you will receive a notification email or Wrike comment from them when they have updated your account with your branded unsubscribe & FTAF for you to test drive. To give you a rough guideline, this whole process will take 7 to 10 working days to complete depending on our queues.
Should you have any functionality amends, you can reply back to the coder during your 10 business day testing period after receipt.
