### ISSUE TITLE
Typography review

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2699]
## Type
🎩 Clean up

New base page and promo styling may have some inconsistencies that need some cleaning up.
Homepage
- Fully booked style doesn't seem to match other status font style
- Section header (What's on, Latest articles...) should be WB4 33px 
Content list and Section header styles in conflict
- The description header (Henry Wellcome Auditorium) is bigger than the section header (Explore each room) on mobile. Check the size. https://wellcomecollection.org/pages/Wuw2MSIAACtd3SsC

**Comment by pollecuttn** [comment]
Design development has been done for:

- part of
- call to action
- labels
- breadcrumbs
to be included in the evolution of the base page.

**Comment by jennpb** [comment]
See also #637
