### ISSUE TITLE
Rogue vertical promo dividers

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2701]
## Type
🎩 

Some funny business with the vertical promo dividers on Explore. What's the display logic for these?

![screen shot 2018-05-24 at 07 51 50](https://user-images.githubusercontent.com/1446139/40469285-eca1d13e-5f27-11e8-8e8a-f2b00c4ff0ac.png)

**Comment by gestchild** [comment]
This was fixed here: #2684 - might be cached in your browser?

**Comment by jennpb** [comment]
You are absolutely correct.
