### ISSUE TITLE
Improving events with schedules 

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2717]
## Type
:sparkles: Feature
This one's a high-priority thing so the content team can publish the event for the next Friday Late Spectacular. 

## Who's the change for
- Content and events people who are creating content for a multi-event event (Friday Late Spectacular)
- Potential attendees of the event who want a view of everything that's happening during the event

## Problems to be solved
1. We need a way to create scheduled happenings that don't have event pages. This is because there may be all-night/all-event things (like musicians or pop-up performances). When we first build events with schedules, we talked about this as a next step.

2. We also need to be able to define the format for the event

3. Content team would like to be able to choose the images at the top of the page. Right now, they're automatically taken from the three events already in the group.

Please look to other examples like symposia or conferences that have a schedule listing but not necessarily individual pages for each slot.

**Comment by jamesgorrie** [comment]
1. We currently have it that if an event doesn't have a description, we don't link off to it. This still feels like the right solution, as we still surface all the other content, and having another way to create events is more load on the content team and the system in terms of complexity
1. Jen S created a format "Late" - we can run this past people to see if it makes sense. "Festival" was also suggested, but that feels like it would be for larger events, such as Why Music.
1. This will be addressed when we move the event over to the `BasePage`and they can add images, galleries etc. It's an interesting challenge as we're not sure if either of those solve the problem of "How do we give a visual impression of the different types of things going on".

**Comment by Heesoomoon** [comment]
Update: 
- James demoed to Jen S. on how to display events info without creating an event page. She updated upcoming Friday Late Spectacular event, 'Handle with care'.
- Jen S. has added 'Late' format to use for this type of multi-events. Hayley to get user feedback on the label.
- Ability to choose images will be addressed when we migrate the page to the base page template.
- We won't make any updates to how events are ordered or grouped till we know more about how the events team programmes these multi-events.
