### ISSUE TITLE
Create a robots.txt that isn't Drupalised

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2724]
https://wellcomecollection.org/robots.txt
☝️ That's what we inherit from Drupal.

**Comment by jennpb** [comment]
@wellcometrust/experience-devs Is this one still relevant?

**Comment by davidpmccormick** [comment]
We don't have a `robots.txt` currently (the Drupal one looked like [this](https://github.com/wellcometrust/collection/blob/6848b63d08c50cae01c378750d0740337f69958b/www/robots.txt) (just boilerplate from the looks of things).

Is there anything that we would want to prevent from being crawled?

**Comment by jamesgorrie** [comment]
Taking this on so I can sort out some of our routing.

**Comment by jennpb** [comment]
@wellcometrust/experience-devs Can this be closed?

**Comment by jamesgorrie** [comment]
The only thing I can think we would put in the `robots.txt` is the sitemap, which we don't have.

We could create a new issue for that and make a task of it to add the `robots.txt`?
