### ISSUE TITLE
Relegate V1 to the fallback

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2726]
Currently there is a lot of tom foolery, especially in router, to get traffic split between V1 and V2.
I'd like to get rid of a lot of it.

A process:
* Wait for the analytics to see where the 404s and V1 traffic is still be accessed
* Deal with those
* Have the domain point straight to the `wellcomecollection` infra service
* Have that proxy fallback to V2

A drawback to this is that we then 404 from Drupal.
I think we might be able to catch that 404, and point back in our direction.

Drupal tooling will still be available at `prev.`.

**Comment by jennpb** [comment]
Can we close this one @jamesgorrie ?

**Comment by jamesgorrie** [comment]
Labelled as techprofit - but hasn't been done.

**Comment by jamesgorrie** [comment]
Closing for #2826
