### ISSUE TITLE
Getting here: Map improvements to make it easy to plan a visit

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#2732]
## Type
- ✨ Feature

## Who is this for?
Visitors who are planning a visit to Wellcome Collection

## Problem to be solved
Current map view doesn't display Wellcome Collection prominently and it's unclear to people who aren't familiar with the surrounding area. Also it doesn't allow user to get a direction. The map on Science Museum solves this quite well.

Our map
![screenshot-wellcomecollection org-2018 05 25-13-36-25](https://user-images.githubusercontent.com/29206031/40544781-566bdaac-6021-11e8-9cfa-be57ddd3fa91.png)

Science Museum Example
![screenshot-www sciencemuseum org uk-2018 05 25-09-48-08](https://user-images.githubusercontent.com/29206031/40544515-80fc0702-6020-11e8-986e-e2b990894e4b.png)

**Comment by gestchild** [comment]
Have had a quick look into this. The Science Museum is using the The Maps Embed API which adds the place card.

The downside of that API is "The Maps Embed API may include on-map advertising. The ad format and the set of ads shown in any given map may change without notice." - https://developers.google.com/maps/documentation/embed/guide

We're using the Maps Javascript API, which doesn't have the potential ads, but also doesn't have a straightforward way of adding the place card, although I think it should be achievable.

**Comment by Heesoomoon** [comment]
@gestchild Thanks for looking into it. For now, I suggested to the content team to add 'Get direction' link below the address which will either link to Google map or TFL.

**Comment by jennpb** [comment]
## Heatmap data
Hotjar / 2000 page views / ended 28 Jun 2019

**Desktop**
![heatmap-4374085-click-desktop](https://user-images.githubusercontent.com/1446139/61125072-ac109000-a4a0-11e9-89a8-95dd7b9a2e72.jpg)

**Mobile**
![heatmap-4374085-click-phone](https://user-images.githubusercontent.com/1446139/61125083-b7fc5200-a4a0-11e9-874b-e457434fd86c.jpg)

**Comment by jennpb** [comment]
Lots of hovering over the text address on Desktop. If we make this a link, users would be able to open a map directly on their device, instead of having to copy the postcode and paste into an app/map site.
