### ISSUE TITLE
Events UX: nuanced versions of 'interpretation'

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2736]
We automatically fill the BSL events with the phrase 'BSL interpreted', but it's actually a bit more nuanced than that. Sometimes BSL providers are themselves deaf, and don't see their service as being 'interpretation', but just their language. It's like saying 'this event will be English-interpreted' for a group of English speakers. In teh case of this event, Orla raised concern that this would be alienating to the tour guide.

Do we need to rethink how to deal with this kind of dynamically populated text. How might we allow for more nuance?

![image](https://user-images.githubusercontent.com/1446139/40555144-1180df0e-6040-11e8-967b-f009e9552610.png)

**Comment by jamesgorrie** [comment]
We might also use something similar to contributor role here, such as `interpretationType` and have something like language? This might be useful to think about, but I wouldn't implement it just yet as we don't have any other examples bar language.

**Comment by Heesoomoon** [comment]
Update: Jen S. to update the copy to make it more clear.

**Comment by jamesgorrie** [comment]
Closing as the content was updated

**Comment by jamesgorrie** [comment]
Thinking this a little we could do the following

Before:
```JSON
{
  "times": {
    "start": "2100-01-01",
    "end": "2100-02-01",
    "isFullyBooked": true
  },
  "interpretations": [
    {
      "isPrimary": true,
      "interpretation": {
        "id": "123",
        "title": "British sign language" 
      }
    }
  ]
}
```

After:
```JSON
{
  "times": {
    "start": "2100-01-01",
    "end": "2100-02-01",
    "isFullyBooked": true,
    "interpretations": [{
      "isPrimary": true,
      "interpretation": {
        "id": "123",
        "title": "British sign language" 
      }
    }]
  }
}
```

There are some limitations I would like to explore here first before committing to this e.g. I am not sure we can have multiple times and then attach multiple interpretations to it, you might need to have 1 interpretation / time.
