### ISSUE TITLE
Missing 'Email update' module on What's on screen

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#2742]
## Type
- 🐛 Bug

## Problem to be solved
The email update module is missing on What's on screen. The module should be displayed above the footer. 
![screenshot-wellcomecollection org-2018 05 29-16-35-04](https://user-images.githubusercontent.com/29206031/40669208-54ddf374-635e-11e8-81fe-584b44a47a46.png)

**Comment by gestchild** [comment]
Just needed to deploy the What's On service - it's there now
