### ISSUE TITLE
Dashboards for core metrics for core types

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2762]
# Core metrics across all pages
* Pageviews
* Return visitor count
* Average session duration

# Core types

## List pages
E.g. `/explore`, `/works?q=hats`
* CTR
* Bounce rate

# Articles
* Time on page
* Scroll %
* Could ☝️ be merged into a "Engagement" metric?

# Events
* Click rate on "book a ticket"
* Add to calendar

# Exhibitions
* Time on page?
* Onward journeys (CTR)?

**Comment by hthair** [comment]
I think we could add bounce rate to list pages as a metric. i.e. we don't want people landing on a list page and giving up/leaving

**Comment by hthair** [comment]
link to notion page https://www.notion.so/wellcometrust/Core-metrics-meeting-4d11019ebd6a48ad83bbcd61dfd162e3

**Comment by hthair** [comment]
Dashboard created, for events we have gone with pageviews and bounce rate due to all our different event types meaning there is no other consistent measure (i.e. book a ticket isn't an option on all events).
