### ISSUE TITLE
Measurement of core user journeys

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2763]
It feels like whenever we've wanted to measure journeys through the site, it's been a bit fiddly.
We need a way to define, and measure our defined user journeys scalably (easy to set up) and reliably (when the results are in, we trust them).

**Comment by jennpb** [comment]
https://www.notion.so/wellcometrust/Core-metrics-meeting-4d11019ebd6a48ad83bbcd61dfd162e3

**Comment by jennpb** [comment]
@hthair asked me to think about metrics for Events pages. It's a tough one when we don't always have a booking option:

Events as a whole: 
I'd go for engagement metrics - while we can't be sure whether the person actually turned up to the event, does the event page provide enough interest that the user thinks it's worth engaging with more content? do they go on to view other events (maybe this event wasn't at the right time, or was already booked, but i'm interested enough to see what else is happening?)

Secondary purpose is of course booking a ticket, so can we get any kind of data on Event page > Book ticket flow?

**Comment by hthair** [comment]
We can see number of eventbrite outbound link clicks. Presumably all of these will be available only from event pages and not elsewhere on the site?  

I'll see what the data looks like and could add in that graph for events measure. I think the click through to other events might not be the primary purpose of the page. It might be they find one they like and that's the end, or maybe view more things on the site (not limited to other events?) 

If we think in practical terms for the page and what we should track to ensure it's not 'broken', we want people to understand the practical info, where it is, what, when and what they need to do to attend (i.e. book a ticket or not). I wonder if we should track 'add to calendar' AND book button/outbound links to cover bookable and non bookable events. I'll see whether add to calendar actually gets used currently.

**Comment by jamesgorrie** [comment]
> add to calendar

316 clicks since 14 Feb, when we started tracking.

**Comment by jennpb** [comment]
We can't use GA to measure understanding, though. Happy to include qualitative measures but I thought this was just for dashboardable things? 

What do we think about the use of the 'add to calendar' - is that low? high? worth keeping? @Heesoomoon . We didn't set ourselves any success measures for this, so it's going to be an entirely subjective decision.

**Comment by jamesgorrie** [comment]
> is that low? high? worth keeping? 

It was a test to begin with, now that we're moving over, I wander if we only reimplement it as a test, and set success measures, otherwise remove or iterate on it.

**Comment by jennpb** [comment]
It hasn't made it into the new design, that's the problem. We would need to place it in the 'useful information' section or near the bottom CTA. But you're right, if implemented again it should be as a test with defined success measures.

**Comment by hthair** [comment]
Dashboard updated based on decision from planning meeting; consistent measures for events are pageviews to events and bounce rate on these pages. Other things like booking clicks aren't available on all events. If we specifically change something on one of these types of event pages then we can get a retrospective measure as the data is available still.
