### ISSUE TITLE
A/B testing content with Prismic

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2764]
We would like to be able to take ideas from the content team and test them.

An example is Ben would like to test if people would navigate from whats-on to events more if we use images of past events vs people shots.

Prismic does support [A/B testing vis experiments](https://prismic.io/docs/rest-api/beyond-the-api/experiments), albeit a bit fiddly.

**Comment by jennpb** [comment]
We agreed in this week's planning session that we will use Optimize for the first A/B image test for Ben, and see whether there is a demand. 

It would probably be worth doing this if the content team wanted to run tests every week, but may not be worth the effort if it's 1-2 tests a month.

**Comment by jamesgorrie** [comment]
💥
