### ISSUE TITLE
Design System: Consistent 'Plan a visit' information

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#2778]
## Type
✨ Feature

## Who is this for
Visitors planning a visit to Wellcome Collection

## Problem to be solved 
- We have very complex opening hours for 5 different locations within the building and many visitors turn up on Mondays to see exhibitions.
- Since we display the hours for all 5 locations on 7 days, it makes the footer quite long and making it difficult to get an overview of what's open and when.
- Since we used existing components between footer and exhibitions and evolved it to today's hours on What's on view, there are inconsistencies to how we present the information to the visitors.
![screenshot-wellcomecollection org-2018 06 06-17-59-22](https://user-images.githubusercontent.com/29206031/41053440-6695809a-69b3-11e8-8570-179870d0706d.png)

## Potential solution
- Consistent 'plan a visit' information through out the site and public programme pages to provide clear opening hours and visit related info
- Contextual visit info to the page content
![wc_visitusmodule](https://user-images.githubusercontent.com/29206031/41053461-7b5ecfae-69b3-11e8-86c3-8b7acbcdd15d.png)

## Success Metric (TBD)
- reduced number of visitors coming to see exhibitions on Monday
- increased number of visitors visiting cafe outside of gallery hours

**Comment by jamesgorrie** [comment]
Looks great!
Do you think the metrics are something to correlational though?

This could be affected by many things, including just an increase to visitors to the building (we could use percentiles, but that still feels to loose)

Could we potentially work with the VEAs to see if requests about opening hours drop?
