### ISSUE TITLE
Get NextJs performance at par ++ to Nunjucks 

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2806]
# NextJS
<img width="669" alt="screen shot 2018-06-12 at 13 50 32" src="https://user-images.githubusercontent.com/31692/41291465-acdaf696-6e47-11e8-8b21-bb16bdc269fa.png">

# Nunjucks
<img width="670" alt="screen shot 2018-06-12 at 13 51 02" src="https://user-images.githubusercontent.com/31692/41291487-b9eddfd8-6e47-11e8-8c34-648eede34601.png">

**Comment by davidpmccormick** [comment]
The remaining recommendation from Lighthouse to get parity with the Nunjucks setup is to preload our font files.

The way we've currently written our font declarations, you will only load the fonts required for your system, so if you're on a Mac, you'll only load Wellcome Bold and Lettera (2 x woff2 files).

If we follow Lighthouse's recommendation, we will force all users to download all 8 font files, regardless of how many they need.

On balance, I think it makes sense to overrule Lighthouse's recommendation on this occasion.
