### ISSUE TITLE
Comments at end of article

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#281]
![image](https://cloud.githubusercontent.com/assets/1446139/21859325/10ba17ca-d824-11e6-88f2-114c22718216.png)

**Comment by Norvard** [comment]
Something to note, the icons within this design, that are given to users when they comment would be generated by the system. If its easier, I can basically create SVGs for each letter but maybe there is a better way to do it? The idea is that 2 contrasting colours are chosen and the first letter of the user, these would make up the default icon.

When we get to this, lets chat on how to make this work.

**Comment by jennpb** [comment]
Also depends on what authentication system we use. Gravatar, for example, has its own default icons with option to upload one's own.
