### ISSUE TITLE
Get v1 site into S3 bucket

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2826]
We want to shut down Drupal for good so:
- we don't have to maintain this system anymore
- users don't stumble across v1 site in a web search

The site has been archived at archive.org (hurrah) but we may still want an archive of the site for ourselves, for temporary fallback or to make the published Drupal legacy content findable.

Details, corrections to follow...

**Comment by jennpb** [comment]
Reported to VEAs via info@wellcomecollection.org:

> From https://wellcomecollection.org/events/type-tasting-language-laboratory press "All events" which goes to https://wellcomecollection.org/whats-on/events/all-events which returns "Not Found".
> 
> Same issue for when the "Exhibitions" button is pressed.
> 
> When: at time of this email
> On: Using a chromebook.

**Comment by jamesgorrie** [comment]
@jennpb a suggestion could be to remove the prev.wellcomecollection.org route (so don't split traffic, just route to V2).

We can then track 404, setup any relevant redirects, and then move on.

Saying that - maybe something to do would be setting up the 404 page to be nicer, explaining perhaps that they could request information?

Here's the report of the pages being accessed over the past 28 days:
![screen shot 2018-08-28 at 15 15 56](https://user-images.githubusercontent.com/31692/44728855-54aa4100-aad5-11e8-872a-af12e5425dbf.png)

**Comment by jamesgorrie** [comment]
@jennpb just went over this with @wellcometrust/experience-dev.

There are a few options we thought of:
1. Route all traffic to V2, if that 404s, route to V1, if 404, use V1 404.
  __Pros:__ We don't serve 404 content to users, keep track of V1 pages via GA, content team doesn't need to rush to fill the content gaps
  __Cons:__ We lose the ability to use our own 404 page, we still serve from Drupal
1. Route all traffic to V2. Track 404s via GA
  __Pros:__ We stop serving Drupal content, we report to the content team which pages are being 404ed
  __Cons:__ We start serving 404 content to users which might mean watching that content lose any Google juice and disappear

Considering we serve the V1 404 page most the time, we could remove the massive gif and start with 1?

**Comment by jennpb** [comment]
@wellcometrust/experience-dev 
The only prob with Option 1 is precisely the 404 page problem: we'd still be sending people to a page that has the old footer, with the old newsletter signup without all of the GDPR padding.

What would we need to consider before moving from Option 1 to Option 2 (were we to go with Option 1 in the short term)?

**Comment by pollecuttn** [comment]
- [ ] Remove v1 newsletter sign up from footer - @gestchild 
- [ ] Add content about Wayback Machine to 404 page https://github.com/wellcometrust/wellcomecollection.org/issues/2908#issuecomment-416901088
- [ ] https://wellcomecollection.org/exhibitions/past should go to v2 not v1
- [ ] Default to v2; top 20 content above to go to v1
