### ISSUE TITLE
BUG: dead links on articles page

### ISSUE THREAD

**Issue by hthair** [wellcometrust/wellcomecollection.org#2835]
- 🐛 Bug

Dead ends noticed by visitors on articles page. Received in hotjar feedback 4 hours ago.

**Comment by jennpb** [comment]
@hthair Does Hotjar give info on which page?

**Comment by hthair** [comment]
yep: https://wellcomecollection.org/articles?page=2

**Comment by hthair** [comment]
SESSION DETAILS
 5 hours ago
Desktop (1512 x 708)
Chrome 67.0.3396
Windows 10

**Comment by davidpmccormick** [comment]
Ken’s ten: looking back at ten years of Wellcome Collection: https://wellcomecollection.org/articles/WXInvioAABlsbLHu

Looks bust to me.
