### ISSUE TITLE
Spacing and paragraph breaks on articles

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2839]
## Type
- 🐛 Bug

Kirsten spotted this bug yesterday. Doesn't seem to be a problem on any other templates (base page or otherwise).

> Hi there, just noticed when I looked at the articles just now on Stories that all the line breaks/ spaces between paragraphs seem to have been removed. They're now looking more like one big block of text...

**Comment by davidpmccormick** [comment]
Fixed by #2842.
