### ISSUE TITLE
Prismic Home page

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2855]
# Date
30.05.18 - 03.06.18

# Page
https://wellcomecollection.org/

# Purpose / Hypothesis
To see how people are interacting (scroll and click) with the new Prismic home page. 

# Primary outcome
"Visit us" most clicked on part of the page. 	

# Sample size / power
2000 pageviews.  

# Comments

**Comment by hthair** [comment]
https://insights.hotjar.com/h?site=3858&heatmap=2718120&token=cede530e9dd1a89f3a384f19aa168aaf
