### ISSUE TITLE
Design system - QA - global

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#2858]
- [x] Section divider spacing https://zpl.io/amn8N1r 
- [x] Section title larger and aligned to the top https://zpl.io/amn8N1r 
- [x] Text sizing update for different breakpoints https://zpl.io/VQYonYk and https://zpl.io/2ym1r9p

**Comment by jennpb** [comment]
@davidpmccormick @GarethOrmerod Just checking whether this has already been dealt with? Also #2859
