### ISSUE TITLE
Design system - QA - header

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#2859]
- [x] Page with featured image: update the height of the background to not go beyond the featured image, ideally it should cover 2/3 of the featured image (e.g. The Library) https://zpl.io/bLOBzD7
- [x] Installation: display rule for the header background and text size on mobile - documented in Sketch; talk to Gareth O
- [x] Header text update to 33px https://zpl.io/bLOBzD7
- [x] Header text background always cropped to word length https://zpl.io/bLOBzD7
- [x] Feature image display rules for different breakpoints - documented in Sketch; talk to Gareth O

**Comment by jennpb** [comment]
@pollecuttn @wellcometrust/experience-dev Has this issue been dealt with as part of all the other header changes?

**Comment by jamesgorrie** [comment]
I'd say so
