### ISSUE TITLE
Text overlapping image + captioned image bug

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2883]
:bug:

Two weird things:
The intro text is overlapping the image here
The info icon is nudged up.  

This is in Safari 1200x800 screen resolution

<img width="888" alt="screen shot 2018-06-22 at 14 44 40" src="https://user-images.githubusercontent.com/1446139/41779828-ecdfbd86-762a-11e8-9197-59ed1fdf6551.png">

**Comment by jamesgorrie** [comment]
@jennpb could you pop a link into the issue pretty please?

**Comment by jamesgorrie** [comment]
https://wellcomecollection.org/pages/WvlygCAAACAA3yTb
