### ISSUE TITLE
Books: not displaying price or publication date

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2892]
Reported by Suzanne:
The books pages aren't displaying price or publication date.

Both are parts in Prismic.

I understand the publication date is tied up in #2733 

but can we resolve the price not displaying?

**Comment by jamesgorrie** [comment]
Yea, publication date is exactly that... 

In terms of price - there was a small discussion that I thought had the output of excluding price as they can and have been seen to go out of date, which could leave people confused.

Shall we still have it there? Not sure if as affiliates, we have access to any APIs / widgets that give us access to a live price?

**Comment by jennpb** [comment]
Publication date now displays when in Prismic.

I don't think there's any need to show a price when our primary bookseller has variable pricing. For example, when clicking through to see Medical London, I can see the book has been discounted from it's RRP
![screenshot 2018-11-29 at 07 35 16](https://user-images.githubusercontent.com/1446139/49206274-6b4c8680-f3a9-11e8-8e4c-7b0765b6cc50.png)

Also, people may want to buy the book in their local currency.

**Comment by jennpb** [comment]
Reopening this issue because the display of publication dates is inconsistent. On some pages it's showing, on others it's not, despite presence of pub date in Prismic. 

Not displaying
https://wellcomecollection.org/books/WwVK3CAAAHm5ExyB
https://wellcomecollection.org/books/WwVK3CAAAHm5ExxD

Displaying
https://wellcomecollection.org/books/W3GgbikAACIAC6nC
https://wellcomecollection.org/books/W3FPiSkAACkACkrO

**Comment by jamesgorrie** [comment]
@jennpb this was the issue #2733 
I've gone through and fixed them all.
