### ISSUE TITLE
404 page content

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#2908]
## Content

[in wellcome font]This isn’t the page you’re looking for, but how about these?
 
•	[Our exhibitions and events](https://wellcomecollection.org/whats-on)
•	[Our library](https://wellcomelibrary.org/)
•	[Our stories](https://wellcomecollection.org/explore)
•	[Our books](https://wellcomecollection.org/books)
•	[Our images](https://wellcomecollection.org/works)
•	[Our youth programme](https://wellcomecollection.org/youth)

---

### Analytics
Jen would like to monitor:
- what links are bringing people to the 404 page
- if people follow any of the links from the 404 page

**Comment by jennpb** [comment]
@hthair Something to look at... setting aside a bit of time to do a regular check in Google Search Console for pages that are 404ing, so we can figure out why and what to do about it.

**Comment by hthair** [comment]
@jennpb I've set up a reminder for me to check weekly.

**Comment by pollecuttn** [comment]
Add some content to [Wayback Machine](https://archive.org/web/) for other older content from previous WC sites for move from V1 to V2 (@jennpb )

**Comment by jennpb** [comment]
@wellcometrust/experience-dev 


to add after the list of links: 

Looking for something published before 2018? Our websites have been archived by the Internet Archive [https://archive.org] in its Wayback Machine [https://web.archive.org/].
- See the Wellcome Collection website from 2007-present [https://web.archive.org/web/*/wellcomecollection.org]
- Read blog posts from 2013-2017 [https://web.archive.org/web/*/blog.wellcomecollection.org]

If you're looking for something specific you'd love to see return to this website, email us at digital@wellcomecollection.org.

**Comment by jennpb** [comment]
Closed via #3246 and #3247
