### ISSUE TITLE
Articles not rendered properly in reader view

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2917]
In safari and pocket.

<img width="886" alt="screen shot 2018-06-27 at 08 08 03" src="https://user-images.githubusercontent.com/31692/41958204-3e06addc-79e1-11e8-9cdf-28b3132b35c5.png">

Checked again on 23/8/19 - still not rendering properly. Seems to be taking a fragment of the article from the middle of the article, rather than starting from the beginning and displaying whole article. - JPB

**Comment by pollecuttn** [comment]
https://github.com/wellcometrust/wellcomecollection.org/pull/2918
