### ISSUE TITLE
Delayed booking on events with multiple dates

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2926]
As reported by Alice W, the current flow is that:
* We create a dummy event with when the tickets become availble
* We attach this to the Prismic event
* Publish
* Five minutes before Alice W removes the dummy event and attaches the new multi date event

☝️ hmmm.

**Comment by jennpb** [comment]
@jamesgorrie @gestchild do you know whether this would be resolved by using the EB widget? Or problematic in a different way?

**Comment by jamesgorrie** [comment]
I thought it might have been something to do with us, but it's not.

> NOTE: For events with multiple dates and times, you'll only see the option to set the "Tickets sales end" date for a time that is a specific number of "hours, minutes, or days" before the event either "starts" or "ends.

https://www.eventbrite.co.uk/support/articles/en_US/How_To/how-to-change-the-start-end-date-and-time-for-ticket-sales?lg=en_GB

Let's have a think of how we can help...

**Comment by jamesgorrie** [comment]
Closed in #3147
