### ISSUE TITLE
Republish our content

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2937]
Both to make it easier for others to reuse our articles + make it clear that we encourage it.

@jamesgorrie Have you got any examples of good ones? Or is it more of a "You can republish this."
@jamesgorrie I quite like this one: https://aeon.co/ideas/utopia-is-a-dangerous-ideal-we-should-aim-for-protopia 
@derivadow Slick. I quite like a lot about Aeon.

**Comment by jamesgorrie** [comment]
Worth mentioning Mosaic:
https://mosaicscience.com/story/spain-uk-organ-donation-transplants-liver-kidney-heart-lungs-surgery-nhs/republish/
