### ISSUE TITLE
Build multi date Events prototype 2 for usability testing

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#2944]
References #2901 

![option-2](https://user-images.githubusercontent.com/6051896/42166060-c9afdd94-7e01-11e8-8688-be3fa6d77856.jpg)

- [x] ~Prototype will be available at /whats-on/events/:id~ - done in #2943 
- [x] ~Use cohort to determine which prototype the user is given (Option 1 is the default)~ - done in #2943 (link will be /whats-on/events/:id?cohort=prototype-2)
- [x] Display date range and how many dates there are
- [x] 'Check dates and book' CTA is anchor link to further down the page
- [x] Dates are shown in the page body
- [x] Incorporate eventbrite widget, to allow date, number of tickets selection in page
- [x] Need to set up dummy event in eventbrite

**Comment by Heesoomoon** [comment]
Here's the event content order:
What you'll do (body)
About your hosts (contributor)
Dates and Times (list of dates and booking CTA)
Useful Information
- Location
- Booking info
- Interpretation info
- Event T&C link
Part of... (series)
