### ISSUE TITLE
Usability testing multi-date events

### ISSUE THREAD

**Issue by hthair** [wellcometrust/wellcomecollection.org#2949]
Prototypes being build - #2944 & #2943 

These will be available as webpage links that will allow users to complete an uninterrupted path through the site from a list of events to the individual page to booking. We're also allowing people to complete the booking process on event brite.

Hypothesis:
Having multiple promos for different times/dates appearing on a list page (whats-on or /events) is confusing for a visitor and does not easily show the alternative dates on offer.

Objectives:
- discover what the user flow is for event booking
- discover any barriers in enabling visitors to find and book an event (how does having one date displayed affect their flow vs multi select).

Recruitment:
- New visitors (4)
- return visitors (2)

Methods:
2 prototypes being built on webpages.
usability session asking users to show us how they'd book an event, including finding a date they can attend, getting them to search to find all possibly dates. 

things to follow up:
- [ ] do we need a fake email to have them enter in event brite? (can we use the same one multiple times?)
- [ ] is the event brite booking going to be fake data somehow?

**Comment by hthair** [comment]
recruitment underway, twitter and poll on events pages providing our email for them to get in contact.

**Comment by Heesoomoon** [comment]
@hthair @jennpb Here's the prototype link.
Option 1 Multiple promos
https://invis.io/C4MV8SB8XYP#/307835227_EventList1
Option 2 Combined promos
https://invis.io/UYMV90NA9QW#/307890034_EventList2

**Comment by jennpb** [comment]
https://docs.google.com/presentation/d/1YlJOkrj6xeKecSIWe1zI0sC2dstu2dxqcsq6ZtIpL1Y/edit#slide=id.p

Will take forward any recommendations under separate issues.
