### ISSUE TITLE
update component referral state in GA

### ISSUE THREAD

**Issue by hthair** [wellcometrust/wellcomecollection.org#2950]
In order to better understand how our homepage is performing we'd like to record how well a promo is doing on a particular page and position i.e. promos in positions 1-3 feed through a lot of traffic. This will also tell us how people are interacting with the home page. 

Can we add position on page of promos and the page it's come from (homepage)?
@jamesgorrie or @davidpmccormick or @gestchild ^

**Comment by jamesgorrie** [comment]
As a note we could use the events for this.

It must be noted though that events use beaconing, which isn't supported in IE, which is 3.8% of our traffic.
