### ISSUE TITLE
What's On + homepage: making way for new installation 24 July

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2971]
Pharmacy of Colour opens on 24 July so we should get it up on the site: https://wellcomecollection.org/installations/WyuWLioAACkACeYv?dm_i=4U4Z%2CPW0%2CP9T34%2C20K8%2C1

**What's On**
What's On is not yet a properly managed list, so we'll need to add Pharmacy in manually.

The most straightforward thing to do is to put it alongside Reading Room in the list.

**Homepage**
We also need to make sure it appears on the homepage for the duration of its opening.

Any thoughts on whether this falls at the end of the list or with the temporary exhibitions @Heesoomoon?

**Comment by jamesgorrie** [comment]
See #2972 for current orderings to help inform where we might put it.

**Comment by Heesoomoon** [comment]
@jennpb To have the Installation appear on the homepage, we need to define the display logic of the combined list view (exhibitions and events) across the homepage and what's on. I've listed suggested order in #2972. 

When we migrate What's on, we may want to regroup 'Try these too' and 'Eat and shop' to one section.
