### ISSUE TITLE
A/B test Event promo position on homepage

### ISSUE THREAD

**Issue by hthair** [wellcometrust/wellcomecollection.org#2975]
Testcard:
![screen shot 2018-07-09 at 14 36 59](https://user-images.githubusercontent.com/26549021/42453748-944dce84-8385-11e8-94f9-519539619885.png)

**Comment by hthair** [comment]
Analysis completed. Results here: https://wellcomecloud.sharepoint.com/:p:/s/wcdigitalexperience/EWfoqYlt9-NJuUBaMSlugg4BYSdtEUtHRxpLdEbjT2aNsg?e=SNwpFk

**Comment by jamesgorrie** [comment]
@hthair does [this](https://github.com/wellcometrust/wellcomecollection.org/issues/new?template=research.md) not work for this?

**Comment by hthair** [comment]
@jamesgorrie Yes! I just had already made the card so easy to copy and paste
