### ISSUE TITLE
Update 'Feeling curious?' tags in Works Landing

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#2976]
As Hayley noted in our May Analytics report, our users are using the tags (e.g. Paintings, Health, Botany, Science) on Works landing to discover the collections. We haven’t updated since we launched it last year and could use some refresh. It would be great if the results represent diverse topics or formats (books and images). 

Suggestions
**Bodies**
Anatomy, DNA, 

**Mind and therapy**
Mental health, Healthcare, Asylum

**Medicines and Intoxicants**
Medicine , Smoking, Medical recipes, Alchemy, Opium, Arsenic/Poison, Pharmaceuticals

**Disease, Illness and Conditions**
AIDS, Sleep disorder (insomnia), Birth defects

**Nature and Environment**
Botany, Almanac, Herbals

**Culture and Society**
Sanskrit, Quacks, Devil

**Humanity**

**Material types**
Paintings, Ephemera, Health posters, Etchings, Portraits, Manuscripts

**People**
James Gillray, Charles Darwin

**Comment by jennpb** [comment]
Consider using Harrison's image colour browser or image similarity experiments

**Comment by jennpb** [comment]
New idea from Beta Release discussions:
Featured set of items to reflect our collection, that helps users to see what they can find in our collections. (New release will have Digital images, Pictures, and Books).

**Comment by Heesoomoon** [comment]
@jennpb I've updated the list based on the suggested topics from Collection Info team and Alice.
