### ISSUE TITLE
Migrate event series to BasePage

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2983]
# Steps

- [x] Migrate as it is to `BasePage` with `description` as `body` 
- [x] Add `body`
- [x] Migrate description to single slice `body`

**Comment by pollecuttn** [comment]
- [ ] Header - needs multi-date
- [ ] Booking info block - needs multi-date
- [ ] Contributor
- [ ] Location
- [ ] Quote
- [ ] Free tag

**Comment by jamesgorrie** [comment]
@pollecuttn is this comment meant for events rather than event series?

**Comment by pollecuttn** [comment]
@jamesgorrie Yep - sorry!

**Comment by jamesgorrie** [comment]
Closing as this is done.
Assuming some more work will come out when we review it after catalogue week.
