### ISSUE TITLE
Allignment

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3000]
![screen shot 2018-07-12 at 12 06 24](https://user-images.githubusercontent.com/31692/42629682-21aa33d8-85cc-11e8-82a8-abf1b265b083.png)

**Comment by davidpmccormick** [comment]
I believe we're still reliant on the editorial team uploading pre-cropped 16:9 images anywhere we need that to be the aspect ratio.

**Comment by jamesgorrie** [comment]
Fixed
