### ISSUE TITLE
Implement new event page design

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#3022]
## Design 
- [x] Yellow labels - move and style
- [x] Green links - Type
- [x] Keep tags for now
~- [ ] Background pattern - need to discuss logic around title white background~ - moved to #3090
- [x] Free label
- [x] Useful info block - (more detail below)
- [x] Contributors - roles in prismic
- [x] Check dates anchor
- [x] Inactive button - need to confirm logic/ display
- [x] Keep each date in dates/booking module chronological
- [x] Keep dates visible
- [x] decide on and implement multi date display

## Text changes
![event-text](https://user-images.githubusercontent.com/6051896/42813121-ce4f43fa-89b7-11e8-85cd-a42fa241ea5d.jpg)

## Questions:
- Do we show past events with EB widget?

## Hold off on:
- Drop in / other messaging in header
- When past, kill CTA
- More to explore - ignore for now, pick up with promos

**Comment by gestchild** [comment]
Useful info. block:
- Title should be 'Need to know'
- Location. 'We'll be in the ${place.title}.' Followed by the ${locationInformation}

**Comment by jennpb** [comment]
After discussion with @gestchild @GarethOrmerod @Heesoomoon and me - here are some decisions that impact on the event card:

**DISPLAY LOGIC**
- display nearest upcoming date even if it has `fully booked` status
- display extra messaging: `See all dates/times` when multiple dates and times are scheduled
- continue to display fully booked events on Homepage and What's On (though we may revisit in the future)

**FULLY BOOKED events**
- show `fully booked` as usual even when nearest upcoming is fully booked - this is a disappointment trade-off we need to make: either the user doesn't see fully booked status, and clicks through to find that their preferred date is booked, or the user does see a fully booked status, but is given a hint that there may be more dates/times available. We felt that the latter option was preferable.

**Comment by Heesoomoon** [comment]
In terms of the order of information for the event card, @GarethOrmerod will explore it as part of Promo+Card project. For now, we decided on following.
- Event title
- Date, time
- Status
- Messaging: # events, See all dates/times
- Part of [event series]
![wc_eventcard](https://user-images.githubusercontent.com/29206031/43190244-7ab03ecc-8ff0-11e8-9816-3053df9363af.png)

**Comment by jennpb** [comment]
Connected to #3008

**Comment by Heesoomoon** [comment]
@gestchild @davidpmccormick @jennpb 
Here's the event messaging and CTA display logic we reviewed this morning.

## Events Messaging and CTAs
**Use Cases**
Session
- Single date
- Multi date/time

Event Status
- Upcoming
- Past

Booking Type
- Just turn up
o Unlimited
o Limited
- Email to book
o Book
o Fully booked
o Partial for multi session
- Book (Eventbrite)
o Booking opens [date, time]
o Booking available
o Fully booked
o Partial for multi session

## No Booking
[Event_NoBooking.pdf](https://github.com/wellcometrust/wellcomecollection.org/files/2244957/Event_NoBooking.pdf)

## Email Booking
[Event_Email.pdf](https://github.com/wellcometrust/wellcomecollection.org/files/2244956/Event_Email.pdf)

## Eventbrite Booking
[Event_EB.pdf](https://github.com/wellcometrust/wellcomecollection.org/files/2244955/Event_EB.pdf)

**Comment by gestchild** [comment]
Remaining items captured in 

Before page live:
- #3105
- #3093

After page live:
- #3090 
- #3091 
- #3092
