### ISSUE TITLE
Promos break when no image is supplied

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3035]
Actions:
- [ ] Add hatched background when there is no image
- [x] Add warning to validation #3036

**Comment by davidpmccormick** [comment]
The `Promo` component already checks for the presence of the image and shows the hatched background if there isn't one.

When we came across this bug, this is what _was_ happening on the `/explore` page, while the same component was apparently breaking on the homepage.

**Comment by davidpmccormick** [comment]
Did we ever get to the bottom of what caused the error?

**Comment by jamesgorrie** [comment]
Ah, sorry, I thought your comment was the conclusion.
Should I reopen?

**Comment by davidpmccormick** [comment]
Not sure – I suppose everything on the ticket is 'done'. I think it probably makes sense to be closed, but not sure how we might figure out what was actually happening. Possibly just going to have to wait till it happens again ¯\_(ツ)_/¯.
