### ISSUE TITLE
Less restrictive event booking descriptions

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3053]
## Who it's for
Content team for more flexibility in dealing with special cases in booking information. 

## Problem to be solved
Our current way of autopopulating booking info is sometimes too restrictive; we have occasional events that just don't fit the model.

Here are the current texts: https://docs.google.com/spreadsheets/d/1QZK9Ori7fgFCSnwqyUGET7tAqDMhMaMTZT1WsOShDR0/edit?usp=sharing
And we dealt with this in #1790 and #2205 

Jen TS says:
>We're having some trouble with giving incorrect or inconsistent messaging to users (usually around a deviation from the go-to process in the programming, but likely to keep coming up especially as we start having research-oriented events too....
>
> While I quite like having some rigid rules in place around messaging, there are times when this automatic text doesn't quite work. Here are two examples that help illustrrate:
> 
> Saturday Studio
> It's unticketed, but there are some specific rules around when you arrive and how the allocation goes on the day, ie.  
> Sign-up will open at 13.30 in the Studio. Places are given out on a first-come, first-served basis.
> 
> I would say having a specific message for this one might be helpful, but the timings might switch, so I was wondering if you thought it might be helpful to have an override for the message for test cases.
> 
> Our Brains and Us
> Another example where we've had trouble is with an event that's being run in the Hub. It's ticketed, but once you get your ticket you can arrive anytime on the day: https://preview.wellcomecollection.org/events/WzZHDyMAAIIxgM96/preview
> 
> We chose drop-in, but the messaging isn't consistent - you can just turn up but only once you have your ticket, so a tweak would be ideal.  We explored not ticking the 'drop-in', but when we did that, it brings up the ticketed text, which is this:
> Please note, booking a ticket for a free event does not guarantee a place on the day. Doors usually open 15 minutes before an event starts, and you can take your seats in order of arrival. We advise arriving 10 minutes before the event is scheduled to start.
> 
> Hope this is helpful background. It would be great to explore what options are out there for helping us with inconsistent messaging.

**Comment by jennpb** [comment]
Here's another example where it's gone awry: 

https://wellcomecollection.org/events/W2RQnyYAACYAR93g

**Booking information**

Ticket guarantees a seat.

**First come, first seated**
Please note, booking a ticket for a free event does not guarantee a place on the day. Doors usually open 15 minutes before an event starts, and you can take your seats in order of arrival. We advise arriving 10 minutes before the event is scheduled to start.

Apparently this was discussed last week on Slack but not actioned in any meaningful way
https://wellcome.slack.com/archives/C3N7J05TK/p1533646567000072

This is now an active problem and will need to be dealt with.

@wellcometrust/experience-dev @Heesoomoon

**Comment by Heesoomoon** [comment]
One more thing to update. Now that we handle the booking status through the eventbrite widget, we will need to revisit how we message the fully booked status and waitlist info. 
![fullybooked](https://user-images.githubusercontent.com/29206031/44150910-e3c9b56a-a098-11e8-945e-37e5f03c5752.png)

**Comment by pollecuttn** [comment]
For https://wellcomecollection.org/events/W2RQnyYAACYAR93g it’s possible to guarantee seats for everyone who books a ticket and Events would be happy with noting this on the website if possible.

**Comment by jamesgorrie** [comment]
See #3180
