### ISSUE TITLE
Migrate opening times to content page

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3062]
## Who's it for?
Us.

## Problem to be solved
Moving from the article template to the base page so it can use all components consistently across the whole site.

## Done when
- Page layout reworked to fit in base page
- Holiday closures follow rules previously set out
- We agree what to do with #2429 

## out of scope
Design enhancements that aren't urgent but 'nice to have'

**Comment by pollecuttn** [comment]
## Components
- [ ] Opening times table: will be covered by exhibition page opening times https://github.com/wellcometrust/wellcomecollection.org/issues/3009
- [x] Body text
- [ ] Dividing line (if kept)

Tick = in design system
