### ISSUE TITLE
Migrate Newsletter sign up page to base page (header and body style)

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3064]
## Who's it for?
Us.

## Problem to be solved
Moving from the article template to the base page so it can use all components consistently across the whole site.

## Done when
- Using consistent header style
- Body text and check boxes present
- Users can submit the form to subscribe to any/all newsletters
- Confirmation pages (ours, not Dotmailers)

## out of scope
Page redesign, ie design enhancements that aren't urgent but 'nice to have'

**Comment by pollecuttn** [comment]
- [ ] Header
- [ ] Body
- [ ] Form

**Comment by jennpb** [comment]
@gestchild @davidpmccormick This has been done, right?

**Comment by davidpmccormick** [comment]
hmmm… don't think so – https://wellcomecollection.org/newsletter doesn't look very Base-/Content-Page-y

**Comment by jennpb** [comment]
https://github.com/wellcometrust/wellcomecollection.org/issues/2703
