### ISSUE TITLE
Redirect /youth to new Young People page

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3065]
## Who it's for
Any site visitors using a root URL

## Problem to be solved
Previously we had a Youth and Schools combined landing page. This is now being split into two separate pages, so we need to put a redirect in place. 

- [x] `https://wellcomecollection.org/youth` now needs to point to `https://wellcomecollection.org/pages/Wuw2MSIAACtd3Ssg` 

- [ ] The former Youth and Schools page has been delisted in Prismic but it should be deprecated

**Comment by davidpmccormick** [comment]
Closed by #3069.
