### ISSUE TITLE
Migrate lists to base page

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#3086]
## Who's it for?
Us.

## Problem to be solved
Moving from the lists to the base page so it can use all components consistently across the whole site.

- What's on
- Stories
- Works
- All exhibitions, All events
- Past exhibitions, Past events, Touring exhibitions (?)

## Done when
- Components available to include in Prismic

## out of scope
Page redesign, ie design enhancements that aren't urgent but 'nice to have'

## Components
- [ ] Header
- [ ] List of promos - will be covered in promos work https://github.com/wellcometrust/wellcomecollection.org/issues/3014
- [ ] Pagination
- [ ] Segmented control's (what's on)
- [x] Contributor

Tick = in design system and available on base page

**Comment by jennpb** [comment]
@wellcometrust/weco-experience-devs @pollecuttn Is this still relevant?

**Comment by gestchild** [comment]
no, think this was done here: https://github.com/wellcometrust/wellcomecollection.org/commit/e5d89acb40b3bf0285dd766008a5337edd93ae89
