### ISSUE TITLE
Migrate works landing page to base page

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#3087]
## Who's it for?
Us.

## Problem to be solved
Migrate the works landing page to the base page so it can use all components consistently across the whole site.

## To do
Information gathering with team.

## Done when
- Components available to include in Prismic

## out of scope
Page redesign, ie design enhancements that aren't urgent but 'nice to have'

## Components
- [ ] Header
- [ ] Search box
- [x] Body text
- [ ] Tags
- [ ] Promos - will be covered in promos work https://github.com/wellcometrust/wellcomecollection.org/issues/3014
- [ ] Captioned image
- [ ] Alert ("improving how search works")

Tick = in design system and available on base page

**Comment by jamesgorrie** [comment]
Closing these as I think these pages are going to have a life of their own.
