### ISSUE TITLE
Migrate works page to base page

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#3088]
## Who's it for?
Us.

## Problem to be solved
Migrate the works page to the base page so it can use all components consistently across the whole site.

## out of scope
Page redesign, ie design enhancements that aren't urgent but 'nice to have'

## Components
- [ ] Image viewer
- [x] Buttons
- [ ] Meta unit(s)
- [ ] Drawer - if needed?
- [x] Download module: done with heading and buttons
- [ ] Share module: button done; text input / text area to be done
- [ ] Licence module
- [ ] Captioned image
- [ ] Alert ("improving how search works")

Tick = in design system and available on base page

**Comment by jamesgorrie** [comment]
Closing these as I think these pages are going to have a life of their own.
