### ISSUE TITLE
QA: Implement new event page design

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3143]
Part of #3022 
**For Dev**
- [x] 'See all dates/times' link seems a bit disorienting. It would be good to add transition to show it's taking user to the bottom of the page. #3158
~~- [ ] Vertical spacing between all sections should be consistent. Review the spacing between 'Where we'll be', 'In partnership with', and 'Dates'. Gareth O will do a visual QA (typography, spacing and CTA size) post on Zeplin and review with the dev next week.
https://wellcomecollection.org/events/W2LlgyYAACUAQah7~~ This is a base page problem and will be dealt with separately.
- [x] Update the contributor image for missing profile photo use case. Check corner and which pattern should be used.
https://wellcomecollection.org/events/W0dp8CYAACUAZ188
- [x] Booking opens CTA and messaging should be updated to a label 'Booking opens [date] [time]'
- [x] Remove empty spacing between the contributor name and description.
https://wellcomecollection.org/events/W1ctwiYAACcArDqD #3159
- [x] Suppress 'Need to know' section for past events
https://wellcomecollection.org/events/WzIRMCoAAEKDJnSm
- [x] ~Remove 'with' label on EB Booking CTA~ https://github.com/wellcometrust/wellcomecollection.org/issues/3143#issuecomment-413267171

**To follow up**
@jennpb 
- Should we update the content for current events (7 events in August and September)? About the host and partnership should be move to 'Contributor' content. The location should be part of 'Need to know' section. 
https://wellcomecollection.org/events/W3E2DSkAACcACdql
Update: Jenn will follow up with the content team.

@GarethOrmerod 
~~- Should we display the interpretation icon after the label? Update: leave it as is~~
~~- Should we keep the wobbly line in the header for events? Update: yes~~
~~- Which background should we use for the contributors with no profile photos? Update: provided the pattern to David.~~
~~- Confirm EB 'Book tickets' CTA treatment Update: remove 'with'~~

**To postpone**
- The date format will be updated with #3008 
- Event booking info will be addressed with #3053 
- Move Fully booked message to 'Need to know' section #3053 
![fullybooked](https://user-images.githubusercontent.com/29206031/44102998-f38f895e-9fe2-11e8-89b4-4fd434209fb7.png)

**To research**
- Does user discover and understand 'See all dates/times' label on promo and events?
- Does user understand if an event requires booking?
- Does user discover booking related info?

**Comment by jennpb** [comment]
> Should we update the content for current events (7 events in August and September)? About the host and partnership should be move to 'Contributor' content. The location should be part of 'Need to know' section. https://whats-on.wellcomecollection.org/events/W3E2DSkAACcACdql

I'm not sure what value it'll add but it might be a good 'training case' for the content team. I'll let them decide what they want to do about it.

> Should we move fully booked message to 'Need to know' section?
https://whats-on.wellcomecollection.org/events/WzIRMCoAAEKDJnSm

Yes!

@Heesoomoon

**Comment by Heesoomoon** [comment]
@pollecuttn @davidpmccormick I've updated the QA list based on Jenn's comments and added one more request (removing 'Need to know' section for past events). Would you also follow up with @GarethOrmerod on visual definition?

**Comment by Heesoomoon** [comment]
@jennpb For CTA, here are some considerations to make 'Book tickets' more generic. Let us know if you have any preference.
'Continue to book'
'Check dates & book'
'Check for availability'

**Comment by jamesgorrie** [comment]
@Heesoomoon @GarethOrmerod 

> Update the contributor image for missing profile photo use case. Check corner and which pattern should be used. 

Could you let us know what we need to use please?

**Comment by davidpmccormick** [comment]
@jamesgorrie same image, but square, not circular:
![contributor_default 1x](https://user-images.githubusercontent.com/1394592/44089527-fdbba56c-9fbe-11e8-95ba-0a15c7028376.png)
![contributor_default 2x](https://user-images.githubusercontent.com/1394592/44089528-fdcf9388-9fbe-11e8-8d14-a1445f206c4c.png)

**Comment by davidpmccormick** [comment]
☝️ I'm on this.

**Comment by Heesoomoon** [comment]
@davidpmccormick @GarethOrmerod One more item to note. Would you follow up on how the header background should render on mobile view? Currently, it's not covering the image depending on the length of event title.
![screencapture-wellcomecollection-org-events-w3e2dskaaccacdql-2018-08-14-13_24_32](https://user-images.githubusercontent.com/29206031/44091800-895dacf8-9fc6-11e8-98d9-5f5156792152.png)

**Comment by jennpb** [comment]
<img width="259" alt="screen shot 2018-08-14 at 15 53 26" src="https://user-images.githubusercontent.com/1446139/44099303-3beac60e-9fda-11e8-8f01-a07e54db9c84.png">

@Heesoomoon @wellcometrust/experience-dev I think 'Check for tickets' is the most accurate, and retains the notion of ticket.

**Comment by jamesgorrie** [comment]
@davidpmccormick That was removed.

**Comment by jamesgorrie** [comment]
>  Remove 'with' label on EB Booking CTA

@Heesoomoon it's then just a floating word "Eventbrite" - should we think of giving context?

**Comment by jennpb** [comment]
Legal would prefer us to be more specific when we link out to 3rd-party services where personal data is collected, e.g.  
`We use Eventbrite to process tickets`
`We use Eventbrite to issue tickets`
`Tickets processed through Eventbrite`
`Tickets issued through Eventbrite`

These options are quite long though!

I suggest we leave as is for now and seek feedback from Legal.

**Comment by Heesoomoon** [comment]
@davidpmccormick Have we released the change for 'Booking opens [date] [time]' messaging? This event is still showing 'Check for tickets' rather than the message. https://wellcomecollection.org/events/W2RQnyYAACYAR93g

**Comment by Heesoomoon** [comment]
@jamesgorrie I was browsing on my phone this evening and kept getting the weird behaviour I mentioned earlier. When I clicked on 'Check for tickets' in two separate events, I couldn't get the EB widget. It seems to happen roughly 1 out of 10 times but can't seem to reproduce regularly. Is there ways to detect if our users are experiencing the same?

![img_4549](https://user-images.githubusercontent.com/29206031/44172037-de204300-a0d3-11e8-92c6-e621fd1616ca.png)

![img_4550](https://user-images.githubusercontent.com/29206031/44172038-de204300-a0d3-11e8-8501-7d22a417ef95.png)

**Comment by jamesgorrie** [comment]
@Heesoomoon moved your comment over to #3184 to try keep clutter down.

**Comment by jamesgorrie** [comment]
@Heesoomoon 

> Have we released the change for 'Booking opens [date] [time]' messaging?

Currently we rely on the EB widget for the following messaging: 
* Not yet on sale
* on sale
* fully booked

We can override the "Sales starts" in Prismic, this is predominantly used for multi-date events where you can't do that in Eventbrite.

If we want to have more conversation around the integrations with EB, let's not in this ticket. My understanding though was that we were setting the limitation to being: Defer ticket sales information to Eventbrite to avoid overly complicated and brittle integrations where the widget does all of it for free.
