### ISSUE TITLE
Twitter embed cards

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#315]
Do something nicer with the twitter embeds.
[See here for an example](https://next.wellcomecollection.org/articles/no-photography).

**Comment by jennpb** [comment]
Linked to #148

**Comment by jamesgorrie** [comment]
[See here for my thoughts](https://github.com/wellcometrust/wellcomecollection.org/issues/316#issuecomment-273165351).
