### ISSUE TITLE
Image gallery scrolling too far

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#3156]
In Firefox (61, Mac and PC), the image gallery can scroll further than the width of the currently selected image.

![overscroll](https://user-images.githubusercontent.com/1394592/44088246-5e85cd50-9fba-11e8-8a8b-1aff7f89ae2e.gif)

Doesn't always happen, and seems to be fixed by resizing browser (which will re-calculate image sizes). Probably due to image sizes being calculated initially before they're fully loaded.

__Steps to reproduce__
1. scroll down to image gallery on [this page](https://wellcomecollection.org/articles/WtR31CUAAEhq9ZHV)
2. reload page
3. click on the right arrow several times

**Comment by jennpb** [comment]
No longer relevant
