### ISSUE TITLE
Instagram embed cards

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#316]
Do something nicer with them.
[See here for an example](https://next.wellcomecollection.org/articles/no-photography).

**Comment by jennpb** [comment]
This also connects with #148

**Comment by jamesgorrie** [comment]
Yip - so we're getting the HTML in from WP. I'd be tempted to close #148 for these two - and leave the right rail as "can embed anything"?

**Comment by jamesgorrie** [comment]
[See here for my thoughts](https://github.com/wellcometrust/wellcomecollection.org/issues/316#issuecomment-273165351)

**Comment by jamesgorrie** [comment]
By more interesting, I think we're agreed on standard Instagram embed.

**Comment by jamesgorrie** [comment]
By more interesting, I think we're agreed on standard Twitter embed.
