### ISSUE TITLE
Convert another service to NextJS

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#3175]
In order to wean ourselves off Nunjucks and onto JSX everywhere, we should convert either the what's on service or editorial content/pages to a NextJS app. 

- [ ] decide which service to convert (preferably something that won't be expected to change much for a couple of weeks)
- [ ] establish how to handle any client-side JavaScript that might still need to exist in both React and non-React land

**Comment by jennpb** [comment]
Can this be closed @wellcometrust/experience-dev ?
