### ISSUE TITLE
Render HTML entities correctly

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/wellcomecollection.org#318]
Spotted while looking at the example for #315:

https://next.wellcomecollection.org/articles/no-photography

There’s an ugly `&#8220;` and `&#8221;` being shown in the title where I assume some nice curly quotes should be displayed.

(The question of “should this be treated as HTML” is a long and thorny one.)

**Comment by jennpb** [comment]
Also `&#8217` here 
https://next.wellcomecollection.org/articles/strike-a-pose-vogues-emergence

**Comment by alexwlchan** [comment]
I’m not entirely sure, but I reckon you probably need some extra `| safe` in this template:

https://github.com/wellcometrust/wellcomecollection.org/blob/master/server/views/components/page-description/index.njk

**Comment by gestchild** [comment]
[Already fixed here](https://github.com/wellcometrust/wellcomecollection.org/blob/master/server/model/article.js#L55)
