### ISSUE TITLE
Eventbrite widget not loading

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3184]
From @Heesoomoon 

@jamesgorrie I was browsing on my phone this evening and kept getting the weird behaviour I mentioned earlier. When I clicked on 'Check for tickets' in two separate events, I couldn't get the EB widget. It seems to happen roughly 1 out of 10 times but can't seem to reproduce regularly. Is there ways to detect if our users are experiencing the same?

![img_4549](https://user-images.githubusercontent.com/29206031/44172037-de204300-a0d3-11e8-92c6-e621fd1616ca.png)

![img_4550](https://user-images.githubusercontent.com/29206031/44172038-de204300-a0d3-11e8-8501-7d22a417ef95.png)

**Comment by pollecuttn** [comment]
@jamesgorrie Sorry but this is still having problems on Edge. It was reported to me by staff and I've seen it to when I've used Edge on Windows with https://wellcomecollection.org/events/W2QmBCYAACQARyhr 

Even waiting for 'Check for tickets' after 'Loading' I still just get the 'with Eventbrite' message but nowhere to book tickets.

Me: 
Edge Microsoft Edge 40.15063.674.0
Win 10 (I think)

**Comment by pollecuttn** [comment]
Closed by https://github.com/wellcometrust/wellcomecollection.org/pull/3203
