### ISSUE TITLE
Event ticketing workflow documentation

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3186]
## Problem to solve
In our event redesign we've used the Eventbrite widget to handle the complexity of single and multi date ticket booking.

With it comes compromises - there are things that we can handle through the site and other parts that need to be carried by EB (with its limitations).

This task is to draw out the ticketing workflow so content editors, events teams and the Product Manager can understand how it all fits together.

**Comment by Heesoomoon** [comment]
@jennpb Here's the Eventbrite workflow. I'll create one for 'Email to book' workflow and post here.
[EventsLifecycle_Eventbrite.pdf](https://github.com/wellcometrust/wellcomecollection.org/files/2311940/EventsLifecycle_Eventbrite.pdf)

**Comment by jennpb** [comment]
@Heesoomoon I would suggest we keep this pdf and the email to book workflow in Notion. Please can you provide all relevant ticketing workflow docs and then close this issue?

**Comment by Heesoomoon** [comment]
It's posted in Notion. 
https://www.notion.so/wellcometrust/Event-Workflow-8c565b8ac18d429eac1b2fdb85e4a54d
