### ISSUE TITLE
Add correct footer links 

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#320]
The footer links need to go to the right place: 

Privacy https://wellcome.ac.uk/about-us/terms-use
Cookies https://wellcome.ac.uk/about-us/terms-use
Press https://wellcomecollection.org/press/press-releases

**Comment by davidpmccormick** [comment]
The TripAdvisor logo doesn't lend itself to being scaled down very well. Does it count as 'social'?

**Comment by jennpb** [comment]
@davidpmccormick Yeah, I see your point. I think we would still want to include it in the social bit of the footer, but it also inconveniently present us with the odd 7 accounts.

We'll keep it closed for now and leave as is until I have more info from the social media folks about which accounts they're intending to maintain.
