### ISSUE TITLE
Packed Lunch header not right

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#3225]
## Problem to be solved
The header for the Packed Lunch page is funny - the beige part is missing/tiny bits can occasionally be seen.

https://wellcomecollection.org/event-series/WifrbikAAGSyDtHk

## Acceptance Criteria

- [ ] Header looks correct

**Comment by jamesgorrie** [comment]
@pollecuttn as far as I know, resource pages (`events`, `events-series`, `exhibitions` etc) need a promo image - could we make this issue a content question?

**Comment by pollecuttn** [comment]
@jamesgorrie I asked Alice to help - and turns out Jenn's already asked Ben to supply an image.
