### ISSUE TITLE
Installing SurveyMonkey popup to collect data for top tasks research (date TBC)

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3248]
## Who it's for
User researchers

## Problem to solve

We're using SurveyMonkey to collect data for the top tasks research. We're looking for 400-500 responses total, and this survey will also be put on the library site, sent to the user panel, and shared on social media.

The easiest way to get this in front of the most people on the wellcomecollection site will be to use the SM script https://help.surveymonkey.com/articles/en_US/kb/Website-Collector?uid=fC2ODtHrLNR5Zu85k6dkfPbPSZIjTv7CfHnPfAiRrRtJ8CV0ZjRlBL6Kz2pp0RX40ZpnJIhItxx_2F_2F_2BfCDderXg_3D_3D

This installs a modal popup that links directly to the survey - we wouldn't be able to do this by using the existing Hotjar functionality.

However, I'd want to test this first to see how minimally-invasive we can make it, so as not to totally annoy everyone. 

Please try this out on any less-used pages on the site first to see whether it's going to be suitable.

The script can be grabbed from SurveyMonkey - in Jenn's absence, Lyndsay can point you in the right direction.

**Comment by Heesoomoon** [comment]
**Update**: The team decided to go ahead with the global banner on WC.org first then turn on the SurveyMonkey popup if we don't get enough responses. The global banner can be activated by the content team. And the dev will get things ready to be activated when the decision to have the popup displayed on the site.

Here's sample message and CTA which needs to be reviewed by the content team.
Help us to improve our website experience.
[Take our survey](https://www.surveymonkey.co.uk/r/5DG983J)
link: https://www.surveymonkey.co.uk/r/5DG983J

@pollecuttn Would you follow up with the content team to coordinate the effort?

**Comment by pollecuttn** [comment]
@Heesoomoon Content team say the wording you have is fine.

I'll bring this up again when Jenn and Hayley have returned.

**Comment by davidpmccormick** [comment]
Work to implement the pop-up is small. I set up a test account to add the script. By default it will show immediately, and will only show once per session. We can wrap it in a timeout if e.g. we only want to display it after someone’s been on the page for e.g. 20 seconds – not sure if that is more or less offensive?

<img width="782" alt="screen shot 2018-09-11 at 12 16 15" src="https://user-images.githubusercontent.com/1394592/45362116-d7e68f00-b5cb-11e8-98c7-bde97a7b02c5.png">

Or we _could_ add our own fixed position link to the page á la hotjar, that links off to the survey on a separate page.

<img width="81" alt="screen shot 2018-09-11 at 12 26 27" src="https://user-images.githubusercontent.com/1394592/45362119-d917bc00-b5cb-11e8-8148-fc310aae37ab.png">

…although I don’t think that gives us a way to handle the return URL (i.e. where to send the user once they’ve completed the survey).

Final option is to embed the survey within the page (but styling is a challenge).

**Comment by jennpb** [comment]
@Heesoomoon @davidpmccormick @pollecuttn So are we going with the banner or the popup?

**Comment by Heesoomoon** [comment]
@jennpb See my update above from 4 days ago.
