### ISSUE TITLE
Works: next.js Error on IE 10

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3256]
`TypeError: Unable to get property 'groupedVenues' of undefined or null reference `

~Looks like next.js will serve JS to IE10, whereas on the old app we don't.~ - we do serve JS to IE10 on the old app

Not sure if that's _why_ this error occurs, but it''s flagged it, and we'll need to fix it before swapping over.

**Comment by gestchild** [comment]
- [ ] TypeError: Unable to get property 'groupedVenues' of undefined or null reference

This seems to be something to do with babel-plugin-transform-class-properties, which doesn't seem to work properly for the OpeningHours.js - at least writing it out longhand with constructor removes the error. Still looking at how to get the plugin working.

There are also other errors in IE10:
- [ ] Page not displaying correctly (poss. CSS loading issue)
- [ ] Prop did not match server errors - related to svg
- [ ] Uncaught (in promise)TypeError: Invalid calling object
   at g (https://cdn.polyfill.io/v2/polyfill.js?features=default,Array.prototype.find,Array.prototype.includes,WeakMap:2995:1815)
