### ISSUE TITLE
Relaxed performances

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3290]
Our programming has evolved, and we will start creating [relaxed performances](http://www.roundhouse.org.uk/blog/2015/03/what-is-a-relaxed-performance/). 

We should definitely start labelling content as such, allowing people to quickly know about it on the site, and potentially, similar to interpretations, list them out later on.

It might be a good exercise to think of what might be another example before we turn it into a list, or we could just boolean flag it up as a relaxed performance.

__thoughts__
* Could just be a boolean on the event `isRelaxedPerformance`
* Could be part of the audiences, but we have said before this is an exclusive field eg. schools. (but we could bend this, but feels wrong).

**Comment by jamesgorrie** [comment]
Looking at the roundhouse, they have this information:

> A Visual Story will be available to download one week before the performance

> A chill-out space will be provided with a relay of the performance if any audience member(s) feel they need to leave the space.

Which in essence you could infer that's it is then a relaxed performance.

**Comment by jennpb** [comment]
Is this currently needed? I'm not aware of any Relaxed programming in the schedule. It's a good idea - I'm just not sure it's timely. @jamesgorrie

**Comment by jamesgorrie** [comment]
@jennpb we are programming them with Heart N Soul, and it looks like they're going to do some really cool things with our programming. We also already have a few in the pipeline.

This was a note, as it would be nice to label events up and have them filterable - but having it in the content would be a first step.

**Comment by jennpb** [comment]
Ah, ok. I was unaware.

**Comment by silveroliver** [comment]
@jamesgorrie might this fall under event format? Agree audience feels wrong for this.

Current definition of event format: What an attendee might expect from the structure of an event and the level of participation. For example tour, discussion, workshop or study day.

Maybe we can tighten up our definition of format if not?

**Comment by jamesgorrie** [comment]
@silveroliver my concern then is how would we label it as a `screening` that has relaxed performace? Unless we alliw for multiple formats?

**Comment by silveroliver** [comment]
Yes good point. Do we have a list of event formats currently?

**Comment by jamesgorrie** [comment]
[A note is that we are also developing events for kids with SEND](https://wellcomecollection.org/event-series/W5ZFlSYAACUALCfw).

If these are exclusive, which I think they might be, I am assuming they should probably be an audience.

**Comment by jamesgorrie** [comment]
The discussion is still good, but it is just a flag on the event now.
