### ISSUE TITLE
Base Page: Issue with body column width

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3309]
The layout for the base page looks a bit odd. Was there a layout change?

**Desktop**
The body content is stretched out of the grid.
![screenshot-wellcomecollection org-2018 09 12-08-53-33](https://user-images.githubusercontent.com/29206031/45410374-6ceb9580-b669-11e8-8c2e-ea775bb641c1.png)

**Mobile**
The padding on the body content is missing.
![img_4675](https://user-images.githubusercontent.com/29206031/45410264-30b83500-b669-11e8-93e5-94ff21aeea74.png)

**Comment by davidpmccormick** [comment]
Fixed by #3313.
