### ISSUE TITLE
Event Card: missing 'audience' label

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3331]
The audience types (Schools or 14-19 years old) are displayed in the event page but missing in the event cards.

Event card
![screenshot-wellcomecollection org-2018 09 17-14-50-25](https://user-images.githubusercontent.com/29206031/45627728-7a01ed80-ba8a-11e8-97d0-8a69b443d665.png)

Event page
![screenshot-wellcomecollection org-2018 09 17-14-53-59](https://user-images.githubusercontent.com/29206031/45627729-7a01ed80-ba8a-11e8-94cb-2b4e7c756e16.png)

**Comment by jamesgorrie** [comment]
Note this is only on `/events` not what's on.
