### ISSUE TITLE
Image list: Improve ability to navigate to subsequent images on all devices

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3333]
As agreed in planning today, we're going to move the existing inline gallery into a React component, making minimal changes to enhance usability (as suggested by @heesoomoon)

this is the first step in getting our image list component into the base page

**Comment by jamesgorrie** [comment]
See here for prototype #3323

**Comment by Heesoomoon** [comment]
Here are the recommendations.
**Large_Landscape**
![d_landscape](https://user-images.githubusercontent.com/29206031/45802322-6afb8500-bcae-11e8-9830-4d7359e23848.png)

**Large Portrait**
![d_portrait](https://user-images.githubusercontent.com/29206031/45802323-6afb8500-bcae-11e8-89a9-ef69c7a2cabf.png)

**Small Landscape**
![m_landscape](https://user-images.githubusercontent.com/29206031/45802324-6afb8500-bcae-11e8-9c98-47b578e75440.png)

**Small Portrait**
![m_portrait](https://user-images.githubusercontent.com/29206031/45802325-6afb8500-bcae-11e8-84ff-c93cc06b384d.png)

Updates
- [ ] Move the previous and next button to the right of the title on L breakpoint and below the title on M and S breakpoints
- [ ] Darken the non-selected images

For considerations
- [ ] Try to reveal part of the next image on Landscape images
- [ ] Try to reveal part of the caption text in the viewport
- [ ] Remove image icon to optimise the layout
- [ ] Apply same display logic for the the previous and next buttons on Digital Story transporter used in What's on and bottom of the Digital Story pages

**Comment by jamesgorrie** [comment]
@Heesoomoon Why move the buttons on different breakpoints. It's not great inclusive design thinking, but buttons are after on the right on mobile as the majority of people use their right hand on their phone (there are some hacks as a left hand user of swapping to LtR).

**Comment by jennpb** [comment]
Won't fix this. We'll roll forward with the new Image Lists.
