### ISSUE TITLE
Header: Breadcrumbs

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3348]
## Background
We implemented the breadcrumb on the site to provide a hint of what the content is about and allow users to browse back to the category the content belongs. We need to review the purpose and display logic for some key use cases.

## Examples 
**Installations**
Installations will be grouped with Exhibitions under 'Exhibitions' category. We should update the Installation header to align with rest of the header work by updating the category link and adding 'part of' link if the relationship exists. 

For example, Global Clinic should display the following links.
https://wellcomecollection.org/installations/W3LDcCkAACcAEKqy
[Exhibitions](https://wellcomecollection.org/exhibitions)  |  [Part of **Living with Buildings**](https://wellcomecollection.org/exhibitions/Wk4sPSQAACcANwrX)

**Event Series**
Event series belongs to Events. We should make 'Events' as a category link and 'Event series' as a format.
https://wellcomecollection.org/event-series/WlYT_SQAACcAWccj
Link: [Events](https://wellcomecollection.org/events)
Format: Event series

**Landing**
The breadcrumb on the landing pages, Visit us or What we do, isn't useful. 
https://wellcomecollection.org/what-we-do
https://wellcomecollection.org/visit-us
Do we have the ability to suppress the display?

**Events**
This SEND event has too many references to what it belongs to.
Part of Send Schools Workshops, Part of Study Days, Send Workshop, Schools
https://wellcomecollection.org/events/W40RtB4AACEAm3-8

## Next steps
- [x] Heesoo to audit and list the display logic
- [ ] Review with the team

**Comment by Heesoomoon** [comment]
@jamesgorrie Let's chat about this later this week. It will be good to get on same page and flesh out additional use cases. 
![img_4677](https://user-images.githubusercontent.com/29206031/45761751-c1bc7c80-bc24-11e8-95a7-8d7d76371201.jpeg)

**Comment by jamesgorrie** [comment]
@Heesoomoon There is also some thinking we need to have around the `part of`.
![screen shot 2018-09-19 at 16 46 48](https://user-images.githubusercontent.com/31692/45764920-b28cfd00-bc2b-11e8-8486-645c51f8d3b8.png)

There is also the case where something is part of more than 1 series of thing where this is causing problems. https://wellcomecollection.org/events/W40RtB4AACEAm3-8
![screen shot 2018-09-19 at 16 52 35](https://user-images.githubusercontent.com/31692/45765262-88880a80-bc2c-11e8-83a7-62c588e6aa67.png)

Maybe having those as labels did make more sense, but let's buckle down on the definitions of these areas before we start shifting things around

[See the purpose of the breadcrumb](https://cardigan.wellcomecollection.org/?selectedKind=Components&selectedStory=Breadcrumb&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs)

https://github.com/wellcometrust/wellcomecollection.org/blob/master/common/views/components/Breadcrumb/README.md

**Comment by jennpb** [comment]
It feels to me that these are two separate use cases:
- Part of: FORMAT
- Part of: NAMED SERIES/EVENT

Format usually gets a yellow format label, whereas unique, titled things like Body Squabbles, Living with Buildings, Daylighting, are more editorial/curatorial/marketing in nature, and could contain lots of different formats. For this reason, I don't think @jamesgorrie's example above is something we'd want to do (though I see there are inconvenient text wrapping issues on mobile)

**Comment by jamesgorrie** [comment]
Yea, there seems to be two examples of where we use a labels and event series.
It this ☝️ and study days.

The above I assume has been done to create a link to let people see a list of our send events. This 100% can be a filter, and then the series can disappear.

The study days is odd, as I thought the agreement was to use an event series, and then have the format as something like `workshop`... worth checking in the content team.

Feels like a face to face conversation might help with this.

**Comment by Heesoomoon** [comment]
@jennpb I had a chat with @jamesgorrie about this. We support 'Visit us' and 'What we do' for the breadcrumb at the moment. Therefore, I would recommend the following updates by the content team to make things a bit more coherent.
- [ ] What we do https://wellcomecollection.org/what-we-do
Remove tag > 'What we do'
- [ ] Families https://wellcomecollection.org/pages/W1CenyYAACUAj4Oy
Add tag > 'What we do' (Should we also include this in 'Visit us'?)
- [ ] Wellcome Shop https://wellcomecollection.org/pages/WwgaIh8AAB8AGhC_
Add tag > 'Visit us'
- [ ] Press Release
Currently, it's displaying 'Home'. Should we tag this to 'What we do'?

And then we update the breadcrumb logic with the following rules.
- Suppress the breadcrumb display on the main landing pages e.g. Visit us, What we do, etc.
https://wellcomecollection.org/visit-us
- Allow the content team to tag the category the content is belongs to. For example, 'RawMinds' should display 'Young People'
https://wellcomecollection.org/pages/Wuw2MSIAACtd3Sts
- Event series should display 'Events' similar to Article series which display 'Stories'.
https://wellcomecollection.org/event-series/W5Zj_CYAACQALK5B
- Add standalone Installations to 'Exhibitions' #3425
https://wellcomecollection.org/installations/W5Y-NyYAACMALAdp

**Comment by jennpb** [comment]
I've gone ahead to do the actions above. The bulleted list all seem like different, separately actionable tasks, so I'd suggest pulling those out into separate issues.  @pollecuttn can you help?
