### ISSUE TITLE
Messaging: visual design update

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3354]
We currently use Yellow box for formats, info box and messaging. Looking at how it's currently displaying information on Event Schedule, it feels necessary to treat the messaging differently from labels or CTAs. 

**Current Messaging**
Event Schedule
![messaging_schedule](https://user-images.githubusercontent.com/29206031/45756593-2671da00-bc19-11e8-9178-479b028f1d5b.png)

Events
![messaging_event](https://user-images.githubusercontent.com/29206031/45756599-28d43400-bc19-11e8-96fb-f3edf942b4b9.png)

**Recommendations from @GarethOrmerod** 
New design
![message](https://user-images.githubusercontent.com/29206031/45759417-c9c5ed80-bc1f-11e8-9e76-dee95c5ce468.png)

Events  with schedule
![02](https://user-images.githubusercontent.com/29206031/45759274-781d6300-bc1f-11e8-9c7b-2505dae49299.png)

Events
![01](https://user-images.githubusercontent.com/29206031/45759280-7a7fbd00-bc1f-11e8-9ed6-9b8a8e81d60b.png)

**Comment by Heesoomoon** [comment]
#3341

**Comment by jennpb** [comment]
I like this 👍

**Comment by Heesoomoon** [comment]
@jamesgorrie Is this good enough for now? I have a feeling this yellow line could scale to other usage but for now, let's keep it simple.

Label_Message
Used to highlight key message within a component 
- display yellow vertical line to separate from other contents and draw attention
- accompany short message or description
Example
Booking info: Just turn up, Booking opens [date, time], Fully booked
