### ISSUE TITLE
Article: Serial story navigation

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3360]
How we move people to and from other parts of the serial

**Comment by Heesoomoon** [comment]
@jamesgorrie Can you review the display rule?

Display most relevant article with an option to 'View all' which links to Serial list.
- If next article is published, display normal serial card with 'View all stories'
- If next article isn't published, display 'Coming soon' serial card with 'View all stories'
- If last article, display first chapter in the serial with 'View all stories'

**Comment by jamesgorrie** [comment]
@Heesoomoon a few questions on the PR for this #3389 

* We don't have images for the `coming soon` version - what shall we do?
* Should we be maintaining colour differences selected in the CMS, or do we use purple ubiquitously, or do we find a way to generate the colour from some meta information e.g. title?

**Comment by GarethOrmerod** [comment]
SVG and PNG zipped up:
[pattern.zip](https://github.com/wellcometrust/wellcomecollection.org/files/2425044/pattern.zip)

**Comment by jamesgorrie** [comment]
Implemented and released
