### ISSUE TITLE
Some past exhibitions missing

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#3397]
https://wellcomecollection.org/exhibitions/past

When past exhibitions were published on 25 September they all showed up back to 2007. Today (26 September) the oldest is 'Death: a self-portrait' 15 November 2012-24 February 2013.

An example of a missing exhibition is 'The Heart
21 June 2007–17 September 2007' https://wellcomecollection.org/exhibitions/W30t8ykAACcAPoc1 

They were all on a single page on 25 September, not divided over multiple pages.

Can we get all the past exhibitions back as far as 2007.

**Comment by jamesgorrie** [comment]
Pagination was broken, fixed now #3433
