### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#340]
Based on discussion with 8th floor, lets change/retain the favicon to the icon that WC currently use

**Comment by jamesgorrie** [comment]
I'd prefer not to for now as it's really useful to differentiate. 

Could we add a subtle change? Either colour of a dot or something?

What is the logic of having the stripes? It isn't very clear on tabs nor home screens as to what it is.

**Comment by Norvard** [comment]
The rationale was that its what users of WC recognise today and its the most neutral mark (2 l shapes from WC logo) in terms of full brand architecture.

We can change the colour (yellow and teal?) but we should test keeping the 2 stripes

**Comment by jamesgorrie** [comment]
Could we have something different? At least for now, we can change it back when we usurp `wc.org` (not serving from `next.`). @jennpb Are you happy with this? I personally think sign posting that we're on a separate platform.

**Comment by derivadow** [comment]
For home screens we can/should have an apple-touch-icon i.e. a big one and that could be the Wellcome Collection logo (e.g. https://trustnet.wellcome.ac.uk/sites/all/themes/int_base/touch-icon-192x192.png)

**Comment by Norvard** [comment]
Yep agree. There we have an opportunity to use full WC logo since the space is bigger

**Comment by Norvard** [comment]
Could be nice to use a WC monogram as the favicon, but this feels like a bathroom sign too much...

The 'W' itself is a no-go from brand team

**Comment by jamesgorrie** [comment]
@derivadow Yes, there's a few we need to take into account (we're going to be moving dow the PWA route, so need it for android etc too).

**Comment by jamesgorrie** [comment]
@Norvard If we get an SVG - we can run a task to create these for us.

**Comment by jennpb** [comment]
@jamesgorrie @derivadow If we want a new favicon, we need to engage with the Brand & Comms team, and the head of marketing for WC. I don't think that's a good use of @Norvard's time right now. 

The idea behind the two-colour block is that it represents the two ll in Wellcome; this pattern gets used on WC print marketing assets as well. That's why I felt that retaining the existing WC favicon is good enough for now.
