### ISSUE TITLE
Events: missing 'Fully booked' status indicator

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3400]
When an event with 'Email to book' goes fully booked, we decided to display the 'Fully booked' status to inform users upfront (similar to 'Past event' status). However, it's currently missing in the event card, header and date listing.

**Example**
https://wellcomecollection.org/events/W40IWR4AACEAm1YS

**Event cards**
![screenshot-wellcomecollection org-2018 09 26-17-04-08](https://user-images.githubusercontent.com/29206031/46093045-3c9a1000-c1ae-11e8-9410-93d0ee91e83e.png)

**Event header**
![screen shot 2018-09-27 at 13 39 20](https://user-images.githubusercontent.com/29206031/46146481-d1f2de00-c25a-11e8-89d5-5bdcaa495ef3.png)

**Event dates**
![screen shot 2018-09-25 at 17 19 57](https://user-images.githubusercontent.com/29206031/46093038-399f1f80-c1ae-11e8-8769-594e8ae2d42a.png)

**Comment by Heesoomoon** [comment]
Here's another use case to investigate.
When an event with Eventbrite booking goes fully booked, it's showing the fully booked status in the event card. However, when you land on the event page, you don't see it listed in the header nor the date list. You only find out when you land on Eventbrite after selecting 'check for dates' then 'register'.

**Event Card**
![screenshot-wellcomecollection org-2018 09 28-16-33-52 3](https://user-images.githubusercontent.com/29206031/46337684-08977280-c626-11e8-8057-e7a7fedf44b9.png)

**Event Header**
![screenshot-wellcomecollection org-2018 09 28-16-33-52 4](https://user-images.githubusercontent.com/29206031/46337685-08977280-c626-11e8-96f4-1b874efe05fe.png)

**Event Dates**
![screenshot-wellcomecollection org-2018 09 28-16-33-52 5](https://user-images.githubusercontent.com/29206031/46337686-09300900-c626-11e8-9e0e-2a701d588094.png)

**Comment by Heesoomoon** [comment]
@pollecuttn This means the content team is responsible to update Prismic when an event date goes fully booked for both Eventbrite and Email to book events. I will update the event workflow document accordingly. Would you inform the content team about this change?

**Comment by jamesgorrie** [comment]
@Heesoomoon I'll chat to them in the morning as we're chatting anyway, thanks for updating the doc...

**Comment by Heesoomoon** [comment]
@jennpb @jamesgorrie I had a chat with Jen S. about this. She doesn't think managing the status should be done by her team. Currently, they don't have access to Eventbrite and even if so, they can't react right away when an event becomes fully booked. She asked if we can look into a different solution. Let's chat during the planning meeting.

**Comment by jamesgorrie** [comment]
Note to self for chat on Monday - how are they managing the email to book events as is?

**Comment by Heesoomoon** [comment]
Per Alice, the event manager follows up with the content team. Then the content editor updates the status to ‘Fully booked’ in Prismic.
https://www.notion.so/wellcometrust/Event-Workflow-8c565b8ac18d429eac1b2fdb85e4a54d
