### ISSUE TITLE
Events: schedule missing booking info

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3404]
Booking related info should be displayed in the schedule to inform users whether to book a ticket in advance or not. Currently, it displays the info for events requiring booking but doesn't show the info for 'Just turn up' events. 
https://wellcomecollection.org/events/W5fKOiYAACYAMt8T

Question: Could we confirm if 'Email to book' is supported in the schedule?

**Comment by jamesgorrie** [comment]
This is working: 
https://wellcomecollection.org/events/W5fKOiYAACYAMt8T
