### ISSUE TITLE
Automating dotmailer extract

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#3406]
- Need to automate emailing Linda with the latest address book updates.
- Emails should happen weekly

@davidpmccormick already has a way of extracting and formatting the data, we need to add the email functionality and automate it

**Comment by davidpmccormick** [comment]
This is now running as a lambda in AWS – it should ping me and Linda once a week. Linda is aware (and she received the first email this morning).

**Comment by davidpmccormick** [comment]
https://github.com/wellcometrust/dotmailer-reporter
