### ISSUE TITLE
/exhibitions and /exhibitions/past enhancements

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3416]
## Problems to solve
from Tom:
> The sort order for https://wellcomecollection.org/exhibitions means that the extant and upcoming exhibitions are at the bottom of the list. Obviously we want people to use what’s on but /exhibitions is highlighted as a sub nav on Google’s SERP which means (a) we probably have a lot of inbound links to that page; (b) people will get to that page from Google. Related, I suggest, the past exhibitions probably should also be titled ‘Past Exhibitions’ (rather than Exhibitions) for similar reasons.

## TODO
- [x] Change page title of exhibitions/past to `Past exhibitions`
- [x] Come up with a plan for sort ordering on Exhibitions so that all currently open exhibitions appear at the top, with all past/closed exhibitions at bottom (see previous issue https://github.com/wellcometrust/wellcomecollection.org/issues/2972)

**Comment by pollecuttn** [comment]
### Sorting
**/whats-on**
order by end date
then group:
1. current
2. permanent
3. upcoming

**/exhibitions**
order by end date
then group:
1. current
2. permanent
3. upcoming
4. past

**/exhibitions/past**
order by end date
then group:
1. past

**Comment by Heesoomoon** [comment]
Just noticed the title of exhibitions/past hasn't been updated. It should be updated to 'Past exhibitions'.

**Comment by davidpmccormick** [comment]
Think this has been done?
