### ISSUE TITLE
Design System: Consistent spacing between children component on BasePage

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3419]
Now we know, round about, what children etc we are going to have on the Content / Base pages, we should find a way to consistently space the component on it.

**Comment by Heesoomoon** [comment]
Here are some examples.
**Quotes**
![screen shot 2018-10-03 at 14 25 25](https://user-images.githubusercontent.com/29206031/46413285-7c19ac80-c718-11e8-83f4-e5312a7f8812.png)

**Exhibitions**
![screen shot 2018-10-03 at 14 26 01](https://user-images.githubusercontent.com/29206031/46413286-7cb24300-c718-11e8-9c71-93290f5ea045.png)

**Events**
![screen shot 2018-10-03 at 14 26 18](https://user-images.githubusercontent.com/29206031/46413288-7cb24300-c718-11e8-8705-5c99d50cc597.png)

**Event Schedule**
![screen shot 2018-10-03 at 14 26 44](https://user-images.githubusercontent.com/29206031/46413289-7cb24300-c718-11e8-8e9a-eee6061b4aee.png)
