### ISSUE TITLE
Landing: missing thumbnail images

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3423]
The thumbnail images for some categories are not being displayed in the landing pages as it used to. Visually, it makes it hard to distinguish between a link and group header.
https://wellcomecollection.org/visit-us
https://wellcomecollection.org/what-we-do

![screen shot 2018-10-02 at 12 34 51](https://user-images.githubusercontent.com/29206031/46346434-f3c7d880-c63f-11e8-911d-cc2e983513e1.png)

Note: The content team thinks it's because it's referencing to Drupal.

**Comment by Heesoomoon** [comment]
@jennpb I think this is problematic. Should we have the content team to upload new images from Prismic or have the team investigate why this is occurring? 
Moving forward, we should make sure the compact card #3097 covers use case for missing image to avoid usability issues. e.g. display pattern thumbnail when an image is missing.

**Comment by jennpb** [comment]
@wellcometrust/experience-dev Do you know why this is happening?
