### ISSUE TITLE
Add 'Installations' to Exhibitions 

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3425]
## Problems to solve
There's an upcoming temporary installation called '[Our Voice, Our Way](https://wellcomecollection.org/installations/W5Y-NyYAACMALAdp)' on 24-28 October. However, it's not being promoted on the site because Installations are added to 'Try these too' section manually.

## Previous work
[added by @jennpb] We took a previous decision based on SiB: where installations form part of an exhibition, they don't get promoted as equal weight on the homepage and What's On. Rather, the exhibition is promoted and contains the installations within. This is to reiterate that:
- Some installations are standalone
- Some installations/exhibits/displays are in an exhibition
The model needs to reflect this. We need to make display decisions that treat installations different to or same as depending on whether they're standalone or part of. 

## Decisions
**Standalone installation**
We want to include standalone installations to 'Exhibitions' and have the ability to promote upcoming ones and archive past installations.
- All standalone installations need to be treated the same as Exhibitions, and display according to the same logic (current, permanent, upcoming, past)
- Standalone Installation card will display similar info as Exhibition card (image, format, title, Date range)
- Breadcrumb: links to 'Exhibitions' 
- The content team may decide to create past installations
- Add 'Visit us'

**Children of exhibitions**
- Any installations that are children of exhibitions will need to be delisted by the content team
- Children installation card will continue to display image, format, and description. (TBD)
- Breadcrumb: links to 'Exhibitions' and 'Part of [Exhibition name]'

**Comment by jamesgorrie** [comment]
Thought: Installations could be exhibitions, with `installation` as a format, as they share every other aspect of their model (and most their definition) with exhibitions.

Ping @silveroliver

**Comment by jennpb** [comment]
That makes sense to me. Installations should behave the same as Exhibitions in terms of how it appears in lists because it's on over a date range (or could be a permanent installation).

Other formats could be:
- Performance art
- Exhibit
- Display

**Comment by jennpb** [comment]
Just remembered a previous decision that may impact the solution we come up with. Added to the description at top.

**Comment by jennpb** [comment]
Re: the additional task of creating a new promo style for this, can we wait to specify the details until we've understood the model? I would suggest then making that a separate issue because it's more a VD/UI thing rather than a model thing. @Heesoomoon @jamesgorrie

**Comment by jamesgorrie** [comment]
We have a few technical limitations too on ordering and querying if we have 2 content types - which would be solved by moving to GraphQL (just being released) - which would require time to setup.

**Comment by silveroliver** [comment]
Bit late to this.

So with the model we have at the moment an installation would work like an exhibition and would be considered an exhibition format/type.

I can see exhibition formats could include:
- Installation
- Performance art
- Exhibition

We have a separate thing which is an exhibit. This is contained in an exhibition and represents a work in the context of an exhibition. A bit like an article series relationship.

I would see an exhibit sharing the work types from the works model. It is essentially a work in the wrapper which holds an exhibition specific description (interpretation), a location in the exhibition and an order.

I think that is largely the same as what is being said above!

**Comment by jennpb** [comment]
- All standalone installations need to be treated the same as Exhibitions, and appear according to the same logic (current, permanent, upcoming, past)

- Any installations that are children of exhibitions will need to be delisted by the content team

**Comment by Heesoomoon** [comment]
I've updated the description with the latest decisions.

**Comment by jennpb** [comment]
As this is a much larger discussion about the domain model (.e.g. can of worms), the decision we took today was to:
- manually add Our Voice installation to What's On and Homepage today or tomorrow (within 1 week of opening)
- manually remove Our Voice installation from those views after 28 October
- Revisit this issue in Q2 when we know more about future installations

**Comment by jamesgorrie** [comment]
@jennpb are we happy to close this?

I've added a slack reminder to remove the Our voice installation. I was going to have a time condition in the code, but I'd rather clean the code out and just remove it.

**Comment by Heesoomoon** [comment]
Rather than closing, could we move to Ideas and prioritise in Q2?

**Comment by jennpb** [comment]
I’ll tuck it away for later.
