### ISSUE TITLE
Contributor: profile photo (visual issue)

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3452]
Part of the profile photo is being cropped even though the image added in Prismic is right format. 
Haven't seen it elsewhere. Might be good to monitor. 
https://wellcomecollection.org/books/WwVK3CAAAHm5ExxN
![screen shot 2018-10-04 at 09 37 40](https://user-images.githubusercontent.com/29206031/46462397-4a0c5700-c7b9-11e8-90a8-cec7a1cfe4de.png)

**Comment by gestchild** [comment]
We expect people pictures to be square, this one is landscape, which is why it looks like it's being cropped.
