### ISSUE TITLE
Newsletter signup on Next apps

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#3461]
We need to add the newsletter signup to the default page

**Comment by jamesgorrie** [comment]
Scrap the above, I thought you meant the page.

**Comment by jennpb** [comment]
@GarethOrmerod Did a bit of design exploration for a newsletter signup promo. We'll have to wait to implement it though.

**Comment by Heesoomoon** [comment]
@jamesgorrie I would leave it as is for now till we implement the newsletter signup pomo. Also, it will be good to resolve it once we add 'More from Wellcome Collection' component which will be on white background. https://zpl.io/bznd9L4

**Comment by Heesoomoon** [comment]
Here's the Newsletter Signup promo design. https://zpl.io/V1lrEpX

**Comment by jennpb** [comment]
@Heesoomoon I've moved that to https://github.com/wellcometrust/wellcomecollection.org/issues/2559 so it can be done under a separate ticket.
