### ISSUE TITLE
Books: header missing divider line

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3462]
## Problem to solve
The header in the Books template is missing a line between the top nav and header. It needs to look like other headers. https://wellcomecollection.org/books/W3GgbikAACIAC6nC

![screen shot 2018-10-04 at 12 50 21](https://user-images.githubusercontent.com/29206031/46474452-d5e2ab00-c7da-11e8-990d-cf8db8b3ede1.png)

**Comment by Heesoomoon** [comment]
Let's leave it as is till we can follow up with @GarethOrmerod.

**Comment by jamesgorrie** [comment]
Just to record the conversation, the reason this has become a design issue is because of the removal of the grey line under the nav.

**Comment by jamesgorrie** [comment]
To capture the conversation - why this has become a design issue is because of the removal of the grey line under the nav.

**Comment by Heesoomoon** [comment]
@jamesgorrie I changed this to bug since all it needs is the line between the navigation and the header like it's done in other templates. https://wellcomecollection.org/exhibitions/Wk4sPSQAACcANwrX
I've updated the description above.

**Comment by jamesgorrie** [comment]
As far as I knew, from @davidpmccormick, the conversation with @GarethOrmerod led to them removing it.

Saying this, it seems to be applied inconsistently - so maybe worth bringing up with GO when he's back.

**Comment by Heesoomoon** [comment]
Thanks, it's already in the list of things we plan to review with @GarethOrmerod

**Comment by jennpb** [comment]
This appears to have been resolved
![screenshot 2018-11-29 at 07 40 11](https://user-images.githubusercontent.com/1446139/49206461-0c3b4180-f3aa-11e8-9694-42ebe8b687b3.png)
