### ISSUE TITLE
Cards: add hover states on Compact Cards

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3479]
## Problem to be solved
Current implemnetation for Compact Cards don't support hover states. There aren't enough visual cue to differentiate between a link and list heading. 

**Content cards**
![screenshot-wellcomecollection org-2018 10 08-15-47-21](https://user-images.githubusercontent.com/29206031/46616213-f465e080-cb11-11e8-87a1-6edaf0335f2c.png)

**Event cards**
![screenshot-wellcomecollection org-2018 10 08-15-48-23](https://user-images.githubusercontent.com/29206031/46616215-f465e080-cb11-11e8-84e2-0b39926bca60.png)

## Design
- Change the title colour on hover as implemented in the default cards
- Apply 'dark' overlay on image thumbnails as implmented in the image list https://wellcomecollection.org/exhibitions/Wk4sPSQAACcANwrX

## Next steps
- [ ] Dev to implement

**Comment by jamesgorrie** [comment]
Let's nake sure the active state is part of this for keyboard users and general accessibility

**Comment by jamesgorrie** [comment]
@heesoomoon you say lost, I can't see the designs to them?

**Comment by Heesoomoon** [comment]
@jamesgorrie Good point. I don't think we've documented it anywhere. I think we just assumed it's picking up the logic from the default cards which changes the colour of the title. I've updated the description.

**Comment by Heesoomoon** [comment]
@jennpb I've relabeled this to 'Improvement'. I've reviewed this with @GarethOrmerod and we thought the overlay (darker image on hover) implemented on the Image list would be a potential solution for hover states across the site. 

As a note, the thumbnail images used to have a transition on hover but it's been removed. We can't recollect why this was removed.

**Comment by jennpb** [comment]
It looks like we need to review hover states across the whole site, as the examples given above no longer show a colour change on hover (like the image gallery images do), and we don't change the text colour either.

Going to close this whole issue, but pinging @GarethOrmerod to consider hover states in cards with current work on card scaling.
