### ISSUE TITLE
IE11 rendering of contributors on events

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3480]
IE11 seems to be struggling with contributors. You can see here the image overlays the bio text:
https://wellcomecollection.org/events/W498dB4AACEAph-V

![image](https://user-images.githubusercontent.com/1446139/46619876-24fe4800-cb1b-11e8-887f-742b41ca6dd3.png)

FWIW it doesn't seem to be an issue on new articles or even events with schedules: 
https://wellcomecollection.org/events/W5fKOiYAACYAMt8T

https://content.wellcomecollection.org/articles/W6zJhRAAAB8Ae6NL
![image](https://user-images.githubusercontent.com/1446139/46620010-7d354a00-cb1b-11e8-96e1-da10a0db0219.png)

**Comment by pollecuttn** [comment]
Same problem on IE11 on Windows, but no problem on Edge on Windows.
