### ISSUE TITLE
Wellcome Kitchen page is missing image

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#3483]
## Problem to be solved
https://wellcomecollection.org/pages/Wuw19yIAAK1Z3Snk has a promo image in Prismic but it is not showing on the web page.
https://wellcome.slack.com/archives/C3N7J05TK/p1539003438000100

Related to https://github.com/wellcometrust/wellcomecollection.org/issues/3423?

## Acceptance Criteria

- [ ] Wellcome Kitchen page displays the image

**Comment by jamesgorrie** [comment]
The promo image and featured image were purposefully decoupled on pages so they could create pages without featured images.

I've flagged this on slack.

**Comment by davidpmccormick** [comment]
An editorial image has been added. The issue as described is fixed: https://wellcomecollection.org/visit-us
