### ISSUE TITLE
Allow the content team to tag the category the content is belongs to

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#3488]
## Who it's for
Content team

## Problem to be solved
Allowing tagging the category the content belongs to e.g. 'RawMinds' should display 'Young People'

## Acceptance Criteria

- [ ] Content team can add the appropriate tags

**Comment by jamesgorrie** [comment]
This sounds like a solution to what might be a much larger conversation around sitemaps etc.
Tagging is not something we have, and not something it feels we want.

If we were to start modelling out the site, we would land up with things like site sections etc etc.

@jennpb has a ticket open here #1611 - maybe it's worth closing this, as this ticket feels like a solution to a problem we haven't really explored or researched fully yet?

**Comment by jennpb** [comment]
Yep, will keep #1611 open for now and close this one.
