### ISSUE TITLE
Build themed articles block

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#351]
![image](https://cloud.githubusercontent.com/assets/1446139/22105840/e3b53d84-de3d-11e6-8c82-9a0d710a3392.png)

Contains:
* Title
* Description
* Accommodates between 2-8 articles

**Comment by jamesgorrie** [comment]
Making a note of some rules from the conversation I had with @Norvard before building.
`n` == number of items.

* `n <= 8`
* `row1.length = 1 row2.length = n-1` `row2.modifier = 'scroll' (small screens)
* `if n > 4 rows = 2` (larger screens)
* `row1.length <= row2.length` (larger screens)
