### ISSUE TITLE
Review: Article Implementation

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3511]
It's nice to see all major pages being migrated to the base page format. The site feels consistent and connected.

I came across following issues in Stories. Let's follow up to see if we want to take any actions.
**Functional**
- [x] When you click on a link from an article and tries to return to the article using the browser back button, it leaves you with a blank page. 
https://wellcomecollection.org/articles/W2hqSiYAACcAWdI-
- [x] The upcoming/unpublished article in the 'Read more...' component displays 'Available Invalid date'
https://wellcomecollection.org/articles/W1byZiYAACgAqzV7
- [x] When you reach the last article (part 6) of the serial, we decided to send the user to the beginning of the serial (part 1) as an onward journey. However, the 'Read more' section is missing in the last article. #3512 
https://wellcomecollection.org/articles/WyjfeCYAACYAzWPS
- [x] Missing contributor component in the comic template.
https://wellcomecollection.org/articles/W7ZC9xAAALuY1_Fq #3513 

**Content**
~- [ ] Should the header in the comic template support description to provide richer context?
https://wellcomecollection.org/articles/W7ZC9xAAALuY1_Fq~ 

See https://github.com/wellcometrust/wellcomecollection.org/issues/3544

- [x] Previous Article Series didn't support feature image nor description as in the new template. It's something the content team will have to retroactively add in future. Since they just published an article from Research Notes series, it will be good to add it so it shows up in the article series landing and 'Read more...' section in the article page.
https://wellcomecollection.org/series/WedR3iQAAKu4NMzW
https://wellcomecollection.org/articles/W2hqSiYAACcAWdI-
- [x] @jamesgorrie Have you set up a standalone image gallery we can review? Or is this something we should ask the content team to do?

**Visual**
The comic image looks quite small on the desktop. It's about a half of what it used to be. Could we see what other options we have? https://wellcomecollection.org/articles/W7ZC9xAAALuY1_Fq - to be done under under https://github.com/wellcometrust/wellcomecollection.org/issues/3543

**Comment by jennpb** [comment]
@Heesoomoon I don't believe there are any standalone galleries that have been published as such, so this is a something for the content team. When they're ready to publish a standalone gallery, they're now able to do so. 

The closest things we have to standalone galleries (by intention) are: 
https://wellcomecollection.org/articles/Wpl_iCUAAKUUF0Je
https://wellcomecollection.org/articles/WqLANiUAAM8VP-1D
but they won't render as a standalone gallery because they were built as an old-style inline gallery, and we shouldn't attempt to change it on our side.

**Comment by jamesgorrie** [comment]
> The comic image looks quite small on the desktop. 

Agreed. I was going to sit with @gestchild to see if we could make it fill out more of the real estate.

**Comment by jennpb** [comment]
What would happen if we treated it like a regular article with the comic as featured image?

**Comment by jamesgorrie** [comment]
> What would happen if we treated it like a regular article with the comic as featured image?

It'd be cut into a thin image, and then go to a square at mobile unfortunately.

I think there's something a little screwy with the image gallery logic, as it should be taking up as much width as it can, without going higher that 80% viewport height, which is looks like it's not. So probably worth just peeking into why that is the case.

**Comment by Heesoomoon** [comment]
@jamesgorrie Re: 'Read more...' in the last article of the serial, is there a way to promote the first article from different serial? i.e. last published serial, The history of the NHS 
Maybe we can AB test to measure what works better?

**Comment by jennpb** [comment]
Pick up the comic size issue here: https://github.com/wellcometrust/wellcomecollection.org/issues/3543
