### ISSUE TITLE
Build single digital story block

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#352]
![image](https://cloud.githubusercontent.com/assets/1446139/22105902/365e7384-de3e-11e6-9816-5f1481a2077e.png)

**Comment by jennpb** [comment]
Leave out colour treatment for now until we test series navigation. The hero + title/desc block can be built without for now.

**Comment by davidpmccormick** [comment]
> Leave out colour treatment for now until we test series navigation. The hero + title/desc block can be built without for now.

Totally missed that when I picked this up, so I used the pre-existing colour treatment we have for the article series variant. It can be easily removed if necessary, though.

**Comment by jennpb** [comment]
@davidpmccormick Yeah, let's remove the colour treatment.
