### ISSUE TITLE
Missing images from Somewhere in Between 'about this exhibition'

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#3520]
From Alice W:
the final two pictures for the stories I added to “about this exhibition” for SiB seem to have disappeared for some reason: https://wellcomecollection.org/exhibitions/WhvoAykAACgAlDoo

https://wellcome.slack.com/archives/C294K7D5M/p1539269627000100

**Comment by jamesgorrie** [comment]
This was a content issue where promo text and images hadn't been added.
Fixed.
