### ISSUE TITLE
Consistency of comic vs. article

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3544]
Need a new feature?
https://github.com/wellcometrust/wellcomecollection.org/issues/new?template=feature.md&labels=feature

Should the header in the comic template support description to provide richer context?
https://wellcomecollection.org/articles/W7ZC9xAAALuY1_Fq

Promo text 
Body
Image size
Contributor

**Comment by jamesgorrie** [comment]
They can add it like they do with standard articles, along with any body text they want too (basically it works the same as articles).

![screenshot 2018-11-02 at 13 20 06](https://user-images.githubusercontent.com/31692/47917693-2b75aa80-dea2-11e8-83bd-1591b6928229.png)
