### ISSUE TITLE
Document where and why we have decoupled featured and promo images

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#3559]
Certain types of content share the promo image as the featured image, others don't. The content team would like a list of the instances where they are decoupled.

Possibly revisit whether decoupling everywhere (or nowhere) is an option, for consistency?

<img width="300" alt="screen shot 2018-10-17 at 14 29 16" src="https://user-images.githubusercontent.com/1394592/47089819-8314e480-d219-11e8-83d9-390561750802.png">

**Comment by jennpb** [comment]
Kate says "We've had a chat and come to the conclusion that this isn't a particularly urgent task - not sure how we would use the information. So don't worry!"
