### ISSUE TITLE
Linking to past events from Events

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3572]
## Who it's for
People looking for past events

## Problem to be solved
On /events we show upcoming events only https://wellcomecollection.org/events. 

from @Heesoomoon 
> To follow up on the conversation from #3531 Events ordering with @gestchild, here are the usability reasons for removing Past events in /events
> - Users often miss 'past' status and think all events in the list are available to attend
> - It's likely people will miss the 'Past events' grouping in a long list
> - Past events are only relevant when trying to find about specific event program i.e Packed lunch
> Having said that, it wouldn't hurt to add 'Past events' link at the bottom of /events to allow for people looking for past events they've attended. (note: 265 clicks for Past events from What's on past 3 months.)

## Acceptance Criteria

- [ ] Add `View past exhibitions` link https://wellcomecollection.org/events/past at the bottom of https://wellcomecollection.org/events

**Comment by jamesgorrie** [comment]
@jennpb It might be good to start thinking about a general URL strategy here for lists.

From my understanding and the common way the internet works, `/{content-type}` would give you everything.

[This also follows [the draft URL structure](https://github.com/wellcometrust/platform/blob/master/ontologies/WIP/wellcome urls.csv) from @silveroliver.

We currently support [periods (ranges)](https://github.com/wellcometrust/wellcomecollection.org/blob/master/common/model/periods.js) on the URL, just type `/exhibitions/{period}` and you'll get exactly that.

Saying that then, I wonder if we link from `/whats-on` to `/events/current-and-coming-up`. 

On those list pages, we could have a the above list of the other periods (or a subsection) which people can choose from?

This system can be generalised as:
`/{content_type}` & `/content_type/{saved_filter}`.

Would set us on the way to building a scalable system for filter me thinks.

e.g.
![screen shot 2018-10-19 at 08 28 23](https://user-images.githubusercontent.com/31692/47203658-fa14bf00-d378-11e8-8f42-fcaf4fb90b54.png)

**Comment by jennpb** [comment]
Agreed, but that’s a medium term strategy (like maybe we deal with it next quarter) while this improvement is more of a quick fix that helps us make our site more linky.

**Comment by jamesgorrie** [comment]
A note on this then is to probably get the URLs working in a defined, predictable way (`/events` is all events, `/events/time_period` is that), and then make sure we link through to the right ones.

My concern is that we keep changing what's on `/events` whereas if we just gave ourselves the options, we could just do that.
