### ISSUE TITLE
Wellcome Collection logo SVG image size/colour issues

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#359]
Using the SVG image rather than the inline SVG has created a few issues.

1. Header image is cut off on smaller viewports
![screen shot 2017-01-19 at 16 54 39](https://cloud.githubusercontent.com/assets/1394592/22116479/854ac612-de68-11e6-9e4b-d72f9d0c2f1e.png)

2. Image in the footer is invisible as it isn't targetable by CSS and is black on a black background
![screen shot 2017-01-19 at 16 54 52](https://cloud.githubusercontent.com/assets/1394592/22116525/a2287e46-de68-11e6-95b7-5a399f7d95c8.png)

3. Calling the image in this way means another network request.

**Comment by jennpb** [comment]
@davidpmccormick I also noticed that the bottom of the logo appears to be chopped off at the bottom in IE11

![image](https://cloud.githubusercontent.com/assets/1446139/22118808/0efc5b0c-de71-11e6-90ef-5a8e8ab15153.png)
