### ISSUE TITLE
Dotmailer: move Wellcome Book Prize into Wellcome Collection subaccount

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3596]
## Who it's for
Marketing team 

## What is it?
Marketing and Comms want to have the Wellcome Book Prize newsletter form part of the WC subaccount. As we set up the subaccount as part of the newsletter signup integration, we've been asked to bring in the last of the WC properties.

**Comment by davidpmccormick** [comment]
Will this mean adding it as an option on the `/newsletter` form also, and adding it to the list Linda needs for Care?

**Comment by jennpb** [comment]
No to adding it to /newsletter form (for now)
Yes, I would imagine that Linda will want the data.
