### ISSUE TITLE
Cards: displaying old article format label

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3619]
The article cards in the Stories landing and list are displaying old article format where as the homepage is showing correct format.

**Stories Landing and List**
https://wellcomecollection.org/stories
https://wellcomecollection.org/articles
![screen shot 2018-10-25 at 21 20 36](https://user-images.githubusercontent.com/29206031/47528165-5e191500-d89c-11e8-9b18-998e05693ffd.png)

**Homepage**
https://wellcomecollection.org
![screen shot 2018-10-25 at 21 21 02](https://user-images.githubusercontent.com/29206031/47528152-55284380-d89c-11e8-8b1d-3da4b1fc2f83.png)

**Comment by davidpmccormick** [comment]
Fixed in #3793.
