### ISSUE TITLE
Link styling in Contributor component

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3621]
## Problem to be solved

The embedded links in the Contributor component have missed out the hover state. Is this a new style, or has it been overlooked?

https://wellcomecollection.org/articles/W7TfGRAAAP5F0eKS

![screen shot 2018-10-26 at 07 50 50](https://user-images.githubusercontent.com/1446139/47549501-2ccc3380-d8f4-11e8-85b6-1e043e433e31.png)

## To do
- [ ] Decide on link style to use
- [ ] Add a sample link to contributor component in Cardigan

**Comment by Heesoomoon** [comment]
@jennpb This link style has been defined and is currently used in all components other than body content (e.g. breadcrumb, header in stories landing, info box). The link is displayed in black with underline then changes to teal with no underline on hover.

**Default state**
![screen shot 2018-10-26 at 09 32 06](https://user-images.githubusercontent.com/29206031/47554818-25ac2200-d902-11e8-9267-97502f80800d.png)

**Hover state**
![screen shot 2018-10-26 at 09 32 16](https://user-images.githubusercontent.com/29206031/47554819-25ac2200-d902-11e8-96a0-d02be02dde09.png)

**Comment by jennpb** [comment]
Yes, but the hover state is not working on the contributor component.

**Comment by Heesoomoon** [comment]
The hover state colour is defined through #3634
