### ISSUE TITLE
Design System: Consistent use of spacing within components

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#3627]
## Problem to be solved
#3564 addresses the treatment of space _between_ page sections and the space _between_ components. We need to establish/implement rules for space _within_ components where possible.

## Design guidelines
Initial spacing rules for e.g. compact cards are at https://zpl.io/aBqOM9L

__TODO__
- [ ] establish rules
- [ ] implement: start with updating components on works, exhibitions, stories; then update other components in Cardigan

**Comment by jennpb** [comment]
@GarethOrmerod @davidpmccormick Can this be closed or refined in any way?

**Comment by davidpmccormick** [comment]
I think this should be closed – don't think it needs any further refinement now we're using the spacing component everywhere.
