### ISSUE TITLE
Primary link colour contrast

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#3634]
@Heesoomoon @GarethOrmerod Accessibility issue with the colour contrast of a primary link on the cream background:
![47435631-e44e3200-d79c-11e8-9024-cb3e96e39e9e](https://user-images.githubusercontent.com/6051896/47653414-703ad200-db80-11e8-9b0b-750fa1c7b4c3.png)

This uses green(#088574) on cream(#F0EDE3), which has a contrast ratio of 3.88:1, not the required 4.5:1

**Comment by GarethOrmerod** [comment]
Updated green for links **#007868** which has a contrast ratio 4.62:1
