### ISSUE TITLE
v2 API migration prep: establish v1 baseline

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3639]
# Purpose
Before we migrate over to the v2 API with `digitalImage` filter, we need to establish a search results baseline for the v1 API. This will allow us to check that the move to v2 does not introduce unexpected results.

**_Assuming_** no modifications will be made to the default ElasticSearch configuration
**_and_** that there may be a slight increase in the total number of `digitalImage`s available (due to license changes, inclusion of some archive images and reindexing)
**_We should expect_** to see roughly the same number of search results per query, delivered in roughly the same order.

Once this is verified, we move on to ✨making search better:sparkles: 

# Documents

I ran a GA report of the top 5000 works queries from 1 Jan-29 Oct 2018, then selected 25 queries from amongst the top results (and sprinkled throughout), along these criteria:
- single keyword
- keyword(s) + page
- `creator:` queries
- mixed keyword + date queries

I logged the number of results for each query and took a screenshot of the page (for reference).

[Document can be found on Sharepoint](https://wellcomecloud.sharepoint.com/:x:/s/wcdigitalexperience/EZRQzrnWiaNElQpWMewunrQB63WOA1u8yGXv1b4x_xfBLw?e=GK2yaG). Use the filters to exclude blank fields.

@wellcometrust/experience Please comment with any other thoughts you might have on establishing this baseline. I don't think it needs to be too in-depth at this stage (as we haven't begun thinking about ES and relevance), but should be just enough for us to be confident that nothing is borked.

**Comment by jamesgorrie** [comment]
# List for comparison

https://wellcomecollection.org/worksv2?query=paintings
https://wellcomecollection.org/worksv2?query=health
https://wellcomecollection.org/worksv2?query=science
https://wellcomecollection.org/worksv2?query=botany
https://wellcomecollection.org/worksv2?query=quack+OR+quacks
https://wellcomecollection.org/worksv2?query=optics
https://wellcomecollection.org/worksv2?query=sun
https://wellcomecollection.org/worksv2?query=james+gillray
https://wellcomecollection.org/worksv2?query=creators:"AndrÃ©. Just"
https://wellcomecollection.org/worksv2?query=creators:J. Thomson
https://wellcomecollection.org/worksv2?query=brain
https://wellcomecollection.org/worksv2?query=anatomy
https://wellcomecollection.org/worksv2?query=bills of mortality&page=1
https://wellcomecollection.org/worksv2?query=cholera
https://wellcomecollection.org/worksv2?query=heart
https://wellcomecollection.org/worksv2?query=witch
https://wellcomecollection.org/worksv2?query=plague
https://wellcomecollection.org/worksv2?query=alchemy
https://wellcomecollection.org/worksv2?query=manchu
https://wellcomecollection.org/worksv2?query=skull
https://wellcomecollection.org/worksv2?query=syphilis
https://wellcomecollection.org/worksv2?query=china
https://wellcomecollection.org/worksv2?query=tuberculosis
https://wellcomecollection.org/worksv2?query=eye
https://wellcomecollection.org/worksv2?query=surgery

**Comment by jennpb** [comment]
all looks good to me.
