### ISSUE TITLE
Strategy for monitoring site search in GA

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3646]
## Who it's for
Us.

## Problem to be solved
We currently don't have Site Search set up in Google Analytics. But before we make any rash decisions, we need to map out a longer term strategy that takes into account a single search for the site. This would likely mean we'd need to plan to use GA's category parameters to split catalogue from editorial (for example).

Let's do this as a group alongside any work done on our KR to 'Implement a strategy for measuring use'

https://support.google.com/analytics/answer/1012264?hl=en

**Comment by jamesgorrie** [comment]
A note on something I was thinking about this:

Creating two views (or more) - 1 being overall site, 1 being catalogue, etc... Just a thought maybe worth thinking about.

**Comment by jennpb** [comment]
Subsumed by #3847
