### ISSUE TITLE
Study Days event series: some incorrect links

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#3652]
Study Days: https://wellcomecollection.org/event-series/W1m-yyYAACYAt4Lb

The first four things in "What's next" have incorrect links:

- HIV and AIDS (Thursday 1 November 2018, 10:30—13:00) links to Faster, Smarter, Stronger

- Head Space (Wednesday 7 November 2018, 10:30—12:00) links to HIV and AIDS

- Body Image (Thursday 8 November 2018, 10:30—15:30) links to Head Space

- Faster, Smarter, Stronger (Tuesday 13 November 2018, 10:30—15:30) links to Body Image

The subsequent ones link correctly, from Design for Life onwards.

The "What we've done before" things link correctly to.

### To do 
- [x] Get the links for the first four items corrected

**Comment by jamesgorrie** [comment]
This was fixed in #3647 where the reason it happened is tracked.

**Comment by pollecuttn** [comment]
@jamesgorrie Great! I looked for an issue before I wrote this but didn't check PRs (and probably wouldn't have recognised it as the same issue anyway)

**Comment by jamesgorrie** [comment]
@pollecuttn no problem, good to have it flagged with the user issue rather than the technical problem.
