### ISSUE TITLE
Improve wording on newsletter signup confirmation email

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#3667]
## Who it's for
People who sign up for newsletters

## Problem to be solved
Wording in the newsletter confirmation email and on the button. The email says you've signed up. However, you haven't completed signing up until you've also confirmed by hitting the green button. The button doesn't have 'confirm' on it, but wording about updates instead.

![signup](https://user-images.githubusercontent.com/1446072/47865958-7be2fe80-ddf5-11e8-898f-bea4290c77fc.png)

## Acceptance Criteria

- [ ] Wording in the email and on the button is clearly understood and acted on by people signing up for the newsletter(s)

**Comment by jennpb** [comment]
I believe this is the wording in Dotmailer and not customisable but would need to go back into old notes.
