### ISSUE TITLE
When YouTube embeds bust through the rail

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#368]
![image](https://cloud.githubusercontent.com/assets/1446139/22159339/3f8c552a-df38-11e6-9d2d-335324134733.png)

Might just be a simple fix of changing the dimensions in the original blog post. Not sure how many of these issues we'll come across in legacy content. 
 
https://next.wellcomecollection.org/articles/christmas-part-the-second

**Comment by alexwlchan** [comment]
I don’t think that’s a YouTube embed, it’s a GIF from what looks like a Wordpress site.

The other images on the page have a `width: 100%` attribute; this image doesn't. Adding that fixes the problem, but I’m not going to guess where in the CSS source that should be added to make that work.
