### ISSUE TITLE
Get Sierra data onto v2 /works

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#3705]
- [x]  Render all data using MetaUnit component
-  ~Fix non-showing images~ - captured in #3697
- [x] Download options working
- [x] License info. displaying
- [x] Use this image section on page

## Acceptance Criteria

- [x] Sierra data showing on /works
- [x] Images displaying correctly
- [x] Download link present and working correctly

## Future (ripe for being split into other issues)
Moved to https://github.com/wellcometrust/wellcomecollection.org/issues/3742
~Ordering and grouping of meta data~
~Move/restyle the 'We're improving...' message~
~Group work type with title~
~Positioning of 'Using this image' section - potentially grouping with Download~
~Positioning of Download actions, especially on mobile~
~Test flipping title and image positions~
~Add search field to top of work page (this work will be related to site-wide search)~
~Spacing of image viewer controls~
 
### Questions potential tasks for Platform team / Silver
- Reword 'Physical description' heading?
- Rename work type title?
- Clean up text (semi-colons, case etc.)
- Production - question about how place and date are related?
- Clarification of Type

**Comment by pollecuttn** [comment]
@Heesoomoon What's your question about how Production place and date are related? I might be able to help.

**Comment by pollecuttn** [comment]
@Heesoomoon As I didn't answer before Silver came in did you follow these up with him instead? Do you have your answers yet or are you still waiting?

**Comment by Heesoomoon** [comment]
@pollecuttn @gestchild and I met with @jennpb to review the metadata. We have following requests for the platform team. Do we have a process in terms of making requests/updates for the platform team?
**Updates**
- Display name in order of [first name] [last name] and remove ',' end of [first name]
- Remove '.' used for separating [subject] and [genre]
- Use sentence case for [subject]

**Questions**
- What order is used when there are multiple values in the field?

**Comment by jennpb** [comment]
I am not 100% sure on the `first name, last name` part yet - needs more consideration. The other two bullets apply.

**Comment by jtweed** [comment]
Having spoken to @jennpb, I’ve created wellcometrust/platform#3046 to address this.

**Comment by jamesgorrie** [comment]
Is it this field that being exploded?
https://www.loc.gov/marc/bibliographic/concise/bd100.html

**Comment by jamesgorrie** [comment]
@jennpb @jtweed Where do we want to track the progress for this issue?

I thought the higher level issue is that we take some fields from Sierra, and explode their subfields into new API fields. Another example is:

- [Physical description 300](https://www.loc.gov/marc/bibliographic/bd300.html) split into fields `physicalDescription`, `extent`, `dimensions`.

It feels like we might have a few more examples come up as it's a common pattern with the source data, should we be looking at approaching it from that level i.e. how do we deal with subfielded data types?

**Comment by jennpb** [comment]
@jamesgorrie Yeah, we'll have other issues that come up, but it makes sense to me to raise them at the point when decisions are made, hence wellcometrust/platform#3046 which covers two issues that the Platform team can do now.

**Comment by pollecuttn** [comment]
Deploy: https://github.com/wellcometrust/wellcomecollection.org/issues/3744
