### ISSUE TITLE
Add components to (Storybook) Cardigan

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#3727]
- [ ] ArticleCard
- [x] Author (deprecated?)
- [x] Avatar (just part of Contributor?)
- [ ] BackToTop
- [ ] BookPromo (out of WIP?)
- [ ] Breadcrumb
- [x] Buttons
- [x] Caption (just part of CaptionedImage?)
- [x] Card
- [ ] CardGrid
- [x] ChapterIndicator (delete)
- [x] Contributor (just part of Contributors?)
- [x] CopyUrl
- [ ] DailyTourPromo (?)
- [ ] DateAndStatusIndicator
- [x] Divider
- [ ] ErrorPage
- [ ] EventBookingButton
- [ ] EventbriteButton
- [ ] EventCard (add to Cards?)
- [ ] EventPromo (is this the same as EventCard?)
- [ ] EventsByMonth (proobably not - logic only?)
- [ ] EventSchedule
- [ ] EventScheduleItem
- [ ] ExceptionalOpeningHoursTable
- [ ] Excerpt (delete? Not being used anywhere as far as I can see)
- [x] ExhibitionPromo
- [ ] FacilityPromo
- [ ] FeaturedText
- [ ] FindUs
- [x] Footer
- [x] FooterNav
- [x] FooterSocial
- [x] FooterWellcomeLogo
- [ ] FreeSticker
- [ ] GifVideo
- [x] Header
- [ ] HeaderBackground (not sure how this will work without context)
- [ ] HeaderText (delete?)
- [ ] HighlightedHeading
- [ ] HTMLDate
- [ ] HTMLInput
- [ ] Iframe (maybe not?)
- [ ] ImageGalleryV2 (get rid of ImageGallery or still needed for WP?)
- [ ] ImagePlaceholder
- [ ] Image
- [ ] UiImage (check difference from Image)
- [x] CaptionedImage
- [x] ImageViewer2 (kill v1)
- [x] InfoBanner
- [ ] InstallationPromo (Promos: Installation)
- [x] Label
- [x] LabelList
- [x] License
- [x] LinkLabels (used in contributors)
- [ ] MainMedia (delete)
- [ ] Map
- [x] MetaUnit
- [x] NewsletterPromo
- [ ] NewsletterSignup
- [ ] OpeningHours
- [ ] OpeningHoursTable
- [x] ~PageDescription (maybe kill? only used on works landing page)~ killed it in #3766
- [ ] PageHeader
- [ ] PageHeaders (delete - not being used)
- [ ] PageHeaderStandfirst
- [x] Pagination
- [ ] PartNumberIndicator
- [x] Promo this is only on the `/stories` page now – let's kill it instead of moving it into Cardigan?
- [x] Quote
- [x] SearchBox
- [ ] SearchResults
- [ ] SegmentedControl
- [ ] SeriesNavigation
- [x] Standfirst (delete)
- [ ] StaticWorksContent (the stuff on the works landing page)
- [ ] StatusIndicator
- [ ] StoryPromo
- [ ] Tags
- [ ] Tasl
- [ ] Templates (delete)
- [ ] VideoEmbed (can we/do we suport this )
- [ ] WobblyEdge
- [ ] WorkCredit ? not in prod?
- [ ] WorkDrawer (delete?)
- [ ] WorkEmbed ? not in prod?
- [x] WorkImage
- [x] WorkMedia (delete v2?)
- [ ] Layout8
- [ ] Layout10
- [ ] Layout12

**Comment by jamesgorrie** [comment]
Not to sound like a broken record, but if we can not see this as a task list, but a chance to question and audit what we have (and potentially improve on them) - let's.

Things are becoming nice and neat, so let's refactor as we go.

**Comment by jennpb** [comment]
Yo @davidpmccormick - Is this still a WIP?

**Comment by davidpmccormick** [comment]
It wasn't a list I was working to for the latest updates. There are a few things that I haven't put in Cardigan, like layouts (wasn't quite sure how they would look/if they would be useful), but in the main everything that has UI is now in, so I think this ticket can be closed and new Cardy stuff should get a new issue.

**Comment by jamesgorrie** [comment]
@davidpmccormick worth writing up a doc about the process we were talking about on slack?

If we start by adding a component to Cardigan it will probably start making us question more about adding new things, but also allow us to see if there is anything we already have?

It will also stop the process of having to have someone (nearly always you) go through this every 3 months.
