### ISSUE TITLE
Strategy for measuring library collections usage

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3737]
- [x] Define goals and what we need to know (collaborate with Collections and Platform team)
- [x] Work out how we can analyse multiple data sources 
- [x] Get baseline conversion and search log data for Platform and Collections teams (number of searches that result in a CT/request) - data needed to support Archives Accreditation (see #3845)
- [x] Audit current setup of GA  - any views, goals, events that are no longer used?

**Comment by jennpb** [comment]
Collections Information needs: https://wellcomecloud.sharepoint.com/:x:/s/wcdigitalexperience/Ed0gZzJlgWhBkeaxhNBYxLsBLN9XXdcDCoZHn9cA8bQT4Q?e=39hVUx

**Comment by jennpb** [comment]
> Audit current setup of GA - any views, goals, events that are no longer used?
@hthair @wellcometrust/experience-dev Is this being done as part of any of the GA week issues?

**Comment by jamesgorrie** [comment]
Good to clarify this, I think after the conversations with @hthair and hopefully the conversations with the GA consultant, we're not really changing very much in the current setup, but rather only implementing what we've actually orchestrated and learnt from the last property, into a new property.

This won't affect much as most of the changes are on factors that are destructive to data (dimensions for example, we can't go back and get them into the state we want them).

@hthair does that sound about right?

**Comment by jamesgorrie** [comment]
@hthair as a point, the data layer doesn't exist, we need to build it manually.
Unless we really need it, and we'd need to chat to Tom Crane about it, I can't see it existing on wl.org.

**Comment by jennpb** [comment]
@hthair @jamesgorrie @pollecuttn 
This issue is still live, but I'm thinking it needs to spin off into a Data Layer issue. These two tasks were marked as complete, but I'm not aware that they are complete - at least I don't know where I'd go to find the information relating to

> - Work out how we can analyse multiple data sources
> - Get baseline conversion and search log data for Platform and Collections teams (number of searches that result in a CT/request) - data needed to support Archives Accreditation

Can someone who knows about the data layer open a new ticket with more detail so we can prioritise this?

Here's a related ticket that, AFAIK, can't be done with out this mysterious data layer: https://github.com/wellcometrust/wellcomecollection.org/issues/4163

**Comment by jamesgorrie** [comment]
@gestchild where did you get with looking at the data layer?

**Comment by jennpb** [comment]
Subsumed by other tickets
