### ISSUE TITLE
Design an opt-in/opt-out workflow

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3739]
## Who it's for
- Website users (internal or external) who agree to use features/functionality in development

## Problem to solve
How to get people to self-select into a toggled cohort, and how to let them get out of it again

**Comment by Heesoomoon** [comment]
I'll sketch out few options for us to review next week.

**Comment by jamesgorrie** [comment]
@Heesoomoon would it be good to talk about what we're trying to do, maybe some examples etc, before coming up with the solution (he says after building one)?

**Comment by jamesgorrie** [comment]
Potential duplicate of #3959?

**Comment by Heesoomoon** [comment]
@jennpb Could we close this and keep #3959?
