### ISSUE TITLE
User Feedback mechanism

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3740]
## Who it's for
- Us, because we want to know what people need from our site
- Users who want to report any site/feature related issues 

## Problem to solve
We have a few scenarios where we want to collect free-text or other qual data from users:
- when we've released new functionality
- when user has any site/feature/content related issues (as part of good practice)

## Acceptance criteria
- [x] Users can access the Feedback feature easily across the 'Collections'
- [x] Users can inform us whether they've found what they were looking for (TBD)
(not specifically asking currently, but free form response allows this.)
- [x] Users can provide specific issues or suggestions
(free form response allows this)

## Things to consider
- Explore more integrated solution rather than the popup experience to minimise user complaints
- Scale for contextual (per component) or persistent location
- Workflow for feedback responses (do we reply to feedback directly?)
- If possible, streamline internal reporting and analysing workflow

## Questions/Next Steps
- [x] Discuss what we want from feedback to determine appropriate feedback method
- [ ] We are currently capable of launching a Hotjar poll or free-text Feedback widget. Is this possible behind a feature toggle?
- [ ] What data do we need to extract for reporting? e.g. url, mode, etc.
- [x]  Decide solution to implement? Hotjar, Google form embed, SurveyMonkey

## UPDATE:
- Going ahead with Hotjar 'incoming' feedback widget
- placement on right edge of browser in middle (says feedback, out the way until they click to expand) Message then says "how would you rate your experience?"
- what we get: 
1) rating on a 5 point smiley face scale
2) optional additional comment
3) option for user to enter their email if they would like a reply.
4) records their country, browser type, device category, operating system, date, page they were on and option to capture screenshot of page they responded on too.
- being put on all pages on the site (but can filter responses)
- comments that want a response are being forwarded to a specified email as well as being stored in hotjar.

**Comment by jamesgorrie** [comment]
> Is it possible behind a feature toggle?

Could you elaborate on what you mean by that? Do you mean the hypothetical new service, or something else?

**Comment by jamesgorrie** [comment]
As a point, we are looking into a uptime tool called updown run by [uservoice](https://www.uservoice.com/product/). They're generally really dev friendly (APIs etc), and the pre-made components are pretty good too: https://www.uservoice.com/product/

**Comment by jamesgorrie** [comment]
Example of survey monkey being used:
https://www.research.net/r/XJKRR62

**Comment by jamesgorrie** [comment]
From the discussion with @Heesoomoon @davidpmccormick @GarethOrmerod @gestchild 

There was talk about whether there should be a global style feedback, or a contextual one. Both had their merits:

## Global
Allowed users to feedback in general. A great way to collect any feedback, especially feedback on things we hadn't thought about.

A challenge if using this for more specific feedback, especially something like an A/B test (#3954) would be that we would have to share data between the site the service we might use<sup>*</sup>, specifically the URL, and if they are in any toggled situations, like the [new beta suggestion](https://github.com/wellcometrust/wellcomecollection.org/issues/3959). For this you can use things like pre-filled fields on Google forms ([e.g.](https://docs.google.com/forms/d/e/1FAIpQLSdDV-x9riLPAXOe9onFFNA3jHjrvdYyLB7R8JLOT0sXzB7gUA/viewform?usp=pp_url&entry.622499167=https://wellcomecollection.org/works/jqp7ngre)), or [prefilled values in Survey Monkey](https://help.surveymonkey.com/articles/en_US/kb/What-are-custom-variables-and-how-do-I-use-them). I quite like the Google forms idea as it allows someone to omit their data if they'd like.

e.g.
![screenshot-www gov uk-2019 01 16-07-59-12](https://user-images.githubusercontent.com/31692/51234539-e9b6b500-1964-11e9-88c0-69b2cb903264.png)


## Contextual
Allow users to feedback on specific features. A great way to get feedback on a feature, especially one being tested (again, #3945), where a GA metric wouldn't suffice.

A challenge with this is around having loads of "tell me, tell me, tell me" messages everywhere. This sounds like a design challenge in the sense of being able to make sure the mechanism is only obvious when involved in a certain feature. Language can also help here, similar to the Gov.uk example, where the feedback is a leading question, "Is there anything wrong with this page?", we could similarly have a question specific to the feature, e.g. "How'd you find the new search?", or "Is this information laid out clearly?"

e.g.
![screenshot-github com-2019 01 16-07-57-53](https://user-images.githubusercontent.com/31692/51234467-b70cbc80-1964-11e9-89a6-c1e23395414b.png)


<sup>*</sup>unless we build our own, which doesn't sound like a great idea.

**Comment by Heesoomoon** [comment]
I've updated the ticket description with what was discussed yesterday.

Few additional thoughts.
- When I brought up about the feedback mechanism initially, I didn't mean for 'General' feedback. It should be a tool to help us to identify the issue and resolve. For the Library Collections work, I think the key thing we should ask is 'Are people finding what they are looking for?' focusing on findability to help us improve search relevancy and meta data. 
e.g. Did you find what you were looking for?
Yes -> collect metric on how we are improving findability
No -> capture issues (inline free text form) then 
- The Beta group will be small. So we should open up the feedback mechanism to all users for us to learn and react.
- Currently, the feedback loop is a bit manual. People email to us or provide their comments in hotjar. Then we have to collate it and analyze. It will be good to think about different ways to streamline and automate the internal workflow which frees up the time for doing more impactful work.

**Comment by jamesgorrie** [comment]
Could workflow can just be a spreadsheet, or email converted to Github issues? This was we can track any progress, as well as making sure we respond to the people taking the time to feed back to us.

Got it - so one of the features we want to get feedback on is relevancy Another would be the collection search beta.

# Relevancy
Do we think a simple "Yes / No" feedback mechanism would give us anything to react to? It's a really complicated domain, and I wonder if this could cloudy the water, unless a metric we were chasing is less nos?

In conjunction with a question of, "No? What were you expecting?" or similar it could  quite powerful, but we should think of collecting the search term along with that, but wonder if we're invading privacy here.

# Beta
> So we should open up the feedback mechanism to all users for us to learn and react.

When you say all users, do we mean all users beta or not? Or do you mean all beta users?
What type of questions can you see us asking, about the beta in general, or specific features that we have in the wild?

**Comment by jamesgorrie** [comment]
Quite liked Zeit's feedback mechanism - makes it look a little like search, but interestingly makes it really evident.

![screencast-zeit co-2019 01 18-13-11-21](https://user-images.githubusercontent.com/31692/51388899-b752b680-1b22-11e9-9a59-75e4dac98be7.gif)

**Comment by Heesoomoon** [comment]
I've started a list of different ideas for the copy and CTA. Feel free to add.
https://www.notion.so/wellcometrust/3740-User-Feedback-Mechanism-ee46aa9f52a24a809e0cf785a0d9d5b4

**Comment by jennpb** [comment]
Using Hotjar for now, will reconsider other feedback UI if Hotjar gets too many 'i hate this feedback tab' comments.
