### ISSUE TITLE
Works pages: v2 design and layout

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3742]
## Who it's for
- People doing research, to help them scan for relevant information and comprehend information about the work

## Problem to be solved
The works page was initially designed only with v1 API/Miro metadata in hand. We now have 1+ year's usage data and additional metadata fields from Sierra (MARC) that we need to accommodate and enhance.

**Considerations**
- Ordering and grouping of metadata
- Move/restyle the 'We're improving...' message
- Group work type with title?
- Positioning of 'Using this image' section - potentially grouping with Download
- Positioning of Download actions, especially on mobile
- Test flipping title and image positions
- Add search field to top of work page (this work will be related to site-wide search)
- Spacing of image viewer controls

## Dependencies and Constraints
- Some data from the Sierra record still not available in API - (reference numbers for citation purposes, location information for on-shelf items, some notes fields)
- User research / card sorting to prioritise order of information https://github.com/wellcometrust/wellcomecollection.org/issues/3693

**Comment by jamesgorrie** [comment]
@jennpb has this been duplicated in #3801?

**Comment by jennpb** [comment]
@jamesgorrie Yes!
