### ISSUE TITLE
Combine production fields from platform API

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3745]
Combine the production fields to more represent what we have on the currently library site.

**Comment by jamesgorrie** [comment]
@jennpb @Heesoomoon @pollecuttn 

From the [code here](https://github.com/wellcometrust/platform/blob/master/catalogue_pipeline/transformer/transformer_sierra/src/main/scala/uk/ac/wellcome/platform/transformer/sierra/transformers/SierraProduction.scala#L84-L89), I'm not 100% we can combine the fields back into their original state.

What that code is doing is combining:
- subfield `a` & `e` into the list `places`
- subfield `b` & `f` into the list `agents`
- subfield `c` & `g` into the list `places`

As these are all lists, we won't be able to tell whether e.g. index 0 in places _should be_ combined with index 0 of agents.

@jtweed am I right in saying this, or misreading the explanation in the comment?

**Comment by jtweed** [comment]
It certainly seems like you might be right. I'm going to have to defer this one to @silveroliver, as I'm sure this was discussed at length during his sessions with the librarians.

**Comment by jamesgorrie** [comment]
So I think I misunderstood the exploding. from what I can tell I was saying, if we have three 260 fields:
- `a1 b1 c1`
- `a2 b2 c2`
- `a3 b3 c3`

We then zipped them into 1 production event, which would be:
- places: `a1, a2, a3`
- agents: `b1, b2, b3`
- dates:`c1, c2, c3`

This is wrong, what we do is have three production events:
- places: `a1`, agents:  `b1`, dates: `c1`
- places: `a2`, agents:  `b2`, dates: `c2`
- places: `a3`, agents:  `b3`, dates: `c3`

Why each field of each event is a list is to account for a record that is:
- `a1b1 a2b2 c1`
- places: `a1, a2`, agents:  `b1, b2`, dates: `c1`

Which would result in a production event of:
- places: `a1, a2`, agents:  `b1, b2`, dates: `c1` 

This record above would allow us to stick it back together, but if we had the record:
- `a1 a2b2 c1`
- places: `a1, a2`, agents:  `b2`, dates: `c1` 

Basically we couldn't tell that `a2` is associated with `b2` as we can't use order for reference.
__However - I'm not sure that this ever happens.__ 👈 if not, we can infer how to stick these back together.

---

# What next
So using the above examples, we were talking about flattening out the production events into multiple events.
__Marc__
`a1b1 a2b2 c1`

__Old JSON__
```JSON
[{
  "places": ["a1", "a2"],
  "agents": ["b1", "b2"],
  "dates": ["c1"]
}]
```

__New JSON__
```JSON
[{
  "places": ["a1"],
  "agents": ["b1"],
  "dates": ["c1"]
}, {
  "places": ["a2"],
  "agents": ["b2"],
  "dates": ["c1"]
}]
```

...and...

__Marc__
`a1 a2b2 c1`

__JSON__
```JSON
[{
  "places": ["a1"],
  "dates": ["c1"]
}, {
  "places": ["a2"],
  "agents": ["b2"],
  "dates": ["c1"]
}]
```

Ping @silveroliver @Heesoomoon - sorry if this is verbose, but covers my understanding of the issue?

**Comment by silveroliver** [comment]
What makes this hard is we might get:
`a1 a2b2 c1`

Where the a and c are shared by the 2's!
Would result in:
```
a1 a2 c1
a1 b2 c1
```
I need to dig out more examples like this.

**Comment by silveroliver** [comment]
Transformation file has been updated. This is ready for review by @jtweed and then ready to be worked on.

**Comment by jamesgorrie** [comment]
@silveroliver Do we have an example, just for completion of this issue?

**Comment by jamesgorrie** [comment]
If this is correct:
```JSON
 {
 	"production": [{
 		"label": "London : Mac Keith Press, NY : HarperCollins, 1998",
 		"places": [{
 			"label": "London",
 			"type": "Place"
 		}],
 		"agents": [{
 			"label": "Mac Keith Press",
 			"type": "Agent"
 		}],
 		"places": [{
 			"label": "NY",
 			"type": "Place"
 		}],
 		"agents": [{
 			"label": "HarperCollins",
 			"type": "Agent"
 		}],
 		"dates": [{
 			"label": "1998",
 			"type": "Period"
 		}],
 		"function": {
 			"label": "Publication",
 			"type": "Concept"
 		},
 		"type": "ProductionEvent"
 	}]
 }
```

We've got duplicate keys for `places` and the others, which makes it invalid and unparsable?

**Comment by jamesgorrie** [comment]
This works?
```JSON
 {
 	"production": [{
 		"label": "London : Mac Keith Press, NY : HarperCollins, 1998",
    "event": [
      {
        "type": "Place",
        "label": "London",
 			  "type": "Place"
      },
      {
        "type": "Agent"
        "label": "Mac Keith Press",
        "type": "Agent"
 		  }
    ],
 		"type": "ProductionEvent"
 	}]
 }
```

**Comment by jamesgorrie** [comment]
Progress notes:
<sub>These aren't defined, but just on a conversation @silveroliver and I had</sub>
<sub>They're also based on the fact that 260 is a broken field, and it might be worth sorting that systemic problem out</sub>

## Short term
We going to be adding the label to the current structure.
This will allow us show the label, and search on the different terms within that label.
This will not allow us to combine the fields in an order defined by us.

## Medium term
Look at migrating `260` to `264`

## Longer term
Continue modelling in a world where the data is more consistent and expressive.

@jennpb I'd say this ticket is probably closed as the next steps have been defined?

**Comment by jennpb** [comment]
Yep, now the next step is #3890
