### ISSUE TITLE
User Research: V2 Metadata Card Sorting

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3761]
## Research objectives
To collect user feedback to help us prioritise the order of information for Works Pages V2 Design #3742 
- Validate information hierarchy and grouping
- Collect any missing info needed for their research
- Collect label suggestions

## To do
- [x] Card labels and questionnaire
- [x] Review with Jenn
- [x] Finalize the methods for recruiting participants (#3693)
- [x] Scriptwriting

## Card labels and questionnaire (draft)
https://docs.google.com/spreadsheets/d/1ZLoPOnVBpNS40gYjCfTcp_M-YaEALkTkEoAWvxQr3sA/edit?usp=sharing

**Comment by hthair** [comment]
Draft version card sort ready for review today.

**Comment by hthair** [comment]
Optimal sort priority ranking complete and closed. Need to export data and store

**Comment by Heesoomoon** [comment]
#3954

**Comment by hthair** [comment]
documentation here:
https://docs.google.com/spreadsheets/d/1-LiVKFaaPlFVlOgK55wuBMsacuJG5D-dxwLpP8x4a-8/edit#gid=0
