### ISSUE TITLE
Library Collection Data

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3776]
## Purpose  
To help the team make better product design decisions by understanding the types of Work we have in our Library Collection.

## To investigate (TBD)
- % breakdown by Work types and % of digitised Work
- Number of digitised images per Work (histogram?) overall (not per worktype) - info to help design works page and viewer
- Available metadata per Work type (i.e. most frequent fields per worktype) - info to help design works page summary

**Comment by jennpb** [comment]
@pollecuttn I'm assigning this to you to assemble the data with the help of @wellcometrust/platform @wellcometrust/experience-dev and/or Rioghnach - thanks!

**Comment by jamesgorrie** [comment]
## % breakdown by Work types

**ID**|**Label**|**Count**|**%**
:-----:|:-----:|:-----:|:-----:
a|Books|377164|30.34287015
b|Manuscripts, Asian|5757|0.4631510522
c|Music|9|0.0007240506288
d|Journals|15069|1.212302103
e|Maps|44|0.003539803074
f|E-videos|2320|0.1866441621
g|Videorecordings|5409|0.4351544279
h|Archives and manuscripts|270618|21.77123701
i|Sound|2182|0.1755420525
j|E-journals|10400|0.8366807267
k|Pictures|76497|6.154188995
l|Ephemera|15569|1.252527138
m|CD-Roms|62|0.004987904332
n|Cinefilm|2018|0.162348241
p|Mixed materials|19|0.001528551328
q|Digital Images|159|0.01279156111
q|Digital images|71612|5.761190404
r|3-D Objects|59|0.004746554122
s|E-sound|515|0.04143178598
u|Standing order|2|0.0001609001397
v|E-books|385786|31.03651066
w|Student dissertations|657|0.05285569591
x|E-manuscripts, Asian|495|0.03982278459
z|Web sites|585|0.04706329087

**Comment by alexwlchan** [comment]
I've attached a zip file with a collection of spreadsheets. [collection_analysis.zip](https://github.com/wellcometrust/wellcomecollection.org/files/2727003/collection_analysis.zip)

> % breakdown by Work types and % of digitised Work

See `work_type_tally.csv`

> Number of digitised images per Work (histogram?) overall (not per worktype) - info to help design works page and viewer

See `digitised_images--any.csv`. I also broke out `iiif-image` and `iiif-presentation` separately, as right now I think you only support the former?

> Available metadata per Work type (i.e. most frequent fields per worktype) - info to help design works page summary

See the grid in `metadata_by_work_type.csv`.

Hopefully the spreadsheets are self-explanatory; yell if anything doesn't make sense!

**Comment by jamesgorrie** [comment]
That's fabulous! Thanks @alexwlchan

**Comment by pollecuttn** [comment]
@Heesoomoon Alex and Harrison have got data for you

**Comment by jamesgorrie** [comment]
@alexwlchan @harrisonpim are you just running a python script to run through each line in the snapshot and create aggregates from there?

**Comment by harrisonpim** [comment]
I've also got access to source data in the dds database through Tom Crane, if that helps with any further questions

**Comment by jennpb** [comment]
Can we close this? @pollecuttn @jamesgorrie
