### ISSUE TITLE
Search results: need a more helpful 'no results found' 

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3777]
![screen shot 2018-11-21 at 10 08 11](https://user-images.githubusercontent.com/1446139/48834376-94e82b00-ed75-11e8-8b00-5bd685233634.png)
https://wellcomecollection.org/works?query=V018139&page=1

**Comment by jamesgorrie** [comment]
@jennpb actually put a basic version in a PR tidying up / enhancing a few interface elements [here](https://github.com/wellcometrust/wellcomecollection.org/pull/3775#issuecomment-440627061).

**Comment by pollecuttn** [comment]
https://github.com/wellcometrust/wellcomecollection.org/pull/4641
