### ISSUE TITLE
Design system: link style audit and recommendations

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3800]
## Problem to be solved
We seem to have a proliferation of link styles that are inconsistent in behaviour, sprawling in number, and aren't fully documented.

@jennpb started a [link style audit](https://docs.google.com/document/d/1W0lQuZ0ZKEbUqEAhySVd-jTLJfGYGRtjcrpAIYSDgTg/edit?usp=sharing)

@GarethOrmerod will need to comb through to find other strays and to consolidate and make recommendations

**Comment by jamesgorrie** [comment]
>  No-image compact card style outro

Why would this require a CMS change? The outro is already there, it's just about bringing it into the `ContentList`?
