### ISSUE TITLE
Prototyping work pages

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3801]
We have some new designs that, if put into the browser, might help the direction, or directions, that the design could go in.

Given the large amounts of state a work can be in, this feels like a more sustainable way to be viewing which parts of the design work and don't work.

We can start using them for any user research we have in the pipeline as an alternative to the current designs.

This is completely of the mindset that things are transient, but the system is flexible enough to add things, and remove them as the conversations and research suggest we should.

https://zpl.io/VQ94zEn

Ref #3742

e.g.
![wc_works_components](https://user-images.githubusercontent.com/29206031/49092328-b9527480-f259-11e8-92fe-48da396e1acb.png)

**Comment by Heesoomoon** [comment]
@GarethOrmerod @davidpmccormick @gestchild I've updated the design with the notes from our meeting earlier. Let me know if you have any questions.

**Comment by jamesgorrie** [comment]
@jennpb @Heesoomoon from a small conversation with @wellcometrust/experience-dev, we wondered if we could plan this to potentially look at the separate parts, and if, once we have an understanding that we've delivered something better, we move that 1 piece to the current template?

We wouldn't lose a picture of the whole, because we could be developing that too. e.g. We work on the Info sections as part of the new version, they prove to be better, we ship them to everyone.

Or do we see us working on all the different parts and this being shipped as a full piece?

**Comment by jennpb** [comment]
Componentize?: yes

Shipping?: That feels like the wrong question, or a question asked too early. I'd like to prototype the pages so we can see how the content and metadata fit, as a reality check and first step in determining whether a design is feasible. There's a nice bridge into #3741 too - it might be more valuable to prototype that journey from works page to full rendered item if we're going to put something in front of users.

But we haven't talked yet about success measures; not enough task-based usability data collected from current /works to determine whether we'll make any improvements to the user's experience by making the design changes. Any thoughts on how we might measure success, either on a component-by-component basis, or as a whole piece?

**Comment by jamesgorrie** [comment]
> But we haven't talked yet about success measures

Shipping was definitely what I was hoping we wouldn't do.

Looking at the segmentation above (header, media, items, info) - those feel like they could have their local, and probably hyper-focused, purpose and success measures.

Where the work page would have something similar, and there could also be relationship / exploratory success measures too...

As an example:
I am looking for things authored by Tom Quinn.
- The hyper-super-focussed point of the author metadata is to let you know if this is authored by Tom Quinn or not.
- The hyper-focussed point of the metadata is to let you know if Tom Quinn was involved in anything to do with this.
- If not, maybe he was mentioned in it, somewhere in the items.
- Or maybe... etc etc

So if someone is looking for something specific, there is a component to do that, but if there's more vagueness, there is components (or groups or components) to try and achieve that.

I suppose it's similar to when we right unit tests, making sure a component does at least what it exactly needs to.

And then integration tests, to make sure that components play well in the greater system.

But maybe programming tests is not the right
 paradigm for user testing.

**Comment by jamesgorrie** [comment]
@jennpb after some thought on it, I think I was just asking what the research and iteration plan was for this, but know that's why we're building it, to get it front of people.

What could be good to test as a methodology is having this put in front of people for a day or so, but iterating on it during the research? Having a observe => test => iterate cycle all in fast succession?

**Comment by jamesgorrie** [comment]
After a conversation with @hthair, I think I have a clearer question.

Would it be useful to be able test multiple configurations of a prototype to test withe a small bunch of users that we could quickly iterate on?

e.g.
- We have a set of tasks that we would like people to try and achieve, let's say, is this item relevant to a person.
- We build the designs as is
- We have a version with the sections in a different order
- We have a version with the heading of the sections as links in the header

We can then give this to the researcher, receive the feedback and move forward with the design.

Almost like inviting users to our design reviews.

disclaimer: none of this takes into account the resource we might need for this.

This is based on some reading and watching on the 5 people testing model, where it's power becomes apparent when you iterate and re-test on another sample size.

https://www.nngroup.com/videos/usability-testing-w-5-users-design-process/
https://www.nngroup.com/videos/usability-testing-w-5-users-roi-criteria/

**Comment by Heesoomoon** [comment]
Here's the sketch of Access info for the prototype. @GarethOrmerod is going to provide the design.
![img_4962](https://user-images.githubusercontent.com/29206031/49747326-1b1fcf00-fc9b-11e8-8578-38328481eae4.jpeg)

**Comment by jamesgorrie** [comment]
>  @GarethOrmerod is going to provide the design.

@wellcometrust/experience-dev if we have a minute, we can get the HTML in and then apply any additional design, might be worth @GarethOrmerod seeing it in browser.

**Comment by jennpb** [comment]
Closing this as it's been overtaken by other tickets.
