### ISSUE TITLE
GA Week: How to deal with marketing params

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3833]
# Problem
Having marketing parameters in pageviews makes things like `/articles/1` and `/articles/1?fb_id=3` count as two different pageviews, whereas they're the same page.

# Solution
Strip out irrelevant marketing parameters 

# Questions:
* Is there an whitelist  rather that blacklist?

**Comment by hthair** [comment]
Updated the exclusion criteria to remove all common string add ons on the new clean GA account. Will monitor generally in future to spot any other unwanted strings creeping in.
