### ISSUE TITLE
GA Week: Cross domain tracking

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3834]
Can we have a property with the following views:

* Main - lib & WC
* Raw - no filters
* Test - to test goals and dimensions etc
* Lib
* WC

**Comment by jamesgorrie** [comment]
Another option would be to look at having Data Studio dashboards with two data sources from each GA account.

**Comment by pollecuttn** [comment]
Depends on outcome of https://github.com/wellcometrust/wellcomecollection.org/issues/3843

**Comment by jamesgorrie** [comment]
This was done in #3842
