### ISSUE TITLE
Group and report on lists of URLs

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3840]
We need a way to group and then report standard metrics on groups or URLs.

__E.g: lists grouping__
* Home (for now)
* Event series page
* Article series page
* What’s on
* All exhibitions ‘/exhibitions’
* All events ‘/events’
* What we do
* Visit us
* Stories 
* ‘All articles’
* Works?query pages

Another example might be `editorial` URLs.
Do we want to report in datastudio or GA?

__Thoughts:__
* Content grouping in GA (but don't know how to report on it, and not sure if it access those in datastudio)
* Calculated fields in datastudio

**Comment by jennpb** [comment]
@hthair Do we need to nail down the groupings before setting this up? I'm wondering if there would be scope for changing the groups after we restructure the categories (e.g. getting rid of What We Do, creating new section and dispersing some of the content into other sections).

**Comment by hthair** [comment]
@jamesgorrie in answer to Qu's above, I'd likely use these in data studio (mainly for reading time, as this isn't available in GA).
Could we do this as a secondary dimension? Like we had for 'editorial' before for example (think it was either a 'category' or 'content type' dim).
I think you can edit custom dims after too. which ever method we choose we want to be able to make adjustments later for example if the home page becomes more content driven and we want to remove it from the list group. 
I was also thinking we should call the list 'link pages' as that's a bit more descriptive or what they do as oppose to content pages. Thoughts?

**Comment by jennpb** [comment]
I think 'listing page' or 'index page' is more appropriate as it describes more of the function of the page - they're for jumping off into more content of a defined type (articles, exhibitions, events, people, topics, etc). If we're creating content properly, all webpages are link pages :)

**Comment by jamesgorrie** [comment]
@jennpb -that's a great name for the dimension: `function`.

**Comment by hthair** [comment]
- [ ] plan out data layer needs

^ this is part of the list grouping. We only get 20 secondary dimensions so I'm compiling a list of things we'd want across the whole site. (and considering if a 2nd dim is the best method for grouping pages.

**Comment by hthair** [comment]
@gestchild could we potentially do this in the same way we did for worktype? As in call it something like pagetype and then tag up the index pages as one thing, events as another etc?

**Comment by jennpb** [comment]
Hold off on this until later
