### ISSUE TITLE
GA Week: Google Tag Manager

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3843]
* @hthair [read about GTM and datalayer](https://www.simoahava.com/)
* @wellcometrust/experience-dev  [read about GTM and datalayer](https://www.simoahava.com/)
* Implementation details - how to implement without breaking what we have.

Things this might solve:
* Reporting custom work fields to dimensions (data layer)
* Cross domain #3834  https://developers.google.com/analytics/devguides/collection/gtagjs/cross-domain
* ...

Potentially another good candidate for using the new GA property

**Comment by hthair** [comment]
Will review with Chris by going through our new proposed set up to see how valuable it is for what we need. Then will work out steps for implementation.

**Comment by hthair** [comment]
Next step is to add the container to wc.org and wl.org

instructions are here for container implementation (can one of you add this to wc.org for me please :) @jamesgorrie @gestchild) https://tagmanager.google.com/?authuser=1#/admin/accounts/4535612927/containers/10552324/install?containerDraftId=1

@jennpb In terms of what we need library wise, we just need this code added to the site. I'll email it as a word doc so the code doesn't get changed which apparently can happen due to security on emails.

**Comment by jamesgorrie** [comment]
Let us make sure we get the implementation straight on our side, then we can talk to Tom C to make sure it's hooked up the same.

**Comment by jennpb** [comment]
OK - I've noted that in the JIRA issue that you'll be the main point of contact.

**Comment by hthair** [comment]
catalogue.library domain unable to support cross domain tracking - looking for way around this. Might be possible to exclude just that one domain and still feed in the others from wl to new property using GTM variable. 

We've decided to strip out the GA code that is sending data to the new property (24), (while keeping the original ga code for the regular ga property) and put in the GTM container to allow HT chance to test out GTM on new property without duplicating pageviews etc.

**Comment by jamesgorrie** [comment]
# Conclusion

We're using two properties, `[Default] Collection`, and `Wellcome Collection and Library`<sup>*</sup>

`Collection` will be used as normal, continue to track everything we already do and only report on wc.org.

`WC and WL` will track separately but across both domains. 

As mentioned ☝️ by @hthair (sorry for repeating), this will allow for testing with GTM while not disrupting BAU.

The cross domain issue is fixed by using a hash in the URL, rather than a query parameter. @hthair happy to show you how that was done.

Pageviews on `wl.org` are being tracked with the standard page view code, whilst page view on wc.org are being tracked with the history API due to the fact that we are (partially) an [SPA](https://medium.com/@pshrmn/demystifying-single-page-applications-3068d0555d46),  and this implementation works for normal, and history change views.

<sup>*</sup>I know we've been trying to avoid this, but it's the most explanatory and clear name we could think of, meaning `wellcomecollection.org` and `wellcomelibrary.org`.
