### ISSUE TITLE
GA Week: Investigate filters work on session based values in Data Studio

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3844]
Checking how filters work in Data Studio on session metrics e.g. pages per session.

**Comment by hthair** [comment]
By comparing segments vs filters it looks like filters are absolute e.g. a filter on time on page saying include works pages gives aggregated time for all works pages only, whereas segments for works pages gives time on site for any session that contained a works page and therefore includes other pages too.
