### ISSUE TITLE
GA Week: Platform requests for tracking on works

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3845]
On 1 page searches
* What results position do people click on?
* What % of people clicking through on a result?

On other searches
* How many pages deep do people go?

**Comment by jennpb** [comment]
@jamesgorrie @hthair Does this need doing? Is the description correct?

**Comment by jamesgorrie** [comment]
It's interesting, but I would say needs more refinement, and there might be more in-depth conversations to have with @harrisonpim on this. Closing for now.
