### ISSUE TITLE
Use Production label from API 

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3890]
Related to #3745 

# Who it's for
People using our collections, so they can determine all aspects of an item's production and be able to parse the meaning of the string (unlike now, where all production events are listed out separately)

# To do
Replace list of production events with full production label on /works

**Comment by jennpb** [comment]
Let's push this one out to all users (@gestchild did the work on our prototype during sprint week) @wellcometrust/experience-devs

**Comment by jamesgorrie** [comment]
@jennpb assuming we want to take the structured list out?

**Comment by jennpb** [comment]
Yes please.
