### ISSUE TITLE
Display of works with iiif-presentation location type

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3924]
Currently we only surface and display works with the [location type of `iiif-image`](https://api.wellcomecollection.org/catalogue/v2/works?items.locations.locationType=iiif-image), which are the works from MIRO (114102  of 1246071 results - 9%).

There are [results in the API that have `iiif-presentation` location types](https://api.wellcomecollection.org/catalogue/v2/works?items.locations.locationType=iiif-presentation). These are things like books, manuscripts etc (237433 of 1246071 - 19%).

We will need to start investigating what tools and libraries we will need to parse and render these presentation manifests. After that we will be in a better position to inform the design as to what data we have, don't have, and what interactive elements we can build in for people to explore this content.

**Comment by jennpb** [comment]
Relates to 🏆#3958

**Comment by jamesgorrie** [comment]
Going to close this in favour of #4198
