### ISSUE TITLE
Works: Omnipresent search bar

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3956]
## The problem: We think that...
Researchers pogo-stick (searching, looking at a result, going back and then refining search) quite a lot. 

## Therefor we hypothesize that...
If we add the search bar to the work result page, a researcher would have less steps to go through to get to their new search

## TBD
- [x] Send search event to GA
- [x] A/B test
- [ ] Qual feedback: @Heesoomoon / @hthair to update issue

## As measured by...
The amounts of searches / session increases

## Acceptance criteria: we are right if...

- [ ] The amounts of searches / session increases

**Comment by jennpb** [comment]
We should look at ending this next week and start pushing the omnipresent search bar to 100% if the test demonstrates success @wellcometrust/experience-devs @hthair @pollecuttn
