### ISSUE TITLE
GA:  update dashboards

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#3969]
@hthair to update dashboards once #3963, #3967 and #3968 completed

- [x] main collection dashboard

- [x] Tom's dashboard

- [x] editorial dasboard

**Comment by hthair** [comment]
- [ ] main collection dashboard

- [ ] Tom's dashboard

- [ ] editorial dasboard

**Comment by hthair** [comment]
All filters and event tracking updated. Editorial dash may change as a result of conversations with team on what is useful to them. e.g. series (when we have this metadata tagged up we can show them series)
