### ISSUE TITLE
Researcher Recruitment for Q2

### ISSUE THREAD

**Issue by hthair** [wellcometrust/wellcomecollection.org#3975]
For fortnightly testing we need researchers to test iterations to works pages.

Current method:
Using our library members
- [x] write screener to find people that use our material rather than just the library space
- [x] compose dotmailer invite
- [x] check copy and branding 
- [x] create calendly set up (so people can select a time slot without a lot of email admin)

Depending on number of responses we may need other options.

**Comment by hthair** [comment]
Calendly currently being reviewed for GDPR. If not returned in time will send out a manual email with list of times for this week and the next sprint.

**Comment by jennpb** [comment]
Can we close this now @hthair ?
