### ISSUE TITLE
Collect search behaviours data on /works and WL.org

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3983]
## Who it's for
Experience team 

## Why
To help us make better product decisions based on user data on WC.org and WL.org.

## To investigate on both /Works and WL.org
- number of search per session (avg. or histogram)
- Return users: how often do they return?
- Device breakdown
- What features are currently being used in Works page?
- Advanced search usage

Related to #3030

**Comment by jennpb** [comment]
I think Return users and Device breakdown is the only thing we can get from GA. @hthair Can we get this info and then close this issue?

The rest of it will be done as part of #4149 @jamesgorrie

**Comment by jennpb** [comment]
@hthair @Heesoomoon Is this still to be done?

**Comment by hthair** [comment]
@jennpb heesoo's got print outs of it all, just checking how we can capture it elsewhere.

**Comment by Heesoomoon** [comment]
![Screen Shot 2019-01-22 at 09 43 22](https://user-images.githubusercontent.com/29206031/54143529-efd78800-4421-11e9-8a61-bcce32110fc6.png)
![Screen Shot 2019-01-22 at 09 43 53](https://user-images.githubusercontent.com/29206031/54143530-efd78800-4421-11e9-99b7-bae80b45a1bc.png)
![Screen Shot 2019-01-22 at 09 44 41](https://user-images.githubusercontent.com/29206031/54143531-efd78800-4421-11e9-8254-00a1b586a0bc.png)
![Screen Shot 2019-01-22 at 09 45 10](https://user-images.githubusercontent.com/29206031/54143532-efd78800-4421-11e9-9830-ecb72dc8ea28.png)
![Screen Shot 2019-01-22 at 09 45 21](https://user-images.githubusercontent.com/29206031/54143533-f0701e80-4421-11e9-93ba-0ace6dafaa44.png)
![Screen Shot 2019-01-22 at 09 46 00](https://user-images.githubusercontent.com/29206031/54143534-f0701e80-4421-11e9-8371-afaf77e807f2.png)
![Screen Shot 2019-01-22 at 10 03 02](https://user-images.githubusercontent.com/29206031/54143535-f0701e80-4421-11e9-9d5a-6abdd81e6720.png)
![Screen Shot 2019-01-22 at 10 03 28](https://user-images.githubusercontent.com/29206031/54143541-f2d27880-4421-11e9-8734-c6992c854335.png)
