### ISSUE TITLE
Analyse and aggregate API data

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3996]
- [x] ~Check if empty arrays are being classified as a count in the tallies~ #3997 [New metadata analysis](https://github.com/wellcometrust/wellcomecollection.org/files/2786702/metadata_by_work_type.csv.zip)
- [x] ~Take a look at https://github.com/wellcometrust/platform/issues/3288~ How many works of each work type have a production date, place, etc.?
- [ ] ...

**Comment by jamesgorrie** [comment]
@Heesoomoon it turns out not everything has the genres, subjects, contributors, and production.
The new analysis is above.

**Comment by jennpb** [comment]
Is this ticket still needed @jamesgorrie @Heesoomoon ?

**Comment by jamesgorrie** [comment]
I was going to keep it open for other requests, but better to close and new ones opened when needed.
