### ISSUE TITLE
Opening Times - regular hours change on 1 April 2019

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4013]
Wellcome Collection's opening hours are changing **effective 1 April 2019**.

We need to change all components that display opening times.

Galleries and Reading Room
**Closed**  Monday
**10:00-18:00** Tuesday, Wednesday, Friday, Saturday, Sunday
**10:00-21:00** Thursday

Library - No change

Cafe, Restaurant and Shop - waiting for info from Commercial Manager

**Comment by jamesgorrie** [comment]
@gestchild can all of this be changed from Prismic?

**Comment by gestchild** [comment]
@james yep, we could change them and schedule the publication for the 1st April

**Comment by jennpb** [comment]
New hours from 1 April 2019 (confirmed with Lisa W and Sophie W)
  | Galleries (inc RR) | Library
-- | -- | --
Mon | Closed | 10:00—18:00
Tue | 10:00—18:00 | 10:00—18:00
Wed | 10:00—18:00 | 10:00—18:00
Thu | 10:00—21:00 | 10:00—20:00
Fri | 10:00—18:00 | 10:00—18:00
Sat | 10:00—18:00 | 10:00—16:00
Sun | 10:00—18:00 | Closed


  | Restaurant | Café | Shop
-- | -- | -- | --
Mon | Closed | 08:30—18:00 | 09:00—18:00
Tue | 11:00—18:00 | 08:30—18:00 | 09:00—18:00
Wed | 11:00—18:00 | 08:30—18:00 | 09:00—18:00
Thu | 11:00—21:00 | 08:30—21:00 | 09:00—21:00
Fri | 11:00—18:00 | 08:30—18:00 | 09:00—18:00
Sat | 11:00—18:00 | 09:30—18:00 | 10:00—18:00
Sun | 11:00—18:00 | 10:00—18:00 | 10:00—18:00

**Comment by gestchild** [comment]
Have made the required changes in prismic and scheduled them to publish at 11:59PM on the 31st March 2019
