### ISSUE TITLE
Build audio as main article

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#403]
![image](https://cloud.githubusercontent.com/assets/1446139/22376131/b4c0fdde-e4a4-11e6-9341-c31505af8bf4.png)

**Comment by Norvard** [comment]
For this I would think we just place a soundcloud embed centered in the black area. With 120 pixel buffer top and bottom

Grab me when you begin experimenting with Soundcloud embeds. Curious to see how they behave at large sizes as Ive only seen them embeded smaller. Maybe we can toss one into codepen quickly and test the responsive nature of them?
