### ISSUE TITLE
Add Primary Button CTA to Books pages

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4089]
## Who it's for
People who want to buy our books

## Problem to be solved
We currently use the `moreLink` style to indicate 'Order online' on all `/books` pages. This is inconsistent with how we indicate primary CTAs on other pages.

This should be turned into a `primary button` with label `Buy the book`

**Comment by jennpb** [comment]
@wellcometrust/experience-devs The button label wasn't changed to `Buy the book` as indicated above. Can you please make this wee change?

**Comment by davidpmccormick** [comment]
Totally missed that – will fix.
