### ISSUE TITLE
Add new Favicon 

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#410]
New asset attached
![wc_favicon](https://cloud.githubusercontent.com/assets/23660297/22422302/8ff5a1ee-e6e3-11e6-8657-6744abf67c5f.gif)

**Comment by jamesgorrie** [comment]
Could we have this as an SVG?

**Comment by Norvard** [comment]
Here you go!

[WC_Favicon.svg.zip](https://github.com/wellcometrust/wellcomecollection.org/files/738986/WC_Favicon.svg.zip)

**Comment by jennpb** [comment]
Could we please have this as 
- favicon
- touch icon 72x72
- touch icon 114x114

woop!

**Comment by Norvard** [comment]
Here you go :)

![wc_touch_72](https://cloud.githubusercontent.com/assets/23660297/22547589/31b90fd6-e93a-11e6-98ff-5c8cbcf292e1.png)
![wc_touch_114](https://cloud.githubusercontent.com/assets/23660297/22547590/31ba0a3a-e93a-11e6-9149-7fbd5afb86c2.png)

**Comment by jamesgorrie** [comment]
I wonder about the efficacy of the icon in context of the home screen.
It should be easily identifiable, especially amongst other icons, which I argue this isn't.

Saying that I am no expert on brand awareness of users through repetition etc etc...

Just thought it's worth seeing in context.

![faviconincontext](https://cloud.githubusercontent.com/assets/31692/22696683/e23c379c-ed46-11e6-93bb-a6a2025a1e41.png)
