### ISSUE TITLE
Search: Create session ID to be able to analyse all action within a search

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#4110]
A search is more that just someone typing in a term, and finding what they want.
How much more is hard to tell.

By adding a search session ID to the requests made to the API, we will then be able to aggregate and analyse those as one whole action, as opposed to analysing lots of micro-actions.

As per the conversation with @harrisonpim
![screenshot 2019-02-12 at 07 30 32](https://user-images.githubusercontent.com/31692/52618934-29a38600-2e98-11e9-8fcb-c2f0e415c53a.png)

**Comment by jamesgorrie** [comment]
An idea of implementation for this could be:
* Segment.io
  * Use the JS lib to store search information
  * Send the information to an S3 bucket
* Run an elasticsearch cluster that is fed off S3 ☝️ 
* Have a Kibana dash on top of that to analyse search results

The data will also be available for any work @harrisonpim or @hthair would like to do.

## Considerations
### Segment.io
#### GDPR
 Currently when using `analytics.js`, no personally identifying data is tracked, except the IP, [but you can disable that](https://segment.com/docs/sources/website/analytics.js/#anonymizing-ip).

#### Cost
[The site says $120 / month](https://segment.com/pricing/), but I have been told there might be discounts for charities by one of their sales team.

### Elasticsearch
This is easy enough to setup, we could run something out of Bonsai to start with, which is free, and then expand from there if we need to.

☝️ I setup a spike for this using my local and it seems to work pretty well (although my segment account is now full and I can't test further).

---

And example of a search log might be:
* Searches for `term1`
* Searches for `term1 term2 term3`
* Looks at `result1`
* Searches for `term1 term2`
* Looks at `result2`
* ...

And as much as that is useful on it's own, we can then start asking questions like:
* What's the average amount of searches done per session?
* What's the average amount of results viewed compared to searches?
* What's the average amount of search terms used?
* What are the outliers and what do they look like?
* ...

Currently GA doesn't get us even close to this, samples some of the data, isn't transparent about what it means by its metrics (results per search for example), and doesn't open up the data for further analysis.

The way people use our search is pretty unique in the sense it's very exploratory, and it feels like GA doesn't really cater for this type of analysis.

I also wonder, if opening up a search like this, we could start sharing it with other libraries. The only bit of proprietary software above is Segment, and we could, if it starts to feel worth it, build that out too.

**Comment by harrisonpim** [comment]
it's worth joining this up with the prototyping that @jtweed has been doing. it seems like we're quickly starting to converge on some good ideas

**Comment by jamesgorrie** [comment]
Closing in favour of #4149
