### ISSUE TITLE
Work Preview: Concept 2 - Flickerrrrrrrr

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#4146]
## Objectives
To test different concepts for Work Preview component

## User Story
- I want to know what it is and how it looks
- I want to know if it's relevant to my research at a glance

## Concept 2
To provide "feel of the book" by displaying all images of the item and allowing users to flick through the images

![item_multiimages](https://user-images.githubusercontent.com/29206031/53348641-5d0ff700-3913-11e9-94fa-9a5b8b1ff75a.jpeg)
- allow users to peak through the item before making the decision to view full image
- visual representation of the item (friendly to non-academics)

Design
https://zpl.io/2GyynNd

Questions
- Any impact to performance?
- Does it discourage users to view full image mode?
- Does it encourage to scroll down to view the information?
- Should we display key pages or all pages?

## Acceptance criteria
TBD

## Next Steps
- [ ] Prototype in the browser for user testing
- [ ] @GarethOrmerod to provide necessary design elements

## Open Issues
TBD

**Comment by jennpb** [comment]
We've ruled out this concept in preference for a static multi-image preview w/ CTA for full view.
