### ISSUE TITLE
AB test: Generic Work Card

### ISSUE THREAD

**Issue by hthair** [wellcometrust/wellcomecollection.org#4168]
## The problem: We think that...
we need to create a generic way of displaying results within collections that covers more than just image results. 

## Therefore we hypothesize that...
changing the work card display to a thumbnail with information along side will provide a better generic way of displaying information for all work types. We hope that this won't lower the CTR of people viewing work results. 

## As measured by...
% of click through from results list to view work ID page. (we can use our event tracking to count number of clicks on a work card/promo, and divide this by results pages viewed) Current conversion = 43% of search result pages had a click through. 

## Acceptance criteria: we are right if...
this number doesn't drop showing we haven't made click through's worse (haven't made results harder to understand if they might be relevant to the user).

**Comment by jamesgorrie** [comment]
There is a light annoying thing that the event is going to be called `WorkPromo`on control and `WorkCard` on the  test to ensure we move forward with the new naming conventions.

Shouldn't be too hard to get into Datastudio

**Comment by jamesgorrie** [comment]
@hthair shall we put your findings on this card and close it off?

**Comment by hthair** [comment]
Link to summary card: https://wellcomecloud.sharepoint.com/:p:/s/wcdigitalexperience/EcPj-hWyZhdOmuPngDpqiDEBGxILHEfnXLKvvgI9Gursaw?e=T8GqkT

Results: 
A = 1.3 avg. click on results per search
B = 1.2 avg. click on results per search
Not sig. different as measured by an independent t-test

@jamesgorrie test can be turned off now and issue closed.

**Comment by jamesgorrie** [comment]
@hthair was that card created retrospectively?
GitHub and the card were the same at some stage.
