### ISSUE TITLE
Allow for selection of queryType on the catalogue API

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#4194]
As a __researcher on the experience team__ I would like __to test different query types on the catalogue search to assess what the best way to weight relevance might be__.

We will be able to do this:
- [ ] When we have a way to select the different query types and put it in front of the people using our service.

## Notes
* [The work on the catalogue API has been done here](https://github.com/wellcometrust/catalogue/pull/14)

**Comment by jamesgorrie** [comment]
Based on a few conversations around algorithms and surfacing to users why you're getting what you're getting, I noticed the library search does this quite clearly.

http://catalogue.wellcomelibrary.org/search~S12/Y?searchtype=Y&searcharg=mary+bishop&searchscope=12&searchscope=12&SORT=D&words=mary&words=bishop

![Screenshot 2019-03-28 at 16 00 18](https://user-images.githubusercontent.com/31692/55172924-be292580-5172-11e9-9224-d61c0320cef4.png)

**Comment by pollecuttn** [comment]
The five categories in descending order of relevance/Right Results (c) are:
[search term] found in main title of [entries x of y]
[search term] found in subtitle or author of  [entries x of y]
[search term] found in chapter title, imprint, subject heading, or note of [entries x of y]
All search terms found in title field of [entries x of y]
All search terms found in catalogue record of [entries x of y]

**Comment by jennpb** [comment]
Comments re: relevance have been copied to #4363

**Comment by jennpb** [comment]
@wellcometrust/experience-devs Can we get this behind a toggle please?

**Comment by jamesgorrie** [comment]
@jennpb https://github.com/wellcometrust/wellcomecollection.org/pull/4358

**Comment by jennpb** [comment]
MEGA thanks @jamesgorrie
