### ISSUE TITLE
Expose workType `v` e-books

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4198]
## Who it's for
People who will be searching for books (available online in viewer) on wellcomecollection.org

## Problem to be solved
We currently only include workType `a` for Books, but this excludes all of the digitised books we've ingested from other libraries. By adding `v`, we increase the total number of books available to search in our next release.

## User Story/Job
- When I search the library's collections for books, I want to be sure I'm finding everything that's available to me.

**Comment by jamesgorrie** [comment]
@jennpb do we also want to lose the filter that only returns `DigitalLocation`s?
