### ISSUE TITLE
Move logo back to centre (from right)

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4260]
The logo in the global nav has been moved to the right (was this intentional?) and it's overlapping with 'Free' label on Exhibition and Events.

I suggest we move the 'Free' label to above the hero image to make it more noticeable and revisit the global nav when we tackle the navigation.

 (![IMG_5137](https://user-images.githubusercontent.com/29206031/54345405-e83efb80-463a-11e9-9b99-0f21c43a86f2.png)

**Comment by jennpb** [comment]
Can I suggest the label movement happens separately to bug fix please? We have the label movement logged here, along with other research questions relating to the free messaging: https://github.com/wellcometrust/wellcomecollection.org/issues/3517

**Comment by Heesoomoon** [comment]
@jennpb Are you suggesting that we move the logo back to the center as it was originally for now?

**Comment by jennpb** [comment]
Yes, I don't know why the logo would have moved. It certainly wasn't a design decision.
