### ISSUE TITLE
Article - Element spacing

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#427]
Some images in articles are bumping really close to images. There should always be 30px space in between any element e.g. paragraph, image

<img width="738" alt="screen shot 2017-02-01 at 15 15 11" src="https://cloud.githubusercontent.com/assets/23660297/22512712/c930bd2c-e891-11e6-8c67-73a5486bfed0.png">

**Comment by jamesgorrie** [comment]
@Norvard - I think this was an issue with the way WP was sending copy to us. Has this been fixed?
https://next.wellcomecollection.org/articles/queer-territory-claude-cahun-and-a-land-without-labels

**Comment by jennpb** [comment]
@jamesgorrie No, it looks like that specific issue still stands.

**Comment by davidpmccormick** [comment]
![screen shot 2017-02-23 at 10 38 11](https://cloud.githubusercontent.com/assets/1394592/23255852/f6d1a55a-f9b4-11e6-9a2c-4ef1a8a9a288.png)

This specific issue is the result of the paragraph of text above the image not being contained in a `<p>` tag (which would give it some bottom-margin). As @jamesgorrie says, this is the result of the way the data's being delivered to us from WP. Don't know if there's anything we could do at our end to auto-wrap instances of text like this in `<p>` tags – not sure how we'd determine whether or not they should be wrapped (and possibly overkill given it won't be an issue when we move away from WP). Perhaps @RussellDornan can fix this instance in WP (give a shout if it needs clarifying).

**Comment by jennpb** [comment]
You're right @davidpmccormick it's probably not enough of an issue to worry about it just now. Just one more reason for us to move away from WP as soon as we can.

**Comment by jennpb** [comment]
@RussellDornan don't worry about editing this instance in WP! I'm just going to close this issue, but it's just something to be aware of in this transitional time.
