### ISSUE TITLE
How should we handle items with multiple authors and production events?

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4280]
## Problem to solve
Some works have multiple production events. How do we decide which is the primary one? How do we keep all dates from bunching up in the header, like this one?

https://wellcomecollection.org/works/k8anyfdd

<img width="720" alt="Screen Shot 2019-03-18 at 16 07 50" src="https://user-images.githubusercontent.com/1446139/54545661-ff168280-4999-11e9-848c-b132e010600c.png">

**Comment by jennpb** [comment]
After discussion with @jtweed about data cleanup, we established that:
- the first contributor in a list of contribs
- the first production date in a list of dates
are the most meaningful, and we should limit to displaying those in the header and at the card level.

This will simplify the presentation, but still allow for the full list of contributors to be shown in the item detail.

**Comment by jennpb** [comment]
See #4452

**Comment by davidpmccormick** [comment]
From #4461:

![Screenshot 2019-05-14 at 10 21 37](https://user-images.githubusercontent.com/1394592/57686803-299b5980-7632-11e9-81cc-3dd8f143ba72.png)
