### ISSUE TITLE
Back to results from a work doesn't return you to where you were in search results list

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#4289]
## Problem
1. Run a search e.g. https://wellcomecollection.org/works?query=mouse

1. Scroll to the bottom of the page

1. Click through to view the last work

1. Use the back button to go back to the list of search results: you get dropped somewhere near the top of the results but not the work you clicked on.

This only seems to be a problem clicking to a work further down the results list - the first 15-20 seem to behave as expected: you go back to where you were in the list.

This was tested with no toggles on and before books were made available on works

## To do
Return the user to the place in the search results list where they came from when clicking back from a work

**Comment by davidpmccormick** [comment]
Possibly related: #3877

**Comment by davidpmccormick** [comment]
Sounds like: https://spectrum.chat/next-js/general/clicking-browsers-back-button-page-scrolls-before-back-navigation-is-done~3d65b436-b085-4eef-ad84-0941c473e09d

…where the page to go back to is shorter than the current page, the furthest down the page you end up after clicking the back button is the height of the page you went back from.

**Comment by Heesoomoon** [comment]
@davidpmccormick I experience how irritating this is this week. Is there some creative solution for this? Users mention they open new tabs from search results. However, for those who don't, they will feel lost...

**Comment by jennpb** [comment]
@pollecuttn When you have some time could you check to see whether this is still happening now that we show fewer results per page?

**Comment by pollecuttn** [comment]
@jennpb Still a bug

- Search https://wellcomecollection.org/works?query=mouse
- Scroll to the bottom of the page
- Click through to view the last work
- Use the back button to go back to the list of search results: you get dropped somewhere near the top of the results but not the work you clicked on: 'Toxocara lava', result no. 10
---
- Search https://wellcomecollection.org/works?query=mouse&page=2
- Scroll to the bottom of the page
- Click through to view the last work
- Use the back button to go back to the list of search results: you get dropped somewhere near the top of the results but not the work you clicked on: 'Early mouse embryo preimplantation, LM', result no. 9
---
- Search https://wellcomecollection.org/works?query=cats
- Scroll to the bottom of the page
- Click through to view the last work
- Use the back button to go back to the list of search results: you get dropped somewhere near the top of the results but not the work you clicked on: 'Health and dietary care for cats & kittens', result no. 15
---
- Search https://wellcomecollection.org/works?query=cats&page=2
- Scroll to the bottom of the page
- Click through to view the last work
- Use the back button to go back to the list of search results: you get dropped somewhere near the top of the results but not the work you clicked on: 'Feline parasites', result no. 9

**Comment by davidpmccormick** [comment]
There appear to be a handful of approaches mentioned on [this issue](https://github.com/zeit/next.js/issues/3303) that we could/should try out.
