### ISSUE TITLE
Document the good, the bad, and the ugly of the current and idealised Prismic model

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#4294]
## Objective
Have a model that is universally understood, and easy to pick up if you are new to the project.

## TODO
* Distill all the learnings from the past couple of years of working on the Prismic model
* Codify any concepts that have arisen or arise in the above exercise
* Document `partOf`
* Have a visual representation of the above
* See if we can start getting any old Prismic content into the agreed shape, and have a process to do this repeatedly 

## Documentation (to be put somewhere more accessible)
We currently have a few shared, and composable data structures.
I am going to use `Thing` for lack of a better word, as `Work` isn't generic enough.

### `Thing`
- `title`
- `format`
- `body`
- `partOf`
- `promoText`
- `promoImage`
- `metadataDescription`

### `ContributedThing`
- ... `ThingFields`
- `contributors`
  - `contributor`
  - `role` 

### `LocatedThing`
- ... `ThingFields`
- `places`

### `TimedThing`
- ... `ThingFields`
- `times`

- [ ] Go through #4295 with @wellcometrust/experience-devs to see if we can progress with it, or if we leave it for another time.
- [ ] Go through with @wellcometrust/experience-devs to have a shared understanding.

**Comment by pollecuttn** [comment]
@jamesgorrie Is this still waiting for https://github.com/wellcometrust/wellcomecollection.org/pull/4295 to be reviewed before this issue can be closed? Or can this be closed now?

**Comment by jamesgorrie** [comment]
@pollecuttn yip - if @wellcometrust/experience-devs want to find some time we can go through and see if it's worth it?

This ticket is also referencing other things, I've added to todos to it.

**Comment by pollecuttn** [comment]
Next time some modelling work comes up we will need to carve off some time to do this properly.
🥇
