### ISSUE TITLE
Book viewer enhancements

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4325]
## Who it's for
Researchers using digitised books

## Background Research
https://docs.google.com/document/d/1ub_JfbzVln62-QtNtHANHhEurmwN51EQR66dH6CWj8c/edit?ts=5c9a4e15#

## Success measures TBC
- Has viewing time increased?
- Breadth of material accessed
- have more specific items viewed
- reduce the long tail for collection material access
- More downloads

## Recommendations
MEDIUM Viewer: ability to zoom in/out
MEDIUM Viewer: ability to jump to specific page
MEDIUM VIewer: display more thumbnails to make it easy to scan for relevant content and reduce the number of clicks
MEDIUM Viewer: option to view single page or double pages to expedite the scanning 
MEDIUM Viewer: Search within a document
LOW Viewer: ability to rotate

**Comment by jennpb** [comment]
Before we do anything on this, I would like to have baseline numbers for:
- Use of zoom on current single-image works
- Average depth of page views in current full view. This could be based on number of 'page canvas' views / number of works viewed.
@hthair Can we get this information this week please?

**Comment by hthair** [comment]
Jan 1st - Mar 31st:
single image works:
- Zoom in: 9605
- Zoom out: 7189

**Comment by hthair** [comment]
depth:
Number of pageviews in the book viewer = 20444 divided by 1406 times the book viewer was launched (estimate of number of times viewed or times a book was 'taken off shelf') 
=
20444/1406 = 14.54
On average each book had 14.5 pages viewed.

**Comment by jennpb** [comment]
@hthair 

I don't think I asked my question in the right way, now that I see the numbers!

For zoom, I guess my question would be what percentage of works viewed resulted in zoom? 

Is this a better way to get a baseline against a moving target (i.e. we'll always be adding more works, so the metric needs to be proportional)

**Comment by hthair** [comment]
@jennpb When we've got the new datalayer in I'll be able to work this out. Currently I could give you the % use of the zoom in button but it's across ALL works (inc. books) so it'll come out inaccurate. But with the datalayer we'll be able to get the number of work items viewed of a particular work type to then calculate % of zoom used.
