### ISSUE TITLE
API things that need looking at

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#4331]
**Nice to have**
- When an item is unstructured, we pull the first image then random images. Some works like this one have many blanks pages. It will be nice to detect and display only the images with some content.
https://wellcomecollection.org/works/pnuqt4gt

**Comment by jennpb** [comment]
~- Images rotated sideways 
(note: from Ashley "Looking at here https://archive.org/details/b28064732 it looks like the book is bound vertically  so it was shot in the Scribe that way but the images weren't flipped.")
https://wellcomecollection.org/works/t8653qqz?query=optics&workType=a%2Cv~

Ashley will ask Internet Archive to reorient, then Production will reingest. No action needed from us.

**Comment by jennpb** [comment]
- Contributors with multiple parts are cut off after the first one, e.g. `Great Britain. Department of Health` becomes `Great Britain.`:
https://wellcomecollection.org/works/g829snzf http://search.wellcomelibrary.org/iii/encore/record/C__Rb3001164?lang=eng

Fixed by #4452
