### ISSUE TITLE
Works we can't view in the viewer

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#4333]
## Problem

- We have works returned in search results that aren't viewable in the current viewer (e.g. PDFs, multi volume works)
- Without making a second API call for the manifest of a work (which we don't want to do on the server), we can't know whether or not the viewer is able to display the work.
- This means we currently have links to the viewer, that result in an error.

## Examples
- e-book (pdf)
no thumbnail in the results, no preview, no download option
https://wellcomecollection.org/works/pscn63yg?query=darwin

- e-book (pdf)
no thumbnail in the results, no preview, with download option
https://wellcomecollection.org/works/k3e2r5vg?query=health

- Picture (pdf)
no thumbnail in the results, preview in Works, a single image in the new viewer
https://wellcomecollection.org/works/erj9qkhq?query=health

## Solution

- [x] We already replace the viewer and rely on a browser's PDF viewer, if the item is a PDF (#4320), but this was put in quickly so want to tidy up the code / cross browser check a bit more.

- [x] Write a function that determines whether the works manifest is compatible with the viewer OR can make use of a browsers in built PDF renderer.

### With javascript available

- [x] Use the function on the work page to suppress the preview/link to the viewer if necessary
- [x] Potentially, provide a message to the user to let them know we are currently unable to offer a view of this work. (@Heesoomoon - what do you think, should we message this explicitly?)

### Without javascript available

- [x] We will have to provide the link, so the viewer page should make use of the function to let the user know we are unable to render the item rather than causing an error.

**Comment by jamesgorrie** [comment]
> provide a message to the user to let them know we are currently unable to offer a view of this work.

The reason for suggesting this was to let people know this is part of the beta work, and that it will update. It would be a shame for someone to use this, and then think that we just don't have it.

**Comment by Heesoomoon** [comment]
Yes, it seems like it wouldn't hurt to display the message in this case till we come up with a more elegant solution.

Just as a side note, few participants have mentioned they would prefer to know if some information is unavailable so they don't go on while goose chase and waste their valuable research time.

**Comment by gestchild** [comment]
@Heesoomoon any thoughts on what the messaging should be and how it should look?
