### ISSUE TITLE
Tag heights misbehaving

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4335]
Weird little sizing problem

The first tag is taller than the second two
https://wellcomecollection.org/works/gzp82jdw

![screenshot-wellcomecollection org-2019 03 26-12-58-00](https://user-images.githubusercontent.com/1446139/54998834-f68c0080-4fc6-11e9-8e82-b2844448d998.png)

And the first two on this one are the same, but the third is shorter
https://wellcomecollection.org/works/mbvg2za7

![screenshot-wellcomecollection org-2019 03 26-13-00-40](https://user-images.githubusercontent.com/1446139/54998922-2e934380-4fc7-11e9-9e8d-1f5cc48d1715.png)

**Comment by davidpmccormick** [comment]
I'm guessing there's some disparity in the line-heights of the medium and light weights of the font, so the tags with some light type end up bigger.

Is this Safari on a Mac? I don't see it in Safari or Chrome.

**Comment by pollecuttn** [comment]
@davidpmccormick I see it on Chrome on Windows.
