### ISSUE TITLE
Additional data about works into GA

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#4341]
## Who it's for
The team to get a better understanding about the works being accessed on the website.

## Problem to be solved
Capture more information about the  work pages being viewed in GA

Need to answer the following and fill out the rest of the issue template:
- [x] Which data do we want to capture?
  - workType
  - identifiers
  - subjects
  - genres
  - language 
- [x] Which GA property do we want to use?
  - Wellcome Collection and Library
- [x] How should we implement, in code or using Tag Manager?
  - Data Layer and Tag Manager
- [x] Do we want to use custom dimensions and/or experiment with enhanced ecommerce tracking?
  - will use custom dimension (TEST first) that uses the data layer to pass the value

- [x] Set custom dimension values from the data layer in Tag manager
- [ ] Use custom dimension as data source in data studio

**Comment by jennpb** [comment]
I'm wondering if this approach is the right one, given that GA only gives us a sample of activity.

What we need to be able to do is track usage (e.g. pageviews, events such as download) on `/works/` and then pair it up with the actual characteristics of the work: what kind of thing it is, identifying information, etc.

The goal of this is to provide internal insight into the types of things and collections being actively used, as this helps our Collections teams to do their work better. 

Pair this with #3737

**Comment by jamesgorrie** [comment]
@jennpb I've added a PR above which would supply those values into the search tracking.

There is a bigger, and hopefully better, solution, which would be to cross query the catalogue index with the search reporting index.

This would allow us to do things as aggregating the data above as requested, but also start to look at things like seeing what search terms are often used for a work to be viewed, or set of works e.g. "Books are more often chosen when 'books' is in the search terms", "f someone searched for a subject, they are more likely to view a result that has that subject", or "images are normally viewed when using short search terms".

**Comment by taceybadgerbrook** [comment]
This ticket has been split into:-
https://github.com/wellcometrust/wellcomecollection.org/issues/4836
https://github.com/wellcometrust/wellcomecollection.org/issues/4837
https://github.com/wellcometrust/wellcomecollection.org/issues/4838
