### ISSUE TITLE
Search input: missing keywords

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4342]
When you land on the search results after clicking on one of the tags under 'Feeling curious', the search input field only displays the instruction and doesn't display the keyword. However, if you click on one of the work, the keyword appears. 

**Expected Behaviour**
When users click on a tag, the search input field should display the keywords so they know what the result is about and they can modify the keywords to refine the results.

**Search results**
![Screen Shot 2019-03-27 at 17 15 53](https://user-images.githubusercontent.com/29206031/55098133-2d404480-50b5-11e9-9f31-e4c74a3057d3.png)

**Works page**
![Screen Shot 2019-03-27 at 17 19 20](https://user-images.githubusercontent.com/29206031/55098132-2d404480-50b5-11e9-85af-e5ac7cc27c28.png)

**Comment by jamesgorrie** [comment]
@wellcometrust/experience-devs [here's the line that does it](https://github.com/wellcometrust/wellcomecollection.org/pull/4336/files#diff-d58fb56fcd657f01f4c7d319500bfbb6R91)

**Comment by Heesoomoon** [comment]
@wellcometrust/experience-devs It might be worth treating the search input field as a component and discuss what it contains and how it scales across Works. I'll bring it up during the planning session.

**Comment by jamesgorrie** [comment]
@Heesoomoon it is a component, it more about how we deal with state across the application (where it comes from and how we retrieve it).

There is a second part of this conversation about storing sensitive state in the URL, and the implications of that (or not doing that) - happy to feed back on that, but probably better in person, or you can read it as part of the [draft RPC here](https://github.com/wellcometrust/wellcomecollection.org/blob/0c856f8b6fd157e09c6ef497f96e561c8792bd7c/docs/rfcs/001-url_strategy/example_strategy_document.md#parameters).

> scale

When you say scale, do you mean visually, or technically? If technical what are your concerns?

**Comment by Heesoomoon** [comment]
@jamesgorrie In terms of scale, it's more to do with the functionality. A few weeks back, we briefly talked about the concept of 'full' and 'compact' mode of the Search component. The full mode will have all the necessary features (input, filters, etc.) and used in search results. And the compact mode will provide quick access and used in other pages where the search isn't the primary purpose of the page.

**Comment by Heesoomoon** [comment]
@davidpmccormick @jamesgorrie I was checking this bug before closing it. However, it's now showing original search keywords rather than the keywords from the tag. 

How to reproduce
1 Search for 'Darwin', click on the first result 'Charles Darwin, portrait'. 
2 Click on 'Portrait Prints' under Type/Technique. The search input still displays 'Darwin'.
https://wellcomecollection.org/works?query=%22Portrait%20prints%22
![Screen Shot 2019-04-04 at 12 44 30](https://user-images.githubusercontent.com/29206031/55553345-d1d70d80-56d7-11e9-93f1-0aaae2ce2842.png)

**Comment by davidpmccormick** [comment]
@Heesoomoon I've just followed the steps to reproduce in your last comment and I'm seeing it working as expected ("Portrait prints" in the search box). Can this be closed?
