### ISSUE TITLE
Works Preview Exploration: Works Examples

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4344]
## Purpose
@GarethOrmerod is exploring the design of Preview to scale for different work types (text-based and visual). These examples help us to consider different formats and form factors we will need to consider.

## Text-based materials
**Books**
- https://wellcomelibrary.org/item/b22425123
- Old, foreign book https://wellcomelibrary.org/item/b10187650
- Landscape https://wellcomelibrary.org/item/b2928773x
- Multiple volumes https://wellcomelibrary.org/item/b18031511

**PDFs**
- https://wellcomelibrary.org/item/b29823547
- https://wellcomelibrary.org/item/b28636028
- https://wellcomelibrary.org/item/b21248710

**Manuscripts**
- Foreign language https://wellcomelibrary.org/item/b20662944
- Different sizes https://wellcomelibrary.org/item/b14850151

**Journals**
- Chemist & Druggist https://wellcomelibrary.org/item/b19974760

## Visual materials
**Artwork**
- Painting https://wellcomelibrary.org/item/b12035282
- Lithograph https://wellcomelibrary.org/item/b16804065
- Front, back, side (@jennpb would you be able to provide an example for this?)
- Square format https://wellcomelibrary.org/item/b11734358
- Multiple images, no structural data https://search.wellcomelibrary.org/iii/encore/record/C__Rb1188422?lang=eng

**Photos**
https://wellcomelibrary.org/item/b11775105

**Posters**
- Landscape https://wellcomelibrary.org/item/b16637835

**Ephemera**
- Different sizes https://wellcomelibrary.org/item/b2868624x
- Landscape https://wellcomelibrary.org/item/b17263815
- Postcard https://wellcomelibrary.org/item/b20588094

**Objects**
- https://search.wellcomelibrary.org/iii/encore/record/C__Rb1588138__Shistory__Ff%3Afacetmediatype%3Ar%3Ar%3A3-D%20objects%3A%3A__Orightresult__U__X3?lang=eng&suite=cobalt#attachedMediaSection

## Other
Letters from archive
https://wellcomelibrary.org/item/b19307214

**Comment by jennpb** [comment]
Tom Crane has made this tool as well (using our content): http://tomcrane.github.io/wellcome-today/gallery/gallery.html.

I've crossed out Journals because we only have one digitised journal (Chemist and Druggist), and it's several hundred parts, and we will treat that entirely differently. There will be no such thing as a Journal preview (at least not in the same way). More likely to be a 'collection' page, with references to each volume that can then be opened separately.

**Comment by jennpb** [comment]
I've added Chemist & Druggist to the list just to cover the bases, even though it's outside the current scope of work.

Also added a multi-volume book: https://wellcomelibrary.org/item/b18031511
