### ISSUE TITLE
Viewer: images not loading properly

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4345]
I've noticed some images in the viewer don't display properly. However, it's very difficult to reproduce. When you return to the item, all pages tend to display. And there's no clear pattern for the type of items. It can happen on items with few pages or 400+pages.

It will be good to monitor to see how often this occurs on the user's end.

**Example**
https://wellcomecollection.org/works/yyxet42g
![Screen Shot 2019-03-28 at 16 35 32](https://user-images.githubusercontent.com/29206031/55176045-4c53da80-5178-11e9-8aaf-0370fc480faf.png)

**Comment by jamesgorrie** [comment]
This has been flagged with Digirati as it's a problem with DLCS.

From Adam Christie:
> I think I've isolated what's going on. It's to do with what happens when Varnish is trying to clear out some room in its LRU cache to store the image object. the cache consists of a mixture of large objects (tiles, images) and small objects (json responses for things like s3 keys for thumbs, results of whether an image has auth required, etc). When the cache eviction happens (as a precursor to storing an object) then there's a chance that the space will get used again before the full set of evictions (of many small files) are completed, leading the storage operation to fail and giving a 503. This is more likely to happen given the new profile of what is being stored in Varnish; namely larger full images instead of just tiles.

[We have also put error handling in sentry](https://github.com/wellcometrust/wellcomecollection.org/pull/4328). So far we have seen 31.

We can leave this issue to track the status with Digirati, but have little we can do about it without thinking about taking over the images from DLCS (which is a long way away).

**Comment by Heesoomoon** [comment]
@jamesgorrie Thanks for the update.
