### ISSUE TITLE
Rich representation of content on social media

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#435]
Jenn is looking into ways of making our content shine on social media platforms.
- Open Graph Protocol: http://ogp.me/
- Twitter cards: https://dev.twitter.com/cards/overview
~~- Pinterest: https://developers.pinterest.com/docs/rich-pins/articles/?~~ supported by schema.org

The current WC site uses both og and twitter markup, but this could be enhanced for specific media types.

**Comment by jennpb** [comment]
Nothing is currently jumping out at me as emerging best practice for social markup, so we'll implement Open Graph for articles and Twitter Cards (summary card). In future we can also look at Twitter Cards for video and audio, but that's not for now.

Properties for both in this document:

[SocialMarkup.txt](https://github.com/wellcometrust/wellcomecollection.org/files/747999/SocialMarkup.txt)

references:
OGP - http://ogp.me
Another good reference for OGP: https://developers.pinterest.com/docs/rich-pins/articles/?
Twitter Cards - Summary https://dev.twitter.com/cards/types/summary

@jamesgorrie @davidpmccormick @gestchild Shout if you want more information

**Comment by jennpb** [comment]
Also to note, we're a NO for watermarking as a way to identify image content off-platform.

**Comment by jamesgorrie** [comment]
> Twitter Cards for video and audio
👍

**Comment by jennpb** [comment]
Reopening this one for collection works! Let me know what information you need in order to make this work nicely.

**Comment by BethPF** [comment]
@jennpb do we need to do this to hit our first milestone of an internal release via a feature switch?

**Comment by jennpb** [comment]
@BethPF @pollecuttn No, I'll remove this from the R1 milestone.
