### ISSUE TITLE
Opening hours for galleries/library/cafe/restaurant/shop

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#4360]
Follow on work from https://github.com/wellcometrust/wellcomecollection.org/issues/3439#issuecomment-478541329

## Opening times page
- A new component to show opening hours:
Regular: list all hours per venue
Holiday hours: list all hours for the duration of the holiday (display two weeks prior)
Easter weekend (Friday-Sunday), Bank holidays (Saturday-Monday), Christmas & New year's (Christmas Eve–New Year's day)
- Library closures
list all closures dates for the year in advance
- Busy times 
Content card links to new 'Busy times' page

## Additional info
- Serving times for Wellcome Kitchen and Wellcome Café are not part of the component but are free text on the Kitchen and Café pages.
- Decided not to display the holiday messaging in the info banner to put less emphasis on physical building. We will explore a 'Visit us' card in the landing pages in future.

## Where to display
 All display on https://wellcomecollection.org/opening-times
* Library component also displays on https://wellcomecollection.org/pages/Wuw19yIAAK1Z3Smm
* Cafe component also displays on https://wellcomecollection.org/pages/Wvl1wiAAADMJ3zNe
* Restaurant component also displays on https://wellcomecollection.org/pages/Wuw19yIAAK1Z3Snk
* Shop component also displays on https://wellcomecollection.org/pages/WwgaIh8AAB8AGhC_
* Galleries and Reading Room component only displays on Opening times page

## Acceptance Criteria

- [x] All display on https://wellcomecollection.org/opening-times
- [ ] Library component also displays on https://wellcomecollection.org/pages/Wuw19yIAAK1Z3Smm
- [ ] Cafe component also displays on https://wellcomecollection.org/pages/Wvl1wiAAADMJ3zNe
- [ ] Restaurant component also displays on https://wellcomecollection.org/pages/Wuw19yIAAK1Z3Snk
- [ ] Shop component also displays on https://wellcomecollection.org/pages/WwgaIh8AAB8AGhC_
- [ ] Galleries and Reading Room component only displays on Opening times

**Comment by Heesoomoon** [comment]
@pollecuttn I've included the info for 'Serving times' above.

**Comment by Heesoomoon** [comment]
For the 'Upcoming holiday', we've decided against the text messaging. We are going to automate the process by listing out the opening hours for the duration of the holiday. This will minimise the workload by the content team and make it clear to the visitors. We plan to test the information display with users with dyslexia in future.

As an example, we will display following for the galleries during Easter bank holiday.
**Easter weekend**
Friday 19 April 10:00–10:00
Saturday 20 April 10:00–18:00
Sunday 21 April 11:00–18:00
Monday 22 April 10:00–18:00

**Comment by jennpb** [comment]
https://wellcomecloud-my.sharepoint.com/:w:/r/personal/j_phillips-bacher_wellcome_ac_uk/_layouts/15/Doc.aspx?sourcedoc=%7B2cbe77cc-9553-435e-858b-29bdc7a1e361%7D&action=default&cid=051c13b6-b088-400b-bf29-dc0787c66520

**Comment by Heesoomoon** [comment]
@gestchild Here's the latest update from the operations team.
## Easter
**Galleries and Reading Room**
Friday 19 April 10:00–18:00  
Saturday 20 April 10:00–18:00 
Sunday 21April 10:00–18:00 
Monday 22 April 10:00–18:00 
 
**The Library**
Friday 19 April Closed 
Saturday 20 April Closed 
Sunday 21April Closed 
Monday 22 April Closed 
 
**Wellcome Kitchen**
Friday 19 April 11:00–18:00  
Saturday 20 April 11:00–18:00 
Sunday 21April 11:00–18:00 
Monday 22 April 11:00–18:00 
 
**Wellcome Café**
Friday 19 April 9:30–18:00  
Saturday 20 April 9:30–18:00 
Sunday 21April 10:00–18:00 
Monday 22 April 9:30–18:00 
 
**Wellcome Shop**
Friday 19 April 10:00–18:00  
Saturday 20 April 10:00–18:00 
Sunday 21April 10:00–18:00 
Monday 22 April 10:00–18:00 

## Bank holidays (4-5 May, 25-27 May, and 24-26 Aug)
**Galleries and Reading Room**
Saturday [date] 10:00–18:00
Sunday [date] 10:00–18:00
Monday [date] 10:00–18:00
 
**Wellcome Library**
Saturday [date] Closed
Sunday [date] Closed
Monday [date] Closed
 
**Wellcome Kitchen**
Saturday [date] 11:00–18:00
Sunday [date] 11:00–18:00
Monday [date] Closed
 
**Wellcome Café**
Saturday [date] 9:30–18:00
Sunday [date] 10:00–18:00
Monday [date] 9:30–18:00

**Wellcome Shop**
Saturday [date] 10:00–18:00
Sunday [date] 10:00–18:00
Monday [date] 10:00–18:00

**Comment by Heesoomoon** [comment]
Here's the copy for the library closure dates.

**Library Closure**
The library will be closed on the following dates: 
Friday 19 April–Monday 22 April 2019 
Saturday 4 May–Monday 6 May 2019 
Saturday 25 May–Monday 27 May 2019 
Saturday 24 August–Monday 26 August 2019 
[Christmas closure TBD]
