### ISSUE TITLE
Opening hours: global footer

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#4361]
Follow on work from https://github.com/wellcometrust/wellcomecollection.org/issues/3439#issuecomment-478541329

Footer opening times to display, and change with the opening times of the day:

Today's opening times
Galleries 10:00-18.00
Library 10:00-18:00
Café 8:30-18:00
Restaurant 11:00-18:00
Shop 09:00-18:00
[Full opening times](https://wellcomecollection.org/opening-times)
Note: We will remove 'Wellcome' and use 'Restaurant' rather than 'Kitchen'.

## Additional updates to the footer
- remove the map to reduce the length of the footer and make the opening times more visible.
- add a link to '[Getting here](https://wellcomecollection.org/pages/WwabUiAAAHQXGNHB)' below the address
- add 'E: info@wellcomecollection.org' below the phone number
- remove 'Finding us:' and 'Opening times:' heading

## To do
- [x] Mock up of module for footer @GarethOrmerod 

## Acceptance criteria
- [x] Opening times display changes depending on the opening hours of the places each day

**Comment by Heesoomoon** [comment]
@pollecuttn It should also display a link to Opening times page. I've updated above.

**Comment by Heesoomoon** [comment]
@GarethOrmerod Here's the wireframe of what we've discussed.
![OT_AccessPoints](https://user-images.githubusercontent.com/29206031/55473597-f8794380-5606-11e9-88c7-74a79b7351a1.png)

**Comment by Heesoomoon** [comment]
@jennpb Here's the mockup from @GarethOrmerod 
Few thoughts
- I understand we don't want to redesign the footer at this point but the heading 'Finding us' and 'Opening times' seem irrelevant and redundant. Could we consider removing it?
- In the spirit of making things more 'linky', could we remove the image of the map (big and not useful) and replace with a link to '[Getting here](https://wellcomecollection.org/pages/WwabUiAAAHQXGNHB)'

![Opening times : BP Small - Irreg Quad](https://user-images.githubusercontent.com/29206031/55622694-d6afc600-5798-11e9-9a97-0ac35e616c0d.png)

**Comment by jennpb** [comment]
OK, just need to make sure that we're using the right language:

Galleries
Library
Kitchen
Cafe
Shop

**Comment by Heesoomoon** [comment]
@jennpb Who do we need to follow up to see if we can omit 'Wellcome' from kitchen, cafe and shop?

**Comment by jennpb** [comment]
Footer doesn't display 'Wellcome', but proper name (e.g. Wellcome Kitchen) should be used in places where we refer to its proper name, like on the Wellcome Kitchen page.

**Comment by Heesoomoon** [comment]
@wellcometrust/experience-devs The footer looks so much better! Thanks for the improvement. 
I just noticed a minor issue. The 'Getting here' link should be directly below the address and not below the email address.
