### ISSUE TITLE
IE browser issue: section header looks odd

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#4368]
The section header looks like this in Chrome:
![section-header-chrome](https://user-images.githubusercontent.com/1446072/55495393-b4049c80-5634-11e9-9b51-65ee8757bf17.PNG)

And like this in IE (IE 11 on Windows):
![section-header-ie](https://user-images.githubusercontent.com/1446072/55495366-a0f1cc80-5634-11e9-9482-a8d6cfbcb710.PNG)

I know pages don't look the same in every browser so this might be a won't fix.

**Comment by davidpmccormick** [comment]
Fixed in #4484
