### ISSUE TITLE
Upgrade Prismic API client configuration to TLS 1.2 by May 15 2019

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#4371]
## Problem to be solved
From Prismic:
Transport Layer Socket (TLS) is part of the HTTP socket secure layer that, among other things, prevent communication eavesdropping. 

Several serious vulnerabilities however affect the 1.0 and 1.1 versions of TLS. 
As a result, SaaS services providers, as well as web browsers editors and other Internet actors, are coordinating their efforts to remove TLS version 1.0 and 1.1 from their services and products.

**We have detected TLS 1.0 or TLS 1.1 is still in use for API queries on wellcomecollection.prismic.io** In order to avoid any disruption, we ask you to ensure to upgrade your API client configuration to force  use of TLS version 1.2, before May 15, 2019 at 00:00 CET.

Please let us know if you have any question and if we can assist you in this upgrade.

## Deadline
May 15, 2019 at 00:00 CET

Email:
[ACTION REQUIRED - TLS 1.0  1.1 discontinuation.txt](https://github.com/wellcometrust/wellcomecollection.org/files/3062782/ACTION.REQUIRED.-.TLS.1.0.1.1.discontinuation.txt)

Is this a data team thing for @jamesgorrie or experience for @davidpmccormick and @gestchild ?

**Comment by jamesgorrie** [comment]
It's an experience thing.
Odd as we use the Prismic SDK.

**Comment by davidpmccormick** [comment]
We've emailed Prismic for a little bit of clarification about this (we're fairly sure we've done what we should have to make sure our app is communicating with Prismic using TLS 1.2). We're thinking the < TLS 1.2 API queries could be the result of client-side requests (for e.g. content lists on `/whats-on` and `/visit-us`) from older browsers.

**Comment by davidpmccormick** [comment]
This from Renaud at Prismic:

> The user agent that i got for your old TLS versions is
> HggH PhantomJS Screenshoter
> 
> So it should be good for your website.
> 
> For the dev environment, we will perform a force routing http -> https; You should have all requests using the https protocol
> 
> Renaud

Sounds like we should be good.
