### ISSUE TITLE
Internal search relevance testing

### ISSUE THREAD

**Issue by hthair** [wellcometrust/wellcomecollection.org#4381]
We want to improve our search relevance by first testing 4 new search queries:
1) justboost
2) broaderboost
3) slop
4) minimummatch

To test this we're asking internal users of the collection to:
1) select a query type first
2) conduct 10 broad searches on topics they are reasonably familiar with in the collection
3) Rate on a scale of 1-4 how relevant the each result is (results 1 through 5) and put their scores in to the template spreadsheet. 
4) select the next query type and do the process again

We'd like them to do this by going in to view each work before determining relevance because of their familiarity with the collection. They may know why a result is being surfaced even though it might not apparent to all users. This will test how each search query performs in terms of relevance. (Rather than what we're displaying at the result list level, and how well that indicates relevance of the item - this is something we may want to do as a separate test with external users)

There are different ways we can then analyse the results. We could convert the numbers to match this scale (this will also be part of the instructions to help with defining a relevant result):

4 - relevant (completely relevant to be at this rank)
3 - near (not perfect but reasonable to be highly ranked)
2 - misplaced (reasonable to be retrieved but should not be this highly ranked)
1 - irrelevant (no apparent relationship to search term)

The above scale helps determine precision of each query; how reasonable is it for the query to return each result?
We can then rank each search query on strict or loose criteria e.g. how did each query perform in terms of providing 'relevant' queries from the scale above, or look at what percentage were relevant, near, or misplaced compared to displaying a high amount of displaced results. 

Next steps:
- [x] create spreadsheet template
- [x] pilot testing with team/Jenn
- [x] send out test with instructions
- [x] analysis data/agree analysis method with data team.

**Comment by jamesgorrie** [comment]
Ping @harrisonpim

**Comment by hthair** [comment]
Round one testing underway, emailed out to LE & E and C&R email lists. Deadline May 3rd.

**Comment by hthair** [comment]
Data handed over to Data team for analysis and insights to then create 'child' queries/next generation.

Need to have a discussion about how to move forward. We'd like to try AB testing a query data team think is better than what we have now and either decide a success metric or implement a rating system on the front end for visitors to use.
If we wanted a more general measure we could look at for A vs B what % are clicking on the top ten results (obviously this isn't always going to be valid e.g. people may click the first results anyway, but might be a good start)
