### ISSUE TITLE
Update Find Us

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#442]
- [ ] For the sake of completeness, we should add itemprop="addressCountry" to the schema markup, and display UK  below postal code. 

- [x] There shouldn't be a comma after 183 Euston Road. Please delete

Relates to https://cardigan.wellcomecollection.org/components/detail/find-us.html

**Comment by jamesgorrie** [comment]
It might make more sense if we started to use JsonLD (It's way less complex that adding it in the HTML) e.g:
```HTML
<script data-schema="Organization" type="application/ld+json">
  // Blah blah
<script>
```

**Comment by jamesgorrie** [comment]
Here's a recommendation:
https://yoast.com/json-ld/

**Comment by jennpb** [comment]
Yeah, I think there's a piece of work here relating to schema.org and json-ld. we should expect to need this markup for basics like organization, location, opening hours, but there's loads more Knowledge Graph stuff we could do with social media, articles, library materials and content. I put a placeholder issue in as #440 for discussion later on.

But if it makes sense to use JSON-LD now, we can start with the standard stuff and move on to more specific stuff.
