### ISSUE TITLE
Exposing work info on list and detail view for orientation

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#4444]
From https://github.com/wellcometrust/wellcomecollection.org/issues/4325

## Who it's for
Users who want an overview of the work, to help them orient themselves. This could be especially valuable to researchers who work across multiple tabs.

## Needs research
Needs research to understand what information about the work needs to be easily accessed from the view modes (list and detail view)?

Build into usability testing

## Acceptance Criteria
TBC

Primary info:

- Title
- Logo
- Back to overview

Secondary info:

- Title
- Author
- Date
- Type

**Comment by jennpb** [comment]
Borrow design pattern from Download component:
- Drop info down
- Keep viewer in view

**Comment by Heesoomoon** [comment]
@jennpb @GarethOrmerod 
Here's one way to simplify the interaction using familiar visual UI for different actions.
It's implying the page view is in the background and these three states are layered on top to provide more info, navigate or save.

**Thumbnail list**
![Viewer_List](https://user-images.githubusercontent.com/29206031/59688882-7b597580-91d6-11e9-821b-36f101d4998c.png)

**Item info**
![Viewer_Info](https://user-images.githubusercontent.com/29206031/59688880-7b597580-91d6-11e9-9856-c5442cdc6cee.png)

**Download**
![Viewer_Download](https://user-images.githubusercontent.com/29206031/59688876-7b597580-91d6-11e9-9c01-eb47df4aadb9.png)
