### ISSUE TITLE
Contributor labels expanding

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#4452]
We are now combining the Name, Prefix, Numeration and Date to the contributor labels.

You can see this by turning on the [staging API toggle](https://dash.wellcomecollection.org/toggles/index.html#toggle-useStageApi).

Some examples:
https://wellcomecollection.org/works?query=British%20medical%20journal&page=2&workType=a%2Cv

There will probably have to be considerations about how many contributors to show.

The order of the contributors is meaningful, i.e. the higher up the list, the closer the relation, the first one often the creator.

**Comment by pollecuttn** [comment]
> There will probably have to be considerations about how many contributors to show.

> The order of the contributors is meaningful

- [ ] First contributor only in the header and search results card
- [ ] All contributors in order on the /works page
