### ISSUE TITLE
Launch OpenSeadragon only after some user interaction

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#4454]
Instead of loading OpenSeadragon into every item viewer, we could display the zoom/rotate controls but only launch the OSD functionality at the point someone interacts with this, potentially saving 300kb of JS being downloaded to the user. We could also launch the viewer on scroll-wheel movement, mimicking OSD's behaviour.

**Comment by jamesgorrie** [comment]
It might also improve UX where we currently load in an image, there's a "loading" jump, and then we're in DZM.

**Comment by davidpmccormick** [comment]
This was done a while back – must have forgotten to reference the ticket.
