### ISSUE TITLE
Render attribution from `iiif-presentation` and fallback to `iiif-image` data

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#4464]
An example is:
https://wellcomecollection.org/works/d2mxjdkb

Where the
* `iiif-presentation` `attribution` is `Wellcome Library` (<= subject to change) ([data])(https://wellcomelibrary.org/iiif/b16691362/manifest])
* `iiif-image` `credit` is `ACT UP` ([data](https://api.wellcomecollection.org/catalogue/v2/works/d2mxjdkb?include=items))

We should always be using other data, if available, over MIRO / wellcome images data.

We should build an `Attribution` type and just create it accordingly.

**Comment by jennpb** [comment]
> We should build an `Attribution` type and just create it accordingly.

@jamesgorrie Is this something for the data team? Anything new to add? (relates to #4938)

**Comment by jamesgorrie** [comment]
Yip, this will be usurped by getting the copyright etc from the mets.
