### ISSUE TITLE
Supporting Boolean in search

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4467]
## Who it's for
Researchers

## Problem to be solved

Experienced searchers looking for comprehensive, targeted searching are attempting to use Boolean, which we don't currently make possible.

We need to decide how we want to provide Boolean searching, and how to help researchers know what is available to them.

## Current use

The library catalogue (catalogue.wellcomelibrary.org) allows Boolean operators:
```
To broaden your search, use OR between words.
Example: AIDS OR HIV

To exclude words from your search, use AND NOT between words.
Example: heart AND NOT disease

You can search for words that have the same beginning, eg. midwife, midwives, midwifery, by adding an asterisk * at the end of the stem.
Example: midwi* child* or infant*

You can use a question mark to replace a letter/letters in the middle of a word.
Example: wom?n will search for woman and women

Use near to specify words close to each other, in any order. Use before and after to specify word order, with any number of words in between. To search for the terms “near”, “before” and “after”, enclose them in quotation marks.

```

## TODO
- [ ] Analyse search logs to extract any boolean-like behaviours

**Comment by taceybadgerbrook** [comment]
Based on analysis of 44,000 queries, the most useful boolean functionality to highlight for researchers are operators, “+” and “*.”   

Here is a link to the analysis:  https://wellcomecloud.sharepoint.com/:w:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/Analysis%20of%20boolean%20researcher%20behaviour%20(ticket%204467).docx?d=w135359036d8546239ab1a1998183bee4&csf=1&e=ShCXjm

**Comment by jennpb** [comment]
Closing for now, but will revisit when we start to work on search tips
