### ISSUE TITLE
Articles: Reflecting contributor roles in bylines

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4479]
# Who it's for
Content team

# Problem to solve
The team are keen that bylines at the top of stories reflect roles as they’re allocated when they appear at the bottom (ie words by …. pictures by….) rather than just x and y as they currently appear here:
https://wellcomecollection.org/articles/XNGC5RAAAGwzbXK0

They wouldn’t normally credit an internal photographer with an external author commission, because it’s not clear who does what (in this case Kate was very happy to share the credit) and so our own photographers tend to get under-credited for their work. 

Here's one possible solution:
![Story Credits (002)](https://user-images.githubusercontent.com/1446139/57865038-cc033a80-77f4-11e9-99c4-5ec7a10917d7.jpg)

**Comment by dannybirchall** [comment]
There are currently 16 contributor roles, which are used for events etc as well as for editorial content

Performer
Printer
Conservator
Host
Researcher
Facilitator
Guide
Speaker
Artist
Scientist
Partner
Creator
Curator
Photographer
Editor
Collaborator

**Comment by dannybirchall** [comment]
Just a note to reflect that we've had a couple of complaints from writers about joint credits in the current form; which has meant taking photographer  credits off some stories

**Comment by jennpb** [comment]
Discussed this with @dannybirchall and @GarethOrmerod.

The best solution from an editorial point of view is to be able to highlight the output:
Words by **Ian Curtis**
Illustrations by **Peter Saville**

This is also conventional across editorial sites (as in this example from WaPo)

![Washington Post](https://user-images.githubusercontent.com/1446139/61637987-6c138f00-ac90-11e9-8ce0-a232cb6b24c4.png)

To do this, we'd need to be able to extend the Contributor model to include not just the role, e.g. Photographer, but also the output, e.g. Photos.

Author > Words
Photographer > Photos
Illustrator > Illustrations

@jamesgorrie @gestchild @davidpmccormick How does this sound?

**Comment by jamesgorrie** [comment]
> To do this, we'd need to be able to extend the Contributor model to include not just the role

Assuming we mean extending the `ContributorRole` model to have some rendering information with it e.g. `contributor.role.describedBy` or something - and this sounds great.

**Comment by dannybirchall** [comment]
That makes sense to me. We can easily provide a list.

**Comment by davidpmccormick** [comment]
> There are currently 16 contributor roles, which are used for events etc as well as for editorial content

Should 'Author' be on that list, or are authors 'Creators', or 'Editors' (or something else)?

A list would be useful, yes please. Would there always be a 1:1 mapping from role to description? I'm thinking 'Scientist' and maybe 'Artist' could prove to be problematic. Maybe not, though.

**Comment by jamesgorrie** [comment]
> …And if the mapping was 1:1, would the need for a contributor.role.describedBy field go away?

Why - if the role description / rendering text is mapped to the role, you would store it with the role? Unless I've misunderstood what you've suggested.
