### ISSUE TITLE
Rendering multi-manifest works

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4483]
## Who it's for
Collections researchers

## Problem to be solved
We can't currently render works with multiple volumes, or in the IIIF world, multiple manifests. 

We also can't filter multi-vol books out from the current e-book filter, which has meant a temporary solution that is already past its sell-by date (#4333) 

https://wellcomecollection.org/works/pscn63yg?query=darwin

![screenshot-wellcomecollection org-2019 05 17-13-40-06](https://user-images.githubusercontent.com/1446139/57928653-51482700-78a9-11e9-9d69-8892a8332a35.png)

## The Content

![IMG_2089](https://user-images.githubusercontent.com/1446139/61546696-d1be0c00-aa41-11e9-86e9-deeb9ef62211.JPG)

A IIIF Collection is a set of manifests
A manifest equates to a volume/part; it's a sequence of canvases (which can be grouped in ranges) where the label is the title of the part.

These are:
- Multi-volume books
- Video with transcripts
- Journals (Chemist & Druggist currently the only one, and out of scope for now)

## Acceptance Criteria
- Work page shows how many manifests available to view online
- User can jump to a volume from the full view
- Interface shows what part/volume is in view

## TODO
- [x] Change alert text to July 2019
- [x] UX Design work to consider work preview and viewer

## Other Considerations
- We need to design for missing volumes. Not all volumes of every m-v work have been digitised

**Comment by Heesoomoon** [comment]
Would this apply to multi-section manuscripts? Who would be good person to follow up to get a sense of these items and how they are currently represented on WL.org?

**Comment by jennpb** [comment]
Me, probably? 
As far as how the data structure is created, Christy, Harkiran and Ashley.
As far as subject expertise goes, Elma is your woman.

Not all manuscripts have multiple parts.

Single:
https://wellcomelibrary.org/item/b18934717

Multiple:
https://wellcomelibrary.org/item/b19553146
https://wellcomelibrary.org/item/b19241380

Full list from catalogue: http://search.wellcomelibrary.org/iii/encore/search/C__Sdigwms__Ff%3Afacetlocations%3Aelro%3Aelro%3AOnline%3A%3A__Orightresult?lang=eng&suite=cobalt

**Comment by jennpb** [comment]
I'm going to move these comments into a new issue ⬆️

**Comment by Heesoomoon** [comment]
10 July
Here's the wireframe based on the team discussion yesterday. I reviewed with @GarethOrmerod. He's going to explore
- Preview of multi-volume book
- Preview of multi-volume book (partially digitised work)
- Preview CTA
- View List/Detail: controls and labels

![MultiVolume](https://user-images.githubusercontent.com/29206031/60960338-bb0d0c00-a301-11e9-80d6-f488a5a8cd21.png)

**Comment by GarethOrmerod** [comment]
Links to design updates relating to Design Review 11.07.19
Desktop:
zpl://screen?sid=5d27595b6ca7dc9d9b17dfa1&pid=5aab926b4b6efde01259e959
zpl://screen?sid=5d27595b66f79c9d6409ed8f&pid=5aab926b4b6efde01259e959
Mobile:
zpl://screen?sid=5d27595b22ffa26afacf66a6&pid=5aab926b4b6efde01259e959

**Comment by Heesoomoon** [comment]
@GarethOrmerod Here's the exploration for the view controls. Let's chat on Monday.
![WC_ViewControls](https://user-images.githubusercontent.com/29206031/61071300-a0718a80-a408-11e9-9f30-c7e971988923.png)

**Comment by jennpb** [comment]
As of 12/7/19:

Volumes | Number of things
---------- | -------------------
1 | 248199
2 | 2762
3 | 696
4 | 379
5 | 182
6 | 103
7 | 55
8 | 47
9 | 24
10 | 19
11 | 9
12 | 12
13 | 6
14 | 2
15 | 6
16 | 7
17 | 1
18 | 9
19 | 2
20 | 3
22 | 2
27 | 1
28 | 1
29 | 1
35 | 1
36 | 2
38 | 1
43 | 1
55 | 1
59 | 1
67 | 1
6425 | 1

**Comment by Heesoomoon** [comment]
@jennpb Thanks for getting this data. Does it include just materials available in the current API or other work types like journals? Do you know which work has 6425 volumes?

**Comment by jennpb** [comment]
This is the entirety of the collection that's been digitised, so archives, video, audio, journals, manscripts, books, etc. We only have one journal digitised, and that's the 6425 Chemist and Druggist. 

Tom has just alerted me to the fact that we do have some videos that are multiple-manifestations, where the video is one and the transcript is another. We'll need to accommodate this somewhere.

For the avoidance of further confusion, I've changed 'volumes' to 'Manifestations' (that's in the IIIF).
