### ISSUE TITLE
GA Data for works

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4489]
@hthair Would you collect following data for past 6month?

For users accessing
- WC.org Collections section (Works/)
- WL.org Catalog Search

% Data for
- Device: desktop, mobile, tablet
- OS for desktop users
- Screen resolution

**Comment by jennpb** [comment]
@Heesoomoon Do you want to use your new GA skills to dig out this data, or would you like me to? @hthair has too much on her plate!

**Comment by Heesoomoon** [comment]
I'll take that as a challenge and spend some time tomorrow afternoon.

**Comment by jennpb** [comment]
@Heesoomoon Is this still worth doing? If not, can you please close it?

**Comment by Heesoomoon** [comment]
I think it'll be good to do this at some point. Perhaps we can postpone till we have the analyst onboard?

**Comment by taceybadgerbrook** [comment]
The graph below shows the majority of traffic to works is from desktop users with usage declining during August (note:  graph lumps desktop top and tablet users together.)

![image](https://user-images.githubusercontent.com/32418070/64679747-43c83580-d474-11e9-953b-583ff740e09c.png)

The graph below shows traffic to catalogue search.  While desktop users are still in the majority, usage seems to have surged during August and with the exception of 1 September, looks to be maintaining this level.

![image](https://user-images.githubusercontent.com/32418070/64680799-622f3080-d476-11e9-8f92-d221d4f73a75.png)

**Comment by taceybadgerbrook** [comment]
**OS:**

The table below shows that users access both Collections and Library using Windows more than Macintosh.


  | Mac | IOS | Windows | Android
-- | -- | -- | -- | --
Collection | 13.7 | 32.9 | 26.9 | 24.6
Library | 15.9 | 20.1 | 42.8 | 19.1

Here's more detail on both Collections and Library operating systems:


Collection |   |  
-- | -- | --
1 | iOS | 32.9%
2 | Windows | 26.9%
3 | Android | 24.6%
4 | Macintosh | 13.7%
5 | Linux | 0.7%
6 | Chrome OS | 0.7%
7 | (not set) | 0.5%
8 | Windows Phone | 0.0%
9 | BlackBerry | 0.0%
10 | Playstation 4 | 0.0%



Library |   |  
-- | -- | --
1 | Windows | 42.8%
2 | iOS | 20.1%
3 | Android | 19.1%
4 | Macintosh | 15.9%
5 | Chrome OS | 1.2%
6 | Linux | 0.6%
7 | (not set) | 0.2%
8 | Windows Phone | 0.1%
9 | BlackBerry | 0.0%
10 | Samsung | 0.0%

**Comment by taceybadgerbrook** [comment]
Usage patterns by device for 6-month period 1/3/19-10/9/19 show that most use a desktop device:

Collection (unique views, works + works/) 


Device   type |  
-- | --
desktop | 81.5%
mobile | 14.5%
tablet | 4.0%

Library


Device   type |  
-- | --
desktop | 83.1%
mobile | 16.9%

**Comment by taceybadgerbrook** [comment]
Usage patterns by operating system for 6-month period 1/3/19-10/9/19 show that when using a desktop device, most use Windows when accessing either the Collection (works + works/) or Library.  

For mobile devices, Android and iOS are just about equal in usage levels:

Collections |  
-- | --
Operating System |  
Windows | 40.7%
Android | 19.7%
iOS | 19.5%
Macintosh | 17.9%
Chrome OS | 1.0%
Linux | 0.7%
(not set) | 0.6%


Library |  
-- | --
Operating System |  
Windows | 42.8%
iOS | 20.1%
Android | 19.1%
Macintosh | 15.9%
Chrome OS | 1.2%
Linux | 0.6%
(not set) | 0.2%

**Comment by taceybadgerbrook** [comment]
Usage patterns by screen resolution for 6-month period 1/3/19-10/9/19 show similar results when accessing either the Collection (works + works/) or Library.  


Screen   Resolution | Collections | Library
-- | -- | --
1920x1080 | 12.4% | 10.5%
1366x768 | 11.3% | 10.7%
1440x900 | 7.8% | 7.9%
360x640 | 7.7% | 7.2%
375x667 | 6.6% | 6.4%
1280x800 | 4.3% | 4.2%
1536x864 | 4.0% | 3.6%
768x1024 | 3.9% | 4.9%
2560x1440 | 2.8% | not in top 10
1280x720 | 2.6% | 2.8%

**Comment by pollecuttn** [comment]
@taceybadgerbrook to add link to datastudio, and then close

**Comment by taceybadgerbrook** [comment]
Comparative analysis of Collection and Library by device type, operating system and screen resolution validates the assumption that most users are PC-based.  However, it is worth noting because of the impact on site design that 25% of Collection and 13% of Library users use wide-screen devices.

Here is the link to the Data Studio document:  https://datastudio.google.com/reporting/11F3ZlAiwJQMSjUDBOf8zP1tBeuNjCEdX 

Here is a link to the Sharepoint document:  https://wellcomecloud.sharepoint.com/:w:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/4489%20GA%20data%20for%20works.docx?d=w12ebf766a13349bdbf1e609d684a7f2d&csf=1&e=7wP5B3
