### ISSUE TITLE
Viewer Design & Prototype

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4491]
### Components
**Info Bar**
- Abbreviated title 
- Control to view more info
- Control to switch between 'View all' and 'View page/image' e.g. [Airbnb](https://www.airbnb.co.uk/rooms/plus/2093755)
- Download options

**View Info**
- Link to Viewer 'Return to ...'
- Full title
- Contributor
- Date
- Download options (?)
- License info
- Link to Item Overview
- Footer(?)

**View All**
- Thumbnails
- Scroll bar (native)
- Total page/image #
- Page/image #

**Detail View**
- Double sided for Books, Single for Images
- Scroll bar (custom)
- Previous & Next
- Zoom in/out
- Rotate
- Total page/image #
- Page/image #

### Design
- [x] Explore layout and position of 'View Controls' and 'Info Bar'
- [x] Explore toggle between 'View all' and 'View page/image'
- [x] Design 'View Info'
- [x] Update # of thumbnails/sizes (page type should be visually recognizable)
- [x] Display 2 page view for books
- [ ] Display Total page # and individual page #
- [ ] Design Hover state
- [ ] Enhance custom scroll bar UI
- [ ] Explore different design for the view toggle based on research insights (e.g. Tab or 'View all pages' with an arrow up & down)

### Prototype
For research https://invis.io/NPS621Z3VQX#/364982241_Works_Book
Tech feasibility https://codepen.io/davidpmccormick/full/YbYNYw

### User Research 23 May  (2 participants)
**1 Some confusions around the purpose between the info page and Works.** 
For now, we will just link back to Works. We will monitor how people navigate between Works and Viewer and make necessary improvements

**2 Scrollbar and page number on 'Detail view' were missed.**  
@GarethOrmerod will explore different options to make it more visible.

**3 No major issues with Preview**
@hthair Continue to monitor 'Works' page behaviour (hotjar)

**4 View toggle behaviour**
@hthair Continue to solicit feedback and share insights with the team.

**Update:**
After the user research session, we decided to start implementing the design in phases and do further research with actual content and functionalities (e.g. scroll experience on detail view)

### Open Issues (follow up with @jennpb)
- Could we explore incorporating the branding to the top bar to optimize the viewing area?
- How should we display key info (full title, author, year) and license info?

**Comment by jennpb** [comment]
> Could we explore incorporating the branding to the top bar to optimize the viewing area?
Decided to wait until the enhanced viewer is implemented and see how it works in practice

> How should we display key info (full title, author, year) and license info?
- Full title should be truncated and visible in viewer
- Author and Year - go back to Overview to see 
- Licence info - make part of Download component
