### ISSUE TITLE
Work preview

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#4492]
Implement latest preview designs in Zeplin

## single item
- max width 1010px (10 col)
## Multiple items <= 5
- max-height 400px
- max-width 800px
- images centered
- images get cut of to the right
- wobbly background

**Comment by Heesoomoon** [comment]
In terms of the CTA, could we a/b test?
Work specific (# images or # pages) vs Generic (View item)

**Comment by jennpb** [comment]
Apart from the A/B testing idea above (which I'll put in another issue), is this one ready to be closed @wellcometrust/experience-devs ?

**Comment by gestchild** [comment]
@jennpb yes it is
