### ISSUE TITLE
JS and SASS tests are run on hook even if I haven't changed any of those files

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#45]
We should only run the tests if those files have been changed else it slows development.

**Example:**
I am working on the docker container and when I push all tests have to be run.

**Comment by jennpb** [comment]
hey @jamesgorrie this is an old issue. Is it something you want to pick up soon, is it techdebt, or have you magicked it away through other means?

**Comment by jamesgorrie** [comment]
Still something we need to do - techdept.
