### ISSUE TITLE
Question: should we exclude non-IIIF e-book resources from search for now?

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4501]
# Who it's for
Collections researchers

# Problem to be solved
The workType label 'e-book' covers these actual types:

1. Books that have been digitised
2. PDFs (that may have a hard copy 'book' in the library)
3. 'E-books' provided by third-party electronic resource providers, e.g. 18th Century Collections Online

The 3rd party e-books like this https://wellcomecollection.org/works/m7yy8cst, should in future contain a link to the resource, but for now we haven't displayed it.

Should we exclude non-IIIF resources from 'e-books' for now, if we're not offering access to them?

While it would be easy to add a CTA to 'View resource' (similar to the library catalogue), what we don't have is any of the supporting content to help people understand that this is a library member benefit (login with library card to view), how to get library card, etc etc....

Is it better to offer a link without supporting context? Or to suppress from view for now?

**Comment by Heesoomoon** [comment]
@jennpb Is this result of the PDF source file?
https://wellcomecollection.org/works/g829snzf
![Screen Shot 2019-06-18 at 15 17 37](https://user-images.githubusercontent.com/29206031/59692155-418b6d80-91dc-11e9-9411-332037ee45b8.png)
