### ISSUE TITLE
Single image defaulting to multi-image CTA

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4503]
Not sure what's going on here, but this single image (Picture with only 1 image) is being treated as a multi-image work:

https://wellcomecollection.org/works/nee3jsp3
![image](https://user-images.githubusercontent.com/1446139/58535931-056d7a00-81e7-11e9-9807-64b3f45a4f02.png)

**Comment by gestchild** [comment]
The catalogue API data for this work has a iiif-presentation location type with a iiif manifest, but no iiif-image location. I don't know the reason for that, but that is why it's treated this way on the front end.

**Comment by davidpmccormick** [comment]
Fixed in #5027
