### ISSUE TITLE
Feature flagging 

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#451]
~Team needs to work out its approach to feature flagging. More detail and conversation to follow!~

Decided to initially use feature flagging to:
- help us iterate more quickly with fewer code conflicts etc., deploy more confidently
- allow us to quickly kill features if they cause problems
- make it possible for non tech team members to enable/disable features

In the future we will probably want to:
- release features only to selected groups of users.
- potentially use as a way of A/B testing (although we have other methods to accomplish this)?

##MVP tasks:
- [x] Create github repo to hold flags and setup webhook notify AWS SNS topic of changes
- [x] Set SNS Topic to trigger Lambda function when github repo changes
- [x] Set up Lambda function to copy contents of github repo to S3 Bucket
- [x] Set up S3 Bucket to host flags
- [x] Access flags from application (keep in memory and periodically update)
- [x] Make flags available to node modules/view templates and client side javascript

**Comment by jennpb** [comment]
#656 is a good example of where we need to be able to view and test features before they get released to everyone. Need to kick this up the priority list for when @jamesgorrie returns. @gestchild @davidpmccormick is there anything we can sensibly get started on this week in the meantime?

**Comment by gestchild** [comment]
Decided to initially use feature flagging to:
- help us iterate more quickly with fewer code conflicts etc.
- allow us to quickly kill features if they cause problems
- make it possible for non tech team members to enable/disable features

In the future we will probably want to:
- release features only to selected groups of users.
- potentially use as a way of A/B testing (although we have other methods to accomplish this)?

**Comment by jennpb** [comment]
Superseded by #841 and #845
