### ISSUE TITLE
GA audit

### ISSUE THREAD

**Issue by hthair** [wellcometrust/wellcomecollection.org#4514]
Ready for handover I'd like to audit both GA properties to check:
- goals (old ones need turning off)
- filters (mainly checking new property is set up how we want it)
- events (which events are in which property and how to use them)

I'd like to do this first then run through outcome with team as part of handover.

**Comment by hthair** [comment]
For event related Goals on the new property (wc.org (main)), we'd need to add the event tracking in the behaviour section. For example, on default property we have a goal for going to blackwells website from wc.org. This is based on the outbound link event tracking that is restricted to the default property. 
At present the only events in the new property is 'engagement' (time on page greater than 10 seconds).

**Goals**
- none on new property at present
- default property: unused old goals turned off. These can then be reused/recycled later but be aware of what date any changes are made to know when you can count the hits as being the newly described goal. (GA has a limit on number of goals and they can't be deleted, nor the data, but we can rename and reuse slots but know when to start counting the data). 
-default property: goals remaining ON are: 
      - Email sign up
      - Link to Blackwell's shop
      - Event booking (this refers to outbound link to eventbrite)

**Comment by hthair** [comment]
View settings:
- if switching over to new property we'd need to link the google ad accounts too. Currently there are 3 on the default account. These can be found in admin > view settings

**Comment by hthair** [comment]
**Filter settings**

Account: wc.org (collection only)
- remove wellcome library domain
- add hostname to URL
- exclude localhost

account: wc.org (main) [collection and library users with cross domain tracking so as not to duplicate users]
- lowercase: search term
- hostname/URL: Add hostname to URL
- exclude traffic from digirati
- exclude localhost

wc.org (library only) [wellcomelibrary.org traffic]
- remove wellcome collection domain 
- hostname/URL: Add hostname to URL
- exclude traffic from digirati

**Comment by hthair** [comment]
Key differences between new wc.org property and the default one to be aware of:

* bounce rate - on the default property we changed bounce rate to only trigger if someone spent less than ten seconds on the site to account for engaged but one page sessions. Therefore on the default bounce is around 15% whereas the new property as a GA style defined bounce of 55%

* users - these are slightly different between the collection view and default view as they have different filters. However I would have expected the collection view to have more users, not less, as it has less filters. It might be possible that the reason this data is different is to do with how GTM counts a user vs the hardcoded version that sends data to the default property. 

* pageviews - this is higher on the collection only view by some margin. I suspect this is to do with how we are tracking pageviews on works due to the way the page refreshes within an item, but requires a bit more investigation. Currently on the collection only view we use GTM that sends a page history change as a pageview hit.

**Comment by pollecuttn** [comment]
@taceybadgerbrook to check that bounce rate and pageviews are set up as described above

**Comment by taceybadgerbrook** [comment]
https://github.com/wellcometrust/wellcomecollection.org/issues/4767

**Comment by taceybadgerbrook** [comment]
There are no goals set up on any of the Properties.  Old goals (email signup, link to Blackwell's, event booking) would need to be set up from scratch on the new property Collection + Library.

Comparing  GA property Default (collection only) with Collection + Library/(collection only), bounce rate change to <10 seconds needs to be implemented. Also users levels in Default are higher than Collection + Library (maybe due to hardcoding not copied to over?) and Collection + Library page views are quite a bit lower than in Default (is this why GTM has been set up so that page history change = pageview hit?)

**Comment by jamesgorrie** [comment]
For completion:

The account `[Default] Collection UA-55614-6` is completely controlled by the JS / client application. 

This had a piece of functionality that, after 10 seconds, count someone as not a bounce.

For context this is the account we inherited from the old site.

---

The account `Wellcome Collection and library  UA-55614-24` is controlled from Tagmanager, and has just had a 10 second trigger instated on it (`2019-10-14 17:53`).

It might be worth working through how we might consolidate into 1 account. We got some of the way there a while back, but not sure we tied off the loose edges.

**Comment by taceybadgerbrook** [comment]
This ticket has been split into:-
https://github.com/wellcometrust/wellcomecollection.org/issues/4833
https://github.com/wellcometrust/wellcomecollection.org/issues/4834
https://github.com/wellcometrust/wellcomecollection.org/issues/4835
