### ISSUE TITLE
Build viewer enhancements from design interation

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#4516]
Building on design interations from https://github.com/wellcometrust/wellcomecollection.org/issues/4491

Header view for secondary information: https://github.com/wellcometrust/wellcomecollection.org/issues/4444
Download control: https://github.com/wellcometrust/wellcomecollection.org/issues/4446
Thumbnail drawer: https://github.com/wellcometrust/wellcomecollection.org/issues/4443
Global nav and footer: https://github.com/wellcometrust/wellcomecollection.org/issues/4447

**Comment by jennpb** [comment]
This is a duplicate of #4325.
