### ISSUE TITLE
Book Viewer: thumbnail size

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4544]
## Who it's for
Users viewing digitised books

## Problem to be solved
In the past user research, participants have expressed how they feel "overwhelmed" when we present too many small thumbnails of the book.

The current implementation of the thumbnail list 
- makes it difficult to recognize the type of page
- too many to process at a glance. 

Therefore, we would like to increase the size similar to the one used on Alpha.

**[Current size](https://wellcomecollection.org/works/enws5rhq/items?canvas=37&sierraId=b29299536&langCode=eng)**
![Screen Shot 2019-06-18 at 09 47 02](https://user-images.githubusercontent.com/29206031/59922111-c3230b80-9427-11e9-936f-172e72ef02f2.png)

**[Alpha](https://alpha.wellcomelibrary.org/b20390452)**
![Screen Shot 2019-06-18 at 09 47 18](https://user-images.githubusercontent.com/29206031/59922117-c61dfc00-9427-11e9-80d0-be84850d2348.png)

## Success measures
- Users find the list manageable to review 
- Users are able to recognize the type of page

**Comment by davidpmccormick** [comment]
Closed by #4553.
