### ISSUE TITLE
Digitised books: page number and spacing improvements on list view

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4546]
## Who it's for
Users viewing digitised books

## Problem to be solved
To address known visual and usability issues
- [ ] Improve legibility of page numbers (As part of [Design System Typography](https://cardigan.wellcomecollection.org/?path=/story/global--typography) audit)
- [ ] Revisit visual for the selected page e.g. outline of the page in addition to yellow page number
- [ ] Make it easy to associate the page number and thumbnail e.g. increase vertical spacing
- [ ] Display page number on top of the page to address irregular page sizes

![Screen Shot 2019-06-21 at 14 17 21](https://user-images.githubusercontent.com/29206031/59925315-bd312880-942f-11e9-936d-4e15bf2175d0.png)

**Comment by davidpmccormick** [comment]
Work done in #4908.
