### ISSUE TITLE
Embedded Twitter/Instagram width

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#455]
The Twitter/Instagram embeds currently have a max-width of 500px (as defined by their own CSS) and can end up looking awkward. We could make them always be 100% width of their container (as is the case with our home grown components). I imagine Instagram posts could then end up looking too big. Needs some design consideration.

![screen shot 2017-02-03 at 14 40 48](https://cloud.githubusercontent.com/assets/1394592/22595432/607ceb4a-ea1f-11e6-9c61-b5be09b674c1.png)

**Comment by jennpb** [comment]
One for you @Norvard

**Comment by Norvard** [comment]
Well usually these will sit within the rail, so there we shouldnt have an issue. When the embed happens fully inline like the example above, then we can treat it similar to the quotes, indent and add that grey line. I can mock that second option up if needed.

Make sense @davidpmccormick ?

**Comment by davidpmccormick** [comment]
I hear you – something along these lines:
![screen shot 2017-02-03 at 17 34 52](https://cloud.githubusercontent.com/assets/1394592/22601552/4f7b45c2-ea37-11e6-8673-fea35ff27ff3.png)

?

Would that also apply to back-to-back tweets e.g.:
![screen shot 2017-02-03 at 17 37 10](https://cloud.githubusercontent.com/assets/1394592/22601578/707e23ca-ea37-11e6-922d-a7da87f78a4d.png)

?

**Comment by Norvard** [comment]
Yea that works! Maybe the line continues to cover all back to back embeds?

**Comment by davidpmccormick** [comment]
> Maybe the line continues to cover all back to back embeds?

Ha – kind of knew you were going to say that.

**Comment by Norvard** [comment]
MAgical powers!

**Comment by jamesgorrie** [comment]
Did we do this - and if not are we going to do this?

**Comment by davidpmccormick** [comment]
> Did we do this - and if not are we going to do this?

We didn't. We should. I would advise not attempting to do so before we're off WP though because of the body-parser dance that would be required.

**Comment by jamesgorrie** [comment]
Got it.
