### ISSUE TITLE
AB Test: Book Viewer - View controls location

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4550]
## The problem: We think that...
We display Zoom controls on the top left, Pagination controls on the bottom right, and Viewer buttons on the top right. The controls are spread out forcing users to move their mouse diagonally frequently from top left to bottom right to complete a task e.g. flip through pages and zoom in.

More than 50% of /works users access the viewer using 1366x768 or larger screen resolution.
![Screen Shot 2019-06-26 at 09 15 48](https://user-images.githubusercontent.com/29206031/60163227-119f2400-97f3-11e9-80b3-c14a29da8f95.png)

## Therefore we hypothesize that...
Grouping Zoom and Pagination controls, it will make it more convenient for users to complete a task and encourage them to explore more.

## As measured by...
Higher usage of Zoom and Pagination controls (?)

## Acceptance criteria: we are right if...
TBD

## Next steps
- [x] ideate a few ideas with the team
- [x] implement AB test
- [x] monitor

**Comment by Heesoomoon** [comment]
@jennpb, after talking to @hthair this doesn't seem like a good candidate for A/B test. I'll close it and add to #4325 as part of un-moderated test to validate our assumptions.

**Comment by jennpb** [comment]
Why not? @hthair @Heesoomoon

**Comment by Heesoomoon** [comment]
We all agreed too many things can influence Zoom and Pagination Controls usage and difficult to measure just for changing the location. And there are no other metrics we could think of that will help us set up A/B for this.

It feels like un-moderated screen recording or moderated usability testing may shine a better picture of the issue.

**Comment by Heesoomoon** [comment]
As a background, this is something I recommended during the exploration based on best practice point of view. Also, when we audited different viewers, most examples grouped the pagination and zoom controls and displayed along top or bottom of the screens.
https://www.notion.so/wellcometrust/Viewer-Examples-aab9a06d594946d8afdc3504de00285c

**Comment by hthair** [comment]
Getting a baseline measurement:

option 1: Look at number of users who viewed a work page, and then of those how many clicked the next page arrow (using a segment with those conditions)

19th - 26th June =
- 190 users viewed a book viewer page and clicked the arrow
- 2024 users viewed a book viewer page
190/2024* 100 = 9.4%

This suggests less than 10% of users are either choosing to use the arrows or discovering it (some may see them but chose to use the thumbnail view to jump between pages)
Looking at pages per session, the people that are using the arrows are viewing 31 on average, whereas those that don't use the arrows are viewing 17. 

Iff we want to see an increase of 50% to 13.5% we'd need 450 people in each condition. If we want to increase it by 100% to 18% we'd need 99 people in each condition.

**Comment by hthair** [comment]
We've agreed to move the pagination buttons to below the zoom controls (grouping them) all on the left. 
We hypothesis that people are not discovering the pagination controls but also the distance between the controls poses a usability issue that we want to improve. 
Therefore we'll be expecting the % of people that view a book viewer page and use the buttons to increase. The knock on effect of this should be more pages viewed on average.

**Comment by hthair** [comment]
I've updated this template using the segments in GA so Harrison or anyone should be able to monitor and then calculate conversion rates https://datastudio.google.com/u/0/reporting/1-OFWXCxdyhS_KRUZYivSp9q-b5LxNrOd/page/DwGt/edit

**Comment by davidpmccormick** [comment]
@harrisonpim We've just deployed this. Users will have a `toggle_groupImageControlsWithPagination` cookie set to `true` or `false` when visiting any `/works/.*` page.

When it's `false`, the image controls (zoom/rotate) are on opposite sides of the screen (the 'A' condition?)

Let us know if you need anything else to go on.

**Comment by harrisonpim** [comment]
The dash as Hayley left it was set to track the number of unique users who interacted with the buttons. I think this is probably the wrong metric - i feel like we want to see the overall level of interaction, rather than the share of users who decided to click a button at least once. For that reason, I've tweaked the dashboard to show the total pageviews within the viewer under each condition. I've used [this tool](abtestguide.com/calc) to determine significance

### Pageviews
condition | total | conversions
-- | -- | -- 
A | 1,002 | 356
B | 1,353 | 611

<img width="1012" alt="Screenshot 2019-07-08 at 12 05 31" src="https://user-images.githubusercontent.com/11006680/60805693-c1bc4780-a178-11e9-8110-a830152abbc8.png">

**Comment by davidpmccormick** [comment]
Closed by #4573
