### ISSUE TITLE
Unusual viewer activity

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/wellcomecollection.org#4552]
Saw some weird behaviour in the viewer.

The on-screen controls seem to modify a 2nd canvas while the pointer controls modify the 1st canvas.

In `Chrome Version 75.0.3770.100 (Official Build) (64-bit)` - On OSX.

<img width="813" alt="magnifier" src="https://user-images.githubusercontent.com/953792/60003539-d40b9100-9662-11e9-9a65-d5fb3d40e869.png">

**Comment by davidpmccormick** [comment]
Closing because we can't replicate the issue.

**Comment by jennpb** [comment]
This has just happened to me, so reopening.

Chrome Version 75.0.3770.100 on PC
Opened item, zoomed in on detail view
Clicked into a few new tabs
Returned to detail view
Zoomed image is frozen, but you can see that there's a second image underneath where the zoom actions are visible

https://wellcomecollection.org/works/cdv47pt3/items?canvas=42&sierraId=b2931205x&langCode=eng
![screenshot-wellcomecollection org-2019 06 25-12-00-27](https://user-images.githubusercontent.com/1446139/60093329-0db2c980-9741-11e9-8f34-fa6809c98d4a.png)
