### ISSUE TITLE
Horizontal rules from WordPress

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#456]
It looks like content editors have used `hr` elements to break content up visually on the WP blog. We could turn these into e.g. a divider type and treat them with our own styles (or just provide a better default style for unclassed `hr`s.

![screen shot 2017-02-03 at 14 47 22](https://cloud.githubusercontent.com/assets/1394592/22595587/03fcf094-ea20-11e6-8c12-654ec71b2193.png)

**Comment by jamesgorrie** [comment]
These aren't going to be available in the new system.
