### ISSUE TITLE
Build JS image gallery (inline)

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#458]
![image](https://cloud.githubusercontent.com/assets/1446139/22598696/435bc07e-ea2c-11e6-88b0-c5447928f157.png)

**Comment by jennpb** [comment]
Image gallery built to MVP state.
Still to do: Image popout and overlay

Related to #772

**Comment by jamesgorrie** [comment]
Closing in favour of #1059
