### ISSUE TITLE
View controls not working on mobile devices

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4584]
The zoom in/out and rotate controls are disabled. Also, the previous/next page controls inadvertently download PDF file which consumes huge mobile data.

The dashboard has shown an unusual increase in 'download'. So I assume our users are accidentally downloading the PDF file instead of paginating.

**Comment by pollecuttn** [comment]
And clicking on a page in the grid view sometimes takes you to the Creative Commons page.

**Comment by pollecuttn** [comment]
@gestchild Can you please look at this: previous/next controls downloading PDF file is the part to address first as it's causing people to use data to download when that isn't their intention
