### ISSUE TITLE
Pagination buttons should be before image controls in source order

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#4600]
When tabbing through the elements in the viewer, you arrive at the image controls before the pagination controls. This should be changed in line with the new visual ordering of these elements after the A/B test in #4550

![image](https://user-images.githubusercontent.com/1394592/61369445-06866380-a888-11e9-9e71-bbf3241664f1.png)

**Comment by jennpb** [comment]
@davidpmccormick @gestchild This is no longer a problem, correct?
