### ISSUE TITLE
Mobile nav, free sticker, TASL, and tab nav visibility

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#4603]
Free sticker peeks out…
![image](https://user-images.githubusercontent.com/1394592/61479337-85b09000-a98b-11e9-85d9-4c805099bee5.png)

…and the TASL icon has a z-index above the nav
![image](https://user-images.githubusercontent.com/1394592/61481485-46387280-a990-11e9-8ab3-ba7edef3c2b7.png)

…and the tab nav
![image](https://user-images.githubusercontent.com/1394592/61550762-447fb500-aa4b-11e9-83d3-c292118b5ffe.png)

**Comment by jamesgorrie** [comment]
Have we thought about removing the hidey nav as a test?
[There's some conversation here](https://github.com/wellcometrust/wellcomecollection.org/issues/3542).
