### ISSUE TITLE
Dates prototype development

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#4631]
Build three prototypes for testing that allow a user to filter results by date.

- [x] 2 input fields (completed in #4628)
Provide an input for a `from` date and a `to` date, without any placeholder text so as not to influence what the user wants to enter.

- [x] compound date slider (completed in #4628)
Enhance the above input fields to be controlled by two range sliders, allowing the user to drag a range of dates to be searched.

- [x] aggregate date information
Indicate the number of results within bucketed date ranges and allow a user to get to those results via links.

**Comment by jennpb** [comment]
@davidpmccormick Is this ok to close now?

**Comment by davidpmccormick** [comment]
Yep.
