### ISSUE TITLE
Event tracking on digitised audio and video

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4655]
## Who it's for
Us

## Problem to be solved
Tracking use of digitised video and audio

**Video player**
Event Category = Control 
Event Action = Play video
Event Label = ID  

Event Category = Button
Event Action = Download video
Event Label = ID

Event Category = Engagement
Event Action = **TBC**
Event Label = ID

**Audio player**
Event Category = Control 
Event Action = Play audio
Event Label = ID 

Event Category = Button
Event Action = Download audio
Event Label = ID

Event Category = Engagement
Event Action = **TBC**
Event Label = ID

**Comment by davidpmccormick** [comment]
Would we want to know any other events (e.g. `pause`, `volumechange`)? [This is the full set available](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events) for the native players.

**Comment by jennpb** [comment]
@davidpmccormick @pollecuttn This was done, yeah? Can it be closed?
