### ISSUE TITLE
Map incoming catalogue data to works page

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4661]
## Who it's for
Collections researchers who want comprehensive data about the materials in our collections

## Problem to be solved
Additional data is set to come from the API this quarter (https://github.com/wellcometrust/platform/milestone/14). We need to map and label the information so that it:
- makes logical sense in the flow of the page (info hierarchy)
- is grouped and labelled meaningfully
- is rendered in a readable and/or scannable way 

Note that by combining Notes from various MARC fields, we could end up with odd `<p>` and `<br>` tags from the original metadata (tags put in place so that notes would display better in existing catalogues)

## User Story/Job
In order to determine whether these items are relevant to my research, as a researcher, I want to see comprehensive catalogue information about stuff in the collections.

## Acceptance Criteria
- All new data added in order described here https://docs.google.com/spreadsheets/d/1loJdpA6mOqBQwbTG4BwIKlWsKAZzkuMsTTkLzWcpGSg/edit?usp=sharing

**Comment by jennpb** [comment]
@gestchild @davidpmccormick @pollecuttn When the reindexing happens we'll need to add all incoming metadata to `/works`. I've had a go at placing everything in position on the google sheet listed above. If you get to this before I return, please keep behind a toggle so I can review it on my return.

May need to consider design tweaks too.

**Comment by pollecuttn** [comment]
https://github.com/wellcometrust/platform/issues/3904 closed: incoming catalogue data is now available to us in the API

**Comment by pollecuttn** [comment]
@gestchild Can this be closed now?

**Comment by gestchild** [comment]
yep

**Comment by jennpb** [comment]
Data team will be making changes which will impact us. Reopening this ticket until it's ready to go for a second round.

**Comment by jennpb** [comment]
I'm happy for this to come out from behind the toggle now @wellcometrust/weco-experience-devs. Might have a few more bits to tidy-up, but nothing that warrants holding it back from public view.

**Comment by davidpmccormick** [comment]
So I'm clear, are we talking about the `Return all possible results from the catalogue API, without filtering by type or location` toggle?

**Comment by jennpb** [comment]
IGNORE ME

I can't keep track of which toggles I have on. Turns out we already de-toggled it, I'd just assumed I was in a toggle.

**Comment by davidpmccormick** [comment]
> IGNORE ME

Roger that.
