### ISSUE TITLE
Search results: support update to date facet results with enter/return key

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#4725]
When a user wants to facet by date, the 'enter'/'return' key should update the results the same way the 'set dates' (or 'update') button does when a date has been entered

### Acceptance criteria
- [x] Enter/return key updates search results

**Comment by pollecuttn** [comment]
@davidpmccormick Can this be closed now?

**Comment by davidpmccormick** [comment]
Yep.
