### ISSUE TITLE
Changes to loris image server for Prismic

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#4764]
On 21st of October Prismic will be turning on its new image optimisation service.

We will need to point our loris server to a new url in order for the site to continue serving images correctly.

https://user-guides.prismic.io/en/articles/3309829-image-optimization-imgix-integration

**Comment by jennpb** [comment]
@pollecuttn Has this one been done?

**Comment by gestchild** [comment]
@jennpb Essentially yes, we didn't end up changing loris, but instead made changes to use Prismic's new imgix service - which went live on Monday 28th
