### ISSUE TITLE
Investigate newsletter signup end-to-end workflow for accessibility

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4769]
This email was forwarded to us from Selene, from a visually impaired user:

> I’ve signed up to the access news letter and general events news letter.  However, I came up against a slight issue when trying to confirm my email.  The link in the confirmation email didn’t seem to respond to JAWS and I had to get Chikodi to click on the link with a mouse.  Just for reference I’m using Win 10, Outlook 364, and JAWS 2019.  It could just be some kind of incompatibility issue, or it could be the coding in the email, I’m not sure.
>  
> I thought I’d report this as other Vis may be having the same difficulty.

Not sure whether the confirmation email is ours or Dotmailer/Dotdigital's, but we need to ensure that the full newsletter signup workflow is usable on screenreaders.

**Comment by gestchild** [comment]
- I've looked at the code for the email templates and there is nothing obviously wrong with them.
- I've sent emails to myself and checked them with VoiceOver on Mac and Outlook (and these seem to work as expected, i.e. the links are identified as such and can be activated).

- Will need to try and get hold of a windows machine with outlook and jaws to proceed further with this

**Comment by pollecuttn** [comment]
7/10/19 NP replied to the emailer:
We have a test laptop with Win 10, JAWS 2019 and Outlook on it to try out this issue.

I’ve been able to confirm the sign up by tabbing in the email to the link and pressing return. 

I’ve not used JAWS before so I’m sure I’m using it differently from you, Ian. If you remember, could you please tell me more specifically what the issue was or whereabouts you were running into difficulties? I’m not sure how to replicate your issue otherwise.

**Comment by pollecuttn** [comment]
Blocked until 1 November

**Comment by davidpmccormick** [comment]
I'm doubtful about the ability to _completely_ unsubscribe a user – as far as I can tell it looks like unsubscribing/deleting contacts will always keep their address on a suppression list so that any future subscription request will be a re-subscription rather than a new signup.

I've written to Dotmailer support to see if there's another way.
 
> We had a report from a user with accessibility needs that they had difficulty clicking a link within our confirmation email using their screenreader.
> 
> We are arranging a meeting with him so that we can view his workflow, but we need him to be able to sign up as if he were a completely new user, rather than a resubscribing user, so that he receives the sign-up email again.
> 
> As far as I'm aware, I can unsubscribe him and delete the contact, but his email address will remain in the suppression list so that any future attempt to sign up will be treated as a re-subscription rather than a new subscription.
> 
> Is there a way to accomplish this for an individual contact (without asking him to use a different email address)?
>

**Comment by davidpmccormick** [comment]
Dotmailer allows you to test-send campaigns. The confirmation email is an automated campaign called 'confirm opt in'. We can re-send this as many times as required – possibly the best option.

Probably worth sending this out to our screenreader user ahead of our visit to see if he can provide any further information.

**Comment by davidpmccormick** [comment]
Heard back from Dotmailer and it can be done with these steps:

1. resubscribe contact if they've been suppressed/unsubscribed
2. delete directly from the 'all contacts' address book
3. permanently remove from the 'recycle bin'

![image](https://user-images.githubusercontent.com/1394592/67404853-d8fa3600-f5ab-11e9-835a-c061d6e6827a.png)

So we can do this for our user on the day if necessary, but still worth sending a test-campaign (above comment) beforehand I think.

**Comment by pollecuttn** [comment]
@davidpmccormick Can you please put the link to the video here

**Comment by pollecuttn** [comment]
REQ0013288 Windows 10 machine with JAWS 2019 and Outlook

**Comment by davidpmccormick** [comment]
[low res screen recording + iphone audio](https://wellcomecloud.sharepoint.com/sites/wcdigitalexperience/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fwcdigitalexperience%2FShared%20Documents%2FUser%20Research%2FAccessibility%20research%2FJaws%20%2D%20home%20visit%202019%5F11%2Fian%2Emp4&parent=%2Fsites%2Fwcdigitalexperience%2FShared%20Documents%2FUser%20Research%2FAccessibility%20research%2FJaws%20%2D%20home%20visit%202019%5F11) – the video starts at c. 1:40

There's a [screenflow file here](https://wellcomecloud.sharepoint.com/sites/wcdigitalexperience/Shared%20Documents/Forms/AllItems.aspx?viewid=bb8c30b0%2D6281%2D45fa%2Dbfb1%2D2973d13d217f&id=%2Fsites%2Fwcdigitalexperience%2FShared%20Documents%2FUser%20Research%2FAccessibility%20research%2FJaws%20%2D%20home%20visit%202019%5F11%2Fian%2Escreenflow) that contains all the original media.

**Comment by gestchild** [comment]
Have recreated the confirm newsletter template in dotmailer and tested with JAWS and outlook. It now works as expected.
Have also made a couple of other accessibility improvements, tweaking the button colour and adding alt text to the logo
