### ISSUE TITLE
Inviting participation in surveys or online tests

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4771]
## Who it's for
- Us, because we need a way to get a random sampling of participants in our various bits of online research

## Problem to be solved
Whenever we want to intercept users to invite participation in online tests or surveys, we have to rely on third-party services or widgets. In some cases, the usability testing tools we're using don't even come with their own widget, so we have no way of linking off from wellcomecollection.org to the testing tool.

Rather than relying on third-party widgets or pop-ups, we should explore creating our own reusable pattern that at least adheres to our own product principles.

## Example content
Here's the kind of thing we're likely to need to convey:

- Invitation
- A bit of explanation but not much
- A call to action that links to a testing/survey service (e.g. optimalworkshop, surveymonkey, qualtrics, etc)

Example:
**Help us improve our website** [Link to find out more]
Got 5 minutes? We'd like to know more about how you use Wellcome Collection's website. 
[CTA] Go to survey

## Considerations
- how to do this with subtlety and without being too annoying?
- can it express brand, rather than just a basic alert? any reuse of wobbly line?
- placement and sizing

## Acceptance Criteria

- [ ] The interface should do this thing
- [ ] and this thing
- [ ] and this thing.

## Prompts

- Do we need to set up any event tracking?
- Has this been documented in Cardigan?
- How are we measuring success?

**Comment by pollecuttn** [comment]
8 October 2019:
* it is possible to build it to appear on all of the site or just a particular part
* we start with just the icon, with no autopop up (needs the user to click it to launch)
* the icon moves up and down at pageload once to draw attention, but subtly
* specific event tracking not needed to track clicking on link to survey: we can check the survey link in GA
* we need to add event tracking on clicking of the icon to open the invitation component
* format:  title, descriptive text (could have links), CTA (button), close button on open component

- [ ] @GarethOrmerod to decide on and design icon to use

**Comment by davidpmccormick** [comment]
Work for the UI in
#4782 
#4783 
#4789 
#4791 
#4793 
#4794 
#4797

**Comment by jennpb** [comment]
Can this be closed now? @pollecuttn @davidpmccormick 

The task to make this an editable component in Prismic should be on a new ticket.

**Comment by davidpmccormick** [comment]
Yep
