### ISSUE TITLE
Filter by worktype

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4820]
## Who it's for
Collections researchers

## Problem to be solved
Using `workType` aggregations for filtering of search results 

## User Story/Job
In order to determine whether Wellcome Collection has what I need
As a researcher
I want to narrow my search to the material types I'm interested in

## Considerations

- Do we need to set up any event tracking?
- Has this been documented in Cardigan?
- How are we measuring success?

**Comment by jamesgorrie** [comment]
> Do we need to set up any event tracking?

We are and will continue to track what `workType`s people are searching via the search logger.
