### ISSUE TITLE
Single digital story - type

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#483]
The description paragraph text should top align with article title.

Size should also be larger. 33px at desktop

![screen shot 2017-02-09 at 10 27 30 copy](https://cloud.githubusercontent.com/assets/23660297/22779508/f8b6b0e8-eeb2-11e6-8665-79b7a1f3a591.png)

**Comment by jamesgorrie** [comment]
33px? Where's that from?

**Comment by Norvard** [comment]
Thats one of the type sizes from the styleguide

Wellcome Bold style: WB4

**Comment by Norvard** [comment]
Top align the copy with the format name "Article". Both 30px from the top of the white container.
