### ISSUE TITLE
Implementing changes in the new GA Property

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcometrust/wellcomecollection.org#4835]
As an analyst, I need to transfer appropriate settings used in the old Property/View ([Default] Collection/B – External traffic (A = B+C) >>> Default View (WC)) to the views in the new Property (Wellcome Collection and Library) by first auditing the goals, filters and events to identify which are no longer useful and then making the changes using GA and Google Tag Manager.
 
Acceptance criteria
Data from new property (collection only) should be the same as old property 
Data from new property (library only) should be the same as library property 

https://github.com/wellcometrust/wellcomecollection.org/issues/4514

**Comment by taceybadgerbrook** [comment]
Filters for old Property do not apply to views available in old Property (appear to be a mixed bag of new and library properties.) This would mean none of the filters are in operation.  Could be reason why Data Studio reports using WeCo with Extras data source (linked to old Property) show higher page view levels than the new Property.

Before making changes, will be reading up on GA filtering documentation.

**Comment by taceybadgerbrook** [comment]
Data being directed to Old Property and new Property are defined by Google Tag Manager settings (used to be defined by Google Analytics Tracking Code (GATC) but ga.js is now a legacy library.)

I am prioritising ticket [4834](https://github.com/wellcometrust/wellcomecollection.org/issues/4834) to ensure old and new Properties are correctly defined before implementing changes.

**Comment by jennpb** [comment]
> Anti-secret spam filter (anything with, "secret" in request) - I propose we drop this.

Is this filter there to deal with this problem? https://www.analytics-toolkit.com/referrer-spam/Secret.%C9%A2oogle.com/. If this problem still exists, we may wish to keep it.

> Digirati filter (IP address 87.236.134.47) - To keep? Is IP address still valid?

Yes to keep. We should check with them on whether that's still valid. There's a #digirati channel on slack (they're collaborators/still currently support the library site and the Production + Preservation teams' work).

> Staff filter (IP addresses 195.143.129.132 or 195.143.129.222 or 83.244.194.132 or 83.244.194.222) - Are these IP addresses still valid? Should any be added?

Try the #digital-team channel in Slack. Folks from D&T are on that channel and can advise on whether those are still valid.

> Merging "tickets.tygit.com" reset or email requests generic tickets.tygit.com usage - Drop?

Drop this. Its our former ticketing system, haven't had it for more than 18 months

**Comment by taceybadgerbrook** [comment]
The anti-secret spam filter is for filtering the problem described in your link but it's pretty basic.  Here's an article on how to filter out more sophisticated spam which looks worth implementing:  https://flothemes.com/remove-spam-google-analytics/

Am actioning the rest of the comments

**Comment by taceybadgerbrook** [comment]
Having pruned redundant/obsolete filters and updated others from both the old and new collection only Properties, the old Property is still returning more page views than the new Property (7,506 compared to 7,271.)  David and I spotted an additional trigger criteria for Prod: page equals /works, so have deleted this and will assess data for next complete 24h period (20/11) and decide whether or not this completes the updating of GA filtering.

**Comment by taceybadgerbrook** [comment]
As this ticket has been taken up with updating GA filters, I've created further tickets for implementing changes to goals https://github.com/wellcometrust/wellcomecollection.org/issues/4874
and events https://github.com/wellcometrust/wellcomecollection.org/issues/4875

**Comment by taceybadgerbrook** [comment]
Old property still returning higher page views than new property for data after Google Tag Manager filter removed using 24h period 20/11.  As the deleted GTM filter was for page views, below is a comparison of page views which are actually higher for new Property:


  | Old Property | New Property
-- | -- | --
19/11 | 7,354 users | 7,068 users
19/11 | 26,464 page views | 28,755 page views
20/11 first 24h period after GTM page filter deleted | 7,283 users | 7,037 users
20/11 | 25,894 page views | 27,180 page views

@jamesgorrie @gestchild 
I am closing this ticket because the filter work has been completed and these discrepancies appear to be about how Google Tag Manager is processing the data.  I am opening a new ticket https://github.com/wellcometrust/wellcomecollection.org/issues/4883
