### ISSUE TITLE
Documenting the Data Layer

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcometrust/wellcomecollection.org#4836]
As an analyst, I need to find or create documentation on the Data Layer for business continuity and also to support implementation of changes to Google Tag Manager to protect the integrity of the Data Layer.

Acceptance criteria
Documentation in Sharepoint

https://github.com/wellcometrust/wellcomecollection.org/issues/4341

**Comment by pollecuttn** [comment]
Decided to close at 2019/20 Q2 planning, followed by investigation of benefits/disbenefits of Google Tag Manager
