### ISSUE TITLE
Creating KPI reporting

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcometrust/wellcomecollection.org#4838]
As an analyst, I need to understand the data available in Elastic Search by Kibana queries and working with the Data Team in order to create KPI reporting.

OR

As an analyst, I need to use Google Tag Manager to tag workType, identifier, subject, genre and language (if not already tagged) so that I can analyse breadth of usage for DE and Collections teams to track progress on enabling researchers to engage with more of our collections.

Acceptance criteria
Able to produce KPI(s) from chosen tool.

https://github.com/wellcometrust/wellcomecollection.org/issues/4341

**Comment by jennpb** [comment]
@taceybadgerbrook We can leave language out of the GTM tracking. I don't believe we have a use case for analysing collection use by language. However, I would add in addition to identifier (e.g. `f4qaqqv6`) the reference (e.g. `Wellcome Library no. 42427i`). In future we'll have reference numbers for archive material that look like `PP/CRI` or similar, should be mapped to the same property in the API.

**Comment by taceybadgerbrook** [comment]
KPI reporting spans GA and Kibana which cannot be stitched together.  

Have created sharepoint doc below to express use cases described in https://docs.google.com/document/d/1gT2GIb4GMB6UbhGppXDgO3872D0Yv7sUe3I01dvq_b0/edit?usp=sharing to identify what data we don't have to inform discussion of alternative tools:

https://wellcomecloud.sharepoint.com/:w:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/Measuring%20use%20of%20our%20collections%20(data%20we%20have%20vs%20data%20we%20need).docx?d=w789b56b0e09e42ebae3e8c48fb3a488d&csf=1&e=S5iau0

**Comment by taceybadgerbrook** [comment]
Have created the discussion document and circulated for comment via Slack (Tom, Jenn, Jonathan, Christy, Danny.) Documentation of KPI discussion to sit with a new ticket. https://wellcomecloud.sharepoint.com/:w:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/4838%20Creating%20KPI%20reporting.docx?d=we3351ec1b9804afdab2aaef715bc827a&csf=1&e=EdAEvp
