### ISSUE TITLE
NewsletterPromo on Microsoft Edge 

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4841]
As seen on https://wellcomecollection.org/series/Xa8QaRAAACJUwLdl

Our lovely pattern turns into a big purple block:

![image](https://user-images.githubusercontent.com/1446139/68120273-cad9dd00-fefc-11e9-9c0e-7d4047a9529d.png)

## Acceptance criteria
- [ ] Promo design is consistent across all modern browsers.

**Comment by davidpmccormick** [comment]
The latest version of Edge (18) [supports css masks](https://caniuse.com/#feat=css-masks), but 17 and below don't.

I think we can either replace the CSS mask with an image to support older versions of Edge, or test for the support of css masks and remove the `RepeatingLs` component if necessary, so you'd end up with something like this if your browser didn't yet support masks:

<img width="841" alt="Screenshot 2019-11-04 at 17 48 43" src="https://user-images.githubusercontent.com/1394592/68144877-73ebfc00-ff2c-11e9-9255-02e46e154825.png">

Using an image adds a bit (possibly negligible) of extra page weight, and isn't as versatile as the mask, but works in more places.

Which solution do we favour (or do @wellcometrust/weco-experience-devs have any other ideas?)

**Comment by jamesgorrie** [comment]
Given that we've bought into progressively enhancing I would suggest we follow the "It's plain and we enhance it with Ls" - adding weight to older browsers, where, not always, but often, the connection can be worse seems slightly counter intuitive.

This is based on the assumption though that the Ls are considered enhanced content, as opposed to integral content.

**Comment by davidpmccormick** [comment]
I’d say that was what I was leaning towards, aye.
