### ISSUE TITLE
Stories survey for content team

### ISSUE THREAD

**Issue by Elltie** [wellcometrust/wellcomecollection.org#4862]
Assist content with writing a survey to add to pop up on stories pages on wellcomecollection.org page/s.

Help with the analysis of the results

**Comment by Elltie** [comment]
Pop up to be installed on all stories pages except stories landing page.
@taceybadgerbrook investigating whether a page referral can be gleaned

**Comment by Elltie** [comment]
Link to survey monkey https://www.surveymonkey.co.uk/r/GDWR9BD

**Comment by Elltie** [comment]
@davidpmccormick has found a way to tag on the referral page to the end of the survey monkey link and will familiarise himself with how to do this and how it works. Survey monkey username and password has been shared (as this is a paid feature)

**Comment by Elltie** [comment]
Copy for pop up 
"Help us improve our stories. We want to understand what you are interested in reading on our website"

**Comment by pollecuttn** [comment]
@Elltie Is there anything to add here after your meeting about this? Are there next steps?

**Comment by Elltie** [comment]
@pollecuttn Meeting is next week so will update then

**Comment by Elltie** [comment]
Deck can be seen here https://wellcomecloud.sharepoint.com/:p:/r/sites/wcdigitalexperience/_layouts/15/Doc.aspx?sourcedoc=%7B2BED7CE7-D57A-4A3E-BC25-AF582434EAC6%7D&file=Stories_Research%20201911.pptx&action=edit&mobileredirect=true
No next steps for Digital Experience team, DB will work with content team to make sure the insights are reflected in the upcoming stories and future plans.
