### ISSUE TITLE
Provide filtered search for images only

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4870]
# User story
In order to source images for my project
As a `Content Hunter`
I want to see all images that meet my interest, regardless of the format of its original.

# Problem to solve
We're working toward a whole collection search, but we still need to cater for the `Content Hunter` profile - someone who is looking for images to use in their creative/commercial/academic output, and may not want to dig through full books, manuscripts, etc. to find interesting stuff.

We need a way of exposing an option to `Search images only`

This would include
- worktype: Pictures
- worktype: Digital images
- worktype: Ephemera
... and anything else in the API that has an image property (confirm details with Data)

UI could do something simple like this as a start:
![images_checkbox](https://user-images.githubusercontent.com/1446139/69076549-a23d0180-0a2b-11ea-8700-0fac1eb2b501.png)

- Work card for image displays title as `From {title}`
- Deep link to image in viewer

Experimental image search prototype #4880

## Considerations
- [ ] Any event tracking?
- [ ] Cardigan documentation
- [ ] Success measures?

**Comment by jennpb** [comment]
Now at https://github.com/wellcometrust/platform/issues/4070

**Comment by jamieparkinson** [comment]
@jennpb can this ticket be closed after our discussions yesterday and with continuing work in other tickets?

**Comment by jennpb** [comment]
https://github.com/wellcometrust/platform/issues/4079
