### ISSUE TITLE
New interpretation type for events: Captioned

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4878]
We have a new interpretation type for events: Captioned.

Alice has set up the `eventPolicy` in Prismic, but we need to add the `closedCaptioning` icon to the policy, so she can then use it the same as BSL, STT and AD.

**Comment by pollecuttn** [comment]
closedCaptioning icon is at https://cardigan.wellcomecollection.org/?path=/story/global--icons
