### ISSUE TITLE
Spacing/styling of thumbnails in image viewer

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#4888]
Part of #4848

- [ ] thumbnail images are a fixed width of 130px
- [ ] horizontal and vertical spacing of thumbnails should be proportional to the browser width (need to establish exact proportions)
- [ ] thumbnail rows should be centred within the viewing area
- [ ] thumbnail rows should be left aligned with each other
- [ ] styling, see #4885

- Codepen for exploring how to achieve this: https://codepen.io/gestchild/pen/oNNQxwB

**Comment by jennpb** [comment]
@gestchild Is this one still open or was it done as part of recent changes?

**Comment by gestchild** [comment]
It was done and then superseded by the scrolling work.
