### ISSUE TITLE
Identifying search logic in Kibana data

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcometrust/wellcomecollection.org#4894]
**We think that**
More advanced researchers (Knowledge Gatherers) have distinct search habits that can be used to identify them.

**Therefore we hypothesise that**
If we look at search behaviour for longer sessions, we will see methodical changes in search terms as measured by variations in search terms or the addition of terms or use of terms appearing in works surfaced; pauses indicating use of other sites.

**We are right if**
If we see similar behaviour for more than 10 users.

**Comment by jamesgorrie** [comment]
@taceybadgerbrook This sounds like a super interesting set of data to get.

What might help is if we could get what you might expect the data to look like, and we can probably start doing some data transforms to get it as querying the current index would definitely not be good enough.

We can pair on that to so you know what functionality is available which might help inspire new ways of wanting the data.

**Comment by taceybadgerbrook** [comment]
Initially, I would look at sessions on a given day to produce the following:-
- histogram of the number of searches conducted before a search result is selected
- histogram of max page depth
- histogram of session length

All of these appear to be possible using data from search_result_implicit in Python - but please shout if the data is not what it seems!
