### ISSUE TITLE
Search filters: build per design

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#4926]
# Problems to solve
We need a more scalable solution to filters that 
- is more consistent on mobile
- is easier to scan a list of filters from a menu

New designs replace our current drawer UI with a set of drop-downs.

# Design rationale

Here's what we know:

- We anticipate having around 5 different filters (date, format, language, availability +- filters unique to view, e.g. license for online stuff)
- In the last 3 months, 82% of all /works usage on wellcomecollection.org is on desktop; this is same as wellcomelibrary.org. Researchers using our collections are overwhelmingly using a big-screen experience to search and manage their research process. 
- There is a strong UX case for keeping filters visible on desktop, so that researchers can see the filtering possibilities up front without having to open a filter panel
- Mobile UI conventions for filtering tend toward having single CTA, while desktop filtering tends to be more expansive. Asos, Airbnb and John Lewis are good examples of this. 

For now, we'll have a desktop and a mobile UI for filters:
- Desktop = filter categories exposed 
- Mobile = filter categories hidden behind single CTA

This is because the primary design principle of 'exposing possiblilty' is a lot harder to achieve on mobile, but we're not that concerned because the mobile 'researcher' doesn't exist in large numbers. If we see a big uptick in researcher-type page views on mobile, we can look at how we might expose the 5+ filters upfront so researchers can narrow down their search more quickly. 

**Considerations**
- Success measures
- URL design
- Event tracking
- Cardigan documentation

**Comment by pollecuttn** [comment]
@GarethOrmerod Please add a link to the designs on this issue, with the radio buttons switched

**Comment by GarethOrmerod** [comment]
The links below are for the 'Images Only' search results view which incorporate the filter designs:
https://zpl.io/anQJpLQ
zpl://project?tags=Search%20Results%20Images%20only&pid=5aab926b4b6efde01259e959

**Comment by pollecuttn** [comment]
@davidpmccormick Is this deployment enough to close #4926,  or is there still desktop filters work to do?

**Comment by davidpmccormick** [comment]
Done.
