### ISSUE TITLE
Creating baseline for image search analysis

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcometrust/wellcomecollection.org#4935]
**We think that**
Users searching for images will find the new image search facility enables them to see and compare images more easily.

**Therefore we hypothesise that**
Users searching for images will view and download a higher percentage of items out of total image searches as a result of using the new image search toggle.

**As measured by**
 event=search result selected and iiif viewer events in GA

**We are right if**
%  event=search result selected / total image searches increases compared to period prior to toggle being deployed

% iiif viewer events in GA / total image searches increases compared to period prior to toggle being deployed

This ticket is about producing the baseline.

**Comment by pollecuttn** [comment]
@taceybadgerbrook Were you closing this issue? I think I gave you the post it and I can't see it on the board in Doing or Done.
