### ISSUE TITLE
small change: placeholder text should be consistent on promo and /newsletter page

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#5024]
# Problem to solve

Inconsistency of placeholder text on `NewsletterPromo` and `/newsletter page`

# Changes

Placeholder text on both should read:

`Your email address`

# Future
Look across all of our form fields and come up with a way of not having to use placeholder text. Here are some recommendations:https://www.smashingmagazine.com/2018/06/placeholder-attribute/ (TL;DR - we shouldn't use them. We should be using field labels and helper text instead)

https://uxplanet.org/how-to-design-great-ux-for-sign-up-form-8ce39f84659

**Comment by davidpmccormick** [comment]
FWIW we do always have field labels for screenreader a11y, but we have hidden them visually in this instance.
