### ISSUE TITLE
Image search UI refinements: search results

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#5079]
Continuation from https://github.com/wellcometrust/wellcomecollection.org/issues/4927

We will use the fixed height design for the image search results.

# Implementation considerations
- Success measures:
What does success look like?
Will you need to set up additional tracking?
Have you talked to Tacey?
What is the expected life span for tracking?
- URL design
- Event tracking
- Cardigan documentation

**Comment by pollecuttn** [comment]
@GarethOrmerod Please add a link to the fixed height image search results design here

**Comment by davidpmccormick** [comment]
Visual design: https://app.zeplin.io/project/5aab926b4b6efde01259e959/screen/5de675440259f5576c699702/

**Comment by davidpmccormick** [comment]
I don't think this needs any additional tracking or Cardigan documentation, and doesn't concern URL design.
