### ISSUE TITLE
Remove 1px horizontal line visible above wobbly line

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#510]
![image](https://cloud.githubusercontent.com/assets/1446139/22925192/ae3e5f70-f29f-11e6-9eed-15b0937069b9.png)

**Comment by Norvard** [comment]
Just noticed it on my thunderbolt screen at home, but I dont get it at work screen. The line comes as goes as you resize the browser window.

![screen shot 2017-02-21 at 10 30 44](https://cloud.githubusercontent.com/assets/23660297/23161190/0baa8cf2-f821-11e6-8932-69ca93dde1b7.png)
