### ISSUE TITLE
Explore landing layout

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#519]
At mid size screens (approx. 930px) the layout can become weird:
![screen shot 2017-02-14 at 15 56 15](https://cloud.githubusercontent.com/assets/6051896/22936820/8d731da6-f2ce-11e6-90bc-e2bda2b48c16.png)

**Comment by Norvard** [comment]
Yea this needs some help. The title and text should never stack too much and should stay within 3-4 lines. As soon as the text begins to stack too much, the layout should break
