### ISSUE TITLE
Add Hotjar tracking code so we can use service to collect user feedback

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#525]
@jamesgorrie has been invited to join Wellcome's Hotjar account. This script needs to be inserted and verified, then I can test out surveys, feedback, funnels, heatmaps and so on.

This is the same tracking code currently on wellcomecollection.org. We can generate a new tracking code for Next if necessary.

````<!-- Hotjar Tracking Code for Collection -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:3858,hjsv:5};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
</script>````

**Comment by jamesgorrie** [comment]
Could we please invite @gestchild and @davidpmccormick?

**Comment by jennpb** [comment]
Of course! Done.
