### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#528]
# Rationale
There's still a small but loyal RSS user base for article content:

WC blog / Feedly subscribers = 238
WL blog / Feedly subscribers = 64
WL blog / Feedburner = 218

# Done when:
- feed aggregators can pull in latest published content from next.wellcomecollection.org
- RSS icon visible on site

# Considerations
* Make the whole article available unlike Wordpress

**Comment by jamesgorrie** [comment]
Is it possible to see which feed they've subscribed to? i.e. any that aren't the root feed.

**Comment by jennpb** [comment]
Closed in preference of #821
