### ISSUE TITLE
WC logomark that can be used in browser/on homescreens/as favicon

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#529]
[was #410]

Need to work with Wellcome design/comms team on this one.

**Comment by jennpb** [comment]
Design brief being submitted this week!

**Comment by jennpb** [comment]
@wellcometrust/experience-dev I have new svgs but GH doesn't like svg uploads. Let me know who wants to pick this up and I'll forward you the deets.

**Comment by jamesgorrie** [comment]
@jennpb upload it to slack!
