### ISSUE TITLE
Component audit

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#535]
Need to make sure all components have the necessary config file, with appropriate values/content for the component

**Comment by jennpb** [comment]
@gestchild @davidpmccormick an oldie but goodie? is this one still relevant?

**Comment by davidpmccormick** [comment]
I'd say that this was done decisively for Cardigan #1 (and probably should have been closed).

We'll have to do it for nu:Cardigan as well, but we _should_ be doing it as we go along and probably don't need another ticket for it

**Comment by gestchild** [comment]
I agree, I think we can close this
