### ISSUE TITLE
Length of standfirst on explore page

### ISSUE THREAD

**Issue by dannybirchall** [wellcometrust/wellcomecollection.org#543]
On the next/explore index page, the standfirst for the top story (currently ladies of L) gets ellipsesed out -- seems like there's lots of room for the full standfirst there, can it be expanded?

**Comment by jennpb** [comment]
The existing standfirsts as they are aren't very useful in the Explore page context. We have a lot of repeated text from article to article. I'd suggest we park standfirsts for now, and take a different approach, such as adding publication date and authors (though authors may not be possible either given what @jamesgorrie concluded in #449) 

@derivadow has also cited research done to show that NOT having standfirsts/article summaries results in better performance. Obv this is something we'd want to test in the future, but given that the standfirsts aren't article summaries anyway, we can take this opportunity to hide them.

**Comment by dannybirchall** [comment]
Confused of Camden here. 

I feel like it's pretty standard on any editorially-driven site to have a standfirst under the headline. Even quartz does it! I'd rather rewrite existing standfirsts in wordpress for the content that comes through than just lose them all.

**Comment by dannybirchall** [comment]
Is a differential solution possible? Keep (full) standfirsts for the Big 4, lose them for the rest?

**Comment by jamesgorrie** [comment]
@jennpb as we use promo text now, is this still an issue?
