### ISSUE TITLE
Right rail images

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#551]
[RED]

In the top featured article "The Ladies of Llangolen", inside the article can we apply the in-line images to the right rail so we can go live with one of our super design features :)

The articles has really nice image which we can test this feature with.

**Comment by jennpb** [comment]
@RussellDornan is on it!

**Comment by jennpb** [comment]
Closing this because I believe it to be in hand! The Llllllladies post was updated.
