### ISSUE TITLE
Theme component - key lines

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#556]
[ORANGE]

Key lines should separate article columns, not the top row and bottom row

![screen shot 2017-02-17 at 10 36 52](https://cloud.githubusercontent.com/assets/23660297/23062359/5d4682fe-f4fd-11e6-85fb-1bf198771cfe.png)

**Comment by jennpb** [comment]
Connected to #351

**Comment by jamesgorrie** [comment]
@jennpb how?

**Comment by Norvard** [comment]
#351 is the design example for the Theme component
