### ISSUE TITLE
Theme component collapse

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#558]
[YELLOW]

When the component is collapsed smaller in browser size. The stacking of the promos is odd and off balance. The hierarchy in size should always be: top article larger, bottom articles smaller. In the example below this hierarchy is switched

![screenshot-next wellcomecollection org-2017-02-17-10-50-21](https://cloud.githubusercontent.com/assets/23660297/23062830/500987ba-f4ff-11e6-85a7-dc045ab83c9c.png)

**Comment by jamesgorrie** [comment]
As discussed with @Norvard and @davidpmccormick:

`n` is the number of promos.
* The top row will always have the lesser of `n/2`
* The top row will never have more than three

e.g.
n of promos | top row | bottom row
-------------|---------|------------
 1 | 1 | 0
 2 | 1 | 1
 3 | 1 | 2
 4 | 2 | 2
 5 | 2 | 3
 6 | 3 | 3
 7 | 3 | 4
 8 | 3 | 5
 9 | 3 | 6

**Comment by davidpmccormick** [comment]
Superseded by work in #607.
