### ISSUE TITLE
Distinguishing standfirsts from epigraphs

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#559]
[RED]

Can we apply our quote styling to the quote which begins the article text.

Since its common practice to have a stand first and a quote to start an article, we might have to experiment more with this styling but for now lets definitely apply the quote style we have in the toolset.

![screen shot 2017-02-17 at 11 03 39](https://cloud.githubusercontent.com/assets/23660297/23063177/0813bc62-f501-11e6-9f34-34298d919467.png)

**Comment by jennpb** [comment]
@dannybirchall @Norvard this connects to the conversation about epigraphs. Is the default block quote style appropriate for epigraphs? https://cardigan.wellcomecollection.org/components/detail/blockquote--default.html

I don't know one way or the other - what do you think?

**Comment by Norvard** [comment]
I would like to test the current style we have rather than just italic text. We might need to revisit or explore it more later but for now I think our quote style will look better than just italic :)

**Comment by dannybirchall** [comment]
Think I might need to see what it actually looks like. My feeling is we might need a variation for actual epigraphs.

**Comment by Norvard** [comment]
Quick mockup:

![screen shot 2017-02-17 at 11 23 27](https://cloud.githubusercontent.com/assets/23660297/23063662/9bce6ee6-f503-11e6-8039-84a9a7468e91.png)

**Comment by Norvard** [comment]
My proposal ideally would be to get rid of the black line in the stand first, **IF** there is a quote after. Not sure if this is something we can do quickly and in that case I would use the previous example before italic text. Anything but italic text and non-hanging quotation marks! :-D

![screen shot 2017-02-17 at 11 24 59](https://cloud.githubusercontent.com/assets/23660297/23063767/1f742330-f504-11e6-9ec2-8380a6ecef5f.png)

**Comment by dannybirchall** [comment]
That looks too much like a pull quote to me -- both obtrusive and invisible.




Sent from Samsung Mobile on O2


-------- Original message --------

**Comment by Norvard** [comment]
Another option would be to create another styling for this while keeping stand first styling, a less obtrusive quote style:

![screen shot 2017-02-17 at 11 50 02](https://cloud.githubusercontent.com/assets/23660297/23064319/5a566636-f507-11e6-9c4c-6152f76cdfc4.png)

**Comment by dannybirchall** [comment]
prefer this style, bigly

**Comment by RussellDornan** [comment]
thumbs up

**Comment by Norvard** [comment]
Ive created a new issue to build this: #573
