### ISSUE TITLE
Alternative quote style

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#573]
To accommodate recent articles which feature a quote directly after the stand-first, we need to add a new quote style which can only be used in this particular area of an article.

Text size is same as normal body copy. Indent text 30px from the left and add larger quote mark (Helvetica). Quote reference name is same style as other quote styles

![screen shot 2017-02-17 at 14 51 45](https://cloud.githubusercontent.com/assets/23660297/23072482/b7201d9a-f529-11e6-9c0b-d87c687157dd.png)

**Comment by jennpb** [comment]
Discussed this design with @Norvard today and we agreeed that it looks better with the bold quote to start the epigraph, but leave off the smaller quote marks at closing. Looks good as a short one/two-liner as well.

**Comment by jennpb** [comment]
I'd like to make sure we use this small quote style in articles now.
https://cardigan.wellcomecollection.org/components/detail/blockquote--small.html

@jamesgorrie @davidpmccormick @gestchild What needs to happen from an editorial POV to style these quotes in articles? 

@dannybirchall @RussellDornan @Norvard

**Comment by jamesgorrie** [comment]
Nothing from an editorial POV.
We're probably best to name this blockquote, and the other pullQuote for clarity.

**Comment by jennpb** [comment]
...and correctness! :nerd_face:
