### ISSUE TITLE
Use of sentence case in 'More from...' links

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#575]
Wellcome house style has been to use sentence case for web titles and headings. It may be time to revisit this!

For accessibility reasons, it's best that link text is specific to its destination. If we had several theme blocks on the page, we can't have multiple links that say 'More from this series'.

However, this just looks terrible!

Editorial and Design thoughts most welcome @dannybirchall @RussellDornan @Norvard 

![image](https://cloud.githubusercontent.com/assets/1446139/23072382/67c1d7d4-f529-11e6-99f0-1a82c5c4d5f3.png)

**Comment by dannybirchall** [comment]
--> A drop in the ocean
 --> A drop in the ocean: more 
 --> A drop in the ocean: more from this series

**Comment by jamesgorrie** [comment]
From and accessible language POV:
`A drop in the ocean: more from this series` works nicely as it makes it work as a standalone link.

**Comment by jennpb** [comment]
What other instances might we have need of 'more from'? 
- Blabby blab blab: more from this digital story
- Blargh blah blooomps: more from this theme

We're not the only ones with the More... quirk: 
![2017-02-23_1916](https://cloud.githubusercontent.com/assets/1446139/23275002/af9e5b72-f9fc-11e6-8455-029aa95505fd.png)

**Comment by jamesgorrie** [comment]
My only concern is using the word theme / digital story is our language and doesn't, if the link is out of context (which it can be for many reasons, screenreaders being one of them), make sense.

The page scans well too if we use the theme name, A drop in the ocean is a great title.

**Comment by davidpmccormick** [comment]
We could downcase the title (using CSS) and add quotes:

More 'a drop in the ocean'

Although that would break for e.g. a series with an acronym/abbreviation capped up as the first word:

More 'lOL cats'.

Probably a bad idea.

**Comment by jennpb** [comment]
@jamesgorrie I agree, but you and danny have already suggested 'more from this series' which implies that 'series' is a meaningful word - I was just trying to explore more of the cases we might bump up against.

Let's try using simply the series title, so ```A drop in the ocean```, ```LGBT month``` etc.

**Comment by jamesgorrie** [comment]
> We could downcase the title (using CSS) and add quotes:

We shouldn't be styling content that way - we can however validate it around a set of editorial house rules. We can set those before migrating Wordpress content.

An example of where this would go wrong programatically is LGBT as you've mentioned.
