### ISSUE TITLE
Make footer map easier to read

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#587]
From user feedback, the footer map is really tiny, both in terms of focal point and overall size within the footer.

Need some more design thinking on this.

Here's a screenshot from @mildlydiverting 

![image](https://cloud.githubusercontent.com/assets/1446139/23132371/499cc896-f785-11e6-98e4-9ab6c5e51358.png)

**Comment by jamesgorrie** [comment]
With user feedback we should be making sure we have enough data to justify the better decision. Else we're putting ourselves at risk of making it better for one, and worse for another. 

Not saying that we shouldn't do this, just making sure we don't just do every request.

> Need some more design thinking on this.

Shows we know this, just reiterating.

**Comment by jennpb** [comment]
I'd rather raise an issue in Github when I get the feedback, rather than holding it for when I want to action it. I'll label things like this so we know more work is needed to understand what the problem is, and the best way to fix it.
