### ISSUE TITLE
Right-hand rail image overlap

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#593]
When an image lower on the page in the RHR replaces one higher on the page, the one above currently fades out _above_ it. The lower image should probably appear to slide over the higher image.

E.g. https://next.wellcomecollection.org/articles/the-power-of-posture/ 

![screen shot 2017-02-21 at 10 17 33](https://cloud.githubusercontent.com/assets/1394592/23160623/188c874c-f81f-11e6-80e6-936060f58a97.png)

**Comment by Norvard** [comment]
There is also another ticket about the fading effect. These rail images should always move down and when they bump up against the next one, they stack and both move. But they should never fade in or out, just move, stay visible and stack.

**Comment by Norvard** [comment]
If someone takes on the rail images, we could just chat about them in general to make sure we get all the details out in same go. If that makes sense from dev POV...

**Comment by gestchild** [comment]
If they stack, what happens if the previous image is longer than the current one? It would look weird sticking out below.

**Comment by Norvard** [comment]
The previous image moves out of view and priority is given to the new image which has appeared

**Comment by Norvard** [comment]
The new image which appears into view from below due to scrolling pushes the last image above it. Does that make sense? :)

**Comment by gestchild** [comment]
It does, but that might be difficult to achieve... I'll have a think

**Comment by Norvard** [comment]
Alternatively the past image would just stay in place, on the spot where it stopped because another image came along. The new image then picks up and follows the reader. Main thing is to avoid images overlapping of fading in/out.

Im trying to find an example of this on the Kinfolk site. They might have something similar

**Comment by gestchild** [comment]
Relates to #574

**Comment by davidpmccormick** [comment]
This bug is so hip – it's only replicable in Opera, and even then, only if you have the dev tools open! Suggest we close it (as 1. it's ridiculously niche and 2. it won't be a thing once we've dealt with #574).
