### ISSUE TITLE
Wordpress body parsing issues

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#596]
* When adding an image at the very top of the page that is aligned-left / RHR, we error
* Adding empty headings errors
* Images without captions align-left/RHR
* Images in RHR don't follow me down the page on Chrome.

**Comment by jennpb** [comment]
@jamesgorrie @gestchild @davidpmccormick 
Anything you want to do with these four problems as a stopgap solution, before we get into the task of sorting out what to use instead of Wordpress?

If you think this should be closed, please do. Otherwise i'll move it to our next Q board.
