### ISSUE TITLE
Shut down public view of WC blog

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#635]
Phase 1: Continue to use blog for content management, use it as a redirection service
- [x] In Drupal, replace all blog references with corresponding `next.` link
~~- [ ] Redirect DNS~~

**Comment by jennpb** [comment]
For the first phase of decommissioning Wordpress, we need to redirect all blog posts, categories, pages to a corresponding place on `next.`

**About pages:**
``/about`` and ``/about/terms-and-conditions`` - 404

**Date pages:**
``/date/YYYY/MM/DD/slug`` becomes ``/articles/slug``

**Categories**
There are 47 of these in Wordpress, one of which has already been mapped to ``/series/a-drop-in-the-ocean``. Following that logic, all `/category/slug/slug` should map to `/series/slug`.

Whitelist all parent and child categories
Exclude `/category/uncategorized`

All series require a brief summary, so this is something for @dannybirchall's team! Not urgent, but should be done as/when a series is highlighted on Explore.

**Tags**
We have 2400+ unique tags, including tags:
- with 0 associated posts
- slight variations of other tags
- a few incomplete/misspelled
- with overlaps of Categories (e.g. when a blog post is assigned the same tag and category)

I would suggest we leave `/tag/tagname` without a correponding URL on `next.` until such a point when we decide how to deal with this taxonomic problem (also taking into account Library blog if necessary).

@jamesgorrie does all this make sense?

**Comment by dannybirchall** [comment]
Content tasks noted, ta.

From a CMS editing perspective, we'll also need to add exceptions for URLs with /stats /posts etc 

(it can also get complicated bc there's some functionality that's also available directly at blog.wellcomecollection.org when you're logged in)

We could add IP-based exceptions for when we're in the building, at least?

**Comment by jamesgorrie** [comment]
>  In Drupal, replace all blog references with corresponding next. link

I'm not 100% sure what you mean by this?

>  Redirect DNS

Let's not have this as a task as it's probably not going to be that, but rather building a router service or the likes.

> About pages 404

[We do have pages like this](https://wellcomecollection.org/what-we-do/about-wellcome-collection) - would the better option not be to redirect to whatever page we think is most appropriate.

> I would suggest we leave /tag/tagname without a correponding URL on next.

We could potentially have a stopgap of having a next.wc.org/search?q=tag:tagname, but let's see how often the tags are used.

**Comment by jamesgorrie** [comment]
@dannybirchall 

> We could add IP-based exceptions for when we're in the building, at least?

I'm not sure I 100% see where you would want this?

**Comment by jennpb** [comment]
>In Drupal, replace all blog references with corresponding next. link

>I'm not 100% sure what you mean by this?

Ignore this! I thought we'd talked about changing links on wc.org where they occur, but we don't have to worry if we're redirecting to next. URLs.

> Redirect DNS

> Let's not have this as a task as it's probably not going to be that, but rather building a router service or the likes.

Noted and struck out

**Comment by jennpb** [comment]
> I would suggest we leave /tag/tagname without a correponding URL on next.

> We could potentially have a stopgap of having a next.wc.org/search?q=tag:tagname, but let's see how often the tags are used.

'How often the tags are used' - There's no way for us to see this data from WP Stats so I don't know how often they're used. I think it's ok to have the stopgap as you suggest but would that mean having index pages as well?

**Comment by jamesgorrie** [comment]
@jennpb Are the stats maybe available on the `/stats` endpoint (that I can't find) that @dannybirchall is talking about?

**Comment by jennpb** [comment]
No, that's where I'm looking. I've exported a CSV of all pages accessed in ALL TIME and I can't see any evidence that it's counting `/tag/tagname`

**Comment by jamesgorrie** [comment]
@jennpb re: about pages.
Do we want to just redirect those two pages to: https://wellcomecollection.org/what-we-do

**Comment by jamesgorrie** [comment]
Or:
`https://blog.wellcomecollection.org/about/ => https://wellcomecollection.org/what-we-do/about-wellcome-collection`
`https://blog.wellcomecollection.org/about/terms-and-conditions/ => https://wellcome.ac.uk/about-us/terms-use`

**Comment by jennpb** [comment]
@jamesgorrie Yes to that ^

**Comment by jamesgorrie** [comment]
We can't forget about the RSS!

**Comment by jamesgorrie** [comment]
# RRS
* https://blog.wellcomecollection.org/feed/ => https://blog.wellcomecollection.org/feed/ (Wordpress)
* https://blog.wellcomecollection.org/category/a-drop-in-the-ocean/feed/ => https://blog.wellcomecollection.org/category/a-drop-in-the-ocean/feed/ (Wordpress)

# Content
* https://blog.wellcomecollection.org/tag/lgbt/ => https://next.wellcomecollection.org/articles?q=tags=lgbt
* https://blog.wellcomecollection.org/2016/12/15/cholerics-the-real-drama-queens/ => https://next.wellcomecollection.org/articles/cholerics-the-real-drama-queens
