### ISSUE TITLE
Enable hanging punctuation in body text

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/wellcomecollection.org#637]
Current appearance:

![screen shot 2017-03-02 at 10 02 02](https://cloud.githubusercontent.com/assets/301220/23502321/55df041e-ff2f-11e6-8d7a-62c5c9876d70.png)

Look at that paragraph that starts with a double quote. That doesn’t look very nice. Booooo.

This is what I see if I add `hanging-punctuation: first` to the style of `p`:

![screen shot 2017-03-02 at 10 02 24](https://cloud.githubusercontent.com/assets/301220/23502381/9692afec-ff2f-11e6-92d2-82ec287d7c36.png)

All the words form a nice left edge. Doesn’t that look much nicer?

I suggest enabling this on all body text.

**Comment by jennpb** [comment]
This is going to be a lot of effort and too fiddly to fix in a way that works across all browsers.
