### ISSUE TITLE
Crediting more than one contributor per article

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#659]
Here's a new design problem. 

We may need to credit more than one author per article, or an author + photographer. Here's an example where the author+photographer credits have been put in the bottom of the article

![image](https://cloud.githubusercontent.com/assets/1446139/25627442/8173924c-2f5a-11e7-9c53-cb69f5f6ec98.png)

Roles that could be involved:
- author
- photographer
- artist
... and so on.

**To Do**

- [x] Clarify scope with Content Team
- [ ] Content model 
- [ ] Visual design

**Comment by Norvard** [comment]
Multiple contributors/credits text element

**Comment by jennpb** [comment]
@Norvard I was going to put in the list of questions that I sent you about your first designs, into this issue, but they've disappeared from #927. Do you have access to these comments anywhere?
