### ISSUE TITLE
Publishing webcomics as articles

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#663]
Components:

- One image comprised of 4 panels (2-up, 2-down): https://wellcomecloud.sharepoint.com/sites/wcdigitalexperience/Shared%20Documents/Webcomics
https://next.wellcomecollection.org/articles/preview/13209
- Comic title (Rob may not assign his own titles, but we may want to use short titles, eg Teeth)
- Series title : Body Squabbles
- Author component : Rob Bidder
- Rights/license detail - CC-BY-NC 4.0 per agreement with Rob. It must be visible on page and machine-readable https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license

Content needed
- [x] Summary - to describe Body Squabbles as a series for promo

**Comment by jennpb** [comment]
Rob Bidder's webcomic will be easy-ish, but here's another example of several comic strips on a page: https://next.wellcomecollection.org/articles/the-transvengers-webcomic/

**Comment by Norvard** [comment]
@jennpb The above requirements. Do those need to just be on the comic article page, or both on article page and if the comic is shown on a promo type of module on Explore landing?

**Comment by jennpb** [comment]
@Norvard Not sure. 

In terms of licensing, I would say that if the comic is displayed as a small image merely as a promo, and you really need to see the whole article to read the comic, then the license doesn't need to appear on the promo. But if we were using a larger scrollable promo style that you designed initially, where a reader could consume the whole comic in that component, then yes, we would need to make the license clear. 

There are a lot of similarities between a webcomic and an item/image page (like, more so than an article, in terms of supporting content for the image.

**Comment by Norvard** [comment]
@jennpb 
Yep makes sense. I will take a look at some options for this next week. Sounds like we need a bit more design thinking added to the initial thing I created

**Comment by jennpb** [comment]
Related design issues:
#803 
#804 
#805 
#806

**Comment by jennpb** [comment]
@davidpmccormick @Norvard: here are @dannybirchall's responses for the record 

**Is Body Squabbles finite?** 
Like a column, it’s on an ongoing series that goes on until it doesn’t any more. So it’s effectively infinite.
**JPB: No series navigation needed.**

**Publication cycle**
I’d like to build the expectation that it’s published every Friday morning (this being something that we can then test as an effective publishing schedule). **No need to indicate the content of the ‘forthcoming’ one.**

**Would there be a main image to represent BS as a series?**
Good question. Not at the moment, but I could ask Rob.

**Any logic to sequence? Is there any requirement to indicate part?**
No overlying narrative or arc. No particular need to indicate part

**Will each individual comic have its own title?**
Rob hasn’t given it one as such. I’ve discussed it with him, I think he’d be happy to/for us to do. Personally I prefer short titles like ‘Teeth’ ‘Thirst’ etc.

**Any additional supporting content we need to take into account now?**
Not at the moment.

**Intention to publish the first 4 over 4 weeks?**
Yes. Once we start I’d like to be able to commit to publishing one a week every week, ongoing.

**Comment by Norvard** [comment]
All that sounds good and by the looks of it, wont have any effect on what we are currently shooting with MVP.

Once its live and kicking, we can then see how the format informs future improvements.
