### ISSUE TITLE
Promo for Image Gallery as Main Article

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#667]
Here's Tomi's first go at a design. Team should discuss before getting started.

![image](https://cloud.githubusercontent.com/assets/1446139/23753082/06ce63b4-04d0-11e7-860b-c1ffc0610b56.png)

Title
Lead image
Summary
Total number of images
Format index: Image gallery > aggregate on /image-galleries

**Comment by jennpb** [comment]
pinging @Heesoomoon and @GarethOrmerod - a stale idea for an image gallery card.

**Comment by Heesoomoon** [comment]
Noted. It will be good to explore an option of displaying more than one image to represent the image gallery. Hinting there are more to see but not fully exposing everything.

**Comment by jennpb** [comment]
I'm going to close this one now as it's too stale!
