### ISSUE TITLE
Related YouTube video feature on mobile interferes with play button 

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#694]
The article videos play as expected on mobile (iPhone). But when you stop the video, the related video strip is overlaid over the play button and you can't close it. 

![img_0376](https://cloud.githubusercontent.com/assets/1446139/24211013/bc94083c-0f22-11e7-9659-00d02bfb6055.PNG)

**How it should work**: It should show related videos at end of video. It should also allow easy access to the play button.

**Comment by jamesgorrie** [comment]
Are we 100% sure we don't want to do this for any videos - or just for some?

**Comment by jennpb** [comment]
Under what circumstances would we want to hide the play button?
Would we want to show related videos in the middle of a stopped video, or should it only appear at the end?

I'm not pushing back, but it's an interesting question  - alongside related videos there will be Wellcome Collection videos mixed with others that YouTube recommends. In all cases, the user may click on one and it will go straight to YouTube (as you'd expect!) But this bypasses any WC articles that include videos within that related set. Not saying this is wrong or right...it's just a behaviour we need to be aware of.

**Comment by jamesgorrie** [comment]
> Under what circumstances would we want to hide the play button?

This is actually a YT problem - I'm assuming that they think that you've got to the end so there you go. Non-ios devices have a replay button on the YT chrome (which you can't do reliably on IOS, so they don't).

I think the question about related videos is a good one as we can turn that on and off - but fixing YT's UI is not something we have control over.

**Comment by jennpb** [comment]
I agree - don't want to worry overmuch about YT's UI. It's just that the behaviour is different on our site between full and mobile. On large screens, pausing the video in the middle does just that, and doesn't show the related videos, while on mobile it does.

If there's a way to switch off related videos if the YT video is embedded in WC.org, that seems to be the most sensible thing. Would that work?
