### ISSUE TITLE
Displaying chapter indicators on digital story promos

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#727]
We're missing the chapter indicators on the main image and promo. According to the digital story system, 
- Thunderbolts and lightning should have one bar... subsequent parts pick up bars that correspond to each chapter
- This pattern should be displayed on both the article hero and in the promo on Explore.

https://wellcomecloud-my.sharepoint.com/personal/t_lahdesmaki_wellcome_ac_uk/Documents/Design%20delivery/Digital%20Story%20Elements/WC_Digital_Story_20170223.png

**Comment by davidpmccormick** [comment]
I'm lost in the server-side code regarding how to get an article's position within a digital story for either the article pages or on the promos (to display e.g. on the explore page). Shelving as 'help wanted' for now cc. @jamesgorrie .

**Comment by jamesgorrie** [comment]
Yea, we'll need to have think about this - I don't really know what the answer is.

**Comment by davidpmccormick** [comment]
Help received – editors are adding `chapterX` tags to each piece, enabling us to determine an articles position within the story.
