### ISSUE TITLE
Inline image gallery: designing for longer captions

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#728]
![img_0382](https://cloud.githubusercontent.com/assets/1446139/24497505/9238b922-1533-11e7-8620-4dab0abdf87b.PNG)
![img_0381](https://cloud.githubusercontent.com/assets/1446139/24497507/93181748-1533-11e7-9f84-dca3023f9925.PNG)

This appears on mobile (iPhone 5 SE). I checked the article in WP for any extra spacing but didn't see any.

**Comment by jamesgorrie** [comment]
This isn't a bug - it's because the images further in the gallery have large captions.

**Comment by jamesgorrie** [comment]
A solution could be to add a `more...` link to the image.
I personally think there must be a better design solution (not sure what / potentially an info button that raises the caption or something)

**Comment by jennpb** [comment]
Of course, i see that now. Too hasty in calling this a bug. I'll change the details on this issue and ask @Norvard to look at this as a design problem.

**Comment by jamesgorrie** [comment]
He had a "more" button as a design solution:
![screen shot 2017-03-31 at 09 55 19](https://cloud.githubusercontent.com/assets/31692/24543631/32df13d4-15f8-11e7-94b3-f669c4aa1d8b.png)
