### ISSUE TITLE
Digital story: Solidify logic around part indicators

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#729]
From Tom:

> Chapter counter – the counter/ set of vertical bars within the article nav is fixed at 6. Can it indicate the chapter number you’re on?

The system was built to show total number of parts, so this would add more complexity to the sticky nav. Will hold off on this for now – would prefer to test to see whether readers pick up on this before adding complexity.

**Comment by jamesgorrie** [comment]
Yea - could we change this issue to something along the lines of:

# Solidify logic around digital story indicators

We can probably add some qualitative user research, although, I paraphrase @Norvard: This was never meant to be a practical indicator, but a abstracted version. 

On that I would suggest we use something more conventional to indicate position e.g. 1/6

**Comment by jennpb** [comment]
Done!
