### ISSUE TITLE
Alternatives to Twitter byline in articles

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#730]
From Tom:

> Not just twitter in by-line – can we extend the by-line component to include links to things other than Twitter (personal websites, other social media services, ORCiD etc.)

Problem to solve:
* Authors might not be on Twitter, or want to use their Twitter account
* Linking up with other content via an authority
* Provide some context around the author (one idea: experiment with short bio (eg. Jenn P-B / librarian, flaneuse, author of award-winning books))

**Comment by jamesgorrie** [comment]
As we're using the [Person schema object](http://schema.org/Person) as a base for this - we have a list of [`sameAs` attributes available](http://schema.org/sameAs) - so yes definitely - although UI wise I image we might want to choose a priority of what to show.

**Comment by jennpb** [comment]
Here's an example of something we might like to try (from Medium)
![2017-03-31_1122](https://cloud.githubusercontent.com/assets/1446139/24546711/7625acc8-1604-11e7-84fe-6dbef50eb929.png)

**Comment by jamesgorrie** [comment]
What are we trying to achieve with this?
Is part of the author block to help authors get more recognition?

**Comment by jennpb** [comment]
By providing social media accounts it can help amplify authors voices (by being mentioned in a tweet, FB post, etc), and encourage them to work with us again.

By providing a really short bio, it gives context for the article itself. A Visitor Experience Assistant's article may be vastly different from someone whose tiny bio says 'Medical historian'.

**Comment by jamesgorrie** [comment]
@jennpb @Norvard do we have real examples of how we want this to work so I can build it into the model.

By the looks of things we have:
* Name
* Photo
* Snappy whoami
* twitter handle
* website
* description

**Comment by jennpb** [comment]
Other IDs: 
- LinkedIn, 
- ORCID ID (eg http://orcid.org/0000-0002-4387-3384)

Of all, I think the ORCID ID is the most interesting one because it is stable and would allow us to link researchers to their work.

**Comment by jamesgorrie** [comment]
@jennpb happy to add those when there's a requirement - do we have one yet?
i.e. an example of an author that needs it?

Only asking as it's really easy to add, but trying to limit complexity.

**Comment by jennpb** [comment]
Nope, not yet!
