### ISSUE TITLE
Image credit/reference on hero images

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#731]
We currently don't display any information to help identify hero images in articles. This needs to be resolved somehow so we can:
* Respect intellectual property
* Reduce workload of staff who may need to help identify images
* Improve SEO

**Comment by pollecuttn** [comment]
This would need to be for all images, not just hero images, wouldn't it?

**Comment by jennpb** [comment]
Yes, that's a separate issue.

**Comment by jamesgorrie** [comment]
We don't have a way of doing this as media comes from wordpress.

There are the options we have:
![screen shot 2017-03-30 at 12 35 00](https://cloud.githubusercontent.com/assets/31692/24502367/615d13cc-1545-11e7-97c4-3ebc763ab46d.png)

I would be loathed to hack this in, as this is a 100% structured content challenge, which Wordpress doesn't support.

**Comment by jamesgorrie** [comment]
This is done.
I'd say the whole copyright UI needs work, but it's definitely done.
