### ISSUE TITLE
Centering play button within a Video element

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#732]
![img_0383](https://cloud.githubusercontent.com/assets/1446139/24498130/8a0cbca6-1535-11e7-9433-d0ff4b051a43.PNG)

The placement of the play button is a bit off-centred. Can this be fixed please?

**Comment by jennpb** [comment]
Alternatively, we bring in the timestamp and adjust spacing accordingly. What do you think @davidpmccormick @gestchild ?

**Comment by davidpmccormick** [comment]
I think we should take the margin off the right of the icon and add it to the left of the timestamp, then everything should have appropriate spacing regardless of whether the timestamp exists.
