### ISSUE TITLE
Indicating parts for digital stories in promos

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#770]
It would be helpful to show the digital story Title and Part on the promos, e.g. Electric Sublime: Part 1
Here's one option: 
![image](https://cloud.githubusercontent.com/assets/1446139/24870241/99170a9a-1e0d-11e7-876b-fcf773dcbeff.png)

The problem with this option is that it is also an Article type, so it introduces inconsistency with all other one-off articles. However, we do use 'Video' .... so would it be a mess to introduce a Title in this way? 

Other ideas? 

@Norvard @dannybirchall @RussellDornan

**Comment by Norvard** [comment]
I wonder if one solution could be to say:
"Digital Story: part 02"
This would indicate type of content, while also calling out the chapter number.

This is not ideal... and 100% consistent with the system. However we shouldn't always be tied to a system and things should be flexible enough to evolve and change as we make this all a reality.

**Comment by jennpb** [comment]
@Norvard In terms of priority, I'd say the story title (Electric Sublime) is more important than its content type. Especially once we have more digital stories - we can't have promos with two different digital stories showing Digital Story: Part 02. 

There is some rationalizing to be done here, I think:

Electric Sublime is a Series (/series/electric-sublime) that can work the same way as https://next.wellcomecollection.org/series/a-drop-in-the-ocean. The difference being that the parts are connected via the grid pattern and the series navigation.

Body Squabbles (the webcomic), is also a series type: It has a main title (Body Squabbles), distinct parts, and will need an index page. 

Content types also have index pages:
All articles
All video
All webcomics

I think we should chat with Nancy adn @jamesgorrie next week!
