### ISSUE TITLE
Digital story nav - current view

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#779]
The article card in the navigation, which corresponds to the article you are on, should be flush left in the navigation. It should move right next to the digital story title block. The users would then have to click the left arrow to reveal previous articles.

![screen shot 2017-04-11 at 16 12 01](https://cloud.githubusercontent.com/assets/23660297/24916466/1eae3092-1ed2-11e7-95b9-f3abe643797f.png)

**Comment by gestchild** [comment]
Just wondering what would happen in the view below, if either 4, 5 or 6 were the currently viewed item. If we aligned them immediately to the right of the story title block, the'd be increasing amounts of whitespace between the last item and the control.

![screen shot 2017-04-13 at 10 57 46](https://cloud.githubusercontent.com/assets/6051896/25000166/3394aa92-2038-11e7-9b02-de38fda02a75.png)

Thinking we should just ensure that the currently viewed item is visible in the navigation when the page loads and maybe have some other way of highlighting it, other than just the text?
