### ISSUE TITLE
Digital story nav key lines

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#783]
Can we make the key lines inside the navigation bar match the key lines we have dividing columns/content within the article body?

![screen shot 2017-04-12 at 13 14 14](https://cloud.githubusercontent.com/assets/23660297/24957043/390a0942-1f82-11e7-8f71-51be39d1beb6.png)

**Comment by Norvard** [comment]
Especially important for the key line at the bottom of the nav:

![screen shot 2017-04-12 at 13 17 00](https://cloud.githubusercontent.com/assets/23660297/24957089/6b26ef6c-1f82-11e7-840c-44cea2172070.png)

**Comment by jennpb** [comment]
What is it about them that doesn't match @Norvard?

**Comment by Norvard** [comment]
The key line used in the body area is ever so slightly darker. If we can darken the key lines in the nav, then the grey "coming soon" containers wont bleed into the background like @pollecuttn pointed out on Slack.
