### ISSUE TITLE
Digital story: are visual cues and navigation helping readers to know where they are?

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#786]
**Research questions**
- What cues are present to help readers understand where in a story they currently are? Are these cues working?
- Can readers identify which part they're reading from the navigation?
- What about unpublished parts?
- Meaningful labels: chapter, part

**User journeys**
- Social media > Chapter 3 > to where next?

See also #779 #780 (Closed)
https://wellcome.slack.com/files/pollecuttn/F4XDX5R9N/tab.png
![image](https://cloud.githubusercontent.com/assets/1446139/24965633/86ce9e3a-1f9c-11e7-851d-c528ec8de76c.png)

**Comment by hthair** [comment]
Is this going to be one of the first usability studies I conduct? Or did you have a more immediate solution in mind? (such as using scroll depth when that is 'live')

**Comment by hthair** [comment]
**Tests**
[ ] A/B sticky nav removed on mobile
[ ] A/B transporter for digital stories (on individual story page) is this increase

**Comment by hthair** [comment]
**Tests**
[] A/B sticky nav removed on mobile
[] A/B transporter for digital stories (on individual story page) is this increase

**Comment by jennpb** [comment]
@hthair Any new insight on digital story navigation now that we've had bottom-of-page transporters?

Might be worth looking at this in the coming weeks so we can understand how both top and bottom navigation options are being used, so we can settle on a solution or improve the two we have.

**Comment by hthair** [comment]
@jennpb this was partly looked at by System concepts, going through the debrief tomorrow so will update based on their findings and then tie that in with analytics we have.
