### ISSUE TITLE
Wobbly line diversity

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#801]
Now that we are well on our way in building a larger experience, I wanted to catch one detail before its too late maybe

The static version of the wobbly line, not the moving one, which can be seen across the site used in various elements. At the moment we are using one single version, or single manifestation of this wobbly line, but the idea is that across the experience these wobbly lines would always be different. This way you get diversity in the static versions, just like the live version.

2 options we have for this is:
A) Build a collection of svg's which the system then pulls from. 
B) auto generate the line each time its used. Use same system as live-wobbly for generating these.

Im thinking this would be a lot harder to implement down the line once the static wobbly is used in a multitude of ways, rather than putting some pieces of this together now?

What do you think @jamesgorrie @davidpmccormick @gestchild ?

**Comment by jamesgorrie** [comment]
@davidpmccormick did some amazing work on this.
