### ISSUE TITLE
Optimising how we use GIFs in articles

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#812]
Two considerations:
- page performance
- GIF of the day / GIF article formats

GIF-heavy pages result in poor performance, but there's a desire from the content team to make use of GIFs to enhance editorial content. Can we make this work better?

**Comment by jennpb** [comment]
Can this be closed @davidpmccormick ?

**Comment by davidpmccormick** [comment]
Think so for now, yeah – #916 will allow for autolooping muted videos to pretend to be gifs (probs best to wait till we've shifted CMS before implementing for realz, though). The 'gif of the day' point in the description hasn't been addressed yet afaik.
