### ISSUE TITLE
Stress test testing platforms

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#813]
- Optimize
- Mixpanel
- Launchdarkly (already ruled out per investigation #787

**Comment by jennpb** [comment]
@gestchild Is this issue still useful? Any actions need to be taken here?

**Comment by gestchild** [comment]
@jennpb not sure where this issue came from. I don't think anything needs doing imminently

**Comment by jennpb** [comment]
Imma gonna close it then.
