### ISSUE TITLE
CMS: Scoping content publishing tools

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#815]
- [x] Reviewing the contenders:
https://www.contentful.com/
https://prismic.io/
- [x] Gather and document requirements from content team
- [x] Finalising budget

**Comment by jamesgorrie** [comment]
Chosen Prismic as the almost winner - and that's where the work is going into, so going to assume that as complete?

**Comment by jennpb** [comment]
_I coulda been a contendah_

Yes, let's proceed on that basis of what you demonstrated yesterday.

**Comment by jamesgorrie** [comment]
Here's the project board for reference:
https://github.com/wellcometrust/wellcomecollection.org/projects/5

**Comment by jennpb** [comment]
Re: Budget:

Assuming we go with Prismic, our costs will be $1440/yr (£1200). This does not include any reduction in cost that we might get from being a non-profit (though it does assume a 20% discount for purchasing an annual plan rather than a monthly).

This is for the Medium level Professional plan, which includes:
-	25 users
-	SLA 99.5% API uptime with basic support
-	User management includes user roles and workflows

https://prismic.io/pricing

**Comment by jennpb** [comment]
**Content Team CMS requirements - notes from a meeting with DB and JG**

**Media Management**
- Group and organise images so that we can retrieve all images within a certain grouping of content

**Workflow**
- unpublished/draft
- unpublished/public (used for content with a future publication date)
- Published

- Version history
- Defining roles for contributors (author/words, photographer/pictures, etc)
- Be able to edit HTML
- Have an external preview link (token in URL)
- Manage user access

**Comment by jamesgorrie** [comment]
Copy / paste functionality

**Comment by jennpb** [comment]
hey @jamesgorrie just checking - does Prismic meet the above requirements?

**Comment by jamesgorrie** [comment]
If you see the requirements here - I am going to bake these all into the new ticket and I'll close these off.

https://github.com/wellcometrust/wellcomecollection.org/projects

**Comment by jennpb** [comment]
Super! Merci boucoup.

**Comment by jamesgorrie** [comment]
Closing as everything is in #956
