### ISSUE TITLE
Images + Search - discovery phase

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#818]
**Objective** 
To understand how users search, decide whether to use, and store/save/consolidate their digital image research.

**TO DO**
- [x] Consolidate what we already know from previous personas and design research
- [x] Write up pain points in to slides with action points
- [x] Draft user stories
- [x] Draft test hypotheses
- [x] Search terms analysis from GA data 
- [x] Search journey analysis from GA data including CTR/no results
- [x] User Research plan:
- Recruitment strategy: who, how many, how often
- Look at previous recruits to highlight knowledge gaps
- Location and incentives setup
- [x] Setting up a collector/screener for a user testing group/panel (name tbc)
- [x]  Ask Hannah for common enquiries about finding/using images

**Outcomes**

- We know what we are testing and with what audience(s)
- Test bootstrap
- KPIs / success measures agreed
- Prioritised set of user stories
- Image and search MVP agreed

**Comment by hthair** [comment]
I've edited the main comment/list to include new small tasks as I come across things that need doing that fall under this topic, hope that's OK! (e.g. look for gaps in knowledge for recruits).

 Also can someone explain to me what we mean by 'test bootstrap'?

**Comment by kenoir** [comment]
Depends: 
- https://github.com/wellcometrust/platform-api/issues/130
-https://github.com/wellcometrust/platform-api/issues/136

**Comment by hthair** [comment]
Search journey/path analysis futile --> URL's not clearly defined so difficult to navigate behaviour flow in GA. Don't use 'frames' for new website!

**Comment by jennpb** [comment]
@hthair Let's agree next steps for research today so we can close off this issue!

**Comment by jennpb** [comment]
@hthair Could you please capture what we agreed here (for reference) and then close the issue?

**Comment by hthair** [comment]
We're going to begin by running usability sessions with internal images users to test image search page results and item pages. (When item page information is available for testing). These sessions will help us decide what questions we want to use in future surveys and what information needs validating. Will also want to test with external users shortly.
