### ISSUE TITLE
Getting more traffic to site from homepage

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#820]
Problems:
- The Explore page isn't getting enough traffic for us to determine how interested people are in the content being published there. 
- We don't want to hive off 'editorial' type content to its own section if few people go there
- We want to legitimise editorial as a digital manifestation of the public programme, and to give it emphasis within the site as a whole
- The homepage should be an eclectic, and eventually more personalised, reflection of Wellcome Collection.

This is a piece of discovery work to establish how might we integrate Explore into the site better, using our most heavily accessed page.

**Comment by jennpb** [comment]
@Norvard We need to tackle this first as a research phase - assembling what we know about how the current homepage is used, what user goals are, etc, before designing any components. Let's discuss the w/c 2 May, yeah?

**Comment by Norvard** [comment]
@jennpb Yep makes sense. Lets discuss and plan.

**Comment by hthair** [comment]
A/B test currently running calling 'explore' 'magazine' instead for 50% of traffic to see if more people click through.

**Comment by hthair** [comment]
@jennpb Do we want to restart an A/B test with the nav again?

**Comment by jennpb** [comment]
@hthair I don't think so.

However, I'd like for you to do a piece of research and analysis work on the homepage itself. In order to progress with a homepage redesign, we need to decide:
- Is it for new or returning visitors? 
- Are we positioning only the venue or also digital? 
- Should the focus be on us or on what's happening? 
- Do we allow people to customise it based on what they've looked at before, or opt in to customisation based on audience type (for example)?

This warrants a new issue, so I'll do that :) 
#1861
