### ISSUE TITLE
Search algorithm follow up improvements [migrated from Collection repo]

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#823]
@davidmillerwellcome commented on [Tue May 31 2016](https://github.com/wellcometrust/collection/issues/192)

## Description/vision/rationale

In the May sprint, we made some [improvements to search algorithm](https://github.com/wellcometrust/collection/issues/34).  This is a ticket for the follow up work.

The numbers below relate to numbers in [Search Algorithm Evaluation for WC](https://docs.google.com/document/d/1wajLq17Fhz8pJj8V5utqneLhKhKR8IFy-WFSPjXPHnA/edit#)

Should we have a keyword boost field as an alternative way of improving results?  Mike and I discussed this and parked it for the time being but it might still be suitable

**w/Code Enigma**
1) Can we apply additional weighting to Exhibitions and Seasons?  Russell said Exhibition/Installation should be fractionally higher than Season.

2) IF exhibitions/installations/seasons are given more weighting, should we / can we also give a temporary weighting boost applied to anything associated with a current OR future

7) Can the actual word take priority over derivatives? e.g. 'body' features before 'bodies'

**w/Mike**
9) Image credits are not searched (Mike had resolved this locally, but its not available to test on stage)
## Q&A

NA
## Acceptance criteria

TBC
## Related/dependencies

NA
## Sketches/mockups/screenshots

NA

---

@davidmillerwellcome commented on [Tue May 31 2016](https://github.com/wellcometrust/collection/issues/192#issuecomment-222636732)

Assigning to @nambisolo so he can write up any feedback from CE regarding the following ticket:

**Wellcome Trust Support - Support #16290**

Hi Jamie

Can I add the following for investigation too:
- Can phrases be searched for by surrounding by quotes?
- Can the actual word take priority over derivatives? e.g. 'body' features before 'bodies'
- Is there any way a particular content type can take precedence when searching e.g when searching "sexology' the exhibition page should appear first.
  Cheers.

Mike

---

@nambisolo commented on [Mon Jun 06 2016](https://github.com/wellcometrust/collection/issues/192#issuecomment-223902214)

Unassigning myself as this ticket has been closed with CE. I suggest reopening once WC work is picked up again.

**Comment by jamesgorrie** [comment]
Closing as I cant' see anything to action here.
