### ISSUE TITLE
Cardigan - Customisation

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#832]
To begin with, this is more of a series of questions to determine what can be done quickly in order customise and brand Cardigan.

Set of customisation ideas:
- Use our own fonts. Use Helvetica Neue and Wellcome Bold
- Insert brand logo in header + additional text e.g. Logo | Wellcome Collection pattern library
- Edit header background colour
- Change link colour
- Change background colour for left side menu
- Add images into standard pages e.g. "Overview"

Once I get an idea of whats possible from the list above, I can then put together assets and samples in order to make these edits easily and quickly.

**Comment by jamesgorrie** [comment]
> Logo | Wellcome Collection pattern library

Where does Cardigan come into it?

> Edit header background colour
> Change link colour
> Change background colour for left side menu

To what?

All of those are 100% possible with a little more information.
Adding images should be, but I'll have to have a look as to where we would host them.

**Comment by Norvard** [comment]
> Where does Cardigan come into it?
Its either Cardigan (logo) or Wellcome (logo) + text (Wellcome Collection pattern library)
Will make options

To what?
Something from our palette. Next step is to determine what.

What about fonts? Can we use Helvetica? (Bonus: Wellcome Bold)

**Comment by jamesgorrie** [comment]
So - steps in order of ease:

* Choose a colour for the header / sidebar / links
* Add logos / site heading
* Fonts

Fonts are a little tricky as I would want to check performance etc, but shouldn't be too hard.

**Comment by Norvard** [comment]
Header background colour: Yellow #ffce3c

Sidebar background colour: Cream #eeebe2

Text (this includes non-link text in side bar): Black #1d1d1d

Link colour: Seaweed #088574

> Fonts are a little tricky as I would want to check performance etc, but shouldn't be too hard.

Helvetica would be first choice if we can only have 1 font in terms of performance.

**Comment by Norvard** [comment]
Few little update request when you get 2 secs @jamesgorrie 

Can we add hero image to the overview page, plus a Cardigan icon into the top right corner? (Assets attached)

![cardigan](https://cloud.githubusercontent.com/assets/23660297/25429871/525f8ef8-2a72-11e7-90c6-377026cb1e0c.png)

![wc_promo_cardigan](https://cloud.githubusercontent.com/assets/23660297/25429884/5d9ac7e2-2a72-11e7-872f-62ed6a7d7eab.png)

Icon SVG:

<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33.75 28.5"><defs><style>.cls-1{fill:none;stroke:#1d1d1d;stroke-linecap:round;stroke-linejoin:round;stroke-width:2px;}</style></defs><title>Artboard 176</title><polyline class="cls-1" points="25.42 20.2 25.23 26.82 10.91 26.82 10.36 7.95"/><line class="cls-1" x1="25.78" y1="7.95" x2="25.56" y2="15.39"/><polyline class="cls-1" points="10.36 9.74 7.54 14.06 4.97 23.37 1.29 22.55 3.79 10.59 8.84 2.58 12.97 1.21 18.07 9.62"/><polyline class="cls-1" points="27.88 14.13 20.74 18.11 21.79 21.5 32.41 17.71 32.5 12.46 27.45 2.58 23.33 1.21 15.71 14.23 15.71 26.82"/><circle class="cls-1" cx="18.73" cy="15.57" r="0.17"/><circle class="cls-1" cx="18.73" cy="21.81" r="0.17"/><path class="cls-1" d="M12.72,1.21a15.84,15.84,0,0,0,5.35.94,15.84,15.84,0,0,0,5.35-.94"/></svg>

**Comment by Norvard** [comment]
[Cardigan-Icon.txt](https://github.com/wellcometrust/wellcomecollection.org/files/958031/Cardigan-Icon.txt)

**Comment by davidpmccormick** [comment]
Closed by #1063.
