### ISSUE TITLE
Feature Flagging improvements

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#845]
Improve the functionality/implementation of Feature Flags (building upon #451)

##Functionality Improvements
- [x] Way to split users into groups that can have different feature flags active.
- [x] More robust/nicer way to create and edit feature flags
- [x] Page to view status of feature flags
- [x] Way to see current group
- [x] Way to set featuresCohort cookie for users
- [x] Make sure cookie is forwarded by cloudfront
- [ ] Share module flag-status between client and server

##Implementation improvements
~Improve Lambda function~ - no longer relevant since move to prismic
~Move Lambda function into code, so can deploy to AWS~ - no longer relevant since move to prismic
- [x] Remove AWS/github setup now we're using Prismic.io to create and edit flags

**Comment by jennpb** [comment]
hey @gestchild What's left to do on this one? Does it need to be considered for prioritisation if we want to finish off #819?

**Comment by gestchild** [comment]
@jennpb this could be closed, the last item left unchecked is actually a wider issue - see #943
