### ISSUE TITLE
Image gallery button drop

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#850]
When a user clicks on "more" CTA within the caption, the arrow icons drop down along with the text. This shouldnt happen and often interferes with the caption text itself (on smaller screen sizes)

![screen shot 2017-05-02 at 10 59 44](https://cloud.githubusercontent.com/assets/23660297/25613636/e536393a-2f26-11e7-85d6-ae021a5f62ee.png)

![screen shot 2017-05-02 at 10 59 50](https://cloud.githubusercontent.com/assets/23660297/25613642/e78af5ae-2f26-11e7-8584-cdcf99e5214a.png)

**Comment by Norvard** [comment]
Caption overlay:

![image-gallery-buttons-overlay_720](https://cloud.githubusercontent.com/assets/23660297/25613764/515f879c-2f27-11e7-8557-5ad6e03c8b7f.png)

**Comment by jamesgorrie** [comment]
@Norvard - does this still apply given that the buttons are now not overlapping?

**Comment by Norvard** [comment]
@jamesgorrie does not apply. We fixed it with another solution
