### ISSUE TITLE
Review onward journeys within articles and explore

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#866]
Now that we're publishing single articles, we need a way to show more 'related' content on article pages.

Things to think about:
- Transporter logic and design
- refreshing Explore page
- machine vs human selection
- definitions of related: programmatic, random, curated, series-based, and so on...

**Comment by Norvard** [comment]
The rules around transporter use (so far).

So far only 2 transporters have been designed. The design of these components is versatile and neutral and can be retrofitted for use in other places across the experience if needed. They were initially designed to sit at the bottom (end) of an article template.

Articles, of any format, can use either one of or both of the transporter components below.
- If an article is part of a series or theme, use transporter 1 to show other articles from the related series/theme.
- All article types can use transporter 2. This transporter can be edited to show articles that are latest, featured, trending etc.
- The order of using the 2 transporters should be: Use 1 before 2, if using both.
- Do not use any other component as a transporter, unless specified and approved by the design team 👮

![screen shot 2017-06-05 at 14 53 09](https://cloud.githubusercontent.com/assets/23660297/26786797/9f14d8f0-49ff-11e7-8595-bc71e8b670ef.png)
