### ISSUE TITLE
Page rendering is over the perf budget

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#869]
Our page rendering speed is over budget on Speedtracker - let's investigate how to get it back down.

http://ghp.wellcomecollection.org/speedtracker/

**Comment by gestchild** [comment]
Breaking this down a bit:

- [ ] #891 
- [ ] #892
- [ ] #893
- [ ] #894

**Comment by jamesgorrie** [comment]
You could use a project board?
https://github.com/wellcometrust/wellcomecollection.org/projects/6

**Comment by gestchild** [comment]
Closing as has been broken down into smaller issues
