### ISSUE TITLE
Making Stories landing page more dynamic

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#870]
This relates to #820 (discovery work around getting more traffic into and from homepage).

Explore is quickly getting stale if we need to keep using devs as the CMS. We can publish articles, but we don't have a way for the site or for the editors to create new thematic groupings. 

**Stale content:**
A Drop in the Ocean

**Waiting for more things to be published in order to create a series blob:**
Body Squabbles
More digital stories

**Things to consider:**
Assigning weight to components
Creating groupings
Series names / format type / aggregation pages

I'm keeping this one in for planning for later, but will need to involve @dannybirchall and team.

**Comment by pollecuttn** [comment]
From Kate Wilkinson (Editorial team):

> Would it be possible to edit the Books section on the Stories page to feature the 3 most recent books: Michael Rosen's Book of Play, Breaking and Mending, and Anatomicum? Publishing were asking. Thanks

https://wellcome.slack.com/archives/C294K7D5M/p1571909714002200
