### ISSUE TITLE
Digital story promo options

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#872]
Below are a some options for how to treat the digital story promo based on some early feedback on what we currently have. Currently the image and text container are so big that on some viewports you cannot see both at the same time.

Each option explores a unique layout and image size/ration that would allow for the image & text to be visible within the viewport at all times. All options are designed as full edge to edge within the page.

**Option 01:**
Closest to what we currently have. Image inside container is constrained in size to fit the viewers viewport. Dark background added when image has space on edges.
![screen shot 2017-05-08 at 14 08 41](https://cloud.githubusercontent.com/assets/23660297/25805584/29f16c36-33f8-11e7-8509-8af8fe4cc3a1.png)

**Option 02:**
Same as option 01, but the text container has layout adjustments. Text is left aligned and stacked.
![screen shot 2017-05-08 at 14 08 53](https://cloud.githubusercontent.com/assets/23660297/25805627/4bb3ac3a-33f8-11e7-9f8b-edb366ac76ff.png)

**Option 03:**
Images and text container are off aligned with image attached to left edge of grid and text box attached to right edge.
![screen shot 2017-05-08 at 14 09 02](https://cloud.githubusercontent.com/assets/23660297/25805681/751c4bcc-33f8-11e7-81a1-f5a850562c6d.png)

**Option 04:**
Image container is centered and uses 10/12 grid. Text sits outside image on background which utilises wobbly line.
![screen shot 2017-05-08 at 14 09 10](https://cloud.githubusercontent.com/assets/23660297/25805723/9f30ac46-33f8-11e7-82ac-4f0d9a379696.png)

**Option 05:**
Image and text container are laid side by side and on top of wobbly line background.
![screen shot 2017-05-08 at 14 09 19](https://cloud.githubusercontent.com/assets/23660297/25805759/c0f57c30-33f8-11e7-9832-dd63138d0cb4.png)

**Comment by davidpmccormick** [comment]
Closing because we got rid of The Collectors digital story promo.
