### ISSUE TITLE
Content model: Clarifying logic of template/type/named groups

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#880]
We need a bit of clarity around article-as-template, article types, and named series of things. Promos are currently being used to:
- identify this as an editorial thing --> Article
- identify the type of Article it is -- > Video
- identify this Article as belonging to a series --> Body Squabbles (which is also a webcomic, but we don't display that)

The rationale for having an 'Articles' grouping is because that would provide an index page, https://next.wellcomecollection.org/articles/

# Why is this a problem?
- Inconsistent use of the label above article title
- Lack of clarity from an editorial POV whether to include Part in title itself
- Is label a link? If so, to what?

Relates to #514 and #770 

# To Do

- [ ] Look at stats for use of /articles/ and /series/ index pages - are these currently a stage in an onward journey?
- [ ] Review content format / series labels

![img_0501](https://cloud.githubusercontent.com/assets/1446139/25910831/9d0231b2-35a9-11e7-9c62-5a0309bca392.JPG)

**Comment by Heesoomoon** [comment]
**14 June Meeting Note (Danny, Jenn, Heesoo and Tomi)**
Objectives: Revisit how we display Promo Label to minimise redundancy and to assist user find relevant article by making it easy to scan. The team decided to explore following display logic.
- Suppress 'Article' label on all promo
- Use the promo label to highlight special feature/series (Electric Sublime, Body Squabbles, etc.)
- Hide the promo label when all articles belong to same feature/series (Series Index page, Feature/Series block, etc.)
- Change the display order: 1 Article Title, 2 Promo Label, 3 Author Name (optional)

Next Steps
- Tomi to mock up Explore landing with new promo label display logic including author name
- Development effort to be on hold till we revisit the template after Image Search project.
- Content team to consider creating a block to highlight key authors similar to Series block in Explore landing

**Comment by jennpb** [comment]
Super - thanks @Heesoomoon. As there are other actions on this issue I'm going to close it and reopen a new one that will be easier to find for future +1
