### ISSUE TITLE
Article - references

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#890]
Reference icons appear at the end of lines within body copy and contain a number (icon - button).
When the user clicks on the icon, a container appears which includes the information associated with the reference (this text can include links).
**Desktop**, this container appears inside the right-rail space and is top aligned with the reference icon (appearing on top of images or content already within the rail). 
**Mobile**, the container appears on the bottom on the viewport and the rest of the screen is covered with dark overlay to further highlight the reference. The user can click the 'X' or the original icon to close.
When clicked, the reference icon inverts with the box becoming an outline. The icon utilises 3px rounded corners.

References are also contained within a larger list at the bottom of the full article.

**Desktop:**
![screen shot 2017-05-15 at 10 38 09](https://cloud.githubusercontent.com/assets/23660297/26052758/684ddefe-395e-11e7-9d21-2b05ef73e1a8.png)

![screen shot 2017-05-15 at 10 38 19](https://cloud.githubusercontent.com/assets/23660297/26052761/6e25992a-395e-11e7-8f5a-1e201496afa1.png)

![screen shot 2017-05-15 at 10 38 32](https://cloud.githubusercontent.com/assets/23660297/26052771/72e2cef6-395e-11e7-8cd5-66a409ef5cad.png)

**Mobile:**
![screen shot 2017-05-15 at 10 39 12](https://cloud.githubusercontent.com/assets/23660297/26052782/7b9d29f6-395e-11e7-8a1f-0361283edc7a.png)

![screen shot 2017-05-15 at 10 39 26](https://cloud.githubusercontent.com/assets/23660297/26052786/7ec695b8-395e-11e7-946a-6d006d34b213.png)

![screen shot 2017-05-15 at 10 39 48](https://cloud.githubusercontent.com/assets/23660297/26052789/821a90c0-395e-11e7-8125-11f899f3f438.png)

**Comment by jennpb** [comment]
Unlikely to need in this format, per conversation with JTS
