### ISSUE TITLE
Article - Footnote

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#895]
(similar in functionality to reference #890)
Footnotes are notes from the editor/writer that can be injected within the body copy of the article without disrupting the flow of the text. This appears to the users as an icon (which inverts when clicked). 
When the user clicks on the icon, a container appears which contains additional copy. 

**Desktop**, this container appears inside the right-rail space and is top aligned with the reference icon (appearing on top of images or content already within the rail).
**Mobile**, the container appears on the bottom on the viewport and the rest of the screen is covered with dark overlay to further highlight the reference. The user can click the 'X' or the original icon to close.

**Icons file attached**

Desktop:
![screen shot 2017-05-15 at 11 37 05](https://cloud.githubusercontent.com/assets/23660297/26054001/0551a39e-3963-11e7-9458-9f5c7bc90610.png)

![screen shot 2017-05-15 at 11 37 17](https://cloud.githubusercontent.com/assets/23660297/26054007/0948cacc-3963-11e7-9f12-f7f0cbbdf37c.png)

Mobile:
![screen shot 2017-05-15 at 11 38 00](https://cloud.githubusercontent.com/assets/23660297/26054017/0ff2736e-3963-11e7-9327-966f44445218.png)

![screen shot 2017-05-15 at 11 38 10](https://cloud.githubusercontent.com/assets/23660297/26054025/14ebf8c2-3963-11e7-8d50-1770278f16c0.png)

[Footnote_Icons.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1000826/Footnote_Icons.zip)

**Comment by jennpb** [comment]
Talked to Jen - these are unlikely to be needed.
