### ISSUE TITLE
Article - Further reading

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#896]
Further reading is a list of text/links that can be found at the end of an article. 

Desktop:
![screen shot 2017-05-15 at 11 43 01](https://cloud.githubusercontent.com/assets/23660297/26054257/c920bf30-3963-11e7-889d-43d1fd6940eb.png)

Mobile:
![screen shot 2017-05-15 at 11 43 11](https://cloud.githubusercontent.com/assets/23660297/26054287/df3a4048-3963-11e7-922e-21aaf13fb04c.png)

**Comment by jennpb** [comment]
Unlikely to need in this format per conversation with JTS.
