### ISSUE TITLE
Allow poetry to be published

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#899]
Using the preformatted (`<pre>`) tag.

**Comment by Norvard** [comment]
Initial explorations.

Desktop: the full poem reaches across the columns
Mobile: the full poem becomes a scrollable (left & right) area 

Desktop:
![screen shot 2017-05-16 at 10 39 56](https://cloud.githubusercontent.com/assets/23660297/26099936/37f45d8e-3a24-11e7-9a83-502368e34220.png)

Mobile:
![screen shot 2017-05-16 at 10 40 04](https://cloud.githubusercontent.com/assets/23660297/26099945/3e164ee8-3a24-11e7-9ec0-b0fdff4073c8.png)
