### ISSUE TITLE
Improve alerting workflow

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#901]
- Improve alerting so it's easier and quicker to determine the cause and impact of the issues.
- Establish way of triaging issues

**Comment by jennpb** [comment]
@gestchild Here's the source of the vagueness. If you can enter more details about what you think should be done or investigated, it'll help prioritise later on.

**Comment by jennpb** [comment]
Is this still something to be done @gestchild ?

**Comment by gestchild** [comment]
@jennpb I think we can close this, we now have a better way of determining the source of 500 errors, which was the main bugbear.

**Comment by jennpb** [comment]
:boom:
