### ISSUE TITLE
Creating a stronger identity for series

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#902]
We currently don't have a strong visual or content-led entry point into /series/. This means that we are currently sending people to a context-free listing page from Explore and social media - not friendly for our users!

**Now**
Series pages are index pages that aggregate all articles tagged under a certain (Wordpress) category.
It is possible to provide a summary text as was done with this one: https://next.wellcomecollection.org/series/a-drop-in-the-ocean

**What next?**
Content model needs to include:
- Series title
- Series summary

**Page** could use a stronger visual treatment, using a  representative image, for example
**Promo on page** needs to include main promo image from article itself; it does not need to repeat the series title but may reflect what part/chapter it is (if required) 

https://next.wellcomecollection.org/series/body-squabbles
https://next.wellcomecollection.org/series/electric-sublime

**Future**
The same model could be applied to audio, video, specialist content series like Research Notes.

**Comment by Norvard** [comment]
The following notes outline design elements for an index page header which can accommodate series content (e.g. Comic and Research notes) and digital stories (e.g. Electric Sublime)

**Index header special 01** (use for series such as Web Comics and Research Notes)

- This header includes space for a hero image which represents the full series (dimensions: 16x9), a series title, description and number indicator for amount of articles. 
- The image is constrained within the background space (top to bottom) and scales with that.

![screen shot 2017-05-24 at 09 55 47](https://cloud.githubusercontent.com/assets/23660297/26397198/648a3630-406d-11e7-93a2-a328d963a2a1.png)
![screen shot 2017-05-24 at 09 55 09](https://cloud.githubusercontent.com/assets/23660297/26397197/64821414-406d-11e7-8efa-5f9b326e4638.png)

**Index header special 02** (use only for digital stories)

- This header includes space for a hero image which represents the full series (dimensions: 16x9), a series title, description and number indicator for amount of articles. 
- The header background colour is the same colour which was denoted for the series initially. This background area also contains a wobbly line for added special effect :) The wobbly line is set in black (hex: 1d1d1d) at 10% opacity.
- The promos within the page are large (2 column at large desktop, single column at small desktop) and contain space for a large number denoting the chapter.
- The image is constrained within the background space (top to bottom) and scales with that.
- The image colour effect is the same as is seen in the series navigation header (top left corner)

![screen shot 2017-05-24 at 09 55 24](https://cloud.githubusercontent.com/assets/23660297/26397467/5dd27f4a-406e-11e7-8e13-2650a06ef5da.png)
![screen shot 2017-05-24 at 09 55 59](https://cloud.githubusercontent.com/assets/23660297/26397468/5ddadf5a-406e-11e7-92a2-da54a30d30f3.png)

**Comment by jennpb** [comment]
no longer relevant
