### ISSUE TITLE
Alert banner is a space hog

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#910]
Raising this as a design issue to consider. 

Internal feedback (including me) is that the yellow banner takes up a disproportionate amount of space, especially when paired with the digital story navigation.

We need to consider how, when we start adding on new features and content, we alert site visitors to NEW! without getting in the way of their experience.

**Comment by jamesgorrie** [comment]
Can we please do this mobile first. Just aware that a lot of design so far has been desktop first.

**Comment by jamesgorrie** [comment]
We could also just remove it too, I suppose the question is, "are people really confused about being on a new design / site".

Maybe what's more important is if people are, how do we let them feedback to us?

**Comment by pollecuttn** [comment]
Or make it dismissable.

**Comment by jamesgorrie** [comment]
@pollecuttn dis-missable things are always tricky - especially with public computers.
I'd always ask if you just let people get rid of it, what's the point.

**Comment by Norvard** [comment]
Just a idea... we could get rid of the banner but design a simple component/module which can sit within the content of Explore landing ( and future: homepage and any other landing page), slot it anywhere we deem right. 

This module would contain similar message as now, plus updated links and news relating to design. This way its not always there on every single page (article) but people who visit the site on a more regular basis will uncover this message. Why does a new site notification matter anyway to a random single visitor who doesnt have previous context anyways? Its only relevant to those who have been to the old and have gotten used to that experience, plus those who plan to visit more and might be interested to learn more about the development happening.

**Comment by jamesgorrie** [comment]
> Why does a new site notification matter anyway to a random single visitor who doesnt have previous context anyways

👍 :+100:

Yea - a simple "New", or "Why this so beautiful" component would be great.

**Comment by jennpb** [comment]
Exec decision: We're going to suppress the yellow banner until further notice. 
- CTR to Find out more link is v low
- Banner keeps people from recognizing that they're in 'Explore' section
- Need to consider it as a useful alert component in future.
