### ISSUE TITLE
Article details

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#919]
Few little tweaks that have gone unseen or forgotten.

When the hero image has no caption, there should still be a thin key-line that stretches across the columns above the author.

The first image in the rail, should always top align with the start of the copy.

<img width="1266" alt="screen shot 2017-05-22 at 13 54 23" src="https://cloud.githubusercontent.com/assets/23660297/26309850/99892454-3ef6-11e7-8845-ade933c3bc78.png">

**Comment by davidpmccormick** [comment]
> The first image in the rail, should always top align with the start of the copy

The positioning of the rail images is contingent on their position within the text. If an image is positioned in the copy after e.g. the fourth paragraph of text, we wouldn't want to show it at the top of the page – it has to be relative to the flow of the content.

**Comment by davidpmccormick** [comment]
Tracking the work to optionally align RHR image with standfirst in #957.
