### ISSUE TITLE
Article - Multiple contributors

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#928]
A text element which can live at the end of an article includes the ability to add multiple contributors to the article content. The title of the element can also be Authors (up to editorial to decide).

Whether the article still has a main author element at the top is up to the author.

The names of people can also be set as links to relevant personal websites if needed.

![screen shot 2017-05-24 at 11 05 33](https://cloud.githubusercontent.com/assets/23660297/26399044/690e9de4-4073-11e7-857f-ce478d01d5f3.png)
![screen shot 2017-05-24 at 11 11 31](https://cloud.githubusercontent.com/assets/23660297/26399041/674b923c-4073-11e7-9980-9dd8d00a6455.png)

**Comment by jennpb** [comment]
How would this work if author(s) all had an avatar and bio? 
Does the list of contributors come before author bio? 
Is the list of contributors part of the body?

**Comment by Norvard** [comment]
Based on my chat with James yesterday, this would take over the author bio, unless the author prefers to have both. This would live at the bottom of the article, part of body) and below an author bio if there is one. In same location as references and notes. However I am not sure what the order is if all these elements are included, however they do all work together if they are all used.

As far as I also understood is that these contributors would not contain pics and bios. Unless that is a requirement then we can make that, but that also could get quite large.

I think we need some more requirements from the Editorial team. Happy to chase them up.

**Comment by jennpb** [comment]
That would be great. I haven't seen the requirements articulated anywhere, apart from the fact that they've had instances where there were two authors, or an author + photographer. I would want to know:
- what content needs to be associated with contributors (whatever their role) - name, social handles or identifiers, avatar, bio
- which content gets displayed
- whether there is a primary author that gets more bling than everyone else who contributed
- whether all contributors end up with an author page (we might want an index page for authors, but does that extend to contributors?)

**Comment by Norvard** [comment]
Yea there really hasnt been any requirements for this. Its one of those floating requests :)
Will chase up on this and make necessary amends.

**Comment by Norvard** [comment]
After gathering further requirements. Below is the latest version of Multiple Authors and Contributors (2 different use cases and treatments).

**Multiple Authors:**
When an article has multiple authors, e.g. The article is equally created by more than one person and a single author does fairly represent the article author, add author information to the top of the article.

![screen shot 2017-06-05 at 11 12 36](https://cloud.githubusercontent.com/assets/23660297/26780549/2b74d7d2-49e2-11e7-84d3-2c70d8f87fae.png)
![screen shot 2017-06-05 at 11 14 51](https://cloud.githubusercontent.com/assets/23660297/26780548/2b71950e-49e2-11e7-8ddf-a474d8268393.png)

**Multiple Contributors:**
When an article has a clear author but also includes additional contributors that should have a mention, e.g. Article was mainly written, commissioned and compiled by one author, however artwork/images/text from other contributors were used within the article, add contributor names, contribution title, picture and bio info to the bottom of the article.

![screen shot 2017-06-05 at 11 22 15](https://cloud.githubusercontent.com/assets/23660297/26780631/85aa8878-49e2-11e7-8a01-8eda86a71985.png)
![screen shot 2017-06-05 at 11 25 19](https://cloud.githubusercontent.com/assets/23660297/26780632/85ae625e-49e2-11e7-8810-15cb46bb8b74.png)


NOTE: Refrain from including multiple main authors at the top of the article. Only do so when clearly the creation of the article was equally distributed and a single author cannot be defined. Try to use Contributors as the preferred option when crediting many people.

**Comment by jennpb** [comment]
@davidpmccormick @gestchild @jamesgorrie Tidying up GH, this one was done and is now possible, yes?

**Comment by davidpmccormick** [comment]
I'm fairly certain the modelling for it has been done – i.e. editors can add multiple authors in Prismic. I'm not _sure_ we got to the front end implementation.

**Comment by jamesgorrie** [comment]
@jennpb @davidpmccormick we have the ability.
We currently just list through the articles.

The content team know that they can do this (it's in Prismic) - we can either build it now on test data, or wait till they want to add multi-authors, or more contributors.

I'd say let's let them know we have it there, and we can tidy it up when they need to add it.

**Comment by jennpb** [comment]
Ah, ok, it must not have been styled then because here's a multi-author article published in July: https://wellcomecollection.org/articles/six-personal-health-zines-that-might-change-your-life

**Comment by davidpmccormick** [comment]
We didn't have a way to do it when we were on WP (there was no way to associate more than one contributor with an article, so that zines article just listed the authors in italics rather than using an author component). Things are different now we're in Prismic-town.

**Comment by jamesgorrie** [comment]
@davidpmccormick tested it with a Prismic article with multi-authors, we don't support this.
@jennpb Do we want to do this work, or could we close it and open it again when the need arises?

**Comment by jamesgorrie** [comment]
Close in favour of #2619
