### ISSUE TITLE
CMS 

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#956]
# Requirements
## Short term?
* To create at least what Wordpress can produce, including hacks around right rail content etc.
* User login
* Make series completely content manageable:
  * Name
  * Description
  * Choice of colour 
  * Image
* Allow content management of Authors
  * Name
  * Image
  * Links
  * Bio
* Have different crops for different contexts (Promo, Hero, in article)
* Article body block style editing ([example](http://madebymany.github.io/sir-trevor-js/example.html))
* Create public, but not yet published, content

## Long term
* Embedding of / linking to content from APIs
* Private preview of unpublished content (articles and listings)
* Content manage other parts of the content model. e.g:
  * organisation pages?
  * promotions?
  * exhibitions?

# Using Prismic (or other service)
- [x] Paste all content into editor and then split it our from there
Prismic are looking into this
- [x] 16:9 crop tool for images
Talking to Prismic, and they seem strangely adverse to this. We could get users to then upload the right crops, but then we lose the nice referency niceness.
- [x] 16x9 images - adding extra background
This should be handled on the client
- [x] Editing the slug
I'm not sure this is something we are going to allow - it's become way less an issue with SEO - I suppose there is a UX argument here, but wonder if going down the route of IDs would be better.
- [x] Hyperlinks in content disappearing
Prismic are looking into this. They have fixed this, but it has a slight bug.
- [x] 10 MB limit on media items
- [x] Published date / Author to books
- [x] Adding heading bug
- [x] title of document isn't being taken from headline
- [x] Preview - 100% doable

# Rolling our own

How would we:
* Manage relational data (Authors, books etc)
* What would we use for a login service
* Media management (cropping etc)
* How would we have different read permissions on the API i.e. for preview?

**Comment by jamesgorrie** [comment]
# Rolling our own

How would we:
* Manage relational data (Authors, books etc)
* What would we use for a login service
* Media management (cropping etc)
* How would we have different read permissions on the API i.e. for preview?

**Comment by jennpb** [comment]
Re: Editing the Slug: I think we need to retain a human-readable article slug to ensure that we're making it superfriendly for sharing. The other benefit is that it's easier to track usage in GA if we can read the URL.
