### ISSUE TITLE
Add option to align rail image flush with standfirst

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#957]
# This is a (please label accordingly):
- [x] feature

Currently, images in the right-hand rail are aligned to the right of the paragraph of body text that they precede in the source order.

They should have the option to align with the top of the standfirst also.

**Comment by jamesgorrie** [comment]
Do we still want this or care about it?

**Comment by davidpmccormick** [comment]
I believe it was @Norvard's (reasonable) request. I'd imagine the move to Prismic _should_ simplify this if we were to go ahead with it.
