### ISSUE TITLE
RSS feed doesn't provide full post

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#980]
## Type
- 🐛 Bug

Looking at https://next.wellcomecollection.org/articles/electropoise in Feedly (desktop browser version and mobile app version) I only get information down to the first paragraph.

Please include all of the post in what comes through the RSS feed.

Feedly desktop browser:
![feedly-desktop-browser](https://user-images.githubusercontent.com/1446072/26918402-bce8defe-4c29-11e7-8989-05bc59165b1b.PNG)

Feedly mobile app:
![feedly-mobile-app](https://user-images.githubusercontent.com/1446072/26918405-c10412f6-4c29-11e7-977b-e921f47c629c.png)

**Comment by jamesgorrie** [comment]
Closing as this isn't actually our feature (we're still feeding off the Wordpress RSS).
Moved it into the RSS ticket #528 to make sure keep this in mind when implementing it.
