### ISSUE TITLE
Display seven A Drop in the Ocean posts

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#991]
## Type
- 🐛 Bug?

Only five of the seven _A Drop in the Ocean_ posts that we were displaying on the explore page are in the 50 most recent posts (that we query the WP API for). This number will come down as more new editorial content is added and the _A Drop in the Ocean_ section will start looking a bit bare.

![screen shot 2017-06-12 at 17 14 55](https://user-images.githubusercontent.com/1394592/27043772-2c1cc026-4f93-11e7-94d3-b9003ec29df4.png)

Maybe we do a separate query to the API (costly) and/or cache/hardcode the required _A Drop in the Ocean_ article stubs.

**Comment by jamesgorrie** [comment]
Related to #1033

**Comment by jamesgorrie** [comment]
Wontfix.
Will be addressed in #1033
