### ISSUE TITLE
Investigate using CSS grids for article page

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#993]
## Type
🚑 Health report

Investigate whether using CSS grids could simplify the article template to get rid of all the complicated maths in the CSS

**Comment by gestchild** [comment]
Made a start on this, but it's on hold - see 'grids-experiment' branch

**Comment by jamesgorrie** [comment]
@gestchild What would we need to get this done?

In terms of value - it would give us a better toolkit to develop the UI for new pages, especially when we get a new designer in, we can say "This is the framework" which I remember @Norvard saying he would have loved to have done more of.

**Comment by jennpb** [comment]
Are we able to close this? Or shall I leave it open until we know more about whether we'll make adjustments to the article body?

**Comment by gestchild** [comment]
I think it's worth keeping it open
