### ISSUE TITLE
Twitter social component - Mobile and small tablet

### ISSUE THREAD

**Issue by Norvard** [wellcometrust/wellcomecollection.org#998]
## Type
- 🐛 Bug

When the component scales down in responsiveness, once the 4 embeds do not fit horizontally on the page, they should move into slider and bleeds of the page. Currently they all stack which creates an enormously long component.

What we do in the awkward middle to small breakpoint, not sure. But would love to explore this a bit.

Come chat to me @davidpmccormick if you gots the questions :)

<img width="373" alt="screen shot 2017-06-14 at 11 42 33" src="https://user-images.githubusercontent.com/23660297/27128485-99949c78-50f6-11e7-8c19-ace6d8c1820f.png">

**Comment by jamesgorrie** [comment]
Marking as wontfix as this component still isn't even in production ready mode... we can reopen it if we decide that it's a priority.

**Comment by Norvard** [comment]
@jamesgorrie What do you mean "not production ready"? We currently feature this component on the site...

**Comment by davidpmccormick** [comment]
Breaking to a bleed-off-the-page slider would be fairly straightforward once two tweets no longer fit on a line, but doing it as soon as four no longer fit would be tricky as it stands.
